### ISSUE TITLE
Add App Configuration example for Service Fabric Stateless ASP.net Core API

### ISSUE THREAD

**Issue by yegu-ms** [Azure/AppConfiguration#100]

**Comment by gsgvijay** [comment]
You would need to enable Managed Identity in the VM and add that identity to the App Config Store with ‘App Configuration Data Reader’ or ‘App Configuration Data Owner’ roles, and then follow [Service Fabric’s documentation ](https://docs.microsoft.com/en-us/azure/service-fabric/how-to-managed-identity-service-fabric-app-code) to obtain tokens needed to access the Config Store.
