### ISSUE TITLE
Offline file cache does not work with managed identities.

### ISSUE THREAD

**Issue by jimmyca15** [Azure/AppConfiguration#101]
The `AzureAppConfigurationProvider` has the capability to use an offline file cache, and it also has the capability to connect to Azure App Configuration via Managed Identity for Azure Services. When using both of these together an error is hit saying "Connection string is required". Thus the offline file cache can never be used in applications designed to authenticate with managed identities.

**Comment by jimmyca15** [comment]
@MSGaryWang

**Comment by jusbuc2k** [comment]
Any update on this issue?

**Comment by MSGaryWang** [comment]
We just have new release for managed identity update and will have another release base on it soon for offline cache.

**Comment by zhenlan** [comment]
When managed identity (or any AAD authentication) is used to connect to App Configuration, the user need to provide `Key`, `IV` and `SignKey` as part of [OfflineFileCacheOptions](
https://github.com/Azure/AppConfiguration-DotnetProvider/blob/master/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/OfflineFileCacheOptions.cs).

We should throw a more helpful error when above condition is detected. @abhilasharora can you please make the change?
https://github.com/Azure/AppConfiguration-DotnetProvider/blob/de3fc18aad838ede93a4796f924a803b67656f7b/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/OfflineFileCache.cs#L247

**Comment by zhenlan** [comment]
Close this as the remaining work is tracked in https://github.com/Azure/AppConfiguration-DotnetProvider/issues/135.

**Comment by wouterroos** [comment]
@zhenlan Is there a workaround for this issue in the meantime?

**Comment by abhilasharora** [comment]
@wouterroos One workaround for this issue would be to use a custom implementation of offline cache. The configuration provider allows users to provide their own implementation of `IOfflineCache` using the [SetOfflineCache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.setofflinecache) method.
