### ISSUE TITLE
Azure App Configuration (Managed Identity) With Container Instances

### ISSUE THREAD

**Issue by sowdhanyakotaru** [Azure/AppConfiguration#102]
Hi Team,

I have created a .Net Core application using Azure App Configuration. I have created a docker image for my app and registered in  Azure Container Registry and created a container instance for that image. I am able to get the output for Azure App Configuration using Connection String, but observed an issues while access Azure App Configuration  using Managed Identity, error details:

![Issue](https://user-images.githubusercontent.com/11170732/60158856-8b450b00-980f-11e9-9f47-172f34eb003c.PNG)

We tried the same with Azure App Services and it was successful, can you throw some light on how to do with Managed Identity for Container instances and resolve above error. 

Thank You Sowdhanya

**Comment by markgould** [comment]
I'm using Managed Identity with Container Instances - user and system assigned work. I did not need to set a connection string. I had issues with Azure App services until I started using connection strings.

You do have the identities setup in your container instance I'm assuming? I'm specifying mine in YAML but you should just be able to turn on through the portal too.

**Comment by zhenlan** [comment]
I remember I tried the *system assigned* managed identity with container instance and it worked with my Azure App Configuration. 

@sowdhanyakotaru, did you figure this out? Are you using system-assigned or user-assigned managed identity in container instance?

**Comment by littlenetcoder** [comment]
@sowdhanyakotaru having same issue with k8s pods, but once elevated its role to **Contributor** solved the mystery which is ideally should have been worked with just **Reader**  role !!

**Comment by sowdhanyakotaru** [comment]
Hi,

Thanks for all your quick replies. Resolved the issue by giving the **contributor** role access to the container instance which I have created.

Thanks,
Sowdhanya K.

**Comment by zhenlan** [comment]
@sowdhanyakotaru thanks for the update. Glad it worked for you.
