### ISSUE TITLE
Featurebits

### ISSUE THREAD

**Issue by muffadalis** [Azure/AppConfiguration#112]
Hi,

There is another package from Microsoft called [FeatureBits ](https://github.com/microsoft/featurebits) having similar features. Should we be using FeatureManagement going forward? Is FeatureBits deprecated?

Thanks

**Comment by yegu-ms** [comment]
@muffadalis Yes, we recommend that you use the .NET Core FeatureManagement library going forward. It’s under active development and officially supported by a Microsoft product team.
