### ISSUE TITLE
IFeatureFilter Evaluate method to accept some custom parameters.

### ISSUE THREAD

**Issue by praveenlearns** [Azure/AppConfiguration#115]
I am trying to understand if a custom feature filter that we write needs to use some parameters which are not part of HttpContext. 

How can we pass extra parameters when we call IFeatureManager.IsEnabled("featurename") which triggers Evaulate method of custom filter.

But how an azure function app or webjob will use it. 

`
    [FilterAlias("AllowedUsers")]
    public class AllowedUsersFeatureFilter : IFeatureFilter
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
     
        public AllowedUsersFeatureFilter(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
       // HOW CAN WE PASS SOME parameter when we call IFeatureManager.IsEnabled("featurename")
        public bool Evaluate**(FeatureFilterEvaluationContext context)**
        {            
            var featureFilterParams = context.Parameters.Get<AllowedUsersFilterSettings>();
            if (featureFilterParams == null)
                return false;
            var userEmail = _httpContextAccessor.HttpContext.User?.FindFirst(ClaimTypes.Upn)?.Value;
            var alias= userEmail?.Split('@').First();           

            return featureFilterParams.Aliases.Split(',').Contains(alias, StringComparer.OrdinalIgnoreCase);            
        }
    }
`

**Comment by jimmyca15** [comment]
Hello @praveenlearns,

With the current preview release of our feature management library this is not possible. However, if you are flow an execution context through your application via AsyncLocal, you could achieve the same affect as using an HttpContext.

This functionality can be expected in our *preview2* release that is in the works. Thanks.

**Comment by praveenlearns** [comment]
Thank you Jimmy. That will be very helpful as we are already hooked on to it.
