### ISSUE TITLE
Document use cases for "Content Type"

### ISSUE THREAD

**Issue by yegu-ms** [Azure/AppConfiguration#116]
Tracking issue for https://github.com/MicrosoftDocs/azure-docs/issues/35422

**Comment by Lukasz994** [comment]
Is there any update on this?

**Comment by zhenlan** [comment]
@Lukasz994 The content-type field is intended to be used to indicate the type of the *value* of a key-value. The field is for customer use. When this information is available, an application can behave differently, for example, use different parsers when value content is bool vs. integer. While you can use any formatting to indicate content-type, we recommend using MIME types - this is how we use content type to indicate feature flags or Key Vault references.

**Comment by zhenlan** [comment]
Document is updated
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value#use-content-type
