### ISSUE TITLE
sample to load azure app configuration could be improved

### ISSUE THREAD

**Issue by sabbadino** [Azure/AppConfiguration#117]
With the code below taken from 
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app

the azure app configuration is the first provider involved.
In a real scenario I think it's better to have json config files and env variables to have priority on azure app configuration , so that you can override locally an azure app configuration  setting. 

public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            var settings = config.Build();
            config.AddAzureAppConfiguration(settings["ConnectionStrings:AppConfig"]);
        })
        .UseStartup<Startup>();

------------------
To address the "issue", I've written something like this: 

var settings = config.Build();
var originalSources = new List<IConfigurationSource>(config.Sources);
config.Sources.Clear();
config.AddAzureAppConfiguration(options =>options.Connect(settings["ConnectionStrings:AppConfiguration"])
});
foreach (var configurationSource in originalSources)              {
 config.Sources.Add(configurationSource);
}

**Comment by jimmyca15** [comment]
@sabbadino, One of our goals with the example is to strike a balance between utility and simplicity. While we understand where you are coming from, it adds concepts to the example that aren't necessarily needed for the quick start case.

Thanks for the suggestion though!
