### ISSUE TITLE
Missing ARM template reference

### ISSUE THREAD

**Issue by yegu-ms** [Azure/AppConfiguration#119]
This is a tracking issue for https://github.com/MicrosoftDocs/azure-docs/issues/35613.

**Comment by zhenlan** [comment]
Similar issue https://github.com/MicrosoftDocs/azure-docs/issues/35615

This is working in progress.

**Comment by wahyuen** [comment]
Is this likely a feature that we could expect in the near term or something that is much further down on the roadmap (Q4? 2020?). We are currently attempting to assess if we use App Configuration and where to invest our time into automation (manual vs cli vs ARM)

**Comment by zhenlan** [comment]
@wahyuen thanks for the query. The feature will be available soon (hopefully, this month). You will be able to reference key-values saved in App Configuration from the ARM template.

**Comment by wahyuen** [comment]
@zhenlan Just checking to see if this ended up getting implemented? or still pending?

**Comment by zhenlan** [comment]
@wahyuen, sorry, this took longer than I would like, but we are working on it. Most implementation is done. We are finalizing a few last pieces such as permission model and documentation. I will keep this thread posted once we have it out.

**Comment by hansmbakker** [comment]
I found the [ARM Template Reference](https://docs.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/2019-10-01/configurationstores) but the following things are missing:
- how to reference key/values
- how to set new settings
- whether there is a difference between "normal settings" and featuremanagement settings
- what sku options there are
- what properties can be set via the arm resource

Unfortunately, the "export template" functionality does not export (and therefore show) the needed things. Also, the App Configuration resources are invisible in https://resources.azure.com/.

**Comment by zhenlan** [comment]
It took a much longer time than expected to get the documentation, but it's finally here.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager

This supports reading/referencing key-values from App Configuration in an ARM template. Writing/setting key-values to App Configuration in an ARM template will be supported in the future (tracked in #268).

Please open new issues if you run into any problems or have any questions.
