### ISSUE TITLE
Key Description

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#122]
When managing a lot of keys, it would be helpful to be able to see what that key is supposed to do.  A simple description field on the key would go a long way to have visibility into what the key is supposed to control.  

Without a description, value editor's must have to have intimate knowledge of what the key controls.  On teams with high turn over, or keys created by transient teams, the knowledge is lost to even the author of the key.

A description field would be like method comments or API documentation.

````
key:  ReadLockTimeOut
value: 3000
description: (milliseconds) Controls how long polling thread will wait until operation exits. Use 2x average execution time)
````

**Comment by drago-draganov** [comment]
KeyValue supports custom defined Tags. Would that work for you, @HashTagDotNet ? 

```Json
{
// Existing properties omitted for simplicity 

"tags": {
"description": "here goes my comment"
}
}
```

**Comment by zhenlan** [comment]
@HashTagDotNet, please let us know in case you feel your question is not answered.

**Comment by HashTagDotNet** [comment]
I would like to see description on the key as tags are variants of the key.

**Comment by drago-draganov** [comment]
@HashTagDotNet 
You are absolutely correct. We don't currently provide key related metadata. Let me try to elaborate on the design decisions.

As you noticed, Tags are part of the representation of Key-Value entity. These entities are completely independent and self-contained. They can evolve over time, labels, etc. All these dimensions or constraints, but rather to provide a reference/pointer. Each key-value metadata is designed to sufficiently describe it's representation. The consumer is expected be able to provide adequate interpretation though.

For example, v1 of ReadLockTimeout provides value as milliseconds, but v2 could up that to ticks, or other numeric scale, or perhaps even define custom format. Content-type per key-value is intended  to help handle such evolution as well. 

I also understand that such freedom may present fair share of inconvenience in case of simplistic scenarios. We choose to focus on client tools (portal, cli, sdk) to help ease the flow of properties, while edit/clone an existing key-value.
.
