### ISSUE TITLE
Can we create Features using REST api

### ISSUE THREAD

**Issue by praveenlearns** [Azure/AppConfiguration#124]
Is there any way to create/edit Features using REST API? 
or in other words Can we allow users to turn off the features for himself that he was entitled to with some custom filter conditions?
 
**Example:**
Name: SendNotifications
State: Conditional ON
Custom Filter: WhiteListUserFilter
Parameters: {"emails":"john@test.com,maria@test.com"}

**Use Case:** John logs in and he wants to remove his access from this feature.

API logic should be like
1. Read from httpContext if email is john@test.com
2. Fetch the feature json (name is input) using REST api and modify to remove his name from "emails" parameter of the custom filter.

**Comment by jimmyca15** [comment]
Hello @praveenlearns,

Yes, it is possible to create features using the REST API.

Features are key-values (accessible via the '/kv' endpoint) that follow a couple specific conventions. These conventions are documented here: https://github.com/Azure/AppConfiguration/tree/master/docs/FeatureManagement 

The key-values representing features have
* A custom prefix for their keys
* A custom content type
* A schema for their content.

So creating or editing features is the same thing as creating or editing any other key-value. The key-values just need to adhere to the conventions.

**Comment by zhenlan** [comment]
@praveenlearns please let us know if you have further questions. Closing for now.
