### ISSUE TITLE
Refresh period clarification

### ISSUE THREAD

**Issue by zak-nye** [Azure/AppConfiguration#125]
Using the Microsoft.Extensions.Configuration.AzureAppConfiguration package in C# I have configured the refresh of a property as follows -

```
.ConfigureRefresh(options =>
{
    options.Register("channelBusSettings.Scope", "dev");
});
```

This alone does not automatically trigger any update. So I use the `AzureAppConfigurationOptions.GetRefresher()` method to get a refresher and call this every 10 seconds. However I can see using fiddler that the call to update is only made every 30 seconds (the default cache expiration time).

So now I'm confused because it seems strange that I need to call this manually, yet it will operate on its own schedule - even if this cache timeout is configurable. Am I using this correctly?

**Comment by qmatto** [comment]
This works great for me:

```
.ConfigureRefresh(refresh =>

                       {
                           refresh.Register("Key");                            
                           refresh.SetCacheExpiration(TimeSpan.FromSeconds(10));
                       });   
```

**Comment by jimmyca15** [comment]
Yes you are using it correctly. Although the update is being made manually, there is still a cache period. It can be overridden using the below method. This is documented [here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core)

```
.ConfigureRefresh(options =>
{
    options.Register("channelBusSettings.Scope", "dev")
           .SetCacheExpiration(TimeSpan.FromSeconds(10));
});
```

**Comment by zak-nye** [comment]
Thanks @jimmyca15 it wasn't quite clear to me but makes sense now.
