### ISSUE TITLE
Import/Export ConnectionStrings from Azure AppService into Azure App Configuration.

### ISSUE THREAD

**Issue by praveena-m** [Azure/AppConfiguration#126]
While import/Export from Azure App Configuration to AppService connectionstrings are not imported/exported from Azure AppService into Azure App Configuration.

![image](https://user-images.githubusercontent.com/1097942/62703716-6c898500-ba07-11e9-885d-6f4306c66150.png)

![image](https://user-images.githubusercontent.com/1097942/62703886-d013b280-ba07-11e9-9dca-156dbfa2ac3e.png)

**Comment by zhenlan** [comment]
@praveena-m the *Connection strings* are considered as *secrets*, which normally needs rotation, etc. This is why we didn't include it in import/export in Azure App Configuration.

**Comment by praveena-m** [comment]
I have done a work around to store the encrypted connection strings in App Configuration and export the same using Azure CLI and update into an Azure App Service.
