### ISSUE TITLE
RBAC with ARM

### ISSUE THREAD

**Issue by ArvidNyden** [Azure/AppConfiguration#128]
Hi, how would I go about to add a my App Service Identity to the Read role of Configuration Store?
My current ARM looks like below (does not work and can't find any documentation on how this suppose to work. 

```json
    {
      "apiVersion": "2015-08-01",
      "name": "[parameters('apiAppName')]",
      "type": "Microsoft.Web/sites",
      "location": "[resourceGroup().location]",
      "identity": {
        "type": "SystemAssigned"
      },
      "tags": {},
      "dependsOn": [
      ],
      "properties": {...},
      "resources": [...]
    },
	{
      "name": "[parameters('configurationStore')]",
      "type": "Microsoft.AppConfiguration/configurationStores/providers/roleAssignments",
      "apiVersion": "2019-02-01-preview",
      "location": "[resourceGroup().location]",
      "tags": {},
      "properties": {}
    },    
	{
      "name": "[concat(parameters('apiAppName'), '/Microsoft.Authorization/', parameters('roleNameGuid'))]",
      "type": "Microsoft.Authorization/roleAssignments",
      "apiVersion": "2018-09-01-preview",
      "properties": {
        "roleDefinitionId": "Reader",
        "principalId": "[resourceId('Microsoft.Web/sites', parameters('apiAppName')).identity.principalId]",
        "scope": "[resourceGroup().Id]"
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/Sites/', parameters('apiAppName'))]",
        "[resourceId('Microsoft.AppConfiguration/configurationStores/', parameters('configurationStore'))]"
      ]
    }
```

**Comment by zhenlan** [comment]
@ArvidNyden it should work if you grant your App Service **Contributor** role to the AppConfig store. This is because the relevant API in AppConfig service has access to both readonly and readwrite connection strings. I know this can be confusing. We are looking into an improvement on this in the future.

**Comment by ArvidNyden** [comment]
I get it to work with Read role if I do it in the portal. Its the ARM thats not working.

**Comment by zhenlan** [comment]
It shouldn't work with the Reader role due to the reason I mentioned earlier. Do you mind to double-check? Did you get a chance to try the Contributor role in your ARM template and see if it works?

**Comment by zhenlan** [comment]
@ArvidNyden I am closing this issue. Please let me know if this works for you or you have more updates.
