### ISSUE TITLE
feature control by non-http context?

### ISSUE THREAD

**Issue by wangyuantao** [Azure/AppConfiguration#135]
We want to use feature manager API (Microsoft.FeatureManagement) to implement feature control by context. Our app is running as worker role, so there is no http context as https://github.com/microsoft/FeatureManagement-Dotnet/blob/272a82a99c4d643ff8cd9456606d515f3763c5eb/examples/FeatureFlagDemo/BrowserFilter.cs.

Example:
_featureManager.IsEnabled("coolfeature", {tenantId:job.tenantId})
In Azure Portal, setup to control 25% tenants enable the feature "coolfeature". - phrased rollout scenario
Or 
_featureManager.IsEnabled("coolfeature", {workspaceId, job.workspaceId})
In Azure Portal, setup to control 2 whitelisted workspace ids enable the feature "coolfeature". - test in production scenario.

Do you have plan to support those in Azure App Configuration? If it is already supported, can you share some samples?

Thanks!

**Comment by zhenlan** [comment]
@wangyuantao this is not supported today but we are adding support of it - so you can pass in your own context to feature filters for feature flag evaluation. Stay tuned for our next update.

**Comment by jimmyca15** [comment]
This functionality is being introduced in this PR: https://github.com/microsoft/FeatureManagement-Dotnet/pull/14

**Comment by jimmyca15** [comment]
This has been added in our most recent release: https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.0.0-preview-010610001-1263
