### ISSUE TITLE
How to refresh configuration in .NET Framework

### ISSUE THREAD

**Issue by VALLIS-NERIA** [Azure/AppConfiguration#136]
I followed [this instruction](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app) to create a console app. `ConfigurationManager.RefreshSection("configBuilders");` does no help.

**Comment by zhenlan** [comment]
@VALLIS-NERIA the .NET Framework configuration system does not support configuration change after the application is started. Please note this is a limitation of the .NET Framework `ConfigurationManager`.

**Comment by zhenlan** [comment]
@VALLIS-NERIA please let me know if you have other questions. I am closing this issue for now.
