### ISSUE TITLE
Conflicts IAsyncEnumerable class under .NET Core 3.0

### ISSUE THREAD

**Issue by xin9le** [Azure/AppConfiguration#139]
# Summary

If we use `IAsyncEnumerable<T>` class under .NET Core 3.0, build error occures because of conflict. Japanese error message is below.

> 型 'IAsyncEnumerable<T>' が 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' と 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' の両方に存在します。

This occurs because the App Configuration library uses [Ix.NET](https://github.com/dotnet/reactive) v3.x. C# 8.0 now supports asynchronous streams (= `IAsyncEnumerable<T>`) as language level, so this conflict increases the potential for users that want to use Azure App Configuration to suffer.

![image](https://user-images.githubusercontent.com/4776688/64917991-95edbb80-d7d2-11e9-9bf9-bb589fbd9a33.png)

# Expect

We want you to resolve conflict to develop under latest environment (C# 8.0 + .NET Core 3.0 + Azure App Configuration). I think that changing the `System.Interactive.Async` package version to **v4** will fix this issue.

**Comment by xin9le** [comment]
Today, `Ix.Async` v4 has been GA :)
https://twitter.com/ReactiveX/status/1176981568491048961?s=20

**Comment by zhenlan** [comment]
This issue will be addressed in an updated release next week.

**Comment by aL3891** [comment]
its been two weeks now, any word on that update? :)

**Comment by abhilasharora** [comment]
@xin9le @aL3891 We just released version `2.1.0-preview-010380001-1099` of the Nuget package `Microsoft.Extensions.Configuration.AzureAppConfiguration` that no longer depends on `System.Interactive.Async`.
