### ISSUE TITLE
Please change the namespace of the Configuration extensions methods

### ISSUE THREAD

**Issue by shibayan** [Azure/AppConfiguration#140]
As a convention of .NET Core / ASP.NET Core, the extension method namespace is generalized.

### Azure App Configuration (2.0.0-preview-009470001-1371)

![image](https://user-images.githubusercontent.com/1356444/64954044-68cb0700-d8bf-11e9-9dd5-6282f09f21cf.png)

### Example: Key Vault

![image](https://user-images.githubusercontent.com/1356444/64953975-420cd080-d8bf-11e9-86e5-19c517054bb3.png)

I'd like you to change the namespace to match other Configuration libraries.

**Comment by jimmyca15** [comment]
This is a breaking change. We can still take it at this point but we will need to weigh out the pros and cons on this.

**Comment by abhilasharora** [comment]
@shibayan Thanks for the feedback. Since this is a breaking change, it might take a while, but we will include it in our next major release for the configuration provider.

**Comment by shibayan** [comment]
@abhilasharora I think that Breaking change is allowed while previewing. You actually have deleted the Watch / WatchAndReloadAll method.

It was quite a breaking change for me

**Comment by jimmyca15** [comment]
@shibayan I believe we moved from 1.x.x to 2.x.x with that change though? We certainly can make the change when we go to 3.x.x

**Comment by shibayan** [comment]
@jimmyca15 Umm. In general, don't change the major version in preview. It is strange that the SDK version is v2.x.x or v3.x.x in the first release of the service 😕 

I think it is important for usability to follow general rules.

**Comment by abhilasharora** [comment]
@shibayan We just released version `2.1.0-preview` of the packages with the namespace change.
