### ISSUE TITLE
Event grid subscriptions no longer working

### ISSUE THREAD

**Issue by nhart12** [Azure/AppConfiguration#142]
I had created some EventGrid subscriptions to a preview app configuration instance in East US. Today I can no longer see the subscription and receive the following error when clicking on Events

![image](https://user-images.githubusercontent.com/8458409/65277272-2982fd00-daef-11e9-95d0-9b063ec08c34.png)

Are event grid subscriptions really no longer available in East US or is this a UI bug?

**Comment by jimmyca15** [comment]
@nhart12 This is a UI bug, working on resolving it. Thanks for notifying us!

**Comment by jimmyca15** [comment]
This has been resolved.

**Comment by nhart12** [comment]
Thanks @jimmyca15 the UI seems to work now, the events however are not firing consistently in our app configuration instance

**Comment by jimmyca15** [comment]
@nhart12. Is this happening in a single region with a single store? Do you mean events are firing sometimes, and then not firing other times or that they're not firing at all?

**Comment by nhart12** [comment]
@jimmyca15 So this is happening in our East US store. Just tried again this morning, created a couple settings, updated them several times and then deleted. I have an EventGrid subscription setup for key-value Modified and Deleted. Only the deleted events fired

**Comment by jimmyca15** [comment]
There was a bug in event grid publishing identified last week. We are in the process of rolling out our fix for that. That may be causing your issue. When the fix is rolled out I will let you know.

**Comment by nhart12** [comment]
Ok perfect thanks for the info @jimmyca15 !

**Comment by jmsalvo** [comment]
@jimmyca15 Can you provide an update regarding when you anticipate the event grid publishing issues may be resolved?  Also, is a GA estimate available...the most recent discussion around this mentioned October timeframe, is that still a possibility?

**Comment by jimmyca15** [comment]
@jmsalvo event grid publishing changes are getting rolled out region by region. Expected to all regions by thursday eod.

Estimated GA is still end of October. Thanks.

**Comment by jimmyca15** [comment]
Yesterday we deployed a fix to event grid to improve some event publishing reliability issues we were facing. Please open another issue if you are still experiencing problems.

**Comment by zhenlan** [comment]
Hi @nhart12 and @jmsalvo, I want to give you an update. We just posted our GA and pricing plan. Please check it out.
https://github.com/Azure/AppConfiguration-Announcements/issues/2
