### ISSUE TITLE
readme: Slack invite link has expired

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/AppConfiguration#146]
This link in the readme:

Slack: https://aka.ms/azconfig/slack

Leads me a page at slack that says "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available." and I'm unable to join.

**Comment by zhenlan** [comment]
@richardpark-msft can you please try again? The link is set to not expire, but @yegu-ms just refreshed it anyway.

**Comment by richardpark-msft** [comment]
That did it - thanks!
