### ISSUE TITLE
Unable to create a new key-value using the Configuration explorer

### ISSUE THREAD

**Issue by anujab** [Azure/AppConfiguration#150]
I'm trying to create the config values by clicking the 'Create' button in the Configuration explorer. The create blade opens up. After I enter the key and value, and I click the 'Apply' button, I'm getting a popup error - "ajaxExtended call failed". And the key-value is not getting created.

More details from the console:
 [Microsoft_Azure_AzConfig]  ‎5‎:‎10‎:‎33‎ ‎PM Resource/CreateEditItemBlade 0 CreateEditItemBlade: Failed to update key/label: daf/, action: 0, reason: _errorData: undefined
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.AjaxError","MsPortalFx.Errors.Error"]
code: undefined
data: {"uri":"https://rmsvcappconfig.azconfig.io/kv/daf?label=%00&api-version=1.0","type":"PUT","pathAndQuery":"","failureCause":"","sessionId":"5a52381642d34c84a2ef1dc10a52030a","status":0,"statusText":"error","duration":189.5}
description: ajaxExtended call failed

I'm unable to use Azure App Config altogether because of this. Is this a bug or am I missing something here?

**Comment by zhenlan** [comment]
Thanks for reporting the issue, @anujab. After a quick check, the request did not appear to reach the App Configuration service. Depending on your location, it may take a while for the DNS name of your AppConfig store to propagate to your DNS servers, so it may fail if you try to access it right after the store is created. If it's still not working now, then it's unlikely the DNS issue. Another possible reason could be the firewall. Do you think if it's possible there is a firewall rule either on your local machine or on your local network that could block the traffic to *.azconfig.io?

**Comment by anujab** [comment]
It was a firewall issue on my local machine. I'm able to successfully create key-values from a different system. Thank you!
