### ISSUE TITLE
Getting an error while loading configuration explorer in Azure App Configuration

### ISSUE THREAD

**Issue by chintan2201** [Azure/AppConfiguration#152]
In Azure App Configuration, 
- I am getting an error while going to configuration explorer and load all the key- value pairs. 
  If I try to click on that error, it is loading "Overview" screen of the resource.
- I have tried this action with both "Owner" and "Contributor" access to the RG. I have approx 47 key-value pairs but I am not able to see anything.

![AppConfigError](https://user-images.githubusercontent.com/9345604/65733400-72086080-e083-11e9-9473-6c6566ee2fab.PNG)

**Comment by zhenlan** [comment]
Thanks for reporting the issue @chintan2201. Can you please try this again in a new incognito window so we rule out any browser caching issue? If this still does not work, could you please drop me an email with some details (eg. AppConfig store name, when did this happen, has it recovered) and I will see if I can find anything from the service side.

**Comment by chintan2201** [comment]
Hi Zhenlan,

It is also not working In incognito mode. Same Error.

It started from last two weeks. 

Exactly what is the information you need from resource? Resource ID or Name of resource?

How should I send this information? Please give me your email id.

Thanks,
Chintan

**Comment by zhenlan** [comment]
@chintan2201, thanks for the response.

Can you please navigate to the "Access control (IAM)" blade of your AppConfig store and make sure you or a security group you belong to are listed under either "contributor" role or "owner" role?

Did you try to create a new AppConfig store, add some key-values and see if you have the same issue?

Just in case, can you please make sure you don't have a firewall rule either on the local machine or local network that may block you from access *.azconfig.io.

Please email me your name of the resource (or endpoint address), when did this happen, has it recovered? You can find my email in my profile by clicking my icon.

**Comment by chintan2201** [comment]
Hi Zhenlan,

Our issue is resolved. From your suggestion in previous comment, we found that our azure config url was blocked from SAW white listing. 

Thanks for giving us possible root causes. 

Thanks,
Chintan
