### ISSUE TITLE
GIGANTIC file sizes

### ISSUE THREAD

**Issue by DWAK-ATTK** [Azure/AppConfiguration#154]
When adding the nuget packages, as per these MS instructions ( https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-core-app ), it appears that it installs the entire AspNet Core runtime - inflating my console app from 9.2 MB to 21.8 MB.  

That's absurd.

**Comment by drago-draganov** [comment]
It's documentation issue. For console app, please use Microsoft.Extensions.Configuration.AzureAppConfiguration package.

https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/

**Comment by DWAK-ATTK** [comment]
Ah.  Thanks.

Wouldn't it be nice if there were unit tests for documentation.

**Comment by zhenlan** [comment]
PR to fix the doc: https://github.com/MicrosoftDocs/azure-docs/pull/39823
