### ISSUE TITLE
No explanation for using Labels

### ISSUE THREAD

**Issue by yegu-ms** [Azure/AppConfiguration#156]
Tracking issue for https://github.com/MicrosoftDocs/azure-docs/issues/34839

**Comment by zhenlan** [comment]
We sort of intentionally left out the label in quickstart documents to make the quickstart easy. Given the label is a concept of AppConfig, should we add a section in all quickstart documents to show how to use label too? We saw similar questions about label in the past too. Thoughts?

cc: @lisaguthrie

**Comment by lisaguthrie** [comment]
I absolutely agree that we need this documentation. I think a scenario-focused tutorial would be a better approach. Keep the quickstarts... quick.

**Comment by jpconnock** [comment]
If the label is not required to complete the quickstarts, I agree with Lisa -- let's create a tutorial that walks the customer through the use of labels from concept to implementation.  I'm syncing with Lisa this week, so I'll get details from her and put together a draft.

**Comment by junaid-ahsan** [comment]
Just like the quick start gives you the option at the end to continue to the tutorial for dynamically refreshing, another  tutorial for using labels is required. While not directly linked, but there is a tutorial for Feature Keys but nothing for Labels - that's what makes this an issue.

**Comment by stimms** [comment]
The issue I ran into getting this to work in a legacy .NET application was that while labels are talked about in a few places none of them mentioned how to filter by labels in the config builder. I think building a full framework version of this tutorial would solve the deficiency: https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-labels-aspnet-core.

I'm happy to write that if you agree with my suggested approach.

**Comment by lisaguthrie** [comment]
@stimms - if you have time, go for it! See [Contributing to Microsoft Azure documentation](https://github.com/MicrosoftDocs/azure-docs/blob/master/CONTRIBUTING.md) for information on how you can submit a PR. Tag me and I'll review.

**Comment by zhenlan** [comment]
This is addressed with the document 
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-labels-aspnet-core
