### ISSUE TITLE
Example Go authentication does not handle escaped path and escaped query string

### ISSUE THREAD

**Issue by tianweiliu** [Azure/AppConfiguration#160]
In the golang section of the authentication code : https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authentication.md#golang

signature is calculated based on `RawPath` and `RawQuery`, this is causing any api call to key or label containing special characters returning with 401 Unauthorized. For example, I have the following key-value and label pair using .Net Core config naming convention:
```json
{
    "key": "Database:Username",
    "label": "foo",
    "value": "bar"
}
```

Original code snippet:
```golang
pathAndQuery := req.URL.Path
if req.URL.RawQuery != "" {
	pathAndQuery = pathAndQuery + "?" + req.URL.RawQuery
}
```
This signs the following `pathAndQuery`: `/key/Database:Username?label=foo`, where the requested path is `/key/Database%3AUsername?label=foo`

Corrected code:
```golang
pathAndQuery := req.URL.EscapedPath()
if req.URL.Query().Encode() != "" {
	pathAndQuery = pathAndQuery + "?" + req.URL.Query().Encode()
}
```

**Comment by abhilasharora** [comment]
Thanks @tianweiliu for reporting the issue. This has now been fixed.
