### ISSUE TITLE
az cli can not filter on KV items with no label using the --label parameter

### ISSUE THREAD

**Issue by devblackops** [Azure/AppConfiguration#169]
According to the [docs](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value#query-key-values), you can query for KV items that don't have a label by using `label=%00`. This does not work when using the az cli.

Example
```
az appconfig kv list -n $appConfigName --label '%00'
```

When querying for no label **or** `E-1`, only items matching `E-1` are returned.

```
az appconfig kv list -n $appConfigName --label '%00,E-1'
```

**Comment by shenmuxiaosen** [comment]
Thanks for reporting this! The document that you mentioned is for restful API instead of CLI.  If you want to query items without a label just do 
```
az appconfig kv list -n $appConfigName --label ""
```

We do have a bug for listing multiple labels which contains "no label". We will fix this and add examples for query no label items in next release in November.

**Comment by perrymana** [comment]
That syntax didn't work for me (when using powershell) to query blank labels. Running:
```
az appconfig kv list -n $appConfigName --label ""
```
resulted in an error
```
az appconfig kv list: error: argument --label: expected one argument
```

Instead I needed to use this syntax:
```
az appconfig kv list -n $appConfigName --label=""
```

**Comment by shenmuxiaosen** [comment]
For current CLI implementation, we use empty string to represent null label. However, different command shell has different behaviors parsing the arguments. [Doc](https://github.com/Azure/azure-cli/blob/dev/doc/use_cli_effectively.md#quoting-issues). CLI framework team is still working on adding more details for quoting issues for powershell. 

Regarding to ``` az appconfig kv list ```  label issue, there is a [code review](https://github.com/Azure/azure-cli/pull/11036) ongoing to fix.

**Comment by zhenlan** [comment]
The fix has been merged.

**Comment by aadje** [comment]
As for clarity you can explicitly filter keys without a label in Powershell or cmd prompt using the \0 value in the label filter :
`az appconfig kv list -n myappconfig --label \0`
