### ISSUE TITLE
Demo app failed with internal server error

### ISSUE THREAD

**Issue by zhenlan** [Azure/AppConfiguration#175]
*From @harrchen88 commented on Sep 29*

https://github.com/microsoft/FeatureManagement-Dotnet/issues/16

**Comment by abhilasharora** [comment]
@harrchen What version of ASP.NET Core are you using? Have you try deleting the `bin` and `obj` directories and rebuilding the project? If the issue still persists, please share the code snippet so we can reproduce it on our end.

**Comment by zhenlan** [comment]
Hi @harrchen88, please let us know if you need any further assistance. Closing for now.
