### ISSUE TITLE
Clarification on GA pricing

### ISSUE THREAD

**Issue by EvanMulawski** [Azure/AppConfiguration#176]
GA pricing was announced here: https://github.com/Azure/AppConfiguration-Announcements/issues/2

1. What is a store? Is it one instance of App Config?
1. Is the pricing per-store or per-subscription? e.g. if I have three App Config instances, is the total cost $1.20/day or $3.60/day?

**Comment by lisaguthrie** [comment]
Hi @EvanMulawski,

1. Yes, a store is a single instance of App Config, aka a single App Config resource. When you go into the App Configuration blade in the portal -- each line listed there is a store/instance/resource.

2. Pricing is per store, not per subscription, so the scenario you outline would be $3.60/day.

**Comment by EvanMulawski** [comment]
Thanks, @lisaguthrie. At first, I was concerned about the high cost for this service where we have many small, independent applications and services (especially if not utilizing the Feature Management feature). However, after reviewing a [section of the documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value#design-key-namespaces), it looks like it is intended to drive developers to use a single store to support many applications across environments (meaning we only need one store).

**Comment by zhenlan** [comment]
@EvanMulawski, correct, use different stores as security boundaries, for example, prod vs. testing or use different stores for redundancy, for example, one as the backup of another; otherwise, use one store for your centralized storage of all your configuration.

**Comment by zhenlan** [comment]
BTW, we updated the announcement to use the term "resource" to refer to the store or instance of App Configuration. Thanks for the feedback, @EvanMulawski.

**Comment by abezverkov** [comment]
The pricing indicates 

> "Requests per day" = Unlimited (First 200,000 included in the daily charge. Additional requests will be billed as overage)

Will you clarify what the contents of a "Request" are, using the SDK?  For example:  Would a "Request" be per key or would it be a batch of all the keys pulled for the App at startup?  If the middleware was configured to refresh, would it again be per key or per batch of keys that were refreshed at one time?

Thanks!

**Comment by jimmyca15** [comment]
@abezverkov it sounds like you are referring to the `Microsoft.Extensions.Configuration.AzureAppConfiguration` package. This package is optimized to deliver configuration in as few requests as possible.

The startup scenario that you mentioned pulls key-values in batches of 100 (the most supported by the service), so there would be 1 request per 100 key-values pulled. However, if multiple select statements are used, for example to select different labels, they get pulled separately. 

When monitoring a single key-value a request is made to ensure that the value is up to date. This occurs as often as the configured refresh cache timeout. If using the "refreshAll" functionality, then it is a combination of a request of the single "sentinel" key and then optimized batch requests to reload configuration given that the sentinel has changed.

**Comment by abezverkov** [comment]
Thanks!  Just so I undertstand ... It sounds like in "typical" practice, it would pull the batch(es) at one request per batch (say at startup).  Then it would would request the sentinel key on the refresh cache schedule and if the sentinel changed it would repeat the batch(es) pull?   So most small web apps are going to be WELL under that 200,000 /day ...  But since there is one per sub,  you would go over with a combination of monitoring lots of single keys or labels, or having a LOT of apps.
