### ISSUE TITLE
Refresh does not reload Key Vault referenced secrets 

### ISSUE THREAD

**Issue by msajid** [Azure/AppConfiguration#177]
I was trying Key Vault reference feature and it looks like refresh doesn't work with referenced secrets. 

  <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="2.0.0-preview-010050001-38" />

**Comment by zhenlan** [comment]
If the secret is changed in Key Vault, the App Config would not know. This is the scenario a sentinel key would be useful to signal the application to reload configuration including secrets from the Key Vault.
