### ISSUE TITLE
Allow Geo-replication for App Configuration.  

### ISSUE THREAD

**Issue by msajid** [Azure/AppConfiguration#178]
Allow Geo-replication to achieve high availability and performance benefits. Currently there is no option other than creating multiple instances of the service and replicating manually using import/export feature.

**Comment by zhenlan** [comment]
Thanks for the suggestion @msajid. Yes, this is definitely something we would love to support in the future.

**Comment by drago-draganov** [comment]
Please check [Geo-replication overview](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-geo-replication)

**Comment by zhenlan** [comment]
The geo-replication feature reached GA today. See announcement https://github.com/Azure/AppConfiguration-Announcements/issues/29.
