### ISSUE TITLE
Refresh (in already running application instances) does not reload or crash when referenced Key Vault secret is deleted

### ISSUE THREAD

**Issue by msajid** [Azure/AppConfiguration#180]
If you delete a referenced Key Vault secret without removing the reference Key from App Configuration, running applications instances do not crash or reload other items, (probably due to the local caching) This behavior is misleading. Imagine if someone deletes a secret and forgets to delete the related key from the App Configuration, it might put applications in an invalid state. 

When you restart the application instance you get the following exception which is good and expected. 

Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException
  HResult=0x80131500
  Message=Key vault error. ErrorCode:, Key:MyApp1:Connection, Label:Development, Etag:VTVSei4raljcWNNSRWiydwpbNrx, SecretIdentifier:https://vault.azure.net/secrets/testsecret
  Source=Microsoft.Extensions.Configuration.AzureAppConfiguration
  StackTrace:
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureKeyVault.AzureKeyVaultKeyValueAdapter.<ProcessKeyValue>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<ProcessAdapters>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<SetData>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<LoadAll>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at AppConfigInAspnetcore.Program.Main(String[] args) in

**Comment by zhenlan** [comment]
Thanks for the feedback, @msajid. Just to make sure I understand, here is what you suggest

For an invalid Key Vault reference (eg. the actual secret is deleted),
- Throw at the app start-up time (ie. the first time load of configuration)
- Do not throw at configuration refresh (eg. triggered by sentinel key change)

This sounds reasonable to me. In the second case, however, the old value from Key Vault will be removed from the configuration instead of keeping a cached value. Does this work for you?

**Comment by drago-draganov** [comment]
It's by design. 
The secret from Azure Keyvault may have changed, but the Keyvault app config reference itself isn't. It's more or less like a shortcut to a file. One can delete the file, but the shortcut isn't affected. 
AppConfiguration doesn't cache/store Keyvault secrets. When it's asked to refresh, it will always try to fetch from Keyvault.
The issue here is that Keyvault didn't offer a mechanism to monitor secrets state - noting that integration with EventGrid (preview) was announced last week. Currently monitoring and refresh on Keyvault reference alone doesn't work. Using Sentinel Key may be a decent workaround, but it still  requites explicit action.

**Comment by msajid** [comment]
- Throw at the app start-up time (ie. the first time load of configuration) **Yes this is the expected behavior in my opinion and it works as expected.** 
- Do not throw at configuration refresh (eg. triggered by sentinel key change) **Yes this is exactly what is happening, I think client provider should throw exception at the refresh when secret doesn't exists or invalid. Here is how I experienced it.** 

1. Create a secret in Key Vault
2. Reference the secret in App Configuration
3. Start the application and it works perfectly and loads all the items including the one in Key Vault
4. Delete the secret from Key Vault
5. Modify sentinel and wait for the refresh to happen. Refresh never happens.
6. Stop the application and Start again. Exception thrown 

I think client provider should throw exception while refreshing if secret is invalid. 
I hope I was able to give better description this time.

**Comment by msajid** [comment]
@drago-draganov Thanks for the clarification, I am referring to a different issue. 
I think refresh does not happen when there is problem fetching a value for the Key Vault secret.

**Comment by drago-draganov** [comment]
I realized I was referring to different scenario by reading your last message. Sorry about that.

There are 2 different workflows to consider. 

###1. Loading configuration at startup:
Any error is propagated to the caller.

###2. Runtime Refresh:
Refresh is atomic - succeeds when all requested config settings are successfully materialized.

In ASP.NET Core app, if you call ```UseAzureAppConfiguration``` then the default refresh behavior is set up. That means all Refresh failures are ignored and the app keeps using __last known good configuration__.

If you prefer to employ different behavior (ex. crashing the app), don't call UseAzureAppConfiguration and add own middleware instead:

```cs
class MyAppConfigurationRefreshMiddleware
    {
        private readonly RequestDelegate _next;
        public readonly IConfigurationRefresher _refresher;

        public AzureAppConfigurationRefreshMiddleware(RequestDelegate next, IConfiguration configuration)
        {
            _next = next;

            //
            // Get IConfigurationRefresher
            _refresher = ((IConfigurationRoot) configuration).Providers.FirstOrDefault(p=> p is IConfigurationRefresher) as IConfigurationRefresher;
        }

        public async Task InvokeAsync(HttpContext context)
        {
            try
            {
                await _refresher.Refresh();
            }
            catch (KeyVaultReferenceException)
            {
                //
                // Keyvalue reference error
            }
            catch (Exception)
            {
                //
                // Ignore unknown errors for now (not the best approach).
                // We are working to provide spec for transitive errors that can safely be ignored here.
            }

            await _next(context);
        }
```

**Comment by msajid** [comment]
Thanks @drago-draganov this is exactly what I was looking for 👍.
