### ISSUE TITLE
Unable to delete configuration from ui

### ISSUE THREAD

**Issue by Prince269090** [Azure/AppConfiguration#181]
While trying to delete the configuration settings from Azure UI which below key, I am getting error.

```
Key= ~`!@#$^&()_+=[]{}|;"'<>./--1114869967
Value= value-~`!@#$^&()_+=[]{}|;"'<>./-
```

![image](https://user-images.githubusercontent.com/34852023/68208544-60599780-fff7-11e9-83d0-fcf54f4dba4e.png)

**Comment by zhenlan** [comment]
Hi @Prince269090 I'm able to create and delete the key (``~`!@#$^&()_+=[]{}|;"'<>./--1114869967``) from the Azure portal without problems. Do you mind to list the key using Azure CLI and share the outputs so I can be sure I am trying the same key.

![image](https://user-images.githubusercontent.com/10566826/68236334-d17a5a00-ffb9-11e9-8687-7dc357c830fd.png)

**Comment by zhenlan** [comment]
@Prince269090 Just noticed from your screenshot your label has special characters too. I'm able to repro the issue in this case.

@MSGaryWang can you please take a look?

**Comment by MSGaryWang** [comment]
This looks a known issue related to the inconsistent single quote encoding which lead to the wrong signature value. The fix is already on the way and should be deployed soon.

**Comment by zhenlan** [comment]
This is fixed.
