### ISSUE TITLE
Storing a SQLAzure connection string as a value

### ISSUE THREAD

**Issue by stilren** [Azure/AppConfiguration#186]
Hi! Im trying to store a value in a app configuration that is supposed to be used as a SQLAzure connection string but I cannot get the formatting of the value input right

Using .net framework 4.7.2

This would be the xml:
`` <add name="MyDb" connectionString="Server=(LocalDb)\MSSQLLocalDB;Database=MyDb;Integrated Security=true;ConnectRetryCount=3;ConnectRetryInterval=10;Connection Timeout=30;" providerName="System.Data.SqlClient" />``

How should I input the key-value in  so that the connection string is parsed correctly? Right now it is not picking up the Provider Name when reading the value as a ConnectionStringSetting object. I have tried many different formats. It works well for connection strings that does not need "providerName"

**Comment by StephenMolloy** [comment]
Presumably you are using 'Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration' for pulling connection string values into config?

In this case, the 'Microsoft.Configuration.ConfigurationBuilders.*' collection of builders are simple key/value substitutes. So they aren't really capable of providing what is essentially two values (connectionString, providerName) for one key out of the box. There are a few ways you can handle this situation though.

Iff you know that 'MyDb' will always use the SqlClient provider regardless of the actual connection string being pulled from AppConfiguration, then you can just hard-code that into your config file and use the AzureAppConfigurationBuilder in 'Strict' mode to replace the connectionString portion of the existing add element. (If this isn't working for you, please file a bug in the aspnet/MicrosoftConfigurationBuilders repo.)
```xml
<configBuilders>
  <builders>
    <add name="AzAppConfig" mode="Strict" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" />
  </builders>
</configBuilders>
<connectionStrings configBuilders="AzAppConfig">
    <add name="MyDb" connectionString="Will be replaced by the value of 'MyDb' that is pulled from AppConfiguration store" providerName="System.Data.SqlClient" />
</connectionStrings>
```


You could also run your AzureAppConfigurationBuilder in 'Expand' mode and use two AppConfig values to configure your connection string and provider. Your connection string xml would look like:
```xml
<add name="MyDb" connectionString="${MyDbConnStr}" providerName="${MyDbProviderName}" />
```


A third option that is available to you in the 2.0 (AppConfigurationBuilder is 1.0, but the rest of the builders from that repo will be 2.0) release of Microsoft.Configuration.ConfigurationBuilders.* (currently in preview, but it will RTM soon) is to develop a custom [section handler](https://github.com/aspnet/MicrosoftConfigurationBuilders#section-handlers) for <connectionStrings> that will be smart enough to see the value you pull from Azure AppConfiguration and populate both 'connectionString' and 'providerName.'

**Comment by stilren** [comment]
This works for my application! Thanks @StephenMolloy

**Comment by jimmyca15** [comment]
Looks like this was resolved.
