### ISSUE TITLE
Feature flags exported to JSON cannot be imported as feature flags

### ISSUE THREAD

**Issue by bryan-hicks** [Azure/AppConfiguration#189]
Feature flags exported to JSON cannot be imported as feature flags; they import as general dynamic configuration properties. If I try to change the content type to the feature flag content type in the portal, the operation fails because the feature flag content type is restricted.

**Comment by zhenlan** [comment]
The import/export of feature flags from/to files is not supported currently and will be added to Azure CLI first. @bryan-hicks, I will be using the issue #190 you created to track this item.

(PS. I believe you can still use CLI to set the feature flag content type.)
