### ISSUE TITLE
Support importing feature flags from service configuration JSON file

### ISSUE THREAD

**Issue by bryan-hicks** [Azure/AppConfiguration#190]
Please add support for importing feature flags from service configuration JSON files. E.g., I would like to be able to import something like the following:
``` json
{
  "FeatureManagement": {
    "MyFeature": {
      "EnabledFor": [
        {
          "Name": "Percent",
          "Parameters": {
            "Value": "50"
          }
        }
      ]
    }
  }
}
```

**Comment by zhenlan** [comment]
Thanks for the feedback, @bryan-hicks. We are adding the support of this to Azure CLI.

**Comment by zhenlan** [comment]
This is already supported in the latest release of CLI.

**Comment by leonids2005** [comment]
>This is already supported in the latest release of CLI.
I cannot find any documentation about it. Could you please provide a link?

**Comment by avanigupta** [comment]
@leonids2005 You can find documentation and some examples here: https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-import 
Alternatively, you can run **az appconfig kv import -h** from latest version of Azure CLI for usage instructions.
