### ISSUE TITLE
Support export/import of all elements. Not only by label.

### ISSUE THREAD

**Issue by mmigala** [Azure/AppConfiguration#192]
Hello,

would it be possible to add support for export/import of all elements in Azure app configuration ? Right now we have around 10 labels in our Azure app config. It's real pain to have to export them one label at a time which is really time consuming and not user friendly. The (No Label) option only exports elements with no Label. There should be option like 'All'.

![image](https://user-images.githubusercontent.com/24477615/69234862-75562f00-0b90-11ea-9f42-36e32e576bc8.png)

Regards.

**Comment by zhenlan** [comment]
Hi @mmigala, can you please help me to understand your scenario better?
1. JSON file doesn't have a concept of the label. When you export multiple labels, there could be multiple values for the same key. How do you like the exported file look like?
2. Do you mind to share why you need to export config to files repeatedly?

**Comment by mmigala** [comment]
Hey @zhenlan 

I don't care about the format as much as the possiblity to easily export/import my Azure app configuration in a single step. If there is such a funcionality as export I don't see why I have to do it in 9-10 steps which is required if I have labels. the same goes for export to different Azure app configuration (doesn't have to be a file)

Regards

**Comment by zhenlan** [comment]
@mmigala agreed. When exporting to another App Configuration store, we should allow exporting all labels with one click. Thanks for the suggestion.

**Comment by avanigupta** [comment]
Import/export of all elements between two App Configuration stores is supported in Azure CLI (2.0.81 or later). 

`az appconfig kv export --destination appconfig --name {PrimaryStore} --dest-name {SecondaryStore} --label * --preserve-labels -y`

**Comment by markleavesley** [comment]
It would be really nice if we could import/export to a file, with labels!

**Comment by xzuttz** [comment]
Is it possible to import/export from one subscription to another using az appconfig kv export ? I see there is a --subscription field but it seems that it looks for the primary store and destionation in that subscription.

**Comment by avanigupta** [comment]
> It would be really nice if we could import/export to a file, with labels!

@markleavesley, please see this issue for importing/exporting to a file with all labels: https://github.com/Azure/AppConfiguration/issues/552#issuecomment-964584196

**Comment by avanigupta** [comment]
> Is it possible to import/export from one subscription to another using az appconfig kv export ? I see there is a --subscription field but it seems that it looks for the primary store and destionation in that subscription.

@xzuttz, yes, that's possible with a command like this:

`az appconfig kv export -d appconfig --endpoint <SourceStoreEndpoint> --auth-mode login --dest-endpoint <SourceStoreEndpoint> --dest-auth-mode login  `

**Comment by jimmyca15** [comment]
It looks like this issue has been resolved. Avani has also provided details on file export capabilities. Please let us know if anything else comes up.

**Comment by zhenlan** [comment]
This issue is to track the portal work.

**Comment by jimmyca15** [comment]
This capability exists in the Azure CLI. Re-opening as work is ongoing for inclusion in the Azure Portal.

**Comment by xzuttz** [comment]
Thanks, works with cli!

**Comment by skironDotNet** [comment]
For example I have 20 labels, and all have some value XXX that I want to rename to YYY, so having export all would be nice because then I could do global find/replace and re-import all.

Would be nice to also export not by key prefix but by value "like" to minimize file size.

**Comment by zhenlan** [comment]
The import/export functionality in the Azure Portal has recently undergone a major update. Please open new issues if you have any further feedback.
