### ISSUE TITLE
UI hangs when filtering to a specific label in Configuration Explorer

### ISSUE THREAD

**Issue by jmsalvo** [Azure/AppConfiguration#193]
We recently noticed in the Configuration Explorer when a label is selected from the drop-down, the UI hangs/spins continuously and never displays the list of key-values associated with that label.

**Comment by zhenlan** [comment]
Thanks for reporting the issue, @jmsalvo. This has been fixed and will be deployed this week.

cc: @jiayi11 @MSGaryWang

**Comment by jiayi11** [comment]
Hello @jmsalvo. The fix for this issue is already been deployed. I'm closing this issue. But feel free to comment or reopen it if you have more questions.
