### ISSUE TITLE
Too many calls breaks key-value

### ISSUE THREAD

**Issue by andrewschmidt-a** [Azure/AppConfiguration#194]
We believe we are making too many calls to a key-value of app config and that it puts that key into a failed state. the reason for this is that we have a function that triggers on lifecycle changes from iothub and pulls a key from app config. When we create 1000+ devices in the span of a few seconds the key in app config starts returning this error

```
ExceptionMessage: An exception occured while getting the value of tenant:403a8e56-447a-4794-9c9b-89611697a140:iotHubConnectionString from App Config:
StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
{
  Server: openresty/1.15.8.1
  Date: Fri, 22 Nov 2019 05:00:20 GMT
  Connection: keep-alive
  WWW-Authenticate: HMAC-SHA256 error="invalid_token", error_description="Invalid Credential"
  WWW-Authenticate: Bearer
  x-ms-request-id: 96d80253-f232-4c24-a238-d0ede00a349c
  x-ms-client-request-id: 0453ca94-5026-4fa0-aeee-ea38de69cfd5, 0453ca94-5026-4fa0-aeee-ea38de69cfd5
  x-ms-correlation-request-id: 96d80253-f232-4c24-a238-d0ede00a349c
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Credentials: true
  Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
  Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
  Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
  Strict-Transport-Security: max-age=15724800; includeSubDomains
  Content-Length: 0
}
```

All other keys work with the exact same code 

```
try
{
    ConfigurationSetting setting = this.client.Get(key);
    value = setting.Value;
}
catch (Exception e)
{
    throw new Exception($"An exception occured while getting the value of {key} from App Config:\n" + e.Message);
}

```
^ they are literally making the same call from the same line of code just to a different key

I also tried deleting the key and re adding it which I hoped would bring it to a success state. but that didnt work. It still gave me the error. 

Any limitations to app config that I am unaware of?

**Comment by zhenlan** [comment]
@andrewschmidt-a, it appears the request is throttled. The exception message is misleading that we will need to take a look.

The App Configuration is targeting server/services scenario at this point, so when 1000+ requests coming for the same config store at the same time, they may be throttled. It will be more efficient if you could load and cache all configuration when the function app starts up and serve key-values from the cache in later function calls. You can refresh the cached configuration as necessary. We updated the Azure Functions doc recently. Please let me know if this is feasible for you.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-functions-csharp

**Comment by zhenlan** [comment]
BTW, can you please share the version of the SDK you are using?

**Comment by andrewschmidt-a** [comment]
we are using 1.0.0.preview!

However we actually found it is not originating from an azure function but one of our C# APIs. 

Is there any information on the behaviour of the throttling? do we get cut off for a day? is it scoped to the key that you pounded over and over?

**Comment by drago-draganov** [comment]
@andrewschmidt-a

Throttling tells the client to slow don't a bit and retry. All of this is handled automatically by the SDK. In this case it seems you've hit a issue with 1.0.0.preview SDK. It should be addressed in the [latest](https://www.nuget.org/packages/Azure.Data.AppConfiguration/) release.

Regarding throttling policy, please refer to [App Configuration GA notes](https://github.com/Azure/AppConfiguration-Announcements/issues/2). Only a free tier can be cut for the rest of the day if exceeds the assigned quota.

For REST protocol specifics check [Throttling](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/throttling.md)

**Comment by drago-draganov** [comment]
@andrewschmidt-a

Throttling tells the client to slow don't a bit and retry. All of this is handled automatically by the SDK. In this case it seems you've hit a issue with 1.0.0.preview. It should be addressed in the [latest](https://www.nuget.org/packages/Azure.Data.AppConfiguration/) release.

Regarding throttling policy, please refer to [App Configuration GA notes](https://github.com/Azure/AppConfiguration-Announcements/issues/2). Only a free tier can be cut for the day, if exceeds the daily quota.

For REST protocol specifics check [Throttling](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/throttling.md)

**Comment by drago-draganov** [comment]
@andrewschmidt-a 

Here are the details of the issue I referenced earlier.

https://github.com/Azure/azure-sdk-for-net/issues/8171

**Comment by zhenlan** [comment]
@andrewschmidt-a thanks for the clarification it's not an azure function, the idea is the same though - instead of retrieving key-values from App Configuration for every call, please consider to load and cache the configuration at startup and refresh the configuration cache as necessary based on activity.

**Comment by zhenlan** [comment]
@andrewschmidt-a please let us know if you need any other assistance. I'm closing this issue for now.
