### ISSUE TITLE
Allow provided refresher to work in function apps like it does in api.

### ISSUE THREAD

**Issue by lpunderscore** [Azure/AppConfiguration#195]
In api projects, the refresher configured with the appconfiguration service is automatically handled when using the (app.UseAzureAppConfiguration()) middleware.

The middleware will call refresher.refresh(), which side note, returns a task which is never awaited and ends up only working on the subsequent call... but anyways.

That is not available in function apps, which forces us to manually inject the refresher into individual functions and call refresh manually everywhere.

We need to have a system like the one available in apis to handle the configured refresher automatically.

**Comment by shenmuxiaosen** [comment]
+ @abhilasharora

**Comment by drago-draganov** [comment]
@lpunderscore

Allow me to provide a bit of context. 

Configuration refresh is meant to be unobtrusive, background operation with bounded staleness consistency. Our goal is to stay of the way of the application request processing. This is the reason the ASP.NET Core middleware doesn't await the refresh operation. As you rightfully noted, the side effect is that the subsequent request will see the changes. I understand the inconvenience in some scenarios (ex. development, debugging, etc.), but I don't expect to be much of an issue it production (correct me if I'm missing something here). Saying that, there is a room for improvement. 

Can you elaborate a bit on the function app. Do you mean non-ASP.NET application, or you are referring to Azure Function App?

**Comment by lpunderscore** [comment]
@drago-draganov Hi,

Yes azure function apps, sorry for the confusion.

As for not awaiting the call, the only issue with it is when, for example, I change a value in app configuration service, I would expect my next call within 1 minute to an api in production to use those new values. But it will only be the second call to that api that will have the new values. Minor inconvenience in our case, and not really the goal of this issue :)

For function apps, I really think some kind of automated mechanism should be provided just like in apis. It looks, from what we could gather, that this would require some changes from the azure function app framework to allow adding middlewares maybe? no sure...

**Comment by drago-draganov** [comment]
Thanks, @lpunderscore 

Can you take a look at [Create an Azure Functions app with Azure App Configuration](
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-azure-functions-csharp)?

**Comment by lpunderscore** [comment]
I understand we can manually refresh in each function call, we have started to put this in place. But,  we have hundreds of functions across many function apps, this means putting this 1 liner everywhere in our functions. Starting to look like code smell to me. 

We need to be able to hook the refresh somewhere central that is executed on each function invoke.

I also do not think this is intuitive at all, since when using the ConfigureRefresh() fluent extension, we are under the impression that this will "automagically" enable key refresh. The reality is an additional step is required (adding the middleware). This is documented, I agree, but a solution for function apps should be provided.

thanks.

**Comment by drago-draganov** [comment]
@lpunderscore 

Got it. It's indeed specific of how Azure Function pipeline works. 

Perhaps [Azure Function Filter](https://github.com/Azure/azure-webjobs-sdk/wiki/Function-Filters) could be utilized to do refresh before each Azure Function call? Sadly, it's still in preview for really long time.

Since you are running Azure Functions it's possible to listen for App Configuration Events directly and and trigger configuration refresh. 
[Reacting to Azure App Configuration events](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-app-configuration-event)
[Route Azure App Configuration events to a web endpoint](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-app-configuration-event)

**Comment by lpunderscore** [comment]
Filters seem like a promising solution. Will look into that more. 

I think it might be worth documenting this somewhere for futur reference as this refresh functionality is going to be very popular.

**Comment by drago-draganov** [comment]
@lpunderscore 

Agreed. We are on it. Thanks for bringing up the topic!

**Comment by msajid** [comment]
I implemented a separate refresh function that runs on a timer trigger. 

https://github.com/msajid/AzureAppConfigurationDemos/tree/master/AppConfigDemos/AppConfigInAzureFunction/AppConfigInAzureFunctionDemo

**Comment by matthewkrieger** [comment]
@drago-draganov I ended up here because I'm using the [Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1) with Azure functions and Azure App Configuration does not appear to be available though the IOptions interface in Functions.

In my ASP.NET Core apps I register my configuration classes like this:

```
services.Configure<MyConfiguration>(Configuration.GetSection("MyConfiguration")); // Adds to IService collection
services.Configure<HerConfiguration>(Configuration.GetSection("HerConfiguration"));
and so on...
```

Then, I inject the configuration wherever I need it, for example: `IOptions<MyConfiguration> myConfig,`, 
 and access it via `myConfig.Value.MySetting1`, `myConfig.Value.MySetting2`, etc.

That's all standard stuff.  In the ASP.NET Core app I do `services.AddAzureAppConfiguration();` which adds the Azure App Configuration config to my services collection/configuration builder.  As a result I can do `myConfig.Value.MySetting1` (or `Configuration["MyConfiguration:MySetting1"]` and the setting will come from Azure App Configuration.

But I do not see an equivalent method for Azure functions.  So `Configuration["MyConfiguration:MySetting1"]` works just fine, but `myConfig.Value.MySetting1` does not.

Thoughts?

**Comment by zhenlan** [comment]
@matthewkrieger `IOptions`/`IOptionsSnapshot` should work just fine in Azure Functions. See the example:
https://github.com/Azure/AppConfiguration/blob/main/examples/DotNetCore/AzureFunction/FunctionApp/ShowMessage.cs

**Comment by matthewkrieger** [comment]
@zhenlan Interesting, thank you for that link. I believe I found my root issue.  I had my configuration builder set as follows:

```
IConfigurationRoot _config = new ConfigurationBuilder()
            .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
            .AddEnvironmentVariables()
            .AddAzureAppConfiguration("...")
            .Build();
```

And I was adding my types to the services collection like this:

```
builder
   .Services
   .AddOptions<MyConfiguration>()
   .Configure<IConfiguration>((e, configuration) =>
   {
      configuration
      .GetSection("MyConfiguration")
      .Bind(e);
   });
```
This wasn't working because _config isn't involved, so I simply changed to:

`builder.Services.Configure<MyConfiguration>(_config.GetSection("MyConfiguration"));`

My original premise was incorrect.

**Comment by tommck** [comment]
@zhenlan I'm confused by a lot of the discussion and conversation here.  Is it correct that you MUST use the ConfigRefresher, even if you are using IOptionsSnapshot and IOptionsMonitor in Azure Functions?  It will never auto-refresh like it will in regular .Net Core?

If so, has this changed in .Net 6?

**Comment by zhenlan** [comment]
@tommck yes, to have dynamic configuration update, you must use the `ConfigureRefresh` (which is not the problem discussed in this thread) AND you must call `TryRefreshAsync` in every function (which is the problem discussed in this thread).

In a normal ASP.NET Core application, you can add the App Configuration middleware once in a central place. The middleware will call `TryRefreshAsync` for you for every incoming request to your application so you don't have to call it in your code. In Azure Functions, however, they don't support the middleware concept, so you have to call `TryRefreshAsync` in every function in your code. This is not a problem in .NET 6 (or earlier versions), but a limitation in Azure Functions.

**Comment by tommck** [comment]
So this won't be fixed with Azure functions even in isolated mode where there is middleware support?

Seems like it should be supported in that instance at least

**Comment by drago-draganov** [comment]
To be honest, the recently added support for middleware in Azure functions is news to me. We will certainly look into supporting refresh in a similar fashion as ASP.NET Core app. Thanks for bringing it up @tommck!

**Comment by zhenlan** [comment]
Now that Azure Functions introduced the isolated mode, you can centralize your configuration refresh now.

First, define the middleware
```cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Middleware;
using Microsoft.Extensions.Configuration.AzureAppConfiguration;

namespace FunctionApp1
{
    internal class AzureAppConfigurationMiddleware : IFunctionsWorkerMiddleware
    {
        public IEnumerable<IConfigurationRefresher> Refreshers { get; }

        public AzureAppConfigurationMiddleware(IConfigurationRefresherProvider refresherProvider)
        {
            Refreshers = refresherProvider.Refreshers;
        }
        public async Task Invoke(FunctionContext context, FunctionExecutionDelegate next)
        {
            foreach (var refresher in Refreshers)
            {
                _ = refresher.TryRefreshAsync();
            }

            await next(context).ConfigureAwait(false);
        }
    }
}

```

Then, use it in *Program.cs* alone with the connection to Azure App Configuration
```cs
using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace FunctionApp1
{
    public class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration(builder =>
                {
                    builder.AddAzureAppConfiguration(options =>
                    {
                        options.Connect(Environment.GetEnvironmentVariable("ConnectionString"))
                               // Load all keys that start with `TestApp:`
                               .Select("TestApp:*")
                               // Configure to reload configuration if the registered 'Sentinel' key is modified
                               .ConfigureRefresh(refreshOptions =>
                                    refreshOptions.Register("TestApp:Settings:Sentinel", refreshAll: true)
                                );
                    });
                })
                .ConfigureServices(services =>
                {
                    services.AddAzureAppConfiguration();
                })
                .ConfigureFunctionsWorkerDefaults(app =>
                {
                    app.UseMiddleware<AzureAppConfigurationMiddleware>();
                })
                .Build();

            host.Run();
        }
    }
}
```

In your function, now you don't need to call `TryRefreshAsync` anymore. Configuration data is accessible via `IConfiguration` obtained through the dependency injection as you did it before. For example,
```cs
using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public class Function1
    {
        private readonly IConfiguration _configuration;
        private readonly ILogger _logger;

        public Function1(IConfiguration configuration, ILoggerFactory loggerFactory)
        {
            _configuration = configuration;
            _logger = loggerFactory.CreateLogger<Function1>();
        }

        [Function("Function1")]
        public HttpResponseData Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
        {
            _logger.LogInformation("C# HTTP trigger function processed a request.");

            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            string key = "TestApp:Settings:Message";
            string message = _configuration[key];

            response.WriteString(message ?? $"Please create a key-value with the key '{key}' in Azure App Configuration.");

            return response;
        }
    }
}
```

**Comment by drago-draganov** [comment]
I think it makes sense to put that in a package.

**Comment by zhenlan** [comment]
We just released a preview of middleware to support dynamic configuration in Azure Functions running in an isolated process ([release notes](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/MicrosoftAzureAppConfigurationFunctionsWorker.md)). You can also find an [example Function app](https://github.com/Azure/AppConfiguration/tree/main/examples/DotNetCore/AzureFunction/FunctionAppIsolatedMode) that uses the middleware. With this, you don't have to call `TryRefreshAsync` in each of your functions anymore. Please let us know if you have any feedback.
