### ISSUE TITLE
Cannot use 3.0.0-preview-010560002-1165 in .NET Core 3.0

### ISSUE THREAD

**Issue by martin-pes** [Azure/AppConfiguration#198]
I have tried to follow [tutorial](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app) in an ASP.NET Core 3.0 app.

However I get a following error when I add `3.0.0-preview-010560002-1165` version of `Microsoft.Azure.AppConfiguration.AspNetCore` to my project:

```
This version of Microsoft.AspNetCore.App is only compatible with the netcoreapp2.2 target framework. Please target netcoreapp2.2 or choose a version of Microsoft.AspNetCore.App compatible with netcoreapp3.0.
```
The added nuget package has a yellow exclamation mark in Visual Studio Solution Explorer - Dependencies window

This is my project file:
```
Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AssemblyName>Avarda.Tools.Test.Web</AssemblyName>
    <RootNamespace>Avarda.Tools.Test.Web</RootNamespace>
    <UserSecretsId>c369d5f5-66b5-479d-a28f-a556e624f602</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

...
  
<ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.0-preview-010560002-1165" />
    <PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.11.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-rc4" />
  </ItemGroup>
...
```

**Comment by zhenlan** [comment]
I just gave the `3.0.0-preview-010560002-1165` version a try with a new MVC app created from VS2019 template (targeting framework `netcoreapp3.0`). Everything works fine for me.

@martin-pes can you please confirm you do have .NET Core 3.0 SDK installed on your machine? I also find this [document](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio) about migration from ASP.NET Core 2.2 to 3.0. Hope it will be helpful to you.

**Comment by martin-pes** [comment]
I have the 3.0 SDK installed on my machine. I have also tried with a new Web API MVC app created from VS2019 and it works there.
My error occurs when I try to add the package to our existing Web API MVC app. This app was ported from ASP.NET Core 2.0 to 3.0 and works fine without `Microsoft.Azure.AppConfiguration.AspNetCore` package. I will try to play a bit more with app dependencies and get back here with more info.

**Comment by martin-pes** [comment]
I have tried to install the package on the solution originally causing the error but this time on a different machine. It works fine. I assume it must be something with my local nuget cache then.
Please disregard my issue.
