### ISSUE TITLE
Portal: Filtering key-values by date doesn't allow the date format used in key-values.

### ISSUE THREAD

**Issue by jimmyca15** [Azure/AppConfiguration#2]
![image](https://user-images.githubusercontent.com/21000428/51645133-d9906e00-1f40-11e9-8bab-2db176f7a727.png)

The portal show's last modified in a form like "12/14/2018, 15:33:39", but If I put this in the date time filter field then I get an error.

**Comment by mlacouture** [comment]
we'll look into this ...

**Comment by zhenlan** [comment]
The filter has been redesigned. Close for now and will watch out for future customer feedback.
