### ISSUE TITLE
Updating to version 3 throws "No managed identity endpoint found" with managed identity

### ISSUE THREAD

**Issue by b10-dslappendel** [Azure/AppConfiguration#201]
It seems that running version 3 doesn't work locally when trying to connect with managed identity.
I'm trying to run the following code:
```cs
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration(x =>
{
    x.Connect(new Uri("https://<name>.azconfig.io"), new ManagedIdentityCredential());
});
var config = builder.Build();
```

This doesn't work. I get the following unhandled exception:
```
Unhandled exception. Azure.Identity.CredentialUnavailableException: No managed identity endpoint found.
   at Azure.Identity.ExtendedAccessToken.GetTokenOrThrow()
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, String pageLink, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass14_1.<<LoadAll>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass14_1.<<LoadAll>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, HostType hostType, Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.CallWithRequestTracing(Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at ConsoleApp14.Program.Main(String[] args) in C:\Dev\ConsoleApp1\ConsoleApp14\Program.cs:line 19
   at ConsoleApp14.Program.<Main>(String[] args)
```

When using version 2.1 in the following way, it works fine:
```cs
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration(x =>
{
    x.ConnectWithManagedIdentity("https://<name>.azconfig.io");
});
var config = builder.Build();
```

I've used the [migration to version 3 mentioned here](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019).

It would seem that it works fine when running it in Azure functions.
In the app configuration access control, my account is added to the role 'App Configuration Data Reader', 'Reader' and 'Contributor'. Plus, I'm logged into my account in Visual Studio just fine.

I've also noticed that it tries to request information from http://169.254.169.254, which isn't available on my machine.

Am I missing something, or is it really a bug?

**Comment by zhenlan** [comment]
Hi, @b10-dslappendel it is expected that the `ManagedIdentityCredential` will only work when the application is deployed to an Azure service that supports managed identity, for example, Azure Function, App Service, Virtual machines, etc.

The pre v3 API `ConnectWithManagedIdentity()` worked locally in the past is because it falls back to local credentials automatically when it detects managed identity is not available. A similar functionality now can be achieved by using the [`DefaultAzureCredential`](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet). I did run into an [issue](https://github.com/Azure/azure-sdk-for-net/issues/8945) with it myself, but please let me know if it works for you.

**Comment by b10-dslappendel** [comment]
Thanks for the quick response.

I've tried `DefaultAzureCredential`, but sadly it doesn't work. If I don't specify any options, it fails:
```
Azure.RequestFailedException: 'Service request failed.
Status: 500 (Internal Server Error)

Headers:
Server: openresty/1.15.8.1
Date: Fri, 29 Nov 2019 09:04:59 GMT
Connection: keep-alive
x-ms-request-id: 3970d7c4-dd41-4088-94cc-f76217781c25
x-ms-client-request-id: 709c7e42-9a7f-43b0-84cc-5c1c3c112307
x-ms-correlation-request-id: 3970d7c4-dd41-4088-94cc-f76217781c25
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0
```

So instead, I also tried adding a `SharedTokenCacheTenantId` since I'm part of multiple tenants, and I've had this issue before with connecting to databases with `AzureServiceTokenProvider`. Sadly, this doesn't work either, and it fails with:
```
SharedTokenCacheCredential is unavailable
No account matching the specified tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx was found in the cache.
To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on.
[ {username: ****** tenantId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy} ].
```

The username it uses is my email address, which is correct, but the tenant id is different from the one I put in. I wonder what's happening here.
I'm hoping that I don't have to add any additional configurations though. v2 worked without manually providing any additional information.

**Comment by zhenlan** [comment]
@b10-dslappendel thanks for sharing the details.

Here is the error message for the response you shared above when you used `DefaultAzureCredential` without any options. Looks like the client did acquire an AAD token (likely via falling back to `SharedTokenCacheCredential`), but the token failed validation on the server-side. The server should have responded 401 instead of 500, which we will be looking into.

`The access token is from the wrong issuer 'https://sts.windows.net/471bxxxxxxxx/'. It must match the tenant 'https://sts.windows.net/4d00yyyyyyyy/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/4d00yyyyyyyy' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.`

I hope the error message above can give you some clue of how to fix it. It's probably related to the multi-tenant environment you mentioned. If you expect this works automatically, maybe it's a good idea to report the issue in the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) repo too.

I totally understand the pain of going through this change while the old API just works. The new API opens up the support of generic AAD authentication and a variety of ways to obtain the AAD token (eg., not limited to the system-assigned managed identity anymore). I hope we can hash out all the issues in `Azure.Identity` quickly and thanks for helping this.

**Comment by b10-dslappendel** [comment]
I expected that the internal server error would be something like this. However, even with the additional information, it seems that I cannot solve it on my side (unless I'm missing something). It would just bring me back to the second part of my issue, where I explicitly set the tenant id.

In your message, 471b is my home tenant, whereas 4d00 is the tenant where the app configuration instance resides in. Respectively that would be the masked yyyy and xxxx tenants from my message.

I have a feeling that it somehow only sees my home tenant, and not any other tenants. Because even with explicitly setting the tenant id to the app configuration instance, it doesn't work. I'll make sure to report it in the repo you mentioned as well.

I understand the possibilities of having a more generic way of authenticating. I hope we can update to the newer version quickly, but if it turns out to be something that needs to be fixed/added, is there any indication of how long the older API will be supported?

**Comment by zhenlan** [comment]
Thanks for reporting the issue in the SDK repo. If a token can be sent with the tenant id 4d00 (the same tenant of App Configuration instance), I think it would work. We will need authors of `SharedTokenCacheCredential` to shed some light here on why a token cannot be acquired when you set the tenant id explicitly.

The v2 API `ConnectWithManagedIdentity()` will continue to work and we have no plan to break it from the server-side. However, it won't be part of the GA release.

**Comment by davidjsteele** [comment]
Hi, It also seems that with the use of DefaultAzureCredential and the new version, that the account logged in with Visual Studio does not work for local development,  this certainly used to be the case. 

@zhenlan My current code is pretty match identical to the current pull request, can you authenticate locally where using MSI in combination with a key vault client?

`  return new ConfigurationBuilder()
                .AddAzureAppConfiguration(options => options
                    .Connect(new Uri(config["AppConfig:Endpoint"]), new DefaultAzureCredential())
                    .Select("Api:*", "EnterpriseConnect-Local")
                    .Select("Services:*", "EnterpriseConnect-Local")
                    .ConfigureRefresh(o =>
                    {
                        o.Register(key: "EnterpriseConnect-Local-Sentinel", label: LabelFilter.Null, refreshAll: true);
                    })
                    .UseAzureKeyVault(kv))
                .Build();`

Error message i'm getting when i run my tests,

Azure.Identity.AuthenticationFailedException : The DefaultAzureCredential failed to retrieve a token from the included credentials.
  EnvironmentCredential is unavailable Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ].
  ManagedIdentityCredential is unavailable No managed identity endpoint found..
  SharedTokenCacheCredential is unavailable No accounts were found in thecache.  To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on..

I have also tried to login and set my subscription via azure cli to no avail.  Any ideas, I can create a new issue if required.

Thanks David

**Comment by zhenlan** [comment]
@davidjsteele Looks like in your case, it's `SharedTokenCacheCredential` that does not work for you. Are you in a multi-tenant environment too? Have you signed into the Visual Studio (I assume that's what you are using)? You may have to report an issue in the [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) repo to get further assistance about `SharedTokenCacheCredential`.

In my case, I did have this [issue](https://github.com/Azure/azure-sdk-for-net/issues/8945) when running the code locally, but if I disable managed identity or I use `SharedTokenCacheCredential` explicitly, it does work. When I have the code deployed to App Service, managed identity works just fine as expected.

**Comment by a-patel** [comment]
I am also getting the same error in version 3.x

**Comment by zhenlan** [comment]
Both issues discovered in this thread are tracked in the Azure SDK repo. They are tracked to be fixed early next year.
- https://github.com/Azure/azure-sdk-for-net/issues/8945
- https://github.com/Azure/azure-sdk-for-net/issues/8957

@a-patel, if you think you ran into something different, please share more details or open a new issue at [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net).

**Comment by zhenlan** [comment]
Just an update:

- Azure/azure-sdk-for-net#8945
  - Fixed in https://www.nuget.org/packages/Azure.Identity/1.1.1
- Azure/azure-sdk-for-net#8957
  - Fix will be available in March (according to the Azure SDK team)

**Comment by abbasc52** [comment]
The preview version of Azure.Identity has added azure cli login and it works with keyvault.
However if i use the same with azure App configuration it throws 400 error and says "Cookie or Header size too large"

I am stuck with this issue and only able to use connectionString at this moment 😞 
```
new ConfigurationBuilder()
                        .AddAzureAppConfiguration(options =>
                        {
                            //this throws 400 error with DefautlAzureCredential
                          options.Connect(Environment.GetEnvironmentVariable("AzureAppConfigEndpoint")); 
                           // but this works                           
                           options.ConfigureKeyVault(kv => kv.SetCredential(new DefaultAzureCredential())); 
                        })
```

**Comment by zhenlan** [comment]
@abbasc52 can you please open a separate issue? It doesn't sound related to the current one.

**Comment by abbasc52** [comment]
@zhenlan I was facing the same issue as mentioned. I was using Managed Identity in v2 which worked with user login in local. I followed the steps to migrate to v3 and also the the steps mentioned here and now i am getting the 400 error.

I posted it here as i found it related. Should i go ahead and create a new issue for this?

**Comment by gbelzile** [comment]
I just converted a project from 2.2 to 3.1 using Azure.Identity 1.1.1 and I'm getting the same error: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.

Here is the code:
`configurationBuilder.AddAzureAppConfiguration(options =>
            {
                options.Connect(new Uri(configEndpoint), new DefaultAzureCredential())
                    .ConfigureRefresh(refresh =>
                {
                    refresh.SetCacheExpiration(TimeSpan.FromSeconds(60));
                }).ConfigureKeyVault(kv =>
                    kv.SetCredential(new DefaultAzureCredential(new DefaultAzureCredentialOptions())
                ));
            });
`

**Comment by zhenlan** [comment]
@gbelzile, can you please open a new issue at [azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net) and share more details such as call stack in exception, environment etc?

**Comment by KirubelTolosa** [comment]
@zhenlan
I am running into the same kind of problem. I followed the steps in the documentation to add the service principal and enable system managed identity. Here's the error I am getting. I have referenced two key vault secrets in my appConfiguration. The app is registered in Azure AD.

`CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
Azure.Identity.ManagedIdentityClient.AuthenticateAsync(bool async, TokenRequestContext context, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, bool async, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueAsync(HttpMessage message, bool async)
System.Threading.Tasks.ValueTask<TResult>.get_Result()....`

My code in **Program.cs**
`public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            webBuilder.ConfigureAppConfiguration((hostingContext, config) =>
            {
                var settings = config.Build();
                var credentials = new ManagedIdentityCredential();
                config.AddAzureAppConfiguration(options =>
                {
                    options.Connect(new Uri(settings["AppConfig:Endpoint"]), credentials);
                    options.ConfigureKeyVault(kv =>
                            {
                                kv.SetCredential(credentials);
                            });
                });
            })
            .UseStartup<Startup>());`

**Comment by zhenlan** [comment]
@KirubelTolosa the code looks fine. The error suggests the code is running in an environment where the managed identity is not available. Which Azure service is the code running from? Can you check out the comments I had in the StackOverflow post below?

https://stackoverflow.com/questions/61729522/403-when-connecting-to-azure-app-configuration-using-a-managed-identity/61738355#61738355

**Comment by KirubelTolosa** [comment]
@zhenlan Thank you for your prompt response. The code is running in AppService. Here is the exception being thrown..(From the deployed app logs). I have checked all points as in your comment as well as deployed other new apps that worked fine reading the configurations. 
````
Application: w3wp.exe
CoreCLR Version: 4.700.20.41105
.NET Core Version: 3.1.8
Description: The process was terminated due to an unhandled exception.
Exception Info: Azure.Identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async)
````
However, the app I am trying to use managed identity with is an already registered app under Azure AD to authenticate users. It has to do with that??

**Comment by zhenlan** [comment]
@KirubelTolosa if you use Azure portal, go to your instance of App Service, click 'Identity' under 'Settings' on the left, and then make sure the 'Status' is 'On under the 'System assigned' tab.

**Comment by KirubelTolosa** [comment]
> @KirubelTolosa if you use Azure portal, go to your instance of App Service, click 'Identity' under 'Settings' on the left, and then make sure the 'Status' is 'On under the 'System assigned' tab.

Everything is set right. Can't make sense out of this.

**Comment by zhenlan** [comment]
I believe most issues discussed in the thread have been addressed. Please open new issues if there is anything new.
