### ISSUE TITLE
Unable to use App Configuration from DevOps build pipeline

### ISSUE THREAD

**Issue by calloncampbell** [Azure/AppConfiguration#202]
After installing https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task&ssr=false#overview I tried to incorporate Azure App Configuration into my DevOps build pipeline. 

Expected behavior:
- Select Azure Subscription (and authorize)
- Select Azure App Configuration

Actual behaviour:
- Select Azure Subscription (and authorize) without issue
- No values in Azure App Configuration dropdown 

![image](https://user-images.githubusercontent.com/4095080/69818386-a2c35e00-11ca-11ea-8f18-2dfc8ea665a1.png)

![image](https://user-images.githubusercontent.com/4095080/69818359-95a66f00-11ca-11ea-84a4-5927f1adfbe4.png)

**Comment by zhenlan** [comment]
@calloncampbell can you please confirm you do have App Configuration stores already created under the selected subscription and you have owner permission to them?

**Comment by zhenlan** [comment]
@Yiming-Jia, any other suggestions?

**Comment by Yiming-Jia** [comment]
Hello @calloncampbell ,

I'm sorry for the inconvenience. Currently I'm not able to reproduce this issue under our testing build pipeline. Could you provide more information about this?

One thing could give us more details is that if you open `Developer Tools` (for Edge/Chrome) or `Web Developer` (for Firefox) and monitor the network request. When clicking the refresh button for `App Configuration name`, you could see a request with a similar endpoint to this `https://dev.azure.com/AppConfig-Test/518f0f28-9bcd-449a-93f3-d9d363967fa6/_apis/serviceendpoint/endpointproxy?endpointId=1157659f-b6f8-46c0-b1e9-3252693c49c8`. And under this response, it gives all the App Configuration names under the subscription you selected.

Another thing you could confirm is that the service connection in the build pipeline needs to be authorized for the subscription. For example, I have my selected service connection as a contributor role for the whole subscription.

Please let me know if you find more details.

**Comment by calloncampbell** [comment]
This is the error I see in Developer Tools window…
errorMessage: "Failed to query service connection API: 'https://management.azure.com/subscriptions/providers/Microsoft.AppConfiguration/configurationStores?api-version=2019-02-01-preview'. Status Code: 'NotFound', Response from server: '{"error":{"code":"SubscriptionNotFound","message":"The subscription 'providers' could not be found."}}'"

I did go into my
I did go into my Project pipeline service connections and for the one I selected for the above error, I added the Contributors role.
--
Callon Campbell
Cloud Solutions Architect | Software Developer | Microsoft Azure MVP
@flying_maverick | https://TheFlyingMaverick.com
+1 (416) 357-9114

**Comment by Yiming-Jia** [comment]
Hello @calloncampbell ,

What you replied helped us to locate the bug in `Azure App Configuration`extension. And we'll have a fix by today and keep you updated when the fix released.

**Comment by Yiming-Jia** [comment]
Hello @calloncampbell ,

The fix has just released. Could you please try it in your end? Thanks.

**Comment by calloncampbell** [comment]
Hi @Yiming-Jia  and thanks for the fix. Yes I can confirm that it works now. I appreciate the quick turnaround.
