### ISSUE TITLE
Error when accessing App Configuration and Key Vault using User Assigned Managed Identities

### ISSUE THREAD

**Issue by martinfletcher** [Azure/AppConfiguration#206]
I have a function app that has been assigned a User Assigned Managed Identity, and the identity has been granted the following access to an App Configuration and Key Vault resource:

Key Vault has the IAM Reader Role, and a Access Policy for Get and List of Secrets
App Configuration has IAM Reader Role

I am getting the following error in the Azure Portal when browsing to the trigger in the function app:

﻿﻿﻿#####
Error:

The function runtime is unable to start. Microsoft.Azure.Services.AppAuthentication: Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked. Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: {"StatusCode":400,"Message":"No MSI found for specified ClientId/ResourceId.","CorrelationId":"e360c419-4837-4ef9-b2ca-de971449a1ba"} Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "D:\local\LocalAppData\.IdentityService\AzureServiceAuth\tokenprovider.json" Parameters: Connection String: [No connection string specified], Resource: https://management.azure.com, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command, operable program or batch file. .

Session Id: 4784e9d0ef9041b68f5cd3794934febe

Timestamp: 2019-12-04T20:34:22.955Z

#####

I have heavily investigated this via the docs etc, and can not find any reason why this would happen.

This does work locally (although its via azure cli fallback) so code wise this is not an issue.

I have posted on the MSDN forums also for some help with this - Forum post: https://social.msdn.microsoft.com/Forums/en-US/8823c83a-164e-4619-b1a1-a272ff936525/error-when-accessing-app-configuration-and-key-vault-using-user-assigned-managed-identities?forum=AzureFunctions

Thanks

Martin

**Comment by zhenlan** [comment]
Hi @martinfletcher, sorry for running into this. 

Can you please confirm if you are using the [3.0.0-preview-010550001-251](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/3.0.0-preview-010550001-251) version of `Microsoft.Extensions.Configuration.AzureAppConfiguration`?

If so, can you please make sure you are following the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019) to set up the managed identity? Particularly, grant your user-assigned managed identity the **App Configuration Data Reader** role in your App Configuration IAM.

Please let me know if this works for you.

**Comment by martinfletcher** [comment]
Yeah, I discovered the new package version last night, and upgraded to this version following the release notes.

![image](https://user-images.githubusercontent.com/5081397/70220942-4ff42400-173f-11ea-98c0-b5c4c8f51b70.png)

The managed identity has the App Configuration Data Reader Role.

After the upgrade, this no longer works locally either - This is the error message:

```
[05/12/2019 09:09:53] A host error has occurred during startup operation 'c0e2e5f5-396b-4ade-8552-640b34a8aeb2'.
[05/12/2019 09:09:53] Azure.Data.AppConfiguration: Service request failed.
[05/12/2019 09:09:53] Status: 403 (Forbidden)
[05/12/2019 09:09:53]
[05/12/2019 09:09:53] Headers:
[05/12/2019 09:09:53] Server: openresty/1.15.8.1
[05/12/2019 09:09:53] Date: Thu, 05 Dec 2019 09:09:47 GMT
[05/12/2019 09:09:53] Connection: keep-alive
[05/12/2019 09:09:53] x-ms-request-id: 88331d55-53db-4e02-a69f-9ed2b3fbacd6
[05/12/2019 09:09:53] x-ms-client-request-id: e9fa78bc-a071-45e2-9b12-62d283b0f4a9
[05/12/2019 09:09:53] x-ms-correlation-request-id: 88331d55-53db-4e02-a69f-9ed2b3fbacd6
[05/12/2019 09:09:53] Access-Control-Allow-Origin: *
[05/12/2019 09:09:53] Access-Control-Allow-Credentials: true
[05/12/2019 09:09:53] Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
[05/12/2019 09:09:53] Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
[05/12/2019 09:09:53] Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
[05/12/2019 09:09:53] Strict-Transport-Security: max-age=15724800; includeSubDomains
[05/12/2019 09:09:53] Content-Length: 0
[05/12/2019 09:09:53] .
```

This is what I have:

```
var _isLocal = string.IsNullOrEmpty(Environment.GetEnvironmentVariable("WEBSITE_HOST_ID"));

configuration.AddAzureAppConfiguration(options =>
{
        options.Connect(
                new Uri(Environment.GetEnvironmentVariable("APPCONFIGURATION_ENDPOINT")),
                 _isLocal ? new DefaultAzureCredential()
                              : (TokenCredential)new ManagedIdentityCredential()
        );

        options.UseAzureKeyVault(
                new KeyVaultClient(
                        new KeyVaultClient.AuthenticationCallback(
                                new AzureServiceTokenProvider().KeyVaultTokenCallback
                        )
                )
        );
});
```

**Comment by martinfletcher** [comment]
Interestingly, when connecting locally using a connection string I do not get the error - This does (to a point locally at least) rule out Key Vault issues

**Comment by zhenlan** [comment]
@martinfletcher when you ran the code locally, it's NOT the managed identity that is used to authenticate with the App Configuration service. It's your local identity (see https://github.com/Azure/AppConfiguration/issues/201#issuecomment-559626040). 

According to the log you shared, you obtained the AAD token of the local identity successfully but the request to the service failed due to authorization (403). Please make sure you grant your local identity the App Configuration Data Reader Role too if you want the code to work locally (after you update the IAM, please wait a little bit for it to propagate).

**Comment by jimmyca15** [comment]
@martinfletcher are you passing in the client id of the user assigned identity as required by the `ManagedIdentityCredential` constructor in this scenario? [Constructor reference](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential.-ctor?view=azure-dotnet#Azure_Identity_ManagedIdentityCredential__ctor_System_String_Azure_Identity_TokenCredentialOptions_).

**Comment by martinfletcher** [comment]
@zhenlan - Yes its my local identity that is used when running locally. The AD group in which I am a member has the App Configuration Data Reader Role.

This is the error 
```
[05/12/2019 21:52:48] FAILED
[05/12/2019 21:52:48] Azure.Data.AppConfiguration: Service request failed.
[05/12/2019 21:52:48] Status: 403 (Forbidden)
[05/12/2019 21:52:48]
[05/12/2019 21:52:48] Headers:
[05/12/2019 21:52:48] Server: openresty/1.15.8.1
[05/12/2019 21:52:48] Date: Thu, 05 Dec 2019 21:52:46 GMT
[05/12/2019 21:52:48] Connection: keep-alive
[05/12/2019 21:52:48] x-ms-request-id: b22e1f62-ab5b-4ad0-aff2-012c1b6f8968
[05/12/2019 21:52:48] x-ms-client-request-id: 5950d151-817d-40cf-8c6d-2c99854c5f8f
[05/12/2019 21:52:48] x-ms-correlation-request-id: b22e1f62-ab5b-4ad0-aff2-012c1b6f8968
[05/12/2019 21:52:48] Access-Control-Allow-Origin: *
[05/12/2019 21:52:48] Access-Control-Allow-Credentials: true
[05/12/2019 21:52:48] Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
[05/12/2019 21:52:48] Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
[05/12/2019 21:52:48] Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
[05/12/2019 21:52:48] Strict-Transport-Security: max-age=15724800; includeSubDomains
[05/12/2019 21:52:48] Content-Length: 0
[05/12/2019 21:52:48] .
```

@jimmyca15 - The ManagedIdentityCredential does not work locally as it requires the AppService local MSI endpoints. This is the error:

```
[05/12/2019 22:01:41] FAILED
[05/12/2019 22:01:41] Azure.Identity: No managed identity endpoint found.
```

**Comment by jimmyca15** [comment]
@martinfletcher I was referring to your initial post where you mentioned you were using `ManagedIdentityCredential` within an Azure Function that had a **user**-assigned identity. I wanted to make sure the client id of the user-assigned identity was being passed to the `ManagedIdentityCredential`.

**Comment by martinfletcher** [comment]
@jimmyca15 Sorry, i got wires crossed answering both questions. This does not make a difference when running in azure.... still get same error (403)

**Comment by jimmyca15** [comment]
@martinfletcher just want to ensure we're on the same page here. 

You updated your code to use `new ManagedIdentityCredential(clientId: userAssignedClientId)` and are now getting a 403 in your Function App ? This is a different error than the initial error so I want to make sure that one has been resolved before solving the 403.

>Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: {"StatusCode":400,"Message":"No MSI found for specified ClientId/ResourceId."

**Comment by ssuing8825** [comment]
I'm using the latest 3.0.0 version and also get this error. I've added the client id but that didn't work. The 2.0 version works fine though. I'm using an App Service with a .Net Core app.

**Comment by zhenlan** [comment]
@ssuing8825 can you please share a bit more details - what code do you use and what error do you receive? And I assume the issue you have is *not* about running locally.

**Comment by ssuing8825** [comment]
Here is the Azure App Service site so you can see the error https://webdemoconfig-as.azurewebsites.net/ConfigTest.

Target Framework - netcoreapp3.0

I have these frameworks installed
```
 <PackageReference Include="Azure.Identity" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.0-preview-010560002-1165" />
    <PackageReference Include="Microsoft.Azure.KeyVault" Version="3.0.4" />
    <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.0.0" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.0.0-preview-010610001-1263" />
```

Here is the code
```
  public IActionResult Index()
        {
            try
            {
                IConfiguration configFromAzure = null;
                var endpoint = new Uri("https://aistestconfig-ac.azconfig.io");

                var builder = new ConfigurationBuilder();
                builder.AddAzureAppConfiguration(options =>
                {
                    var managedCredential = new ManagedIdentityCredential("11c097cf-7e5d-4b3d-982a-1ab9760e54f8");
                    options.Connect(endpoint, managedCredential)
                       .ConfigureRefresh(refresh =>
                       {
                            // This is where you you use a sentinal to avoid splicing
                            refresh.Register("myapp:Sentinal", refreshAll: true)
                                  .SetCacheExpiration(TimeSpan.FromSeconds(20));
                        });
                });

                configFromAzure = builder.Build();

            }
            catch (Exception ex)
            {
                ViewData["Error"] = ex.ToString();
            }
            return View();
        }

```

I used the 2.1.0 version and while I had some errors getting it right, they all made sense, and I was able to get it working smoothly. If you want exact steps to repo let me know.

**Comment by jimmyca15** [comment]
@ssuing 8825, Can you confirm that you assigned the `Azure App Configuration Data Reader` role to your user assigned managed identity?

**Comment by ssuing8825** [comment]
@jimmyca15 That did the trick. I changed it from `Contributor` to `Azure App Configuration Data Reader `and it works fine now. Thanks.

**Comment by jimmyca15** [comment]
@ssuing8825 apologies for the inconvenience. We are working on getting docs out on our official docs page now that we have put out Azure RBAC roles in preview. Right now the only docs are the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019) for the 3.0 library and the [authorization docs](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authorization/aad.md) in this GitHub repo. I think any others who experience the issue will benefit from your troubleshooting, so thank you.

**Comment by zhenlan** [comment]
@martinfletcher has your issue been resolved too?

**Comment by martinfletcher** [comment]
Sorry for the late reply on this!

No, I am still getting the same errors as stated above.

**Comment by jimmyca15** [comment]
@martinfletcher there are a few different scenarios and error codes in this thread. The initial error is about not being able to find a corresponding managed identity in a function app. Are you hitting that error, or are you still hitting a 403? If you are hitting 403, is it in the function app or is it local development?

**Comment by markgould** [comment]
I'm also getting a 403 error. Trying to run from Visual Studio after upgrading from version 2 to 3.0.0-preview-011100002-1192.

Trying to use my Azure identity for local dev, and then MSI when deployed (Haven't tried deploying it yet until I have it working in VS)

**Previous working code:**

```
config.AddAzureAppConfiguration(options =>
{
	options.ConnectWithManagedIdentity(appConfigEndpoint)
	    .Use(KeyFilter.Any)
	    .Use(KeyFilter.Any, "label");
});

```

**New code:**

```
builder.AddAzureAppConfiguration(options =>
{
	options.Connect(new Uri(appConfigEndpoint), new DefaultAzureCredential())
	    .Select(KeyFilter.Any)
	    .Select(KeyFilter.Any, endpointName);
});

```

Error info:

> Service request failed.
> Status: 403 (Forbidden)

> Headers:
> Server: openresty/1.15.8.1
> Date: Wed, 29 Jan 2020 19:32:38 GMT
> Connection: keep-alive
> x-ms-request-id: a173964b-eece-414d-8ee8-14d45dfa68d0
> x-ms-client-request-id: 7ff86eed-4cbf-436d-8fea-4a3c57893aaa
> x-ms-correlation-request-id: a173964b-eece-414d-8ee8-14d45dfa68d0
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
> Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
> Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
> Strict-Transport-Security: max-age=15724800; includeSubDomains
> Content-Length: 0

**Comment by jimmyca15** [comment]
@markgould did you assign the Azure App Configuration Data Reader or Azure App Configuration Data Owner role to the identity you are using to connect?

**Comment by markgould** [comment]
@jimmyca15 Yep!

![image](https://user-images.githubusercontent.com/2712328/73391190-15b98580-429d-11ea-814d-dc329dc0abcf.png)

**Comment by jimmyca15** [comment]
If you just recently added that role assignment it could take some time for the policy to propogate. This is also more likely if you sent some requests with that identity before adding the role assignment. Please wait a few minutes, 15 if possible for max effect, and try again.

**Comment by markgould** [comment]
After talking with @jimmyca15 this looks to have been a caching issue. After waiting a few minutes between requests after adding the role, it started working.

**Comment by TheSpid** [comment]
I am getting a 500 rather than a 403 using my personal azure credentials (logged in to VS) through DefaultAzureCredential. I have been assigned the relevant role as described earlier in this topic.
I'm not sure how related this is, but thought I'd share it in here.

Error message:

> Azure.RequestFailedException: 'Service request failed.
> Status: 500 (Internal Server Error)
> 
> Headers:
> Server: openresty/1.15.8.1
> Date: Thu, 30 Jan 2020 07:18:02 GMT
> Connection: keep-alive
> x-ms-request-id: 48babdfc-9349-4480-a825-b57abf132186
> x-ms-client-request-id: ebd1bd58-a93f-43d3-b49e-f880f0cc4de3
> x-ms-correlation-request-id: 48babdfc-9349-4480-a825-b57abf132186
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
> Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
> Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
> Strict-Transport-Security: max-age=15724800; includeSubDomains
> Content-Length: 0

Code:
```
    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        webBuilder.UseStartup<Startup>()
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
          var settings = config.Build();
          var env = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
          var credential = env.Equals("Development") ? new DefaultAzureCredential() : (TokenCredential)new ManagedIdentityCredential();
          config.AddAzureAppConfiguration(options => options.Connect(new Uri(settings["AppConfiguration"]), credential));
        })
        );
  }
```

**Comment by zhenlan** [comment]
> I am getting a 500 rather than a 403 using my personal azure credentials (logged in to VS) through DefaultAzureCredential.

@TheSpid this is being fixed. Deployment is in progress.

**Comment by jimmyca15** [comment]
@TheSpid 

Thanks for reporting the 500. As Zhenlan mentioned, a 500 should not be expected and we are deploying to fix that. A 401 or 403 should be expected for all authentication failures. In the meantime this issue should be able to be resolved without awaiting the deployment. Can you confirm that

1. The identity you are using via `DefaultAzureCredential` is assigned to either the Azure App Configuration Data Reader or Azure App Configuration Data Owner roles
2. The DefaultAzureCredential is requesting a token for the same AAD tenant that the target Azure App Configuration instance is in. You can find the AAD tenant ID in the Azure Portal by selecting Azure Active Directory > Properties > Directory ID

**Comment by leonids2005** [comment]
I am having problem accessing App Configuration (forbidden 403).  How can I troubleshoot this? Or could you please point me to the full documentation where I can get all the required information.

thank you
