### ISSUE TITLE
AppConfigurationOptions.Connect Secondary Connection string

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#209]
1) I would like to see the capability to provide both primary and secondary connection strings to `AzureAppConfigurationOptions.Connect`.  This would significantly improve our application's ability to get configuration when rolling primary/secondary keys.

The library should try the connection strings in order until successful.

````csharp
public AzureAppConfigurationOptions Connect(params[] string connectionStrings);
public AzureAppConfigurationOptions Connect(TokenCredential credential, params Uri[] endpoints);
````

**Comment by zhenlan** [comment]
@HashTagDotNet thanks for the suggestion. Can you please elaborate on how this can make it easier when you rotate keys, for example, you would have to do 5 steps ... (details) and with this, you only need 3 steps ... (details)?

**Comment by HashTagDotNet** [comment]
###  Set multiple connection strings on Connect()
Ideally, I would like to be able to provide 0..N additional connection strings to the Connect() method.  The library would attempt to read from each connection in provided order until one is successful.  Only when all connections are attempted and all have failed will the attempt to connect be considered a failure.

#### Use Case 1: Rolling Keys
With a single connection string, all the applications need to be upgraded at the same time when the connection string rolls (annually); or every app needs to be pulled from production, the secondary key set, and enabled in production.

With dual connection strings, each connection string's life is offset.  Then when the primary key is due for end-of-life, the secondary will have half of its life.  As applications are pulled due to the normal life cycle they will have their 'primary key' set to the active key, and the 'secondary key' set to the backup key.

Having a secondary key also helps address situations where the primary key was rolled but for some reason the application didn't get refreshed.

#### Use Case 2: 'Temporary Access
There may be times when temporary access to the configuration (e.g. auditing, contractor, etc.) must be granted.  With multiple connections, its possible to more frequently generate new connection strings and deprecate existing ones without affecting the primary one.

#### Use-Case 3: Intermittent Internet Connectivity
Our connectivity to the cloud is not reliable via speed or connectivity.  

We are setting up a pass-through proxy that we want to configure as a non-primary on-premise connection.  Thus when our application(s) cannot connect directly to Azure they will contact our on-premise solution.

On the event of internal network errors, our fail-over providers read/write to local on-disk encrypted cache.  The secondary connection string would allow the applications  to automatically connect to our centralized on-premise configuration server even when our network cannot connect to Azure.

#### Work Around
By configuring two different configuration providers using two different connection strings we can accomplish similar capabilities we are looking for.  When one of the keys change, it will fail but the other instance of the provider should still be able to retrieve settings.

While workable, I think being able to set a list of connections is much more elegant and better aligns with parameters exposed in Azure App Configuration.

#### Reference
Similar capabilities exist with [Azure Storage](https://blogs.msdn.microsoft.com/mast/2013/11/06/why-does-an-azure-storage-account-have-two-access-keys/)

**Comment by zhenlan** [comment]
Thanks for sharing more details, @HashTagDotNet.

**RE: Use Case 1: Rolling Keys**

I see it could save one step for key rotation
* *Before*
  An app is using the primary connection string initially.
  1. Regenerate secondary connection string
  2. Update app to use the secondary connection string
  3. Deploy app
  4. Regenerate the primary connection string (to invalidate the old one)

* *After*
An app is using both primary and secondary connection string initially
  1. Regenerate primary connection string
  2. Update app to use the new primary connection string
  3. Deploy app

A major benefit is any one of the connection strings can be regenerated at any time if it's found to be compromised and the app deployment does not have to happen immediately.

**RE: Use Case 2: Temporary Access**
This is achievable today as App Configuration already provides two connection strings. As long as you only give the connection string that is *not* used by the app for temporary access, the app won't be impacted.

**RE: Use-Case 3: Intermittent Internet Connectivity**
I don't see how a second connection string can connect to your *on-premises* configuration server when the network cannot connect to Azure.

However, this could potentially enable a better experience of fail-over if the provided connection strings are from different App Configuration stores.

**Comment by zhenlan** [comment]
Not exactly the same as what was proposed in this thread, but we are working on the support for geo-replication (#178). It will provide functionality very similar.
