### ISSUE TITLE
AppConfigurationOptions.Connect Timeout Option

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#210]
I would like to be able to set the HTTP timeout of the call.  We may choose to wait for configuration for longer/shorter periods of time depending of environments or other use-cases.

**Comment by zhenlan** [comment]
@HashTagDotNet this will be supported when we support custom `ConfigurationClientOptions` passed to `AppConfigurationOptions`. Similar to https://github.com/Azure/AppConfiguration/issues/179.

**Comment by zhenlan** [comment]
Duplicate of #179
