### ISSUE TITLE
AppConfigurationOptions.TrimKeyPrefix - Support Multiple Prefixes

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#211]
Is it possible to support multiple prefix trimming?  It would be very helpful for us in consolidating our configuration.

I know I can stand up multiple configuration sources in my application, but that seems like overkill.  We could also change our configuration to Reference "Global:<blah>" but that feels like a work around rather than a good solution.

At the moment we can trim only one set of prefixes within a single instance of the provider.

Our expected use case looks something like this::
````
// access shared resources/settings
Global:SomeSharedGlobalKey  value+{env-label}
Global:SharedLoggingService value+{env-label}

// application specific settings
myApp1:appvalue1
myApp1:appvalue2
myApp2:appValue1
````
And the configuration might look something like this:
`options.TrimKeyPrefix("Global","myApp1")`

If 'Global' (in this use-case) shares a trimmed key with 'myApp1' last one wins (to be consistent with everything else).

**Comment by zhenlan** [comment]
@HashTagDotNet I may not follow completely. Does this work for you?
```cs
options.TrimKeyPrefix("Global")
       .TrimKeyPrefix("myApp1")
```

**Comment by HashTagDotNet** [comment]
*Exit on First Match Strategy*

`.TrimPrefix()` would work for what I was looking for as long as `.TrimKeyPrefix()` always works on the original key and not the key that was trimmed with a prior `.TrimKeyPrefix()`.  For many of my use-cases, multiple prefix registrations should exit on first match.  

This might help prevent accidental removal of a key that was exposed by a prior trim operation.

So given these keys:

````
// access shared resources/settings
Global:SomeSharedGlobalKey  value+{env-label}
Global:Shared:LoggingService value+{env-label}

// some other key
Shared:ConnectionString   //key required by legacy code or some other reason

// application specific settings
myApp1:appvalue1
myApp1:appvalue2
myApp2:appValue1

````
And given this code: 
````
options.TrimKeyPrefix("Global:")
       .TrimKeyPrefix("Shared:")
       .TrimKeyPrefix("myApp1:")
````
I would expect these keys to be returned:
````
SomeSharedGlobalKey  value+{env-label}
Shared:LoggingService value+{env-label} // <-- notice we still have 'Shared:' a registered key prefix

// some other key
ConnectionString   // <-- prefix trimmed per registration

// application specific settings
appvalue1
appvalue2
myApp2:appValue1
````
So the above is a simple use case.

---
*Apply All Strategy*

For more advanced scenarios, I might what an 'apply all' behavior.

As I'm mapping out our enterprise configuration and leveraging a semantic hierarchy, I can easily see use-cases where I might want the trimming to occur in succession:

The first registered trim prefix is applied to a key, then the second registered prefix is applied to the result of the prior trim operation and so forth.  That way a hierarchy can be stripped down to it's leaf nodes.

````
node1:key1
node1:node2:key2

.TrimKeyPrefix("node1")
.TrimKeyPreFix("node2");
````
Would result in:
````
key1 
key2
````
**Note:** The *Apply All Strategy* could be implemented using the *Exit on First Match Strategy* using `.TrimKeyPrefix("node1").TrimKeyPrefix("node1:node2")` so technically it might not be necessary.

---
*Duplicate Key Handling*
After the trimming process happens, it is likely there will be a collision of key names.  What value will be integrated into the caller's configuration set?  Value from first key or value from last key or ...?

Maybe as part of the client configuration (yet to be release I understand) the developer could select a collision handling strategy?

````
node1:key1 <- no collision in Azure App Configuration
node1:node2:key1

.TrimKeyPrefix("node1")
.TrimKeyPreFix("node1:node2");
````
Would result in:
````
key1 <-- key collision
key1
````

**Comment by zhenlan** [comment]
@HashTagDotNet thanks for the write-up.

The `.TrimKeyPrefix()` API is designed to work on the original key only and not the key that was trimmed. This should be the "Exit on First Match Strategy" in your list. Did you see it's not working as expected?

**Comment by HashTagDotNet** [comment]
I didn't try stacking TrimKeyPrefix("") calls.  I didn't know that was an
option. (opportunity for the docs?).  I'l try it when I get a chance.

**Comment by zhenlan** [comment]
@HashTagDotNet please let us know if you see any other issues. Closing for now.
