### ISSUE TITLE
AppConfiguration.Options KV Selector Documentation Clarification

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#212]
On .Net Core 3.1, Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.0-preview-010560002-1165"

Need clarification on `options.Select` that there should be NO space after the comma (leading space) when specifying more than one key.  Perhaps on Intellisense notes? 

Also Intellisense should specify a maximum number of 5 keys, and 5 values.

Documentation should state there will be a separate call to Azure for each `options.Select(kv-selector)`

````
/kv/?key=DemoKey-dummy-1&label=%00&api-version=1.0	
/kv/?key=DemoKey-dummy-2&label=%00&api-version=1.0	
/kv/?key=DemoKey-dummy-3&label=%00&api-version=1.0	
/kv/?key=DemoKey-dummy-4&label=%00&api-version=1.0	
/kv/?key=DemoKey-dummy-5&label=%00&api-version=1.0	
/kv/?key=DemoKey&label=%00&api-version=1.0
/kv/?key=DemoKeyNoLabel&label=%00&api-version=1.0	

````

**Comment by zhenlan** [comment]
@HashTagDotNet while the information is documented, I understand the discovery of it could be painful.
https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md#filtering

The amount of text may not be a good fit for IntelliSense. Localization is another issue. I am also a little concerned if we duplicate this information in IntelliSense, it may get outdated over time. I'm open to ideas and like to hear thoughts from others.

**Comment by HashTagDotNet** [comment]
Finding that information in the doc and then making the assumption the client is aligned with the doc is probably an opportunity for documentation improvement.  

As a consumer of your service, I don't want to find the REST documentation (particularly if I'm not using REST), read through it, and compare it with my knowledge of the client, then spend a several hours trying to understand how this all works.  I had to use Postman to grab the requests to better understand how the calls and spent quite a bit of time reading the documentation.  

So updated documentation on each of the clients would be very helpful.  

As an architect on my team who is considering migrating our settings to this platform, it would be helpful to have a few more details on the client that what is currently in the docs.

**Comment by zhenlan** [comment]
@HashTagDotNet I agree with all you said. There is no question about the documentation improvements. This should be made easier.

**Comment by zhenlan** [comment]
More information was included in the IntelliSense of the `Select` API.
https://github.com/Azure/AppConfiguration-DotnetProvider/blob/main/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationOptions.cs#L112
