### ISSUE TITLE
= separator is is not present while importing or exporting the properties file 

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#214]
There is no option of mentioning = separator while exporting or importing a properties file

**Comment by zhenlan** [comment]
@Bhanu88 to help me understand, can you please give me an example of what you are trying to achieve but cannot?

**Comment by Bhanu88** [comment]
@zhenlan my property file look something like this 

```
spring.application.name=someapp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.use-new-id-generator-mappings=true
```

when i am trying to import it in the  app configuration it dose not give me option to provide separator as "**=**"  so i unable to import it

**Comment by zhenlan** [comment]
@Bhanu88 I saved the content you provided as a .properties file and imported it from the Azure portal. It's imported just fine.

![image](https://user-images.githubusercontent.com/10566826/70573191-47905480-1b56-11ea-8467-d38745893c78.png)

There is probably some confusion about what the separator is for. *The separator is used to concatenate the key names when flattening hierarchical configuration files such as json or yaml to key-value pairs.* 

The separator is not applicable to property files as key-values in property files are not in a hierarchical structure. There is definitely room for improvement in our Azure portal to make this clearer.

**Comment by Bhanu88** [comment]
Thanks @zhenlan  for the response i tried  the solution provided and its working but there is a confusion when we are trying to import the configuration as it is asking for a separator  like 

![image](https://user-images.githubusercontent.com/6247773/70592868-23d61880-1c01-11ea-9b1a-393b081efbf7.png)

so i got confused .
