### ISSUE TITLE
i am importing a property as number but i am exporting it is exported as string 

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#215]
i am importing a property as number but i am exporting it is exported as string i mean to say when i did the export the property returned in double quotes

**Comment by zhenlan** [comment]
@Bhanu88 correct, during export, as the type information is not available, all values are exported as strings.

One way to solve this is to add content-type for the key-values that are not a string. We can define a few well-known types such as number, boolean, etc. (in MIME type). Will this work for you?

**Comment by Bhanu88** [comment]
Yes definitely it is going to help ..actually documentation is not clear so i logged this issue .
 i tried the  solution provided by you by setting a configuration as "**number**" but it is still exporting as string ...Please let me know if i am doing something wrong

**Comment by zhenlan** [comment]
@Bhanu88 sorry for the confusion. I was just brainstorming ideas. This is not supported today. We will have to change the code of import/export for this to work.

**Comment by Bhanu88** [comment]
Thanks for considering my request thanks

**Comment by avanigupta** [comment]
Hi @Bhanu88, you can now preserve data types of all key-values during import/export from App Configuration. For more information, see [how to leverage content-type to store JSON key-values in App Configuration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type).
