### ISSUE TITLE
REST API Documentation Filter Example Error

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#223]
[REST API Filtering](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md#filtering) - 

I think the wild card in this example might be reversed?

    Key name starts with abc and include all labels
    GET /kv?key=*abc&label=*&api-version={api-version}

Should this be?

    Key name starts with abc and include all labels
    GET /kv?key=abc*&label=*&api-version={api-version}

**Comment by zhenlan** [comment]
Good catch. Thanks, @HashTagDotNet. Fixing in PR #224.
