### ISSUE TITLE
Total Request Count Metric

### ISSUE THREAD

**Issue by jmsalvo** [Azure/AppConfiguration#229]
I'm trying to understand the data I'm seeing in the Azure portal under Overview > Usage metrics.  There is a chart labeled 'Total Request Count'.  I'm seeing a daily 'Total Request Count' of roughly 200k.  Will this metric be used to compute requests per day for billing purposes (once this is GA), such that what I am seeing in the chart for daily usage is what would be billed?  The number I am seeing is higher than I expected, is there any way to drill into this data further to understand what apps are making the requests?  I assume 'Total Request Count' includes calls from the refresh service as well as any other API calls?  Any information about how the 'Total Request Count' is computed and how to drill into the usage is appreciated.

**Comment by jmsalvo** [comment]
Also, as a follow on to my prior questions - based on an announcement from October, it sounded like the plan for GA is to convert all the existing preview Azure App Configurations to the 'free' tier.  If our existing service usage is above the free tier, will there be an opportunity to select the paid tier before our preview app configs are converted to 'free' to avoid any potential service interruptions/outages (e.g. 429s)?

**Comment by zhenlan** [comment]
Hi @jmsalvo, the intent of these metrics is to let users learn more insight into their App Configuration store. Though in most cases a large portion of the total request count will be included in billing, but not necessarily all of them, for example, the requests that are not authenticated will *not* be counted to your billing. We will improve the metrics to make it more useful. Unfortunately, I don't have a good way for you to tell what apps are making the requests at this point. This is a reasonable ask. We will have to think about it. Yes, the "total request count" includes calls that poll for changes and refresh for configuration as well as any other calls that make requests to the service.

For existing App Configuration stores, while we are still finalizing the details of the plan, but you can be assured you will be given time to upgrade to the standard tier before the quota restriction is enforced to your store even if it's converted to the "free" tier upon service GA. It's our priority not to cause any interruption to your usage of App Configuration.
