### ISSUE TITLE
Nested configuration

### ISSUE THREAD

**Issue by Lukasz994** [Azure/AppConfiguration#230]
Hey,
I was wondering is there any roadmap for adding support for nested JSON format? We'd like to trial the use of this tool but most of our config files are nested which makes it impossible to take advantage of this tool without redesigning our code base.

**Comment by zhenlan** [comment]
@Lukasz994 maybe you can share more details (with examples) of how your current configuration looks like and then we can see if we can figure out something?

**Comment by Lukasz994** [comment]
@zhenlan  , apologies for delayed response.
When it comes to nested JSON lets look at simple format such this:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```
We have more custom config that nests deeper than listed example, but for sake of simplicity lets work with the above. Would you have any ideas on how that could be implemented within App Configuration?

**Comment by zhenlan** [comment]
Hi @Lukasz994 the example you had can be saved as below in App Configuration

![image](https://user-images.githubusercontent.com/10566826/72837894-1ec6a900-3c44-11ea-85ef-93e27c131560.png)

If you have JSON configuration files, you can import them to App Configuration via either Azure Portal or CLI so you don't have to type them manually. The [Microsoft.Extensions.Configuration.AzureAppConfiguration](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-core-app#connect-to-an-app-configuration-store) will load them to your application properly.

**Comment by Lukasz994** [comment]
Hi @zhenlan, I was not aware of such option, this is really helpful. I'll try to setup my config according to this syntax. In the past I've tried to upload my json, but ended up failing. I'll revisit and create new issue if necessary. For now this is plenty to get me going. Thanks for your help.
