### ISSUE TITLE
ConnectWithManagedIdentity got deprecated

### ISSUE THREAD

**Issue by klogan12** [Azure/AppConfiguration#231]
Followed this doc for vault reference. 
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity

Looks like  ConnectWithManagedIdentity got deprecated. What is the alternative.

**Comment by drago-draganov** [comment]
@klogan12 

Please follow the [release notes] (https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019). The official documentation will be updated.

**Comment by zhenlan** [comment]
cc @jpconnock @lisaguthrie

**Comment by zhenlan** [comment]
The document has been updated.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?tabs=core3x
