### ISSUE TITLE
Powershell module for management operations of the service

### ISSUE THREAD

**Issue by eosfor** [Azure/AppConfiguration#232]
hello colleagues, I can't find the AZ PowerShell module for the service. Is it exist? How can I use this service from PowerShell?

Thanks

**Comment by zhenlan** [comment]
Hi @eosfor the PowerShell of App Configuration is available at
https://www.powershellgallery.com/packages/Az.AppConfiguration

@lisaguthrie @jpconnock, can we get this to our documentation?

**Comment by eosfor** [comment]
That would be good, as I can't quickly figure out how to use it :)

**Comment by jimmyca15** [comment]
@eosfor It appears that you opened up a separate issue detailing the request for key-value operations in PowerShell. I have added the enhancement label and we can use that issue for tracking.

**Comment by jimmyca15** [comment]
Re-opening since there was a doc action item.

**Comment by lisaguthrie** [comment]
Thanks! We're tracking this on our docs backlog.

**Comment by ivcarreras** [comment]
I see the CmdLet but I can't find the documentation anywhere. The linked item above (#360) that is already closed does not point to any documentation for the Az.AppConfiguration module

**Comment by jiwanovski87** [comment]
Is there any information when this is available?

I know already this seems in progress (see powershell gallery [https://www.powershellgallery.com/packages/Az.AppConfiguration/0.1.4](url)). Currently we cannot work with these cmdlets... There is no documentation and I believe the cmdlets haven't been finished...

As example: Don't know how to create a new key with cmdlet.... I see the cmdlet `New-AzAppConfigurationStoreKey` but don't know how to use this... 

If you can give information this would be great.

**Comment by zhenlan** [comment]
The [PowerShell module for App Configuration](https://www.powershellgallery.com/packages/Az.AppConfiguration) available today *only* supports the **management operations** of the App Configuration resource (eg. create an App Configuration store). This GitHub issue is to track the documentation of this module.

The support of **data operations** of the App Configuration (eg. create a key-value) is *not* available in PowerShell today and the request is tracked in #267.

**Comment by zhenlan** [comment]
The documentation of the PowerShell module is now available at
https://docs.microsoft.com/en-us/powershell/module/az.appconfiguration/?view=azps-4.2.0#app_configuration
