### ISSUE TITLE
IOfflineCache implementation for AzureAppConfiguration

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#235]
Is there IOfflineCache cache capability for AzureAppConfigurationBuilder?  If not what is the recommended pattern for off-line cache for .Net Framework apps?

**Comment by zhenlan** [comment]
Hi @HashTagDotNet the `IOfflineCache` is not available for the AzureAppConfigurationBuilder.

cc: @StephenMolloy

**Comment by huantingchen** [comment]
Is this on the road map yet?

**Comment by avanigupta** [comment]
@HashTagDotNet, @huantingchen, we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?

**Comment by huantingchen** [comment]
Thanks @avanigupta. We're developing desktop apps within .NET Framework (C#/WPF) and look to inject remote config synced from Azure App Configuration. Sometimes our users don't have access to internet and therefore would like to save a local cache on user machine. Cheers.

**Comment by zhenlan** [comment]
Given the security implications and our focus on service availability/reliability, we decided to move away from offering offline solutions. Users may choose to fall back to local configuration files for offline scenarios.
