### ISSUE TITLE
Managed Identity with Reader role throws UnAuthorized error

### ISSUE THREAD

**Issue by kamalsivalingam** [Azure/AppConfiguration#238]
We integrated Azure App Configuration (version 2.1.0-preview-010380001-1099) with Managed Identity on App Servers.

However We are getting UnAuthorized error trying to access Azure App Configuration with Reader role. Based on the below document, updated the role to Contributor and it works!.
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-app-configuration/howto-integrate-azure-managed-service-identity.md

Does Azure App Configuration Managed Identity work only with Contributor role?

**Comment by drago-draganov** [comment]
That's expected prior version 3.0.0-preview. The newest provider fully supports Azure AAD and only requires *App Configuration Data Reader* role for read access.

Please use the release notes as reference for now, pending documentation update.

https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019

**Comment by kamalsivalingam** [comment]
Awesome, Thanks @drago-draganov for prompt response.
I tried earlier to upgrade to 3.0.0 version and ran into few issues and it looks those issues are being worked on.

**Comment by drago-draganov** [comment]
Duplicated #231

**Comment by drago-draganov** [comment]
Duplictated #231
