### ISSUE TITLE
Portal: Exception when accessing "Configuration manager", "Feature explorer" and "Compare" menu options

### ISSUE THREAD

**Issue by larsathle** [Azure/AppConfiguration#241]
Hi,

I am experiencing exceptions when I'm accessing "Configuration manager", "Feature explorer" and "Compare" on my newly created App Configuration.

I have tried 2 different browsers (Brave/Chrome) with adblockers turned off. I also tried to unregister/register the Microsoft.AppConfiguration resource provider on my subscription. I've created the App Configuration using both ARM and the portal, with the same result.

This is a showstopper in our adaption of the service. I removed our SubscriptionId in this report, if you need this to investigate further please contact me.

**This is the message shown in portal:**
![image](https://user-images.githubusercontent.com/49679908/72349288-84fb7b00-36dc-11ea-89b0-0ab95c5d7332.png)

**Message copied to clipboard:**
{ "shellProps": { "sessionId": "1a9b185e75c54082a0356b855298e2d4", "extName": "Microsoft_Azure_AzConfig", "contentName": "ResourceKVBlade", "resourceId": "/subscriptions/<removed>/resourceGroups/config-rg/providers/Microsoft.AppConfiguration/configurationStores/volmax-test-ac" }, "error": { "message": "User is not able to connect to the service", "details": "We had trouble reaching the server. This is usually an indication that the network is down or a firewall or browser extension (such as an ad blocker) is mistakenly preventing access.", "summaryItems": [ { "label": "Time stamp", "value": "1/14/2020, 2:42:43 PM" } ], "metadata": { "utc": "2020-01-14T13:42:43.928Z", "type": "KV" }, "code": null }}

**This is the console output:**
[Microsoft_Azure_AzConfig]  2:42:43 PM Resource/ResourceKVBlade 0 ResourceKVBlade: Failed to fetch kvs, reason: _errorData: {"readyState":0,"status":0,"statusText":"error"}
_sourceErrorLevel: undefined
baseTypes: ["MsPortalFx.Errors.FetchDataError","MsPortalFx.Errors.DataError","MsPortalFx.Errors.Error"]
code: undefined
data: undefined
dataSetName: KV:DataCache:5:41
errorLevel: 2
extension: Microsoft_Azure_AzConfig
handled: undefined
innerErrors: []
message: 
name: Error
source: KV:DataCache:5:41
stack: Error
    at t.r (https://portal.azure.com/Content/Dynamic/k-T89tKP4bIz.js:18:790)
    at t (https://portal.azure.com/Content/Dynamic/k-T89tKP4bIz.js:18:1563)
    at new t (https://portal.azure.com/Content/Dynamic/k-T89tKP4bIz.js:18:1736)
    at wt (https://portal.azure.com/Content/Dynamic/k-T89tKP4bIz.js:106:680)
    at https://portal.azure.com/Content/Dynamic/k-T89tKP4bIz.js:106:6525
    at o (https://portal.azure.com/Content/Dynamic/qDdhDKs5uKzm.js:4:72)
    at https://portal.azure.com/Content/Dynamic/qDdhDKs5uKzm.js:4:5443
timestamp: 3847116.97000009
type: MsPortalFx.Errors.FetchDataError
 /subscriptions/<removed>/resourceGroups/config-rg/providers/Microsoft.AppConfiguration/configurationStores/volmax-test-ac

Regards,
Lars

**Comment by zhenlan** [comment]
Hi @larsathle, this issue often happens when there are firewall rules that prevent network traffic to App Configuration service *.azconfig.io. Can you please try https://volmax-test-ac.azconfig.io/kv in a browser that is on the same machine where you got the error above? If you receive HTTP 401, which means it's not a network issue. If you receive errors like timeout, which means you are not able to reach App Configuration service from your network. You can also validate this on a different network, for example, from your phone (make sure it is not connected to the same network as your computer via wifi).

**Comment by larsathle** [comment]
Hi @zhenlan, I can confirm that the issue was caused by our FortiGuard Web Filtering Service. I have successfully had them change their classification of *.azconfig.io, and that should solve the issue for everyone using FortiGuard.

Thank you so much for helping me out.
