### ISSUE TITLE
Key Vault question

### ISSUE THREAD

**Issue by eosfor** [Azure/AppConfiguration#243]
Hello colleagues, I did really understand the concept with key vaults. When I refer to the key in key vault, and then trying to get it via REST for example, I'm getting a link to a key vault key. Does it mean that in order to get my actual values in my code I would need to query key vault as well? Or, how does it work?

**Comment by eosfor** [comment]
Actually I expected from the App Config Service to support the scenario like this:

1. I create a key and reference a key vault and a version of the key in the key vault
2. when I pull that key from the App Config Service, it goes to the key vault, pulls the value and returns it to me

Additionally, I'd like to be able to apply RBAC on per-key basis, for example, as i don't want different apps to be able to read each other's parameters, whatever they are.

**Comment by drago-draganov** [comment]
Re: KeyVault

AppConfiguration can store references to KeyVault secrets. Materializing secret values happens by the application using configuration at runtime. All of our configuration providers support that transparently, so no need to do anything much there. In case of REST, you have to make a request to KeyVault to retrieve the secret value. 

The main motivation for this is security:

- Access to application configuration doesn't necessary translate to access to KeyVault secrets. For example, app developers could have access to app configuration settings, but not necessary to secrets.
- If AppConfiguration proxies KeyVault secretes, then important security features offered by KeyVault may render less effective or unavailable - VNET, Auditing, Granular Access Control to name a few.

**Comment by drago-draganov** [comment]
Hello @eosfor 

Re: RBAC per key/label

This is something we've looked at in the past. The challenge here is that AppConfiguration is optimized to deliver multiple key-value items (often 100) with very low latency in a single request, while KeyVault requires a separate request for each item. That naturally brings the question what should be expected if the response payload contains an item that requires different permission than the rest - Fail the request; Omit the item from the payload; Replace the item with an error object?  It isn't clear that single solution fits all. It may also add ambiguity or induce unexpected application startup failures.
Note that, a very important security feature like VNET can't be utilized as boundary between unrelated apps if they share the same configuration store.

We recommend that unrelated applications to be silo-ed in different configuration stores. That provides maximum security, independent endpoints for client firewall rules, optimal latency (deployment closer to the respective app), etc. We offer tools to manage and sync between different configuration stores.
