### ISSUE TITLE
Could not establish SSL connection in docker container

### ISSUE THREAD

**Issue by uptlak** [Azure/AppConfiguration#244]
Hi,
Recently I started using Azure AppConfiguration, and I like it.
I created a very simple demo project (dotnet core console app) just to write out the value
Code:
```c#
var builder = new ConfigurationBuilder();
            builder.AddAzureAppConfiguration(options =>
            {
                options.Connect("ConnectionString")
                    .Select("test:*", "test")
                    .TrimKeyPrefix("test:");
            });
            var config = builder.Build();
            Console.WriteLine(config["test"]);
```
When I run the app on my local machine, everything works just fine, the app itself downloads all the configuration from Azure and work in order.
But when I try to package app into a docker image and run it in the container I get following error:
```
(The SSL connection could not be established, see inner exception.)
 ---> Azure.RequestFailedException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
``` 
A container always crash with this message.

I publish app with command:
`dotnet publish -c Release -o out`
Dockerfile:
```
 FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
 WORKDIR /app
 COPY /out ./
 ENTRYPOINT dotnet name-of-app.dll
```
I tried using both Windows and Linux containers, but I always end up with the same error.
Do you ever encounter this issue?

**Comment by zhenlan** [comment]
Hi @uptlak, I tried everything you had *except* with a .NET Core *3.1* image and everything works fine for me. Here is my dockerfile. Please let me know if you still see the error with the 3.1 image.
```
 FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim
 WORKDIR /app
 COPY /out ./
 ENTRYPOINT dotnet ConsoleApp4.dll
```

**Comment by zhenlan** [comment]
Closing.. @uptlak please let me know if you still see the issue.

**Comment by tgindrup-inroll** [comment]
@zhenlan we're getting this same error when not running in a docker container.  Some dev workstations work without issue, others get the SSL connection error referenced above when calling builder.AddAzureAppConfiguration

**Comment by uptlak** [comment]
The issue, in my case, was the company firewall. After a call with our network administrator, everything works as it should.
Double check your networking, I lost lots of time on such a simple problem with an easy solution :)
