### ISSUE TITLE
Labels missing in 'Select labels' drop-down

### ISSUE THREAD

**Issue by jmsalvo** [Azure/AppConfiguration#246]
When I view the list of labels in the 'Select labels' drop-down, I'm no longer seeing the complete list of labels from our configuration store.

**Comment by jmsalvo** [comment]
This only seems to be an issue in one of our Azure App Configuration instances, in addition to being unable to view the full list of labels I also see this message 'User is not able to connect to the service' when I try to export the configuration to json.

**Comment by drago-draganov** [comment]
Thank you for reporting this, @jmsalvo 

Can you send me an email with your configuration store name?

**Comment by drago-draganov** [comment]
We diagnosed both issues. They appear to be bugs in Azure Portal. Will be addressed with the next iteration.

**Comment by jmsalvo** [comment]
Are you able to provide an estimate of when this may be fixed?  Thank you

**Comment by jiayi11** [comment]
@jmsalvo The fix should be deployed by the end of this week, I'll also update this thread after deployment finishes.

**Comment by jiayi11** [comment]
@jmsalvo The issue is already been fixed.
