### ISSUE TITLE
How to use Azure App Configuration Feature Management in Azure Function

### ISSUE THREAD

**Issue by masonyc** [Azure/AppConfiguration#249]
Hi All,
I am wondering does Azure App Configuration Feature Management support in Azure Functions currently? I don't see the feature management quick start for Azure Function so I assume it is not supported yet?

**Comment by jimmyca15** [comment]
Hello @Masonyc,

The Azure App Configuration feature management solution can be used in Azure Functions. The first step is to get the Azure App Configuration configuration provider plugged up in the Azure Function. There is an example on how to do that here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-dotnet.

After setting up the configuration provider, which provides the feature flags, you can create the feature manager to begin consuming them. We don't have a doc specifically for Azure Functions, but creating the feature manager would be similar to the example here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-dotnet#connect-to-an-app-configuration-store. 

Let me know if that helps.

**Comment by masonyc** [comment]
Hi @jimmyca15 ,
Thanks for the fast reply. Does this only work on Azure Function V3? When I tried to run it on v2, I got 
![image](https://user-images.githubusercontent.com/18006944/73037380-b847c200-3eb3-11ea-8a94-01991ee88b7c.png)

**Comment by zhenlan** [comment]
@masonyc I can reproduce the issue after updating the example to 
TargetFramework=netcoreapp3.1
Microsoft.NET.Sdk.Functions v3.0.2

The example still works fine when it uses its [original versions](https://github.com/Azure/AppConfiguration/blob/master/examples/DotNetCore/AzureFunction/FunctionApp/FunctionApp.csproj) 
TargetFramework=netcoreapp2.1
Microsoft.NET.Sdk.Functions v1.0.29

This does not change regardless I use the v3.x or v2.x of `Microsoft.Extensions.Configuration.AzureAppConfiguration`. We will need to take further investigation. Thanks for reporting the issue @masonyc.

cc: @abhilasharora

**Comment by zhenlan** [comment]
The issue went away after I updated the Azure Functions to v3
```
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
```
Here is a PR (#250) that updated the example to work with Azure Functions v3.

**Comment by masonyc** [comment]
Thanks @zhenlan , I have upgraded to v3 to solve this issue.
