### ISSUE TITLE
App configuration's feature flag manager not working in Azure functions along with DI.

### ISSUE THREAD

**Issue by kaushik-hemant** [Azure/AppConfiguration#252]
Following code I'm using:

Startup:

![Startup](https://user-images.githubusercontent.com/15911296/73160011-e1fc2580-410d-11ea-968e-9b33bdf8402c.PNG)

Function:

![function](https://user-images.githubusercontent.com/15911296/73160023-ecb6ba80-410d-11ea-8bcd-6ff752c7fb1f.PNG)

Config:

![config](https://user-images.githubusercontent.com/15911296/73160129-28ea1b00-410e-11ea-8e57-f97308d7cffa.PNG)

Quick response will be highly appreciated.

**Comment by jimmyca15** [comment]
Hello @kaushik-hemant, can you explain what the issue is. Your setup looks great. I copied it and everything is working as expected.

**Comment by jimmyca15** [comment]
From your picture it looks like you used a label named "Test" when creating the feature flag, but you did not specify that label when calling `UseFeatureFlags`. You can either recreate the feature flag to not have a label, or update the feature flag options to use the "test" label.

**Comment by kaushik-hemant** [comment]
@jimmyca15 IsEnableAsync function returning false every time even if it's true in portal (I checked restarting app after toggling it just not relying on reload cache). And for label, if I don't provide it on portal, then it gives 'method not found' exception during setup. 

I checked both ways as providing same label filter:
`featureflagoptions.CacheExpirationTime = TimeSpan.FromSeconds(5);
featureflagoptions.Label = "Test";`

Awaiting response.

**Comment by kaushik-hemant** [comment]
Actually "EnabledOn" under settings is empty, how to set it from portal.

**Comment by jimmyca15** [comment]
@kaushik-hemant the "method not found" exception results in using the 3.0.0-preview-* version of the Microsoft.Extensions.Configuration.AzureAppConfiguration with v2 of Azure Functions. More details can be found in [this issue](https://github.com/Azure/AppConfiguration/issues/254).

When you created the feature flag with no label and you got the "method not found" exception, you performed all the right steps, it's just that you hit the v2 Azure function issue I mentioned. Once you resolve that everything should work.

**Comment by kaushik-hemant** [comment]
@jimmyca15 I hope following snapshot would be suffice to let you understand better:

Exception after changing azure functions 3.x
![exception](https://user-images.githubusercontent.com/15911296/73329860-0cbcba00-4285-11ea-9313-6a9eb8cefab8.PNG)

with versions as:
![project](https://user-images.githubusercontent.com/15911296/73329896-2958f200-4285-11ea-8e6f-687d25342284.PNG)

Lemme know what exact needs to be done.

**Comment by zhenlan** [comment]
@kaushik-hemant according to your screenshot, you are still using Azure Functions v2. Can you please upgrade to v3?
```xml
<AzureFunctionsVersion>v3</AzureFunctionsVersion>
```

**Comment by kaushik-hemant** [comment]
@zhenlan After upgrading to 3.0, it started working, Thanks.
