### ISSUE TITLE
Last Character Of  ReadOnly Secret can be Changed

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#257]
I can use two different ReadOnly secrets *with the same id* to access my configuration store.  I would have expected 401 error on the non-valid token.

I can change the last character of token one or more ASCII values forward.

I have seen the same behavior using freshly regenerated tokens.

| secret | change | result |
| --- | --- |
| ...KZM/rTFYZZah3c= | generated | returns values |
| ...KZM/rTFYZZah3b= | down change | 401 |
| ...KZM/rTFYZZah3d= | up change | returns values |
| ...KZM/rTFYZZah3f= | values 'd..f' | returns values |
| ...KZM/rTFYZZah3g= | up change | 401 |
| ...AEj5f/3uSjr/LFG4 | generated | returns values |
| ...AEj5f/3uSjr/LFG3 | down change | 401 |
| ...AEj5f/3uSjr/LFG5 | up change | returns values |
| ...AEj5f/3uSjr/LFG56| up change+2 | 401 |

**Comment by jimmyca15** [comment]
Hello @HashTagDotNet,

The examples you have provided are base64 encoded secrets. Base64 encoded values have the property that you are pointing out where changing the last character can result in decoding to the same binary. This is fine and is expected. Even though the last character is changed, the binary being represented was not changed in the cases that resulted in successful authentication.
