### ISSUE TITLE
Invalid Secret Causes .Net Core AzureClient to Silently Fail

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#258]
If I use an invalid encoded secret (e.g. I forgot to copy the padding '=' at the end of the string) then the Startup(configuration) contains an 'EmptyConfigurationProvider' and not an expected exception.

**Comment by abhilasharora** [comment]
@HashTagDotNet I tested it out in a .NET Core Console application with version `3.0.0-preview-011100001-1152` of the package `Microsoft.Extensions.Configuration.AzureAppConfiguration`. I do see an exception, so I'm unable to reproduce the issue.

![image](https://user-images.githubusercontent.com/47916289/73564935-7bc91880-4415-11ea-8ed7-bbff0420185c.png)
