### ISSUE TITLE
Adding keys using ARM templates

### ISSUE THREAD

**Issue by ivcarreras** [Azure/AppConfiguration#268]
It would be great if I could set the keys I need as part of the ARM template deployment. Both regular keys and key vault reference support is needed.

**Comment by zhenlan** [comment]
Thanks for the suggestion. This work is in the plan.

**Comment by tjgalama** [comment]
@zhenlan , it is good to hear that this issue is under construction (am I right?). 
Can you also give a rough estimate when this great functionality becomes available?

**Comment by sanghamanvir13** [comment]
What is the current recommended way of adding bulk configurations to app configuration? Any pointers will help

**Comment by confused-nerd** [comment]
> 
> 
> @zhenlan What is the current recommended way of adding bulk configurations to app configuration? Any pointers will help

Have you looked at the az cli, with the import file option?

example: `az appconfig kv import -s file --path <directory-path-to-file> --format json`

format allows for json, yaml.  if you not sure on the format of the file I would suggest adding one/two in azure portal then exporting to file to show the format required.

**Comment by acarlstein** [comment]
> 
> 
> > @zhenlan What is the current recommended way of adding bulk configurations to app configuration? Any pointers will help
> 
> Have you looked at the az cli, with the import file option?
> 
> example: `az appconfig kv import -s file --path <directory-path-to-file> --format json`
> 
> format allows for json, yaml. if you not sure on the format of the file I would suggest adding one/two in azure portal then exporting to file to show the format required.

The option is good for as a "spear tire"; however, in some corporations, the architecture team insist that ARM Templates should be used. I am surprise that this doesn't allow for the actual creation of keys that is done in the portal.

**Comment by zhenlan** [comment]
ARM template support is on the way. We should have an update in a few days. Stay tuned.

**Comment by trpankake** [comment]
> ARM template support is on the way. We should have an update in a few days. Stay tuned.

@zhenlan Any update on this?  We're overhauling our ARM templates and would love to load our config keys via template.  Thanks!

**Comment by ZhijunZhao** [comment]
@trpankake We just shipped the feature last week. We're still in the process of releasing a quick-start document for this support. Will share the doc link once it goes public. 

Below is a sample template for reference. Feel free to try it out. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "configStoreName": {
            "type": "string",
            "defaultValue": "zhijzhao-prod",
            "metadata": {
                "description": "Specifies the name of the App Configuration store."
            }
        },
        "keyValueName": {
            "type": "string",
            "defaultValue": "myKey$myLabel",
            "metadata": {
                "description": "Specifies the name of the key-value resource. The name is a combination of key and label with $ as delimiter."
            }
        }
    },
    "resources": [
        {
            "name": "[parameters('configStoreName')]",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "apiVersion": "2020-07-01-preview",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "standard"
            },
            "resources": [
                {
                    "name": "[parameters('keyValueName')]",
                    "type": "keyValues",
                    "apiVersion": "2020-07-01-preview",
                    "dependsOn": [
                        "[parameters('configStoreName')]"
                    ],
                    "properties": {
                        "value": "Hello World!",
                        "contentType": "the-content-type",
                        "tags": {
                            "tag1": "tag-value-1",
                            "tag2": "tag-value-2"
                        }
                    }
                }
                // Add multiple key-values to the new App Configuration store by defining additional keyValues resources here.
            ]
        }
    ],
    "outputs": {
        "reference-value": {
            "value": "[reference(resourceId('Microsoft.AppConfiguration/configurationStores/keyValues', parameters('configStoreName'), parameters('keyValueName')), '2020-07-01-preview').value]",
            "type": "string"
        }
    }
}
```

**Comment by mariagullickson** [comment]
So happy to see this. Can you also share an example of a key vault reference?

**Comment by ZhijunZhao** [comment]
@mariagullickson Below is one example for adding a key vault reference. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "configStoreName": {
            "type": "string",
            "defaultValue": "",
            "metadata": {
                "description": "<YOUR-APP-CONFIGURATION-STORE-NAME>"
            }
        },
        "keyValueName": {
            "type": "string",
            "defaultValue": "keyVaultMessage",
            "metadata": {
                "description": "Specifies the name of the key-value resource. The name is a combination of key and label with $ as delimiter."
            }
        },
        "keyValueSecretIdentifier": {
            "type": "string",
            "defaultValue": "<YOUR-SECRET-IDENTIFIER>",
            "metadata": {
                "description": "Examples like https://your-key-valut-name.vault.azure.net/secrets/your-secret/secret-version and https://your-key-valut-name.vault.azure.net/secrets/your-secret"
            }
        }
    },
    "variables": {
        "keyVaultRef": {
            "uri": "[parameters('keyValueSecretIdentifier')]"
        }
    },
    "resources": [
        {
            "name": "[parameters('configStoreName')]",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "apiVersion": "2020-07-01-preview",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "standard"
            },
            "resources": [
                {
                    "name": "[parameters('keyValueName')]",
                    "type": "keyValues",
                    "apiVersion": "2020-07-01-preview",
                    "dependsOn": [
                        "[parameters('configStoreName')]"
                    ],
                    "properties": {
                        "value": "[string(variables('keyVaultRef'))]",
                        "contentType": "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
                    }
                }
            ]
        }
    ]
}
```

**Comment by robfrut135** [comment]
> @trpankake We just shipped the feature last week. We're still in the process of releasing a quick-start document for this support. Will share the doc link once it goes public.
> 
> Below is a sample template for reference. Feel free to try it out.
> 
> ```
> {
>     "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
>     "contentVersion": "1.0.0.0",
>     "parameters": {
>         "configStoreName": {
>             "type": "string",
>             "defaultValue": "<YOUR-APP-CONFIGURATION-STORE-NAME>",
>             "metadata": {
>                 "description": "Specifies the name of the App Configuration store."
>             }
>         },
>         "keyValueName": {
>             "type": "string",
>             "defaultValue": "myKey$myLabel",
>             "metadata": {
>                 "description": "Specifies the name of the key-value resource. The name is a combination of key and label with $ as delimiter."
>             }
>         }
>     },
>     "resources": [
>         {
>             "name": "[parameters('configStoreName')]",
>             "type": "Microsoft.AppConfiguration/configurationStores",
>             "apiVersion": "2020-07-01-preview",
>             "location": "[resourceGroup().location]",
>             "sku": {
>                 "name": "standard"
>             },
>             "resources": [
>                 {
>                     "name": "[parameters('keyValueName')]",
>                     "type": "keyValues",
>                     "apiVersion": "2020-07-01-preview",
>                     "dependsOn": [
>                         "[parameters('configStoreName')]"
>                     ],
>                     "properties": {
>                         "value": "Hello World!",
>                         "contentType": "the-content-type",
>                         "tags": {
>                             "tag1": "tag-value-1",
>                             "tag2": "tag-value-2"
>                         }
>                     }
>                 }
>                 // Add multiple key-values to the new App Configuration store by defining additional keyValues resources here.
>             ]
>         }
>     ],
>     "outputs": {
>         "reference-value": {
>             "value": "[reference(resourceId('Microsoft.AppConfiguration/configurationStores/keyValues', parameters('configStoreName'), parameters('keyValueName')), '2020-07-01-preview').value]",
>             "type": "string"
>         }
>     }
> }
> ```

I have tried this example and it works perfectly
I have done some other test and I see that it does not allow to use the values inside the variables section (for example), can we use references to App Config key-values in variables or parameters section?

**Comment by ZhijunZhao** [comment]
@robfrut135 Below is quoted from this [link](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-resource#valid-uses-1).

> The reference function can only be used in the properties of a resource definition and the outputs section of a template or deployment.

**Comment by hem-sharma** [comment]
@robfrut135 Can I add key-values in already created app configurations? e.g.

```json
{
      "name": "[concat(parameters('configStoreName'), '/', 'abc$xyz')]",
      "type": "Microsoft.AppConfiguration/configurationStores/keyValues",
      "apiVersion": "2020-07-01-preview",
      "dependsOn": [
        "[parameters('configStoreName')]"
      ],
      "properties": {
        "value": "Hello World!",
        "contentType": "the-content-type",
        "tags": {
          "tag1": "tag-value-1",
          "tag2": "tag-value-2"
        }
      }
    }
```

**Comment by ZhijunZhao** [comment]
@hem-sharma Yes, you can! This is a good question, BTW. 

`keyValues` is a child resource type. There are two ways to write in ARM template. I'm using the within-parent-resource style and you're using the outside-parent-resource style. Here is the ARM template [doc ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/child-resource-name-type)for reference.

**Comment by hem-sharma** [comment]
@ZhijunZhao I can verify this is working but not sure how to work with feature-flags related values.

**Comment by ZhijunZhao** [comment]
> @ZhijunZhao I can verify this is working but not sure how to work with feature-flags related values.

Right. Feature flags are a little bit complicated. Could you share one of your cases. I can try it out and get back to you.

**Comment by hem-sharma** [comment]
![image](https://user-images.githubusercontent.com/15911296/92221303-e619ce00-eeba-11ea-9c4b-934febe80223.png)

Can you check this **tiny** image, if I have to add one more feature flag using ARM with the same name but a different label or a new flag altogether?

**Comment by ZhijunZhao** [comment]
@hem-sharma There is a ARM template example above I replied regarding how to add key vault reference. Feature flags should be verify similar to it. Two things to call out. 
1. The `value`. You can notice that I used the `string` function in the key vault reference example. The `string` function helps to convert an object to a json string. So, you can define the value of feature flag as an object and use `string` function to convert it to a string. 
2. The `contentType`. You can find the content type value in your tiny image. :) 

Please try it out. Let me know if there is any blocking issue.

**Comment by hem-sharma** [comment]
@ZhijunZhao In name of the resource I've to specify '.appconfig.featureflag/NotificationEnabled$Global_xyz' to define the key name and label as per configurations mentioned on the portal which is creating issues.

if key template is:

```json

{
      "name": "[concat(parameters('configStoreName'), '/', '.appconfig.featureflag/NotificationEnabled$Global_xyz1')]",
      "type": "Microsoft.AppConfiguration/configurationStores/keyValues",
      "apiVersion": "2020-07-01-preview",
      "dependsOn": [
        "[parameters('configStoreName')]"
      ],
      "properties": {
        "value": "[string(variables('flagValue'))]",
        "contentType": "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
      }
    }



Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template resource 'wmappconfigtest/.appconfig.featureflag/NotificationEnabled$Global_xyz1' for type 'Microsoft.AppConfiguration/configurationStores/keyValues' at line '78' and column '76' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.
```
but with the below template:

```json
{
      "name": "[concat(parameters('configStoreName'), '/', 'NotificationEnabled$Global_xyz')]",
      "type": "Microsoft.AppConfiguration/configurationStores/keyValues",
      "apiVersion": "2020-07-01-preview",
      "dependsOn": [
        "[parameters('configStoreName')]"
      ],
      "properties": {
        "value": "[string(variables('flagValue'))]",
        "contentType": "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
      }
    }
```
then created key is considered as configuration and not a feature flag.


![image](https://user-images.githubusercontent.com/15911296/92238027-030fca80-eed6-11ea-9e38-549a86e48971.png)

**Comment by ZhijunZhao** [comment]
@hem-sharma Try

> .appconfig.featureflag**~2F**NotificationEnabled$Global_xyz1

`.appconfig.featureflag/NotificationEnabled$Global_xyz1` is the resource name of `keyValues`. ARM template doesn't allow `/` and a few other characters in resource name. So, we have to escape it. App Configuration service supports URL encoding to escape these characters. `/` is URL encoded as `%2F`. However, `%` is a forbidden character as well. Instead, `~` is used as the encoding character. This is why `/` should be replaced by `~2F` in the resource name of `keyValues`.

The above rule will be explained in official document, which is in the publication process. Will share the link once it's public.

**Comment by hem-sharma** [comment]
Thanks, @ZhijunZhao, I tried and it's working as expected with `.appconfig.featureflag~2FNotificationEnabled$Global_xyz` thought I'm waiting for you guys to release a stable API version compared to this preview.

**Comment by akshatgupta02** [comment]
Hi,

This template works fine when both appconfig and key vault in same resource group. But I have a situation where my appconfig and Key vault in different resource groups. Any idea how to add key vault (from different resource group) reference in this template

**Comment by ZhijunZhao** [comment]
@akshatgupta02 Below is one example. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "configStoreName": {
            "type": "string",
            "defaultValue": "<YOUR-CONFIG-STORE-NAME>"
        },
        "keyValueName": {
            "type": "string",
            "defaultValue": "<YOUR-KEY-VALUE-REF-NAME>"
        },
        "keyVaultSub": {
            "type": "string",
            "defaultValue": "<YOUR-KV-SUBSCRIPTION>"
        },
        "keyVaultRG": {
            "type": "string",
            "defaultValue": "<YOUR-KV-RESOURCE-GROUP>"
        },
        "keyVaultName": {
            "type": "string",
            "defaultValue": "<YOUR-KV-NAME>"
        },
        "keyVaultSecretName": {
            "type": "string",
            "defaultValue": "<YOUR-SECRET-NAME>"
        }
    },
    "resources": [
        {
            "name": "[parameters('configStoreName')]",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "apiVersion": "2020-07-01-preview",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "standard"
            },
            "resources": [
                {
                    "name": "[parameters('keyValueName')]",
                    "type": "keyValues",
                    "apiVersion": "2020-07-01-preview",
                    "dependsOn": [
                        "[parameters('configStoreName')]"
                    ],
                    "properties": {
                        "value": "[concat('{\"uri\": \"', reference(resourceId(parameters('keyVaultSub'), parameters('keyVaultRG'),'Microsoft.KeyVault/vaults/secrets', parameters('keyVaultName'), parameters('keyVaultSecretName')), '2018-02-14').secretUriWithVersion, '\"}')]",
                        "contentType": "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
                    }
                }
            ]
        }
    ]
}
```

**Comment by zhenlan** [comment]
The document is published
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager

**Comment by gregmalley** [comment]
Can anyone please post a full example of an ARM template that creates a feature flag? I have it working for key/value in Configuration Explorer, but need the key/value to show up in the "Feature Manager" as a feature flag. I would really appreciate a full example, I cannot see to piece together one from the comments above. Thanks in advance if someone can help!

**Comment by ZhijunZhao** [comment]
@gregmalley Below is an example that creates a feature flag. 

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "configStoreName": {
            "type": "string",
            "defaultValue": "<YOUR-APP-CONFIGURATION-STORE-NAME>",
            "metadata": {
                "description": "The name of your configuration store."
            }
        },
        "featureFlagName": {
            "type": "string",
            "defaultValue": "<YOUR-FEATURE-FLAG-NAME>",
            "metadata": {
                "description": "Specifies the name of the feature flag."
            }
        }
    },
    "variables": {
        "featureFlagValue": {
            "id": "[parameters('featureFlagName')]",
            "description": "Your description",
            "enabled": true,
            "conditions": {"client_filters":[]}
        }
    },
    "resources": [
        {
            "name": "[parameters('configStoreName')]",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "apiVersion": "2020-07-01-preview",
            "location": "[resourceGroup().location]",
            "sku": {
                "name": "standard"
            },
            "resources": [
                {
                    "name": "[concat('.appconfig.featureflag~2F', parameters('featureFlagName'))]",
                    "type": "keyValues",
                    "apiVersion": "2020-07-01-preview",
                    "dependsOn": [
                        "[parameters('configStoreName')]"
                    ],
                    "properties": {
                        "value": "[string(variables('featureFlagValue'))]",
                        "contentType": "application/vnd.microsoft.appconfig.ff+json;charset=utf-8"
                    }
                }
            ]
        }
    ]
}
```

Please be noted that for simplicity, the sample doesn't add label for the feature flag. Below is an example of adding label `myLabel`. 
```
"name": "[concat('.appconfig.featureflag~2F', parameters('featureFlagName'), '$myLabel')]"
```

**Comment by gregmalley** [comment]
Thank you @ZhijunZhao - I had finally gotten this working right before you sent this out, but in any case it is good to see the working example. Thanks!

**Comment by gregmalley** [comment]
Hi Everyone, @ZhijunZhao, Now I need to output the connection string but I cannot find an example nor can I piece together how to get tis done from the documentation - clearly I am missing something on how to figure out what functions are available for what resources...? I could use a poiter if there is a good resource on that. Also and to the specific point, I managed to get this working relatively easy for a cosmos resource I deployed per the snippet below, but I cannot figure this out for the app configuration. Can someone help with an example of that, perhaps based on ZhijunZhao's example from above?

```
Below works for cosmos db, how can I do this for app config resource?
      "connectionString": {
          "type": "string",
          "value": "[concat('AccountEndpoint=https://', variables('accountName'), '.table.azure.com:443/;AccountKey=', listKeys(variables('resourceId'), variables('apiVersion')).primaryMasterKey, ';')]"
      }
```

**Comment by gregmalley** [comment]
Hi - I got this working

'''
"connectionString": {
			"type": "string",
			"value": "[listKeys(resourceId('Microsoft.AppConfiguration/configurationStores', parameters('configStoreName')), '2020-07-01-preview').value[0].connectionString]"
		}
'''

**Comment by ZhijunZhao** [comment]
> Hi - Here is how to output the connection string
> 
> ```
> "connectionString": {
> 			"type": "string",
> 			"value": "[listKeys(resourceId('Microsoft.AppConfiguration/configurationStores', parameters('configStoreName')), '2020-07-01-preview').value[0].connectionString]"
> 		}
> ```

@jimmyca15 Can we apply the key filtering in ARM template?

**Comment by jimmyca15** [comment]
@ZhijunZhao not yet, but it's in the works. already being tracked: https://github.com/Azure/AppConfiguration/issues/427
