### ISSUE TITLE
403 Error - .Net Framework - While retrieving configuration

### ISSUE THREAD

**Issue by kamalsivalingam** [Azure/AppConfiguration#272]
I am getting 403 error when trying to pull configuration from Azure App Configuration in a **.Net Framework console App**

I am using below packages on .Net Framework 4.7.2 console project
Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration version="1.0.0-rc"
Microsoft.Configuration.ConfigurationBuilders.Base  version="2.0.0-rc"
Azure.Data.AppConfiguration" version="1.0.0-preview.6" 

I followed the steps from below URL:
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app

Below is the exception I got:
This exception was originally thrown at this call stack:
	Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(Azure.Data.AppConfiguration.SettingSelector, string, System.Threading.CancellationToken)
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by kamalsivalingam** [comment]
Sorry, ignore this ticket. It was due to a firewall issue

**Comment by drago-draganov** [comment]
Thanks for letting us known, @kamalsivalingam!

**Comment by drago-draganov** [comment]
Firewall issue reported
