### ISSUE TITLE
When will the `Microsoft.FeatureManagement` packages be released?

### ISSUE THREAD

**Issue by sanderaernouts** [Azure/AppConfiguration#275]
I noticed on NuGet.org that the Azure App Configuration related packages have been released 6 days ago. Are there any plans on creating a release version of `Microsoft.FeatureManagement` packages any time soon?

**Comment by zhenlan** [comment]
Yes, this is working in progress. A stable release of Microsoft.FeatureManagement.* should be available this/next week.

**Comment by zhenlan** [comment]
This stable version is just released
https://www.nuget.org/packages/Microsoft.FeatureManagement/2.0.0
