### ISSUE TITLE
Azure CLI - Setting KeyVault Ref now results in reserved content type error. 

### ISSUE THREAD

**Issue by perrymana** [Azure/AppConfiguration#276]
I've been using Azure App Config with Key Vault references for a few months now, using the Azure CLI to automate the setup and configuration. However it looks like something has changed in the last week or so. Trying to set Key Vault references in an Azure App Config instance via the Azure CLI now results in an error:
```
Content type is invalid. It's a reserved content type for KeyVault references.
```

My powershell script:
```
# Note that we *want* the backslashes in the actual string, they arn't escape characters in this context.
$ref = "{\`"uri\`":\`"https://dev-xxxxx-kv.vault.azure.net/secrets/MyConnectionString\`"}";

"Ref Value: $ref"
az appconfig kv set -y -n "dev-xxxxx-cfg" --key "testkey" --value=$ref --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
```

And output:
```
Ref Value: {\"uri\":\"https://dev-xxxxx-kv.vault.azure.net/secrets/MyConnectionString\"}
Content type is invalid. It's a reserved content type for KeyVault references.
```

This has been working previously, something must have changed in the last week or 2. 

I can still configure them via the Portal, and looking at the values that the cli returns it looks like the content type and value are the same as they were previously.

How do we now set Key Vault references via the cli? Do I need to format something differently? I've updated my Azure CLI to the latest, 2.1.0 , and don't see any different or additional parameters that I can pass.

**Comment by zhenlan** [comment]
@perrymana sorry for running into this. This is because creating keyvault reference is now officially supported by the CLI and you don't have to create them via the raw kv. Please check out
```
az appconfig kv set-keyvault -h
```

**Comment by perrymana** [comment]
Excellent! Thanks @zhenlan. I figure it would be something like that but didn't see the new command.

I've successfully used the new syntax and it is much easier then trying to construct the json fragment manually.

Cheers.
