### ISSUE TITLE
x-ms-useragent is no longer being accepted by appconfig (customer reported)

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/AppConfiguration#277]
A customer has reported an issue where appconfig is no longer accepting the x-ms-useragent header. This prevents users from using appconfig in the browser.

This was fixed in #217 but appears to have regressed and is missing again. I see this list of headers when doing an OPTIONS request against my own appconfig server (`x-ms-useragent` is not present):

```
$ curl -XOPTIONS -vv https://[app config server].azconfig.io
```

Headers:
```
< Access-Control-Allow-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
```

Customer issue: https://github.com/Azure/azure-sdk-for-js/issues/7529

**Comment by zhenlan** [comment]
This could be a regression due to recent changes for VNET support. We will fix it.

cc: @MSGaryWang

**Comment by edmclinn** [comment]
Any idea on when this will be corrected?  I would like to give an update to management on when this feature will be available again.

**Comment by zhenlan** [comment]
The next train of deployment will be next week, so by the end of next week, I hope the fix can be deployed to all regions if everything goes smoothly.

**Comment by edmclinn** [comment]
Are we still on track of this being deployed this week?

**Comment by alexgman** [comment]
Yes

**Comment by zhenlan** [comment]
The deployment has completed for all regions. This should work now.
