### ISSUE TITLE
Ask: Differentiate between key-value and keyvaultreference setting

### ISSUE THREAD

**Issue by swasun99** [Azure/AppConfiguration#278]
Looking for a way to differentiate between different configuration settings - 
Key-Value or a KeyVault Reference. Is there anything in documentation which am missing?

**Comment by zhenlan** [comment]
The KeyVault Reference has a specific content-type. You can use that to differentiate KeyVault Reference from the rest of Key-Values.

**Comment by swasun99** [comment]
Thank you @zhenlan
