### ISSUE TITLE
Ask: Code sample for EventGrid

### ISSUE THREAD

**Issue by swasun99** [Azure/AppConfiguration#279]
Does anyone have a code sample to handle KeyModified event in an AzureFunction through EventGrid? I referred the official documentation and there seems to be a sample with Azure CLI and am trying to do it using a proper AzureFunction through EventGrid subscription

**Comment by zhenlan** [comment]
@swasun99 you can simply call `TryRefreshAsync` in your Event Grid trigged Azure Function.

Please note, you may hit the issue https://github.com/Azure/AppConfiguration-DotnetProvider/issues/133. You can work around it by delaying the call for the length of your cache expiration time for now.

**Comment by swasun99** [comment]
Thanks @zhenlan
