### ISSUE TITLE
Docs (Design): Should the key "label" be changed to "version"? 

### ISSUE THREAD

**Issue by mlacouture** [Azure/AppConfiguration#28]
The fact that we need to use "version" to explain what a label is seems to indicate it should be called version.  

![image](https://user-images.githubusercontent.com/7647255/52091592-c5182b00-2569-11e9-9bb1-0cdf3489dfb0.png)

Label is quite confusing, it seems more like "tag" … observe the docs

![image](https://user-images.githubusercontent.com/7647255/52091410-31465f00-2569-11e9-8790-e653edfdc727.png)

In the meantime, for consistency, the docs should read "Versioning with labels" (we fixed this for the portal extension in the Azure Gallery).

**Comment by zhenlan** [comment]
Will stick with "label" for now.
