### ISSUE TITLE
Limit access to App Configuration from the Internet

### ISSUE THREAD

**Issue by azachert** [Azure/AppConfiguration#288]
Is there a mechanism to limit access to App Configuration to selected VNet / Subnet or selected IPs? I'm looking for a mechiansm similar to Networking from Key Vault or IP Restrictions from App Service.

**Comment by zhenlan** [comment]
@azachert App Configuration supports both
- VNET via private endpoint
- IP restrictions via service tag

These features will be rolled out in a week or two (public preview). Please let me know if you like to try it earlier and I can include you for private preview.

cc: @lisaguthrie

**Comment by zhenlan** [comment]
Both features are available for public preview now. Please find links to the documentation below.

- VNET via private endpoint
  https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-private-endpoint
- IP restrictions via service tag
  https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview
