### ISSUE TITLE
Auto refresh is not working 

### ISSUE THREAD

**Issue by Karthickramk** [Azure/AppConfiguration#289]
I downloaded sample **JAVA** application and changed connection string.

When I launched the application the keys are getting printed as expected.

Now i change the key value in my app config store and trying to read the property. But still it prints the old value. i do not see the refresh log as well in console.

Can you please let me know, if there is anything has to be done for the auto refresh?

**Comment by mrm9084** [comment]
@Karthickramk as of the latest release the package was split in two as auto refresh required a web dependency. If you want to use auto refresh update the artifact id to be spring-cloud-azure-appconfiguration-config-web. Additional info can be found in the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/SpringCloudAzureAppConfigurationConfig.md#112122---february-25-2020).

**Comment by Karthickramk** [comment]
Thanks Matt. I have couple of questions with app config.

1. Whenever we call get on the app config property, i see the below log in console.
**o.s.boot.SpringApplication               : Started application in 1.339 seconds**
Is the app getting restarted?

2.Can we override the property value for different environments?
Let's say I have configured 10 properties in dev. 
Now I want to use the same values for 9 properties with overridden value for one property in qa.
is it possible, instead of copying/creating all the 10 in qa?

Thanks,
Karthick

**Comment by mrm9084** [comment]
@Karthickramk 
1. The process of updating configurations is from a refreshEvent, which updates all refreshable bean, along with the configurations, which prints out the message when it is done. If there are open request they will be finished in the existing set of beans pre refresh.
2. If you set yourself up with multiple profiles you can override the other ones you want to see: https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config#spring-profiles. If you list your profiles as dev,qa it will load your dev profile then the qa profile overriding anything in dev.

**Comment by Karthickramk** [comment]
Thanks Matt.
