### ISSUE TITLE
Portal: after user types in an existing label, he must select again, otherwise reverts to Empty

### ISSUE THREAD

**Issue by recao** [Azure/AppConfiguration#29]
When user creates a new KV on Portal, after he/she types in an existing label, the user must select the label again with mouse, otherwise the label would revert to Empty by default, hence causing user miss-config potentially. 

1) User types in an existing label, now he/she must select again with mouse: 

![image](https://user-images.githubusercontent.com/20957260/52097559-6316f000-2580-11e9-906b-1ab8e7e81f9e.png)

2) Otherwise it would revert to Empty: 

![image](https://user-images.githubusercontent.com/20957260/52097606-978aac00-2580-11e9-9aab-dc13af1016f7.png)

Imaging the user types in "L1" and click "Apply" immediately, we would create a new KV with empty label.

**Comment by zhenlan** [comment]
This is fixed in the portal update this week.
