### ISSUE TITLE
<Ask> Need help to mock GetConfigurationSettings

### ISSUE THREAD

**Issue by swasun99** [Azure/AppConfiguration#290]
Am trying to mock ConfigurationClient GetConfigurationSettings method using Moq. I see the sample has mocks for GetConfigurationSetting and SetConfigurationSetting but the GetConfigurationSettings method returns a Pageable<ConfigurationSetting> which is an abstract class. Is there any way to mock it using Moq?

**Comment by zhenlan** [comment]
@AlexGhiondea can anyone suggest?

**Comment by zhenlan** [comment]
Add @AlexanderSher

**Comment by abhilasharora** [comment]
@swasun99 For the abstract class `Azure.Pageable<T>`, you can create your own mock implementation, or use the following sample class in your code.

``` csharp
class MockPageable : Pageable<ConfigurationSetting>
{
    private readonly List<ConfigurationSetting> _collection;

    public MockPageable(List<ConfigurationSetting> collection)
    {
        _collection = collection;
    }

    public override IEnumerable<Page<ConfigurationSetting>> AsPages(string continuationToken = null, int? pageSizeHint = null)
    {
        yield return Page<ConfigurationSetting>.FromValues(_collection, null, new Mock<Response>().Object);
    }
}
```

You can then use this class to set up mock for the `GetConfigurationSettings` method.

``` csharp
var testSettings = new List<ConfigurationSetting> { new ConfigurationSetting("testKey", "testValue") };
var mockClient = new Mock<ConfigurationClient>(MockBehavior.Strict, TestHelpers.CreateMockEndpointString());

mockClient.Setup(c => c.GetConfigurationSettings(It.IsAny<SettingSelector>(), It.IsAny<CancellationToken>()))
    .Returns(new MockPageable(testSettings));
```

**Comment by abhilasharora** [comment]
@AlexanderSher It might be useful to add the above code sample to the documentation [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample7_MockClient.md).

**Comment by zhenlan** [comment]
Issue moved to [Azure/azure-sdk-for-net #10662](https://github.com/Azure/azure-sdk-for-net/issues/10662) via [**ZenHub**](https://www.zenhub.com/)
