### ISSUE TITLE
Auto Refresh generating 401 errors

### ISSUE THREAD

**Issue by funkysi1701** [Azure/AppConfiguration#291]
I have configured auto refresh of my AppConfiguration but I can see from Application Insights a lot of 401 errors on https://*.azconfig.io/kv/UpdateKey?label=Prod&api-version=1.0

What am I doing wrong? As far as I can tell everything is working so not sure why I am getting these errors?

Here is the code that I have in my program.cs

```
config.AddAzureAppConfiguration(options =>
{
    options.Connect(new Uri("https://*.azconfig.io"]), new DefaultAzureCredential())
    .Select(keyFilter: "*", labelFilter: "Prod")
    .ConfigureRefresh((refreshOptions) =>
    {
        refreshOptions.Register(key: "UpdateKey", label: "Prod", refreshAll: true);
    });
});
```

**Comment by zhenlan** [comment]
@funkysi1701 can you please share the logs (not just 401, but logs in a period of time)?

**Comment by funkysi1701** [comment]
The issue appears to have stopped, so not sure what is happening. Looking at application insights the issue was happening between 2am Thur 6th March and 6pm Thur 6th March (times very approximate)

Event time | 06/03/2020, 07:54:20 (Local time) |  
Dependency type | HTTP |  
Result code | 304 |  
Dependency call status | true |  
Dependency duration | 30 ms |  
Remote dependency name | GET /kv/UpdateKey


Event time | 05/03/2020, 18:13:14 (Local time) |  
Dependency type | HTTP |  
Result code | 401 |  
Dependency call status | false |  
Dependency duration | 61 ms |  
Remote dependency name | GET /kv/UpdateKey

Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)


Event time | 05/03/2020, 17:43:29 (Local time) |  
Dependency type | InProc |  
Dependency call status | false |  
Dependency duration | 23 ms |  
Remote dependency name | ConfigurationClient.GetConfigurationSetting



Headers:
Server: nginx/1.16.1
Date: Thu, 05 Mar 2020 17:43:29 GMT
Connection: keep-alive
WWW-Authenticate: HMAC-SHA256,Bearer error="invalid_token", error_description="Authorization token failed validation"
x-ms-request-id: ce36b3e6-9584-4dbe-af95-849167da2ba5
x-ms-client-request-id: aedc103b-895f-4e99-8471-b7b324b7aeb3
x-ms-correlation-request-id: ce36b3e6-9584-4dbe-af95-849167da2ba5
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, x-ms-retry-after, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0

   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingAsync(String key, String label, DateTimeOffset acceptDateTime, MatchConditions requestOptions, CancellationToken cancellationToken)

**Comment by zhenlan** [comment]
According to the [document](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authentication/aad.md#errors):

**Reason**: The AAD token is not valid. **Solution**: Acquire an AAD token from the AAD Authority and ensure the proper audience is used.

**Comment by zhenlan** [comment]
@funkysi1701 please reopen if you need anything further.
