### ISSUE TITLE
Refresh configuration and cache expiration are not documented in the right place

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/AppConfiguration#292]
Currently, those are documented as a note under [one of the tutorials](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core#reload-data-from-app-configuration). It would be better to capture the documentation either under Configuration (which it's part of) or Concepts.

**Comment by zhenlan** [comment]
Thanks for the suggestions, @SeanFeldman.

cc: @lisaguthrie

**Comment by lisaguthrie** [comment]
Thanks @SeanFeldman! Agree that this information would be good to split out as a separate doc.

**Comment by zhenlan** [comment]
The refresh configuration and cache expiration are properties of the client libraries. It's not a concept of the service. So where it seems reasonable to me.
