### ISSUE TITLE
403 Forbidden Error with Contributor Role in .Net Framework App

### ISSUE THREAD

**Issue by kamalsivalingam** [Azure/AppConfiguration#295]
I am getting 403 forbidden error trying to access Azure App Configuration using AzureAppConfiguration ConfigurationBuilder 1.0.0 on a .Net Framework App.

However the same App Configuration instance is accessible using .Net Core App.
Note that we had to use Contributor role for the .Net Core app to work

**Comment by jimmyca15** [comment]
Hello @kamalsivalingam,

It sounds like you are talking about the AzureAppConfigurationBuilder mentioned [here ](https://github.com/aspnet/MicrosoftConfigurationBuilders#azureappconfigurationbuilder). When using the endpoint connection attribute, the "Azure App Configuration Data Reader" role or "Azure App Configuration Data Owner" role is required.

**Comment by kamalsivalingam** [comment]
Thanks a ton jimmyca15 for pointing at the exact fix and documentation. 💯

**Comment by jimmyca15** [comment]
@kamalsivalingam You're welcome. Thanks for using Azure App Configuration. 👍
