### ISSUE TITLE
Add "clear filters"

### ISSUE THREAD

**Issue by recao** [Azure/AppConfiguration#30]
After user specified a filter, if he wants to remove filters and see current config, he must refresh the entire Web page, or click another section in Portal and come back again: 

 
![image](https://user-images.githubusercontent.com/20957260/52097893-9c9c2b00-2581-11e9-84b0-831f65add469.png)

It would be great if we have a "clear filter" button that removes filters, so that user could check current config easily without refreshing the whole page.

**Comment by mlacouture** [comment]
filters will be redesigned, will consider this ask.
