### ISSUE TITLE
Updated Documentation for App Config Service Task

### ISSUE THREAD

**Issue by ssulei7** [Azure/AppConfiguration#301]
Hi,

We are currently using the App Config Service Task within our AzDO pipelines, but we do not have adequate documentation for the latest feature update that allows for trim key filters. Would someone kindly update the readme with samples that can be leveraged within our pipeline?
https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/AzureDevOpsPipelineExtension.md

**Comment by ssulei7** [comment]
To add on, we're trying to solve an issue where we have multiple prefixes:
`int:app:mySetting`, where we want to remove the prefix `int:app:`. The task doesn't really say how much in regards to how to properly do the trim, hence why we are requesting documentation.

**Comment by abhilasharora** [comment]
@ssulei7 As per the documentation, `TrimKeyPrefix` specifies one or more prefixes that should be trimmed from App Configuration keys before setting them as variables. Multiple prefixes can be separated by a new-line character.

**Example 1**
For a key `int:app:mySetting`, you can specify the prefix as `int:app:`. This will result in the key name being returned as `MYSETTING`

**Example 2**
For keys `int:app:mySetting` and `int:anotherSetting`, you can specify the prefixes as `int:app:` and `int:` separated by newlines. This will result in key names being returned as `MYSETTING` and `ANOTHERSETTING`.

**Comment by ssulei7** [comment]
Interesting, I have done the first example and that did not work at all in my pipeline. In fact, the task did not even perform the trim when that was specified. I believe there may be a bug present in the task.

![image](https://user-images.githubusercontent.com/22037844/77199460-dfd39900-6ab6-11ea-91d5-650e1483f530.png)

**Comment by ssulei7** [comment]
Update @abhilasharora, seems I needed to add white space at the end of the trim key prefix string. Seems to be a defect, can you try and reproduce?

**Comment by abhilasharora** [comment]
@ssulei7 I'm glad you found a workaround. I will forward this issue to the team for further investigation and make a fix as needed.

**Comment by Yiming-Jia** [comment]
Hello @abhilasharora  @ssulei7 ,

Thank you for reporting us an issue. I cannot reproduce the bug with our Azure AppConfiguration Task. I set a very similar key `int:exm:test`, and ran the task with Key filter as `int:exm:*` and label `dev`, and trim key prefix `int:exm:`. Also I tried with duplicated key as `test` or Key Vault ref as `test`, but I can get the key from environment variable with key name `test` in all test cases.

Could you please give us more details in your cases? 

Thanks,
Yiming

**Comment by Yiming-Jia** [comment]
Hello,

Please let me know if this issue still blocked you, otherwise we will close this issue. 

Thank you.
Yiming

**Comment by ssulei7** [comment]
> Hello,
> 
> Please let me know if this issue still blocked you, otherwise we will close this issue.
> 
> Thank you.
> Yiming

We are unblocked, but I'm concerned that even though the trim key prefix field was available, we still had failed deployments. Now it is working as intended, albeit, we are still appending whitespace and in some cases it does work without appending whitespace. I have not been able to consistently reproduce at this current point in time, but I will close out this ticket as it doesn't seem to be a major blocker as of now.
