### ISSUE TITLE
Question: Where is firewall feature?

### ISSUE THREAD

**Issue by mlomat** [Azure/AppConfiguration#304]
Hello guys,
I found that in the standard version there is option to create Private Endpoint. What is the reason for this feature if firewall is missing?  Or maybe I missed something?

**Comment by zhenlan** [comment]
Hi mlomat,

The Private Endpoint is for you to access App Configuration from within your Virtual Network (VNet) using a local network IP address. This way, you can set the firewall of your VNet the way you want without worrying about outbound traffic to App Configuration. You can find more details from [this document](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-private-endpoint).
