### ISSUE TITLE
Can/Should I use Feature Management for React-based website?

### ISSUE THREAD

**Issue by v-vrusse** [Azure/AppConfiguration#305]
Hi,

I've been tasked to evaluate different feature flag products by my MS team this sprint.  One of the products I'm researching is the new Feature Management section of AppConfiguration particularly since we are already using the Configuration Management section.

Ideally, we would like to add feature flags to our new React-based website.  However, I'm having some trouble determining whether Typescript is officially supported especially since all of the documentation I have found is .NET-based.  I did find this [Access feature flags](https://docs.microsoft.com/en-us/azure/azure-app-configuration/manage-feature-flags#access-feature-flags) section that briefly mentions that you could pretend that they are configuration key/value pairs and retrieve them that way.  Do they still support the [feature filters](https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core#configuring-a-feature-filter-in-azure-app-configuration) when accessed this way?

Could you please provide some design guidance around whether this product should be considered for React-based websites?

Thanks,
Vanessa

**Comment by v-vrusse** [comment]
@zhenlan Is there an internal Teams channel that I could reach out to the team in, since this issue seems to be getting zero traction?

**Comment by abhilasharora** [comment]
@v-vrusse Apologies for the delay in response. To answer your question, when the feature flags are retrieved as key-values, the associated feature filters are also returned.

A feature flags is stored as special configuration settings in the App Configuration store with the following data.

Name : `.appconfig.featureflag/{featureId}`
Value : JSON object that contains feature flag metadata (such as name and description), the actual value (true or false) and the feature filters.
Content Type : `application/vnd.microsoft.appconfig.ff+json;charset=utf-8`

For TypeScript, the REST API for regular key-values can be used to retrieve, create, update and delete feature flags. However, the value needs to be parsed as JSON to retrieve the data associated with the feature flag. The API reference documentation can be found [here](https://github.com/Azure/AppConfiguration#rest-api-reference).

Let me know if you have more questions. We also have a Slack channel that can be accessed [here](https://aka.ms/azconfig/slack).

**Comment by v-vrusse** [comment]
Hi @abhilasharora Thanks for the reply.  If I'm understanding you correctly, I could use the [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/appconfiguration) npm package to obtain the feature flags from App Configuration which also includes the information about the associated filters.  However because there is no Microsoft.FeatureManagement.Typescript package, I would need to implement all of the default filter logic myself.  Whereas if I was working with ASP.NET Core, the Microsoft.FeatureManagement.AspNetCore package would do all of the work for me.

Is this understanding correct?

**Comment by abhilasharora** [comment]
Yes @v-vrusse, your understanding is correct. It would require some additional code to parse the value of the JSON returned by the SDK, and evaluate the feature filters in your TypeScript code.
