### ISSUE TITLE
filter by prefix not functioning

### ISSUE THREAD

**Issue by marek011** [Azure/AppConfiguration#309]
I have problem with filtering only Feature Flags from App Configuration with Feature Flags and other settings (key vault references for example).

``` csharp
//problem with this calls is that they retrieve all key value pairs (not only FeatureFlags) which have no label
config.AddAzureAppConfiguration(options =>
                            {
                                options.Connect(connnectionString)                                    
                                    .UseFeatureFlags();
                            });

config.AddAzureAppConfiguration(options =>
                            {
                                options.Connect(connnectionString)      
                                    .Select(".appconfig.featureflag/*", "FeatureFlag")                              
                                    .UseFeatureFlags(configure =>
                                    {
                                        configure.Label = "FeatureFlag";
                                    });
                            });

config.AddAzureAppConfiguration(options =>
                            {
                                options.Connect(connnectionString)
                                    .Select(".appconfig.featureflag/*")
                                    .UseFeatureFlags();
                            });

// this call is working corrrectly (retrieving only feature flags and no other settings with no label)
config.AddAzureAppConfiguration(options =>
                            {
                                options.Connect(connnectionString)
                                    .Select(".appconfig.featureflag*")
                                    .UseFeatureFlags();
                            });
```
I have to use ".appconfig.featureflag*" instead of ```".appconfig.featureflag/*"```. I have seen that ```".appconfig.featureflag/*"``` is used in UseFeatureFlag extension. I will be thankfull for explanation.

**Comment by jimmyca15** [comment]
Hello @marek011, 

The feature flag support in the configuration provider was designed to always be used in unison with general configuration. It looks like it may be useful to have some method to opt out of the configuration query that takes place on top of the query for feature flags. That doesn't currently exist.

Regarding the current snippet you have to work with this issue I would recommend a different approach to avoid relying on the flag prefix. The idea is to select a non-existent key from Azure App Configuration. This is kind of like a [discard](https://docs.microsoft.com/en-us/dotnet/csharp/discards)

```
config.AddAzureAppConfiguration(options =>
    {
        options.Connect(connnectionString)
                    .Select("_") // Opt out of pulling general settings by selecting non-existent key
                    .UseFeatureFlags();
    });
```

The snippet sets up the Azure App Configuration provider to query for the "_" key for general configuration. We know "_" doesn't exist, or if it does in your app configuration then another non-existent key could be used. Then it sets up feature flags to be queried on top of that.

**Comment by marek011** [comment]
Ok, suggested solution works for me, thanks. I will close the issue.
