### ISSUE TITLE
"Compare" shows partial key-values

### ISSUE THREAD

**Issue by recao** [Azure/AppConfiguration#31]
When user compare two configuration hubs, the page would list ALL key-values, which has two problems when KV number > 500 : 
1) page & operations become very laggy
2) user needs to scroll all the way down to find the keys with different value

![image](https://user-images.githubusercontent.com/20957260/52098543-4086d600-2584-11e9-9054-e00fef1cf45a.png)

user has to scroll to very bottom to see every different key-values: 

![image](https://user-images.githubusercontent.com/20957260/52098574-6c09c080-2584-11e9-901f-c742cd9a7f5a.png)

**Comment by mlacouture** [comment]
We will redesign this blade to have a diff viewer with change type filtering …
