### ISSUE TITLE
Value being pulled into Azure DevOps is incorrect

### ISSUE THREAD

**Issue by ssulei7** [Azure/AppConfiguration#313]
Hello,

We have a use case within our organization where we are storing credentials within our app configuration service. We are currently running into an issue when we invoke the Azure App Config task where the password we are pulling down does not reflect what is out there in Azure.

Example Password: `myPassWord%`

Where the `%` at the end of my password turns into `%25`

This is currently blocking deployments in our lower environments, so I'm hoping there can be a work around to resolve this issue?

**Comment by Yiming-Jia** [comment]
Hello @ssulei7 ,

Thank you for reporting this issue. After testing, I confirmed this bug, and this is actually a bug from the AzureDevOps pipeline library we're consuming, which is a open source library provided by Azure DevOps team. We already created an issue under this repo: https://github.com/microsoft/azure-pipelines-task-lib/issues/627. You could also check the progress of the fix. We will also keep you updated once they provide us an ETA for the fix.

Thank you,
Yiming

**Comment by ssulei7** [comment]
Thank you for the quick response!

**Comment by ssulei7** [comment]
@Yiming-Jia Hi, following up on this bug to see if there's a working solution in flight?

**Comment by Yiming-Jia** [comment]
Hello @ssulei7 ,

Sorry for the delay response. We had internal communications with the pipeline library team to narrow down the issue. As they mentioned it's a 'by-design' from their library, we're preparing a change to take off the dependency from our task, which should fix the issue `%` here. Once we have the update, I'll follow up here.

**Comment by Yiming-Jia** [comment]
Hello @ssulei7 ,

We just deployed the latest pipeline task to fix this issue. To adjust this change, you have to go to your pipeline task, and select `3.*` version. Please let me know if it does not work for you. Thanks

**Comment by Yiming-Jia** [comment]
I will close this issue. And feel free to contact me if you still have the same issue.
