### ISSUE TITLE
Azure Portal Import/Export enhancement

### ISSUE THREAD

**Issue by HashTagDotNet** [Azure/AppConfiguration#316]
When I import a .json file, sometimes I will get a "Failed Importing XX keys".  And when I import again, it succeeds.  Related: when I import a file that doesn't match the schema exactly (e.g. trailing comma after the last item) it fails.

I would expect the UI to tell me which key(s) failed or schema validation errors.  Otherwise, I have to guess.

**Comment by jiayi11** [comment]
Thank you for your feedback. It will help if portal can provide more specific error messages when import fails. I've already created a work item for this and I'll let you know when there are updates.

**Comment by jimmyca15** [comment]
@jaiyi11 do we have any update in this regard?

**Comment by jparta** [comment]
When I try to import a config from another App Configuration in a another subscription, the process fails with the vague error "failed to import key-values". This error is not helpful in trying to get the import to work.

**Comment by zhenlan** [comment]
The import/export functionality in the Azure Portal has recently undergone a major update. Please open new issues if you have any further feedback.
