### ISSUE TITLE
[Question] Which is the correct Content-Type header

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/AppConfiguration#320]
Reading through some of the documentation both `Content-Type: application/vnd.microsoft.appconfig.kv+json;` (https://github.com/Azure/AppConfiguration/blob/master/docs/REST/headers.md#response-headers) and `Content-Type: application/vnd.microsoft.appconfig.keyset+json;` (https://github.com/Azure/AppConfiguration/blob/master/docs/REST/keys.md#list-keys) are listed. Are both values valid or is one valid and the other hasn't been updated?

**Comment by abhilasharora** [comment]
Both of the content types you shared are valid types returned from different REST calls.

1. For the endpoint `/kv/{key}?api-version={api-version}` the returned response would be of type `application/vnd.microsoft.appconfig.kv+json` and contain a key-value in its body.

2. For the endpoint, `/keys?api-version={api-version}` the returned response would be of type `application/vnd.microsoft.appconfig.keyset+json` and contain a set of keys in its body.
