### ISSUE TITLE
Feature Management:  Any plans on adding built-in support for rings?

### ISSUE THREAD

**Issue by v-vrusse** [Azure/AppConfiguration#322]
Are there any current plans to add built-in support for Rings to Feature Management?

Ring as used in this case contains:
- Set of specific users
- Desired state of feature flags

For example, I could set up three rings:
Ring0
     Users: Developers
     Feature Flags:  8 on

Ring1
    Users:  Internal Users
    Feature Flags:  5 on / 3 off

Ring2
    Users: External Users
    Feature Flags:  3 on / 5 off

I realize that it could be difficult for Feature Management to generically define and maintain sets of users particularly if they aren't in Azure AD; so the user sets likely will need to be supplied by an external handler.  The same is likely true for complex is User X in Set 1 checks.  However, It would really be nice to not have to build the rest of the functionality from scratch.

**Comment by zhenlan** [comment]
@v-vrusse this is supported by the recent release of the [v2.1.0-preview ](https://www.nuget.org/packages/Microsoft.FeatureManagement/2.1.0-preview)feature management library. Please check out the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/Microsoft.Featuremanagement.md#210-preview---apr-22-2020), which has a link to more detailed documentation.

Please let us know how it works for you.

**Comment by v-vrusse** [comment]
Awesome!  I'll definitely check it out.

Closing this as question was answered
