### ISSUE TITLE
ARM template for Azure app configuration not considering SKU Free/Standard.

### ISSUE THREAD

**Issue by kaushik-hemant** [Azure/AppConfiguration#325]
Referring to https://docs.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/2019-10-01/configurationstores.

I'm providing Free/Standard but resource SKU didn't get changed as per the value provided in ARM.

Can somebody help me out with this asap?

`{
  "name": "string",
  "type": "Microsoft.AppConfiguration/configurationStores",
  "apiVersion": "2019-10-01",
  "location": "string",
  "tags": {},
  "identity": {
    "type": "string",
    "userAssignedIdentities": {}
  },
  "properties": {},
  "sku": {
    "name": "string"
  }
}`

Awaiting response.

**Comment by zhenlan** [comment]
@kaushik-hemant not sure I get the question. The value of "sku" can be either "free" or "standard", but this may not be your question. Can you please clarify?

**Comment by kaushik-hemant** [comment]
@zhenlan The template specified above is not creating the resource as per the value specified in "SKU" property, It'll create a free tier despite Standard in value. And there is no update from Free to Standard if provided Standard and existing one is on Free.

**Comment by zhenlan** [comment]
@kaushik-hemant if I understand correctly, you are talking about two issues. Can you please confirm?

1. You cannot create a Standard SKU App Configuration store with ARM template even if you specify "standard" in the sku parameter. You always get a Free SKU store. Can you please share your ARM template?
2. You cannot upgrade a Free SKU App Configuration store to Standard SKU with ARM template. Did you get any error?

**Comment by kaushik-hemant** [comment]
@zhenlan Yes, for 2, there is no error in response but tier remains unchanged.

**Comment by wahyuen** [comment]
we had the exact same thing happen on a customer install...we only discovered the issue AFTER we hit the free tier quota restrictions :/ we found no errors in the ARM output to indicate something went wrong.....only that the new standard SKU was NOT applied

**Comment by zhenlan** [comment]
Thanks for the information. We are looking into this.

**Comment by ZhijunZhao** [comment]
@kaushik-hemant  @wahyuen Could you share the template and steps that can repro the issue?

I'm unable to repro using below template. 

_{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "variables": {},
    "resources": [
        {
            "name": "test-sku",
            "type": "Microsoft.AppConfiguration/configurationStores",
            "apiVersion": "2019-10-01",
            "location": "westus",
            "sku": {
              "name": "free"
            }
        }
    ]
}_

1. Use AZ CLI to provision with above template. The config store can be successfully provisioned and it's free tier. 
2. Change `free` to `standard` in the template and rerun the AZ command. The config store can be changed to standard tier successfully.

If `standard` sku is specified in the first place, the config store can also be provisioned and it cannot be downgraded to free tier, which is by design.

**Comment by ZhijunZhao** [comment]
Any update? If possible, please share the configuration store name and the time. 

One possibility is that incorrect API version is used. Old API version '2019-02-01-preview' doesn't support the 'sku' property.

**Comment by wahyuen** [comment]
![image](https://user-images.githubusercontent.com/4549796/83095214-56070400-a0d5-11ea-9ed2-7e230c429082.png)

Perhaps that is the issue...it unfortunately does not seem to indicate any error when you run this, thus we had assumed it had worked. We'll update the API version in our templates to adjust.

**Comment by ZhijunZhao** [comment]
Awesome! Below is a useful link that you can reference for API versions and their supported properties. 

https://docs.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/allversions
