### ISSUE TITLE
How to seed Feature-flags details using Azure pipelines?

### ISSUE THREAD

**Issue by kaushik-hemant** [Azure/AppConfiguration#326]
Is there any way to bulk seed feature-flags while provisioning Azure app configuration using ARM/CLI/PowerShell?

As far as I can see there I only one way to add feature-flags is Azure CLI but it works with single insertions and feature-flags will definitely be more than one for production scenarios. For manipulation, there is a niche dashboard but setting up details in the infrastructure isn't available.

I'll appreciate a quicker response.

**Comment by zhenlan** [comment]
@kaushik-hemant if you have feature flags in FeatureManagement section of a JSON file, the CLI can import all feature flags at once (`az appconfig kv import -h`).

**Comment by kaushik-hemant** [comment]
@zhenlan Is there any sample format for the JSON including labels and filters?

**Comment by mrm9084** [comment]
@kaushik-hemant I don't know of a sample, but we do have a schema file, https://github.com/Azure/AppConfiguration/blob/master/docs/FeatureManagement/FeatureFlag.v1.0.0.schema.json.

**Comment by zhenlan** [comment]
@kaushik-hemant here is an example https://github.com/microsoft/FeatureManagement-Dotnet/blob/master/examples/FeatureFlagDemo/appsettings.json

You can specify the label when you import the file.

**Comment by kaushik-hemant** [comment]
@zhenlan This seems okay, but what if I don't have any filters. Let say I want to enable and ship a feature for all having a label beta with no additional filters like percentage or users.

**Comment by zhenlan** [comment]
@kaushik-hemant you can import the JSON file again to override the values of feature flags in the store. You can also enable individual feature flag with the CLI command `az appconfig feature enable -h`.
