### ISSUE TITLE
Error with the version 3.0.13 : ##[error]Unhandled: Cannot find module '../lib/Utils'

### ISSUE THREAD

**Issue by sebfantini** [Azure/AppConfiguration#327]
Hello,
I downloaded and registered the extension in my AzDevopsAccount.
Next, when I use the simple code in Azure pipeline YAML :
- task: AzureAppConfiguration@3
  inputs:
    azureSubscription: 'myAzDevopsEndPoint'
    ConfigstoreName: 'myazureaccountconfiguration'
    KeyFilter: '*'

I have the error bellow :
##[error]Unhandled: Cannot find module '../lib/Utils'

Thanks for your help,

**Comment by Yiming-Jia** [comment]
Hello @sebfantini ,

Sorry for the inconvenience here. Do you run the task through Azure DevOps pipeline? The reason that we ask is that we just found the task could be ran in both Azure DevOps Services and Azure DevOps Server. And we have been testing the task against Azure DevOps Services and I cannot reproduce this issue. Could you also try to downgrade to version 2.* and try it once. Thanks

**Comment by sebfantini** [comment]
Hello @Yiming-Jia 
Thank you for your quick response. We use Azure Devops Services' YAML Pipelines.
We installed, uninstalled and reinstalled the latest version of the extension (version 3). And it's always that same error that appears when using the extension in the pipeline.
How can I install and use version 2 of the extension ? or how can I downgrade to version 2.* ?
You will find screen copies attached to this message.
![2020-05-12_10-00-50](https://user-images.githubusercontent.com/51829691/81657072-e12a9d80-9437-11ea-9f36-1817d603a018.png)
![2020-05-12_10-05-15](https://user-images.githubusercontent.com/51829691/81657360-1df69480-9438-11ea-9cd9-4bdb0daded39.png)
![2020-05-12_10-07-16](https://user-images.githubusercontent.com/51829691/81657735-657d2080-9438-11ea-8501-2f8ff294a243.png)

**Comment by Yiming-Jia** [comment]
Hello,

Thank you for the information. When specify the task name at yaml file, you could use `AzureAppConfiguration@2` to use version 2.* to see if it works. I'm looking for a fix for version 3.*.

**Comment by sebfantini** [comment]
Hello,
When I use AzureAppConfiguration@2, I have the error : "Build Not found" :
![2020-05-13_12-07-58](https://user-images.githubusercontent.com/51829691/81800189-b6f9de00-9512-11ea-9379-e4cb157d6b34.png)

**Comment by Yiming-Jia** [comment]
Hello @sebfantini ,

We just published a newer version of the task to fix this issue in Linux environment. Please try the build again and let us know if it still doesn't work.

Thanks,
Yiming

**Comment by sebfantini** [comment]
Hello @Yiming-Jia ,
It works with the new version (3.0.14).
Congratulation and thank you for your work.
You can close this issue.

**Comment by sebfantini** [comment]
I close this issue.
