### ISSUE TITLE
Changes in access control (RBAC) have an effect only after substantial amount of time

### ISSUE THREAD

**Issue by marcin-vt** [Azure/AppConfiguration#330]
Granting/revoking role assignment in App Configuration IAM seems to need ~10 minutes to have an effect on REST API calls (python lib). For az cli it is instantaneous. 

Also seems like az cli has different access rules than REST API (https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac). For example account which is owner of an app configuration, but doesn't Data Owner, Data Reader or Contributor roles, can perform any kind of operations on using az cli (e.g. `az appconfig kv list -n XXXX `), however using REST API it cannot do anything. Also the other way account, which has only the Data Owner role on an app config, can manipulate config values through REST API, but not using az cli. Is this intended?

**Comment by drago-draganov** [comment]
RBAC role assignment can take a few minutes to propagate. That is consistent with the RBAC experiences with other Azure services.
When CLI uses the owner of that resource, it first gets app configuration Access Keys. Then sends HMAC authenticated request.  So, it doesn't go through AAD authentication and RBAC.
The rules aren't different for REST. We support both AAD and HMAC authentication schemes. If REST request uses HMAC authentication, it won't be subject to RBAC propagation times.

**Comment by marcin-vt** [comment]
Thank you for clarification @drago-draganov.
