### ISSUE TITLE
Attempting to set JSON content via PowerShell commandlets trims double quotes 

### ISSUE THREAD

**Issue by neraath** [Azure/AppConfiguration#331]
When I run the following command thru PowerShell:

```
$env:app_config_name = "my-app-config-instance"
az appconfig kv set -n "$env:app_config_name" --key "app:keyname" --value "{`"push_to`":`"search_bulk_worker_queue`",`"push_type`":`"queue`"}" --content-type "application/json" -y
```

I get the following:

```
{
  "contentType": "application/json",
  "etag": "<someetag>",
  "key": "app:keyname",
  "label": null,
  "lastModified": "2020-05-17T07:51:52+00:00",
  "locked": false,
  "tags": {},
  "value": "{push_to:search_bulk_worker_queue,push_type:queue}"
}
```

As you can see from above, the quotes around the properly and value names are being stripped from the value. Thus, when my application tries to load those configs, it fails because it cannot parse the JSON properly. 

I get the same result if I use the following to try to escape the JSON:

```
'{"push_to":"search_bulk_worker_queue","push_type":"queue"}'
"{""push_to"":""search_bulk_worker_queue"",""push_type"":""queue""}"
```

If I try to use the following as JSON:

```
"{\"push_to\":\"search_bulk_worker_queue\",\"push_type\":\"queue\"}"
```

I get the following error:

```
az: error: unrecognized arguments: push_to\:\search_bulk_worker_queue\,\push_type\:\queue\}
```

**Comment by drago-draganov** [comment]
Thanks @neraath 
We are looking into this.

**Comment by shenmuxiaosen** [comment]
There are some known quoting issues for using CLI in powershell. Here are more details and solutions. https://github.com/Azure/azure-cli/blob/dev/doc/quoting-issues-with-powershell.md#symptom  Basically in your case, if you are using powershell later than version 3.0, you may use stop-parsing symbol ```--%``` between ```az``` and arguments.
