### ISSUE TITLE
Disabling app configuration via 'spring.cloud.azure.appconfiguration.enabled' property not possible

### ISSUE THREAD

**Issue by duygukuecuek** [Azure/AppConfiguration#332]
**Actual:** Setting the '_spring.cloud.azure.appconfiguration.enabled_' to false on e.g. local environment does not disable the [AppConfigurationWebAutoConfiguration](https://github.com/microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-appconfiguration-config-web/src/main/java/com/microsoft/azure/spring/cloud/config/web/AppConfigurationWebAutoConfiguration.java) and leads to a NoSuchBeanException for the configListener.

**Expected:** Setting the '_spring.cloud.azure.appconfiguration.enabled_' to false should disable App Configuration on the corresponding environment without throwing a NoSuchBeanException.

**Additional information:**

Used app configuration libraries:
- 1.2.5: https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-feature-management-web
- 1.2.5: https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-appconfiguration-config-web

Used Spring Boot version: 2.2.5

**Comment by zhenlan** [comment]
@duygukuecuek thanks for reporting the issue. We are looking into this.

**Comment by duygukuecuek** [comment]
Hi @zhenlan, any updates? Unfortunately this bug is blocking our usage of Azure App Configuration.

**Comment by zhenlan** [comment]
@mrm9084 any updates?

**Comment by mrm9084** [comment]
@zhenlan It seems that when we split into two packages the ability to turn off refresh wasn't removed, an the correct check to turn off refresh if appconfiguraiton is disabled, doesn't exist. We will need to added that in. I can look into creating a new bug fix release to put this into.

**Comment by duygukuecuek** [comment]
Hi @mrm9084 and @zhenlan, any estimation on how long releasing a new version with this bug fix could take?

**Comment by mrm9084** [comment]
@duygukuecuek We are working on a new bug fix release now, which this will be included in. We don't have an exact date at the moment. It will be a week or two depending on how long the planed fixes take.

**Comment by mrm9084** [comment]
@duygukuecuek Version 1.2.7 was just released and should fix this issue.
