### ISSUE TITLE
No change history shown in Activity logs of App Configuration store

### ISSUE THREAD

**Issue by duygukuecuek** [Azure/AppConfiguration#333]
**Actual:** The Activity logs in App Configuration store are currently not showing the change history for the key-values updated in 'Configuration explorer' or 'Feature manager' even changes were made.

**Expected:** The Activity logs in App Configuration store should show the change history in order to track which value was changed by whom.

![change-history-not-working](https://user-images.githubusercontent.com/65530989/82201750-1edc6a00-9901-11ea-9d24-7b6253eea29d.png)

**Comment by zhenlan** [comment]
Dup of https://github.com/Azure/AppConfiguration/issues/366
