### ISSUE TITLE
Support short comment or description for key value pairs in Configuration Explorer

### ISSUE THREAD

**Issue by k8edev** [Azure/AppConfiguration#335]
I would like to associate a short comment with my key value pair to provide context on its meaning. In my case, we are storing client IDs, and I would like to associate each ID with a short comment saying which application/Azure resource it points to.

I see that we can add Tags to individual key-value pairs. If the Tags could be visible in the default view of the Configuration Explorer, that would also solve the problem for me.

**Comment by zhenlan** [comment]
@ccowden the scenario you described makes sense to me. Tags are also the place I would recommend to save this information. To show this information in the default view of the Configuration Explorer, however, needs the support for UI customization. As you can imagine, one field could be important for one user but could be totally waste of space for another user.

Thanks for the feedback. We will take this into consideration for future design.

**Comment by TechWatching** [comment]
Tags seem absolutely necessary to be able to identify quickly which ressource use which setting. That's something that we can see in KeyVault so it makes sense to be able to see it in Azure App Configuration as well. Maybe it does not make sense for all users but maybe you can make the UI configurable depending on what the user wants to see.

**Comment by HFCherish** [comment]
I suggest that there's description column for the configuration explorer, too. Sometimes, we have restrictions on the fields, e.g. it must be positive number, or must be provided with another configuration item, etc. The descriptions on the fields are necessary.
Without it on portal, we have to maintain a separate doc on these fields, and have to consider the different descriptions for different versions.
I also post a [feature request](https://feedback.azure.com/forums/34192--general-feedback/suggestions/41110705-allow-to-add-description-for-each-keys-in-configur)

**Comment by drago-draganov** [comment]
These are great points! 
Looking forward, I think we may need an option to allow some sort of a schema here. Description alone doesn't look solid to deal with constraints long term.

There is relatively new RFC draft for json schema (https://json-schema.org/). The support looks good across tools and libraries. It also fits well with our upcoming support for key-value media type ``application/json``. Here is an example:

Key-Value:

key: "discount"
value: "33.3"
content-type: "application/json"

Schema:

`js
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "description": "Percent discount",
    "type": "number",
    "minimum": 0,
    "maximum": 100
}
`

**Comment by Edgaras91** [comment]
Any progress on this? and are these features being considered? I particularly would want to request for Descriptions field. Would save documenting our configs separately elsewhere and have them out of sync.

**Comment by jimmyca15** [comment]
Hello all,

we added the capability to display tags in the default view of the configuration explorer. The tags column should be added via configuration explorer settings. See below:

![image](https://github.com/Azure/AppConfiguration/assets/21000428/3adfd679-f51d-4a87-85fc-8f41256c9eba)

I will close this issue since the original post mentions this as a solution.

@drago-draganov please let me know if'd like me to open a separate issue to track json schema
