### ISSUE TITLE
RBAC for the APP configuration 

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#336]
I am looking for the way to provide read-only access for a user where a user can only see the key-value pair in configuration explorer.

I tried providing App configuration data reader role to the user but it is not working.

I logged Microsoft ticket and the following reply came 

"**azure app configuration does not support AAD authentication for App Configuration data access**"
 please suggest what we can do about it.

**Comment by zhenlan** [comment]
@Bhanu88 App Configuration definitely supports AAD authentication for *data* access.

I recently updated the document below and added a note for accessing data via Azure portal or CLI. Please let me know if that addresses your question.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#built-in-rbac-roles-for-azure-app-configuration

**Comment by zhenlan** [comment]
@Bhanu88 I am closing this. Please let us know if you have further questions.
