### ISSUE TITLE
AAD authorization and delegated permissions

### ISSUE THREAD

**Issue by et1975** [Azure/AppConfiguration#338]
I'm trying to access AppConfiguration APIs from an SPA (a bowser app) using msal-js 2 beta and authorization code flow. The problem seems to be that I can't specify AppConfig URIs as a scope.

Here's the corresponding issue I opened in the msal repo: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1722, but I think the problem is on the AppConfig side - it's not listed as an API I can request delegated permissions for.

For example, here's what adding delegated access to Storage API looks like when I configure my Application in AAD:
![image](https://user-images.githubusercontent.com/623703/83271078-5b2c8780-a197-11ea-800a-2721e2e5945b.png)

Looking for suggestions.

**Comment by zhenlan** [comment]
@drago-draganov any suggestions?

**Comment by drago-draganov** [comment]
Thanks for reporting the issue, @et1975 
Service manifest section regarding permission delegation is missing. We are working on enabling that.

**Comment by AerikAwesome** [comment]
Have there been any developments on this issue? Running into this myself now

**Comment by drago-draganov** [comment]
Great timing, @AerikAwesome!
The feature is out for deployment. It should be publicly available sometime next week. I will update the thread once completed.

**Comment by drago-draganov** [comment]
The API Permissions feature is deployed. 

At this moment you will need to lookup using Azure AppConfiguration App ID directly. We are working to enlist into the public set of Microsoft APIs, but that may take a couple of weeks to finalize.

If you want to give it a try now:

1.	Go to the Azure Active Directory explorer in the Azure Portal.
2.	Go to your AAD App in that you want to use Azure App Configuration OAuth scopes.
3.	Click the API permissions tab and click Add a permission
4.	Search for permissions exposed by Azure App Configuration, using the App ID `35ffadb3-7fc1-497e-b61b-381d28e744cc`
        Note. it may appear as “Microsoft.Azconfig” on this page instead of “Azure App Configuration”.
5.	Check the permissions you want your App to require and apply.


Let us know on any issues, questions or concerns.
Thank you!

**Comment by AerikAwesome** [comment]
Authorized succesfully, thank you very much.

I'm running into the next issue though (related, or should I open another issue?):
How can I use a token retrieved using the Microsoft.Identity.Web library (TokenAcquisition.GetAuthenticationResultForUserAsync) to authenticate an Azure.Data.AppConfiguration.ConfigurationClient? It seems to only accept implementations of Azure.Core.TokenCredential, but I don't see a way of creating one of the provided implementations with the data I have.

**Comment by drago-draganov** [comment]
@AerikAwesome Please open a new issue.
