### ISSUE TITLE
RBAC access for Service Principals

### ISSUE THREAD

**Issue by sslepova** [Azure/AppConfiguration#339]
Hi! I'm trying to access AppConfig data from Azure release pipeline using [Azure App Configuration task](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task&ssr=false#overview).
But I face an issue: I have two AppConfig resources in the same subscription and one Azure DevOps subscription-level service connection. AAD service principal corresponding with this service connection is included in the "Contributors" group for both AppConfig stores. 

But my release pipeline can get data from one AppConfig and can't from another one.
I tried to access AppConfig data using REST API and identity of this service connection with exactly the same result - I can access data of the first store, but not from the other.
I couldn't find any significant difference between these two stores. What could be the problem here? How can I figure out what's wrong or what's missing in my second AppConfig store?

**Comment by zhenlan** [comment]
@sslepova please let me know if the information in the troubleshooting section of the [Azure App Configuration task](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task&ssr=false#overview) is helpful (copied below for convenience).

>Error message: Access to 'https://example.azconfig.io' was denied. Please ensure the required role assignment is made for the identity running this task.

>Version 2.* and above require the service principal used by the task to be a part of the "Azure App Configuration Data Reader" or "Azure App Configuration Data Owner" roles for the target App Configuration instance. Version 1.* requires the "Contributor" role instead.

cc: @Yiming-Jia

**Comment by sslepova** [comment]
@zhenlan, actually yes. It worked when I've assigned "App Configuration Data Reader" role to service principal.
I just thought "Contributor" role includes permissions specific for the "App Configuration Data Reader" role. And when I read this troubleshooting section earlier, I understood this as role "App Configuration Data Reader" is a minimal requirement to read data and "Contributor" would do the trick anyway.
Moreover, "Contributor" works fine for 2 of 5 AppConfig stores I have tested (still not sure what's the difference besides creation time). So it all got me confused.
Anyway, thank you for your answer!

**Comment by zhenlan** [comment]
@sslepova thanks for the confirmation. I'm glad It worked for you.

The section **Built-in RBAC roles for Azure App Configuration** in the link below has more explanation of the differences between different roles. I hope it will be helpful to you.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac
