### ISSUE TITLE
Search should allow for double wildcards

### ISSUE THREAD

**Issue by ssuing8825** [Azure/AppConfiguration#342]
I used to be able to do this search in powershell back in december. Is that gone now?  I can put the wildcard first or last, but not both. Is that right

`az appconfig kv list --key *Font* --label UAT -o table`

**Comment by drago-draganov** [comment]
Thanks for this question, @ssuing8825. 

We were piloting a bit more extensive query functionality during Azure AppConfiguration Preview. As you've noticed, the service allowed for additional wildcard search at that time. Our analysis back then concluded that the feature doesn't meet the quality bar for the initial General Availability release. Our telemetry also suggested almost no demand. I can assure you that the decision to postpone the feature wasn't taken lightly. 

Your feedback is very important to prioritize accordingly going forward.

**Comment by ssuing8825** [comment]
Thanks for the response. I'm working at a large insurance company and there are thousands and thousands of configuration setting across 15+ environments. I was hoping to use this to create a governance/auditing UI. I think both keys and labels only do prefix or suffix so I'll have to think of another way to accomplish the same goal.

**Comment by zhenlan** [comment]
We currently don’t have a plan for this. If the situation changes, we can revisit it.
