### ISSUE TITLE
Azure App Configuration DevOps task does not find any key-values

### ISSUE THREAD

**Issue by sdas-tech** [Azure/AppConfiguration#343]
I am using version 3.0.14 of the 'Azure App Configuration' task.
The task is using an existing service connection, and the associated service principle has an 'Azure App Configuration Data Reader' role on the App Configuration instance. (same problem if I give it an owner role)

Although there are many values in my App configuration with a label of "LMS", the pipeline task does not find any. I have tried with a filter value of '*' as well however I get the same issue. The task is still marked as succeeded.
![image](https://user-images.githubusercontent.com/1049519/84046806-e7d41280-a9ed-11ea-9098-1dc1fcebc747.png)

![image](https://user-images.githubusercontent.com/1049519/84047258-6c269580-a9ee-11ea-8c81-325e8cc416c5.png)

tail end of logs (some addresses redaced):
2020-06-02T00:18:14.0858684Z Downloading key-value pairs using: 'https://MYAPPCONFIG.azconfig.io'.
2020-06-02T00:18:14.0887320Z ##[debug][POST]https://login.windows.net/***/oauth2/token/
2020-06-02T00:18:14.7260164Z ##[debug][GET]https://MYAPPCONFIG.azconfig.io/kv?key=LMS*&label=%2500&api-version=1.0
2020-06-02T00:18:21.3850429Z '0' key-values were retrieved from Azure App Configuration using the key filter: 'LMS*'.
2020-06-02T00:18:21.3853011Z ##[debug]task result: Succeeded
2020-06-02T00:18:21.3859644Z ##[debug]Processed: ##vso[task.complete result=Succeeded;done=true;]
2020-06-02T00:18:21.3932328Z ##[section]Finishing: Azure App Configuration: esb-app-configuration

**Comment by zhenlan** [comment]
@sdas-tech according to your screenshot, you are loading **keys that start with LMS and have no labels** instead of **all keys with label LMS**.

**Comment by sdas-tech** [comment]
Thanks @zhenlan, Ive got it working when I explicitly filter for the LMS label, but how can I get the task to download all key-values regardless of label? I cant seem to use '*' in the label field.
![image](https://user-images.githubusercontent.com/1049519/84095230-1e3b7d00-aa42-11ea-9348-bc6f5217eed7.png)

**Comment by zhenlan** [comment]
@sdas-tech DevOps pipeline does not support multiple values for the same key. How do you like to use them if you were able to download all values with different labels for the same key?

If you are considering the composition of key-values from multiple labels, please check out the section below under FAQ:
- [How do I compose my configuration from multiple keys and labels?](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task)

**Comment by zhenlan** [comment]
@sdas-tech please let us know if you have further questions.
