### ISSUE TITLE
Issue creating security when calling 

### ISSUE THREAD

**Issue by ssuing8825** [Azure/AppConfiguration#344]
I put this on the slack channel, but no on responded

I'm using postman to make request and I've added security in the prerequest scripts using the example the documentation provided.. I can get some things to work, but as soon as I add a wild card '*' i get a 401. It doesn't look like the security headers are being created correctly. Do I need to change the javascript presented in the documentation?  I've tried escaping the start, but that didn't work.  TIA
This works
https://demo-ac.azconfig.io/keys?name=abc&api-version=1.0
This doesn't work
https://demo-ac.azconfig.io/keys?name=abc*&api-version=1.0

this is the javascript I added. https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authentication/hmac.md

**Comment by drago-draganov** [comment]
Hello @ssuing8825 

Please provide the value of ``x-ms-request-id`` response header. Thank you!

**Comment by ssuing8825** [comment]
Here you go d3dd1dcd-6112-495b-86a6-d205ccc685fb

**Comment by drago-draganov** [comment]
In this case the client sends encoded ``*`` as ``%2A``. It's likely that the HMAC signature is calculated on unencoded path+query. Therefore a mismatch and authentication failure. 
Perhaps you can try the newest version of Postman. It should allow for better control of how the request url is auto-encoded.

**Comment by ssuing8825** [comment]
I upgraded to 7.26 and it still failed. I turned on "Use next generation URL Parsing" and was successful. Thanks for your help.
