### ISSUE TITLE
Cannot filter to selected labels in UI

### ISSUE THREAD

**Issue by jmsalvo** [Azure/AppConfiguration#349]
When I select a label in the drop-down to filter the list of key-values, the UI spins and eventually displays an error stating 'User is not able to connect to the service...We had trouble reaching the server...'

**Comment by jiayi11** [comment]
Hello @jmsalvo, thank you for reporting this issue. Does the error page only show up when you filter by labels? If you refresh all key-values can you see the error page as well? It seems you are experiencing some network issues.

**Comment by jiayi11** [comment]
And just want to confirm with you, does your error page look like the following? If not, could you please send me a screenshot of yours?
![image](https://user-images.githubusercontent.com/14067510/84719503-64a44680-af30-11ea-81fa-19f2dd0cc260.png)

**Comment by zhenlan** [comment]
@jmsalvo please let us know if you have further information.
