### ISSUE TITLE
How to retrieve values in Azure Functions Trigger Attributes?

### ISSUE THREAD

**Issue by JosXa** [Azure/AppConfiguration#354]
With a regular `settings.local.json` configuration, you can access arbitrary configuration values inside of Azure Functions Trigger attributes using a `%Namespace1:Namespace2:Key%` notation, e.g. `[TimerTrigger("%MyNamespace:MyCronExpression%")`. However, the `IConfigurationOptions` registry doesn't seem to load values in the same way from a registered Azure App Configuration by default. 

Any tips on how to make App Configuration values known to Functions trigger attributes?

**Comment by zhenlan** [comment]
Duplicate of #203
