### ISSUE TITLE
Azure Function with MSI reading KV backed App Configuration

### ISSUE THREAD

**Issue by tgindrup-inroll** [Azure/AppConfiguration#355]
We're developing a v3 Azure Function that uses MSI to authenticate  against the App Configuration store using the End Point.  Following the sample found here:
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?tabs=core3x

We implemented the following:
`            var configurationBuilder = new ConfigurationBuilder();

            _configuration = configurationBuilder.AddAzureAppConfiguration(options =>
            {
                string connection = Environment.GetEnvironmentVariable("configurationEndpoint");
                var credentials = new ManagedIdentityCredential();
                options.Connect(new Uri(connection), credentials)
                .ConfigureKeyVault(kv =>
                {
                    kv.SetCredential(credentials);
                });
            }).Build();
`

As expected this throws an exception when running locally.  But when running in the Azure Portal, on a function with MSI turned on, and the Function has App Configuration Data Reader permissions on the App Configuration instance and both the App Configuration Instance and the Azure Function have Access Policies to retrieve secrets along with setting Key Vault Secret User under IAM for Key Vault for both.

When executing in the portal we get simply:
Value cannot be null. (Parameter 'connectionString')

I'm sure there's something I'm missing.

TIA

**Comment by abhilasharora** [comment]
@tgindrup-inroll The code snippet that you shared isn't expected to result in that exception. Could you share the stack trace so we could debug it further? Also, is that the same exception that you get when running locally?

**Comment by tgindrup-inroll** [comment]
This is what I get when running locally:

Azure.Identity.CredentialUnavailableException: 'ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.'

**Comment by tgindrup-inroll** [comment]
@abhilasharora thank you for pointing me to the stack trace!  Stupid noob mistake.  The above code worked - my app using the settings didn't.  Again thank you!!
