### ISSUE TITLE
Azure DevOps Pipeline Task: Filtering keys using comma delimiter doesn't work

### ISSUE THREAD

**Issue by sslepova** [Azure/AppConfiguration#356]
I was trying to filter keys using a complex condition containing several different conditions delimited with a comma like 
`App:DB:*, App:AppInsight:APIKey`
As far as I understand it doesn't contradict [these rules](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value#query-key-values).
But apparently it doesn't work this way. For this type of filter `App:DB:*, App:AppInsight:APIKey` I get this error message:
`An unexpected '400' response was received from 'https://AppConfigName.azconfig.io/kv?key=KeyName&label=Label&api-version=1.0'`
And when I just try to list full key names without using wildcard there are no errors but only one key is retrieved:
`'1' key-values were retrieved from Azure App Configuration using the key filter: 'App:DB:KeyRW, App:DB:EndPoint' with label: 'QA'.`
Just only wildcard '*' works fine but this isn't practical since my AppConfig may have plenty of data that I don't need in a pipeline. Adding separate tasks for each type of key works as well, but this doesn't look practical also.
Is it a bug or it works as it was intended to work?

**Comment by drago-draganov** [comment]
At the moment wild card only works with single filter - ``App:DB:*`` should work fine.

**Comment by sslepova** [comment]
Like I wrote in the initial post, it seems comma delimiter doesn't work:
![image](https://user-images.githubusercontent.com/18029652/85833568-9cb25180-b79a-11ea-9e71-604e6bcc896f.png)
Apparently it gets only the first value from the list.

`App:DB:*` as the only condition for task works, agree. But I need to add separate tasks for each group of keys. Which isn't an optimal solution, I think.

**Comment by drago-draganov** [comment]
Please remove the space after comma in your filter.
ex. ``'App:DB:KeyRW,App:DB:EndPoint``

**Comment by sslepova** [comment]
Ok, that worked. Thank you

**Comment by drago-draganov** [comment]
Your are welcome, @sslepova 

Whitespace characters are valid in key name. The filter was basically looking for 'App:DB:KeyRW' or  ' App:DB:EndPoint'
