### ISSUE TITLE
Spring boot : Feature flags and its properties are not getting refreshed on cache expiration

### ISSUE THREAD

**Issue by pavithrakarthik** [Azure/AppConfiguration#358]
Hi,
I have configured cache-expiration to be every 1 sec (testing purpose)
**My feature flag values are not getting refreshed at all when toggled on and off on azure portal.**
I have autowired the FeatureManager by adding the dependency 
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-cloud-azure-feature-management-web</artifactId>
            <version>1.2.2</version>
**Is there any other configuration that needs to be done for the feature flags to be auto refreshed?**

If my config value changes, my application detects the change and everything works fine.:

**[ForkJoinPool.commonPool-worker-19] INFO org.springframework.boot.SpringApplication - The following profiles are active: local
[ForkJoinPool.commonPool-worker-19] INFO org.springframework.boot.SpringApplication - Started application in 5.808 seconds (JVM running for 282.325)
[ForkJoinPool.commonPool-worker-19] INFO org.springframework.cloud.endpoint.event.RefreshEventListener - Refresh keys changed: [config.message]**

**Comment by mrm9084** [comment]
Hi, @pavithrakarthik just to confirm you are using the following dependencies:

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-appconfiguration-config-web</artifactId>
    <version>1.2.2</version>
</dependency>
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-feature-management-web</artifactId>
    <version>1.2.2</version>
</dependency>
```

with a feature flag in your config store, which in your configuration explorer looks something like this.

| Key                                    | Value      |
|-----------------------------|------------|
| .appconfig.featureflag/Beta | {"id":"Beta","description":"","enabled":false,"label":null,"conditions":{"client_filters":[]}} |
| /applicaiton_local/config.message | Test Message | 


You are using the Feature manager explorer to toggle you feature flag between on and off. And when you refresh you don't see

2020-06-26 16:11:09.864  INFO 3428 --- [onPool-worker-2] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [feature-management.featureManagement]

but if you change the value of /application_local/config.message then you see

2020-06-26 16:11:09.864  INFO 3428 --- [onPool-worker-2] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [config.message]

**Comment by pavithrakarthik** [comment]
That’s correct @mrm9084

**Comment by mrm9084** [comment]
@pavithrakrthik I am having trouble replicating the issue with our standard setup. This doesn't sound like an issue with the feature management library, as that has nothing to do with refresh. If you don't include the feature library and you modify a feature flag in app configuration do you see the change? In addition, are you seeing it update ever?

i.e. if you modify the feature flag, then another configuration then do you see the feature flag change?

Also to verify you get the correct value on startup?

**Comment by pavithrakarthik** [comment]
So I am only using feature flags for my project. I have observed two things:
1. Unless I mention the key name in the property file as - spring.cloud.azure.appconfiguration.stores[0].watched-key=.appconfig.featureflag/feature-420 
My feature flag value is not getting refreshed automatically. If put * in watched key, it still doesnt recognise the changes made in azure portal.
2. Other than feature flags, if i make any change in configuration (key-value), the feature flag values get refreshed as well. But I dont need configurations for my project.
Please help me understand whats going on

**Comment by pavithrakarthik** [comment]
Basically there is an expectation of watched-key to be specified for the feature values to be auto refreshed. Is there anyway to avoid this?

**Comment by mrm9084** [comment]
@pavithrakarthik Have you tried this in a newer version of the provider? We are on release 1.2.6 right now and this seems to be similar to a fixed issue.

**Comment by pavithrakarthik** [comment]
I was using 1.2.2. Let me try this with 1.2.6 now.

**Comment by pavithrakarthik** [comment]
No luck. Even after upgrading the following:
         <artifactId>spring-cloud-azure-appconfiguration-config-web</artifactId>
            <version>1.2.6</version>
            <artifactId>spring-cloud-azure-feature-management-web</artifactId>
            <version>1.2.6</version>
I the feature flag is not getting auto refreshed.

**Comment by mrm9084** [comment]
@pavithrakarthik Thanks for the info. I will try and look into it more.

**Comment by pavithrakarthik** [comment]
Hi @mrm9084 are you able to replicate this issue?  My app config has only feature flags which when modified needs to reflect in my application by auto refresh. Unless I mention one of the feature flag key in watched-key, my values don’t reflect in my application.

**Comment by mrm9084** [comment]
@pavithrakarthik I have been unable to replicate the issue. The only configurations I have set are a spring profile and a connection string. And I see the refresh working fine. My setup is similar to the one found here https://github.com/microsoft/spring-cloud-azure/blob/master/spring-cloud-azure-samples/azure-appconfiguration-sample/pom.xml, but with the web versions of both the configuration provider and the feature management library.

**Comment by pavithrakarthik** [comment]
Hi Matt,
So this is the way it worked for me.
1. Created a feature called watchedKey and then added that in the properties : spring.cloud.azure.appconfiguration.stores[0].watched-key=.appconfig.featureflag/WatchedKey
Whenever there is any update on any of the filters in the feature flags, it gets refreshed now.
But if the watchedKey is not present, it is still not refreshing.

**Comment by mrm9084** [comment]
@pavithrakarthik That is confusing as the default watch key is "*". Is it possible for you to upload a sample?

**Comment by pavithrakarthik** [comment]
No the default watch key * is for configs. Im using only feature flags. Ideally the default watch key for feature flags (.appconfig*) should be able to detect my change and send a refresh event. It is detecting the change but the refresh event is not being sent. So Im configuring a watch key in my bootstrap.properties

**Comment by mrm9084** [comment]
When you are on version 1.2.6 do you see this log or similar when a refresh check happens?
```
2020-07-06 09:12:41.296  INFO 3696 --- [         task-3] c.a.d.a.ConfigurationAsyncClient         : Listing ConfigurationSetting revisions - SettingSelector(keyFilter=/application/*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-07-06 09:12:41.344  INFO 3696 --- [ctor-http-nio-1] c.a.d.a.ConfigurationAsyncClient         : Listed ConfigurationSetting revisions - SettingSelector(keyFilter=/application/*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-07-06 09:12:41.345  INFO 3696 --- [         task-3] c.a.d.a.ConfigurationAsyncClient         : Listing ConfigurationSetting revisions - SettingSelector(keyFilter=.appconfig*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-07-06 09:12:41.393  INFO 3696 --- [ctor-http-nio-1] c.a.d.a.ConfigurationAsyncClient         : Listed ConfigurationSetting revisions - SettingSelector(keyFilter=.appconfig*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
```

**Comment by pavithrakarthik** [comment]
Hi Matt, Yes when I used the latest version these logs appeared. But again without watch-key the updates didn't come up.

**Comment by pavithrakarthik** [comment]
Hi Matt, I tried to look up the user information from the audit events, but the event schema doesn't contain that information (on who modified the key etc.) https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-app-configuration-event
Do you know if I can get the user information by any change?

**Comment by mrm9084** [comment]
@pavithrakarthik Is it possible for your to give me a sample the replicates the issue? Feature Flags are **NOT** affected by the watch-key value.

Also, I don't think you can get the user who modified the key from an event at the moment. I would suggest making a separate issue requesting the feature if you are interested. This is what you get from app config on a modified key.

 ```json
 [ {
  "id" : "e2f7023c-b982-4050-80d9-8ed6bf24e183",
  "topic" : [you-topic],
  "subject" : "https://[your-store-name]/kv/%2Fapplication%2Fconfig.message?label=dev&api-version=1.0",
  "data" : {
    "key" : "config.message",
    "etag" : "r05tB2hfMQs0vo6ITcXu7ScIOhR"
  },
  "eventType" : "Microsoft.AppConfiguration.KeyValueModified",
  "dataVersion" : "1",
  "metadataVersion" : "1",
  "eventTime" : "2020-06-03T21:19:04.019421Z"
} ]
```

**Comment by pavithrakarthik** [comment]
Yes thanks @mrm9084. I will create an issue for this as we need the user information.

**Comment by pavithrakarthik** [comment]
@mrm9084 I will try and upload a sample for debugging soon

**Comment by pavithrakarthik** [comment]
@mrm9084 Hi Matt, Is there any dependancy on spring cloud context version? What is the version you are using? I went back to using 1.2.2 with azure

**Comment by pavithrakarthik** [comment]
> @pavithrakarthik Is it possible for your to give me a sample the replicates the issue? Feature Flags are **NOT** affected by the watch-key value.
> 
> Also, I don't think you can get the user who modified the key from an event at the moment. I would suggest making a separate issue requesting the feature if you are interested. This is what you get from app config on a modified key.
> 
> ```json
> [ {
>  "id" : "e2f7023c-b982-4050-80d9-8ed6bf24e183",
>  "topic" : [your-topic],
>  "subject" : "https://[your-store-name]/kv/%2Fapplication%2Fconfig.message?label=dev&api-version=1.0",
>  "data" : {
>    "key" : "config.message",
>    "etag" : "r05tB2hfMQs0vo6ITcXu7ScIOhR"
>  },
>  "eventType" : "Microsoft.AppConfiguration.KeyValueModified",
>  "dataVersion" : "1",
>  "metadataVersion" : "1",
>  "eventTime" : "2020-06-03T21:19:04.019421Z"
> } ]
> ```

Hi @mrm9084 Could you please share me the link to raise a request for the feature?

**Comment by mrm9084** [comment]
@pavithrakarthik the spring-cloud-azure-appconfiguration-config package has a dependency on spring cloud context. We currently release 2 different versions of the package one for Spring Cloud Greenwich an another for Spring Cloud Hoxton. They use versions 2.1.0.RELEASE and 2.2.0.RELEASE. respectively.

For a feature request you can just make a new issue on this repo and I can mark it as an enhancement.

**Comment by pavithrakarthik** [comment]
Thanks @mrm9084

**Comment by pavithrakarthik** [comment]
@mrm9084 Hi Matt, For the TimeWindowFilter , the example (https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core) says to add parameter as "start" or "end" but in the code it looks for "time-window-filter-setting-start" and "time-window-filter-setting-end". if i give "start" and "end" it doesn't work.

**Comment by mrm9084** [comment]
@pavithrakarthik , yes there is currently a miss match between the two. I created a issue in the spring-cloud-azure repo to track this. We plan to get this fixed in the next release.

The only work around at the moment would for you to create your own time window filter with the start and end paramaters.

**Comment by pavithrakarthik** [comment]
@mrm9084 thank you. It would be great if you could let me know in which release this got fixed.

**Comment by zhenlan** [comment]
@mrm9084 any suggestions?

**Comment by mrm9084** [comment]
@pavithrakarthik, Because of how feature flags are stored they are unable to come from multiple stores at this point in time. I can create a new issue to track the feature request.

**Comment by mrm9084** [comment]
@pavithrakarthik The feature flag naming issue should be fixed in the latest version. I am closing this issue. We can track the multiple stores in the new issue and if the feature flag naming issue is still a problem we should create a new issue as it is different than the original one documented here.
