### ISSUE TITLE
Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration - CustomConfigBuilder - Refresh option

### ISSUE THREAD

**Issue by chvijaybabu** [Azure/AppConfiguration#359]
Provide an option to configure refresh for CustomConfigBuilder that works with ConfigurationManager.

**Comment by abhilasharora** [comment]
@chvijaybabu Thanks for the feature request. We will evaluate it on our end. We do currently support refresh using Azure App Configuration provider You can find more details about it [here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet).

**Comment by zhenlan** [comment]
@chvijaybabu the `ConfigurationManager` in .NET Framework does not support configuration refresh. Once the configuration is loaded, it cannot be changed until the application is restarted next time. This is by design.

cc: @StephenMolloy
