### ISSUE TITLE
how to make consistent for all service instance when retrieving app configuration with refresh interval 10mins

### ISSUE THREAD

**Issue by brucezlata** [Azure/AppConfiguration#362]
I set SetCacheExpiration to 10mins for each service instances. And add middleware in .net core web app. So, each http request will sync app settings if cache is expired. 

but it is possible instances will get different app config values.

Any suggestion or best practice to solve it? Minimal refresh interval might solve the problem, but not a good solution.

**Comment by abhilasharora** [comment]
@brucezlata I understand you'd like multiple instances of your application to have the same configuration at any point of time. Could you share how the configuration updates are used in your application? What is the impact if once instance serves a request with new settings and the next instance serves the subsequent request with old settings?

**Comment by brucezlata** [comment]
I want to enhance feature management based on app configuration with different rollout policies.
If the feature settings are different in different instances, customer might got different user experience.

It has the possible to get different value from app configuration because instance sync has time interval.

BTW, how about the HA of app configuration? Can I have thousands of instances connect to it and refresh setting is 1mins?

**Comment by brucezlata** [comment]
Use event grid?
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-app-configuration-event

**Comment by zhenlan** [comment]
@brucezlata please see the document below for HA/DR
https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery?tabs=core2x

Please note there is a limit of the number requests an App Configuration store will accept. Please plan accordingly.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/faq#are-there-any-limits-on-the-number-of-requests-made-to-app-configuration

Using the event grid for push notification of changes can help to increase the response time of your application to feature flag changes, but please keep in mind different instances may still have different values even though the gap is smaller. I would recommend you consider implement special logic in your application so your user gets a consistent experience regardless of which instance their request hits.

**Comment by brucezlata** [comment]
Thanks, @zhenlan.
I will still get 429 even it is Standard tier and we have enough budget for request.
Based on SLA, it will be 429 if it is over 20,000 requests/hour????

**Comment by zhenlan** [comment]
@brucezlata, like many other services, a throttling limit is in place to ensure the reliability of the service to all customers.

**Comment by brucezlata** [comment]
Thanks, @zhenlan
