### ISSUE TITLE
Question: Azure Cli Import\Export Key Vault Values

### ISSUE THREAD

**Issue by bradshaw84nz** [Azure/AppConfiguration#363]
Hi, 

Question around being able to import values with a key vault reference, is this possible? 

If I export from one App Configuration into a Json File and the import into another via the Portal\Cli they KV reference is lost. 
Is this currently possible? 

or for each key vault value I need to call

`az appconfig kv set-keyvault`

for each value that has a key vault reference?

**Comment by shenmuxiaosen** [comment]
Hi bradshaw84nz, it is possible to import key vault references from file. However, it can't be one shot import for normal configurations along with key vault references. When exporting items, separate key vault references with other configurations using either label or namespace(key prefix). Basically maintain configuration and key vault references in two files. 

Export everything but key vault references:
``` az appconfig kv export -n myAppConfiguration --key * -d file --format json --path exportConfig.json  --skip-keyvault```
Export key vault references only: (assuming the key of all key vault reference starting with "secrets")
``` az appconfig kv export -n myAppConfiguration --key secrets* -d file --format json --path exportSecret.json```

Import key vault references from file:
```az appconfig kv import -n myAppConfiguration -s file --format json --path exportSecret.json --content-type "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8" ```

**Comment by bradshaw84nz** [comment]
Thanks for the reply that helps a lot.
