### ISSUE TITLE
'No Versions Found' After Selecting the Key Vault Secret When Adding Key Vault Reference using the Configuration Explorer in the Azure Portal

### ISSUE THREAD

**Issue by kasunkv** [Azure/AppConfiguration#364]
I tried to create a new Key Vault Reference in one of my Azure App Configuration instances in the portal. I was able to select the Key Vault instance in my resource group and select the Secrets included in the key vault. After selecting the secret i need, i wanted to add a reference to the latest version of the secret and I was not able to select the latest version or any available version. It just shows 'No Versions Found' in the drop down. I can confirm that there are multiple versions available under that Secret in the Key Vault.

![image](https://user-images.githubusercontent.com/4517739/86764047-6495f300-c065-11ea-9440-01ef7fb22343.png)

I have multiple environments for this application, when i try to create a Key Vault Reference for a different environment, with the same Secret Key (Different key vault instance) it works fine. So i am assuming it can not be something related to the Secret key length. 

What could be the reasons that the key vault secret versions are not loaded properly and between different key vault instances the behavior is inconsistent?

**Comment by jiayi11** [comment]
Hi @kasunkv , just want to confirm with you, when you try to create a new key vault reference, you can see all other key vault's secret versions correctly except this particular key vault. Is that correct? Is it possible that your secret is not enabled? Could you also check if you have "GET" secret permission for your key vault in your key vault's access policies?

**Comment by kasunkv** [comment]
Hi,

I have the added the access policy to enable me to manage secrets. And all secrets are enabled. There were multiple secrets that showed the same behavior. And it's random, meaning the same secret that gave me issues is not giving me the issue in a different key vault and app configuration instance.

**Comment by jiayi11** [comment]
@kasunkv  Could you please open "developer tools" of your browser and see after you choose your secret name, are there any console errors showing up or failed requests in Network tab? 
![image](https://user-images.githubusercontent.com/14067510/87093538-3265cc00-c1f2-11ea-9e28-dc6368381f2c.png)

**Comment by kasunkv** [comment]
@jiayi11 Sorry for the delay in responding. Yes the Versions API call is successful and it show a JSON response with a list of secret version ids and a link to the next set of data. But there is a console error visible in the console tab. the following is the content of the error.

`7FuTBelZ6iNJ.js:10 [Microsoft_Azure_AzConfig]  10:25:20 AM Resource/KeyVaultReferenceBlade 0 KeyVaultReferenceBlade: Failed to fetch resource, reason: message: Cannot read property 'nextLink' of undefined
stack: TypeError: Cannot read property 'nextLink' of undefined
    at https://afd.hosting.portal.azure.net/azconfig/Content/Dynamic/pBDeAqq5WXAB.js:5:7196
    at o (https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:72)
    at https://portal.azure.com/Content/Dynamic/P8kXagqyUZue.js:4:5424
 /subscriptions/8fexxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx9b2a/resourceGroups/intxxxxxxxxxxxxdev/providers/Microsoft.AppConfiguration/configurationStores/intxxxxxxxxxxxxdevappconfig
r @ 7FuTBelZ6iNJ.js:10
v @ 7FuTBelZ6iNJ.js:10
d @ 7FuTBelZ6iNJ.js:10
t.error @ 7FuTBelZ6iNJ.js:10
(anonymous) @ pBDeAqq5WXAB.js:5
o @ P8kXagqyUZue.js:4
(anonymous) @ P8kXagqyUZue.js:4
Promise.then (async)
i.then @ P8kXagqyUZue.js:4
i.catch @ P8kXagqyUZue.js:4
(anonymous) @ pBDeAqq5WXAB.js:5
h @ P8kXagqyUZue.js:40
f.<computed> @ 7FuTBelZ6iNJ.js:28
evaluateImmediate_CallReadThenEndDependencyDetection @ P8kXagqyUZue.js:52
evaluateImmediate_CallReadWithDependencyDetection @ P8kXagqyUZue.js:52
evaluateImmediate @ P8kXagqyUZue.js:52
evaluatePossiblyAsync @ P8kXagqyUZue.js:52
notifySubscribers @ P8kXagqyUZue.js:52
tr.notifySubscribers @ 7FuTBelZ6iNJ.js:36
valueHasMutated @ P8kXagqyUZue.js:52
i @ P8kXagqyUZue.js:52
t.setValue @ O40zSL9j9HKP.js:25
(anonymous) @ O40zSL9j9HKP.js:25
notifySubscribers @ P8kXagqyUZue.js:52
tr.notifySubscribers @ 7FuTBelZ6iNJ.js:36
valueHasMutated @ P8kXagqyUZue.js:52
i @ P8kXagqyUZue.js:52
uu @ 7FuTBelZ6iNJ.js:36
we @ 7FuTBelZ6iNJ.js:36
n.applyChange @ 7FuTBelZ6iNJ.js:36
(anonymous) @ 7FuTBelZ6iNJ.js:38
(anonymous) @ 7FuTBelZ6iNJ.js:33
(anonymous) @ 7FuTBelZ6iNJ.js:38
n.handleMessage @ 7FuTBelZ6iNJ.js:38
n.handleEventMessage @ 7FuTBelZ6iNJ.js:38
(anonymous) @ 7FuTBelZ6iNJ.js:38
n.handleMessage @ 7FuTBelZ6iNJ.js:38
_handleMessage @ 7FuTBelZ6iNJ.js:38
p @ 7FuTBelZ6iNJ.js:38
(anonymous) @ 7FuTBelZ6iNJ.js:38
n._processInnerList @ 7FuTBelZ6iNJ.js:38
n._processOuterList @ 7FuTBelZ6iNJ.js:38
n.addItem @ 7FuTBelZ6iNJ.js:38
_handleMessage @ 7FuTBelZ6iNJ.js:38
Show 13 more frames from Library code
`

**Comment by jiayi11** [comment]
@kasunkv Thank you for helping us find the root cause! I'm working on the fix and it should be available in our next deployment.

**Comment by kasunkv** [comment]
@jiayi11 No problem, Thanks for getting to fix the issue quickly. Can you give me a timeline on when this will be release to the Azure Portal?

**Comment by jiayi11** [comment]
@kasunkv Should be sometime next week, I'll update you once I have the date.

**Comment by jiayi11** [comment]
Hi @kasunkv, just want to give you an update that there's a deployment lock down this week, so we cannot start our deployment today as planned😞 The lock down will be lifted next Monday so hopefully this fix will be out to production mid next week.

**Comment by jiayi11** [comment]
The fix is already deployed.
