### ISSUE TITLE
Why do I need credentials for connecting to Azure app Config if I'm using a connection string

### ISSUE THREAD

**Issue by gdodd1977** [Azure/AppConfiguration#365]
I've implemented App Config in my app passing in the conn string like so:

` builder.AddAzureAppConfiguration(options =>
                    {
                        options
                            .Connect(settings["ConnectionStrings:AppConfig"])`

When I deploy out to azure, it doesn't pull back the app config values. I assume it's because my app is not in an assigned role for the App Config. I'm assuming this because running locally, pointing at the same app config resource, I get values back because I'm running as myself who IS assigned in the role assignments. Just seems odd to need to have role assignment for my app if I have a conn string. Seems like it would either be credentials OR conn string.

**Comment by zhenlan** [comment]
@gdodd1977 the code snippet is using connection string to connect to App Configuration, so it has nothing to do with AAD or role assignment.

Which Azure service you are deploying your app to? Have you set the `ConnectionStrings:AppConfig` in that environment?

**Comment by gdodd1977** [comment]
I understand that it is for connecting to app config. My point in showing it was that I don't understand why I'd also need to have a role assignment for my deployed app in App config resource if I'm using a conn string. Just like when connecting to cosmos. You use a conn string with cosmos as opposed to credentials. I would think it's an either/or proposition with app config as well.

The ConnectionStrings:AppConfig is in our keyvault. When running locally and when deployed to dev resource group, the app hits the same keyvault and same app configuration resource. Yet it works running locally. Hence my thought that it has to do with role assignment since the user context of running locally has a role assignment in the App Config resource. I'm just asking why I would need that if I'm using a connection string to connect to the App Config resource.

**Comment by zhenlan** [comment]
> I don't understand why I'd also need to have a role assignment for my deployed app in App config resource if I'm using a conn string.

You don't need a role assignment in App Configuration if you are using a connection string.

If your connection string is saved in Key Vault and both your local app and deployed app access the connection string from the same Key Vault, you need to grant permission of your app (local and deployed) to the **Key Vault**, not App Configuration.

**Comment by gdodd1977** [comment]
My deployed app already has permissions to the keyvault. We use that kv for multiple things in this app. If you don't need app permissions with a conn string, there must be some other issue. But that's (permissions to App Config resource) literally the only difference btw local env and deployed env for this particular app.

**Comment by gdodd1977** [comment]
So it looks like another dev had ServicePrincipal issues on the deployed app. This is working as expected now.

**Comment by zhenlan** [comment]
Glad it worked for you.
