### ISSUE TITLE
Track the user information who changes a key-value

### ISSUE THREAD

**Issue by pavithrakarthik** [Azure/AppConfiguration#366]
Hi, I tried to look up the user information from the audit events, but the event schema doesn't contain that information (on who modified the key etc.) https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-app-configuration-event
Can I obtain the information about the user who modified the key?

**Comment by zhenlan** [comment]
@pavithrakarthik Every change in App Configuration must be authenticated (either HMAC or AAD). However, App Configuration does not track/log who made the change today. Depending on customer demands, this is something for future consideration.

**Comment by duanekord** [comment]
This is needed for SOX applications.

**Comment by Philippe85** [comment]
Yes, we need to follow who changed key-values for audit, if we have an incident in Production.

**Comment by zhenlan** [comment]
We are working on this now. We will make auditing logs available to users. The logs will include the user object id if the user is authenticated using AAD when making changes.

**Comment by VamKon** [comment]
Great to see that you are working on this @zhenlan. Will the logs include a way to tie the log back to a key-value pair via an e-tag or something? When will this be ready for customers to use?

**Comment by zhenlan** [comment]
It's available now. As part of the 'RequestURI' in the log, you can tell which key is related.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/monitor-app-configuration?tabs=portal

**Comment by zhenlan** [comment]
The auditing logs with user information are also available. Follow the doc below to enable auditing logs.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/monitor-app-configuration

Note that, the user identity information is only available when the change request is authenticated with Azure AD (AAD). You can enforce AAD authentication of an App Configuration store by disabling Access keys (under your App Configuration store in Azure portal, go to *Access keys*, and then toggle off *Enable access keys* under *Authentication type* at the bottom of the page).

**Comment by margasat** [comment]
Hi , Can you please let me know where can I find the object Id of the user in logs?

**Comment by zhenlan** [comment]
@margasat please see the reference for audit logs
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/aacaudit

**Comment by spatelGDOT** [comment]
When I look at events in the Activity Log it says: "Change History is not applicable to this type of activity log"

How can I see the audit of the change that was made to the store?  Like UserA changed this specific KV from valueA to valueB.

**Comment by zhenlan** [comment]
@spatelGDOT you can follow the instructions to enable the audit log (not activity log)
https://learn.microsoft.com/en-us/azure/azure-app-configuration/monitor-app-configuration

**Comment by avanigupta** [comment]
@ssundsha-medline , value is not included in the logs since it's considered sensitive information. 
However, you can look at the history of any key-value to see the various revisions of that key-value: https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-point-time-snapshot?tabs=azure-portal#historicaltimeline-view-of-key-value
