### ISSUE TITLE
Alternative to Azure App Configuration Sync in Azure DevOps

### ISSUE THREAD

**Issue by manvkaur** [Azure/AppConfiguration#368]
In Github actions, I have the option to sync my settings using [Azure App Configuration Sync](https://github.com/marketplace/actions/azure-app-configuration-sync).
But I have my repositories hosted in Azure DevOps, any alternative to achieve the same thing from Azure DevOps or ways to automate upload of settings to Azure App Configuration using pipelines

**Comment by abhilasharora** [comment]
@manvkaur You can use Azure CLI in your pipeline task to import JSON or YAML configuration files to App Configuration. Please check out `az appconfig kv import -h` ([Link](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-import)).

**Comment by manvkaur** [comment]
@abhilasharora ,Two things:
I am using a json file to import settings
1. How can I specify the content type for key vault references?
2. In Feature Management section of feature flags, how can specify description? I looked at this [example](https://github.com/microsoft/FeatureManagement-Dotnet/blob/master/examples/FeatureFlagDemo/appsettings.json) but couldnt find this particular property.

1.

**Comment by zhenlan** [comment]
@manvkaur back to what you were asking originally, we are working in progress a new DevOps pipeline task that can upload settings from files to App Configuration. I hope to have a release in a week or two. Stay tuned.

**Comment by Matthew-Solomon** [comment]
@manvkaur we have just released our DevOps pipeline task to upload settings from files to App Configuration! You can check this task out here: https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push
