### ISSUE TITLE
Prerequest script uses a method has a bug for using a disabled parameter, pm.request.url.getPathWithQuery()

### ISSUE THREAD

**Issue by nvwolf418** [Azure/AppConfiguration#370]
**Summary:**
It appears to be on postman's issues page, but they switched it off a bug.:
https://github.com/postmanlabs/postman-app-support/issues/7945

This is the script i'm referring to is the prerequest script mainly used for authentication:
https://github.com/Azure/AppConfiguration/blob/master/docs/Development/postman.md

It appears the line in the above script:
 pm.request.url.getPathWithQuery()

 
This line Includes disabled parameters for some reason, looks like they switched off bug for postman. It feels to me it is one though. I'll probs make an issue their just so it is visible for this script!

Steps to reproduce->
1) Make any request to a site with some parameters added
2) Disable one of the parameters
3) Run and include the below script and look at the console.
4) You should see the included disabled parameter under the url output in the console. This is definitely a bug with postman, but if they don't fix it. I'm afraid a user of the above script for the REST api may run into this.

I have a small prerequest test script:
function signRequest(host, 
                     method,      // GET, PUT, POST, DELETE
                     url,         // path+query
                     body         // message body
                     )     
{
    console.log("host :" + host);
    console.log("method :" + method);
    console.log("url :" + url);
    console.log("body :" + body);
}

var isBodyEmpty = pm.request.body === null || pm.request.body === undefined || pm.request.body.isEmpty();

var values = signRequest(
    pm.request.url.getHost(),
    pm.request.method,
    pm.request.url.getPathWithQuery(),
    isBodyEmpty ? undefined : pm.request.body.toString()
    );

**Comment by et13** [comment]
Thanks for the report - I am able to reproduce the behavior and am investigating alternatives given the known postman issue that you mentioned.

**Comment by zhenlan** [comment]
@et13 do we have any updates for this issue?

**Comment by zhenlan** [comment]
@et13 can this be closed?

**Comment by et13** [comment]
This scenario is now working is recent v8/v9 versions of postman - I tested with 8.11.1 and 9.0.5. `pm.request.url.getPathWithQuery()` no longer includes the disabled parameters

**Comment by nvwolf418** [comment]
Yes, looks all good, thanks again!
