### ISSUE TITLE
Azure DevOps Extension: Azure AppConfiguration - Partial Complete

### ISSUE THREAD

**Issue by jkrusic19** [Azure/AppConfiguration#372]
Hello,

I would like to submit a feature request for the Azure DevOps extension "Azure AppConfiguration". When finding "keys that already exist, and we are going to overwrite" can we have the ability to suppress that warning so our pipelines look all "Green"? 

Expected behavior:
- With this specific step, this is expected behavior and do not see it as an issue.

**Comment by zhenlan** [comment]
@Yiming-Jia, not sure if there is a standard way in ADO to suppress warnings.

**Comment by Yiming-Jia** [comment]
Hello @jkrusic19 ,

Yes, that should be a feature request to the Azure DevOps Pipeline. We use the pipeline task SDK to dump the message with warning log level and mark the task success with issues as the existing key-values overwritten, which is the way the task to notify user. And from Azure DevOps pipeline [document](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml), I saw it support the `conditions` which could let the follow task to continue to ran or canceled based on previous tasks' results.

**Comment by mieel** [comment]
imo this a bug and not a feature.

**Comment by jimmyca15** [comment]
@jkrusic19 I'd like to clarify the original ask a little. We do two things currently when we encounter overwritten keys. We write a warning _and_ we set the pipeline's final state to "succeeded with issues" instead of "succeeded".

Is your request for us only to set the final state to "succeeded" rather than "succeeded with issues" or is it to omit the warning messages as well?

**Comment by TheHodge1234** [comment]
For my 2 cents it should set the final state to “succeeded” and the warning messages should be retained (like in my screenshot from the official Terraform extension)

**Comment by jimmyca15** [comment]
Okay, that's what I'm leaning toward and want to make sure we are all on the same page.

**Comment by jkrusic19** [comment]
Hello,

Yes success with warnings in the log output.

**Comment by crsbrns** [comment]
Came here to make the same case, +1 for success with warnings in the log output

**Comment by Anne56njeri** [comment]
A new release is out for the Azure App configuration -version 3.2.15, this issue has been addressed in the new release, the final state is set to "succeeded" and the warning messages are retained. In case you experience any issues please reach out. :)

**Comment by TheHodge1234** [comment]
I have tested and it works like a charm - thanks!
