### ISSUE TITLE
AppSettings not being overwritten when using strongly typed, named configurations.

### ISSUE THREAD

**Issue by keggster101020** [Azure/AppConfiguration#379]
Hi,

I'm using Azure App Configuration to attempt to override partial configuration keys. However, I'm noticing that this isn't working when using strongly typed configurations.

Below is a stripped down example of what my code is trying to do:

## Loading Azure App Config
```csharp
WebHost.CreateDefaultBuilder()
.ConfigureAppConfiguration((_, config) =>
			{
                                var settings = config.Build();
				config.AddAzureAppConfiguration(options =>
				{
					options.Connect(settings["AzAppConfigConnectionSecret"])
						    .UseFeatureFlags();
				});
			});

```
## Create Strongly Typed Settings Object

```csharp
public class TypedSetting<T>
{
    public IList<T> Keys {get;} // T is convertable to type string via implicit operator override
}
```

## Set setting in Azure App Configuration
I've tried to do this multiple ways. 
|key|Value|
|---|------|
|Test:Keys| ["key"]
|Test|{"Keys":["key"]}
|Test:Keys:0| "key"|

## Startup configuration
```csharp
...
//omit other registrations
services.AddOptions<TypedSettings<ConvertableType>>("Test")
    .Bind(Configuration.GetSection("Test"))
    .Configure(options => options.Keys.count ); //always 0

Configuration["Test:Keys"]; // returns "[\"key\"]"
Configuration.GetSection("Test").GetValue<List<ConvertableType>>("Keys"); // returns null;
```

## Register Middleware
```csharp
IApplicationBuilder.UseAzureAppConfiguration();
```

This should work since setting the following in appsettings.json works
```json
{
    "Test":{
        "Keys":["key"]
    }
}
```

## Service Info
- Microsoft.AspNetCore v2.2.0
- Microsoft.Azure.AppConfiguration.AspNetCore v3.0.1

**Comment by keggster101020** [comment]
I ended up doing a full reset of the solution and re-running the application the value propagated as expected. Might have been a transient issue.

It is worth noting that the only key selector I was able to get working was `Test:Keys:0`

**Comment by abhilasharora** [comment]
@keggster101020 Thanks for the update. The selectors other than `Test:Keys:0` do not work since the value in App Configuration is treated as string literals `["key"]` and `{"Keys":["key"]}`, instead of an array or object.
