### ISSUE TITLE
Don't throw an exception if a filter is not found

### ISSUE THREAD

**Issue by mdarefull** [Azure/AppConfiguration#381]
I'm using `"Microsoft.FeatureManagement.AspNetCore" Version="2.0.0"` nuget package. The issue can be reproduced by simply setting the configurations in the appSettings.json file, for example:
```
"FeatureManagement": {
    "OneFeature": {
      "EnabledFor": [
        {
          "Name": "MyCusstomFeature"
        }
      ]
    }
  }
```
The filter "Name" is a "hard-coded" string and, as such, there's chance for misspelling. Causing a runtime exception when the application tries to check the feature with the error (`OneFeature`):
![image](https://user-images.githubusercontent.com/22510674/88730412-630f9600-d10c-11ea-9066-30cccb895c82.png)

The main goal of a feature flag strategy is to be able to control the features we show to our real users in a production environment, hide unfinished features, perform experimentation, etc. 
The way we specify filters is **very** error prone undermining the whole goal of feature flags if a business member could mistakenly add an additional **s** to the filter name and crash the whole site.

This scenario is even more probable when managing the features through the Azure App Configuration, where I could miss type the filter name, the parameters name or even the values.

**Expected Behavior**
If the filter is not found, the behavior should be the same as when the feature is not found. We should return false and mark the feature as disabled.

In general, if any exception is thrown while evaluating the feature, the feature should be marked as disabled and appropriate logs should be generated, so the team can detect and fix the error.

**Actual Behavior**
If the filter is not found, an exception is thrown and the application crashes.

**Comment by zhenlan** [comment]
@mdarefull you can use `IgnoreMissingFeatureFilters` property to change the default behavior.

https://github.com/Microsoft/FeatureManagement-dotnet#missing-feature-filters

**Comment by mdarefull** [comment]
@zhenlan: My deepest apologies, I did my research on https://docs.microsoft.com/en-us/azure/azure-app-configuration/ and I couldn't find any reference for it...

Is there a reason why the options cannot be configured when registering the feature management services similar to how we configure most of ASP.NET Core services? as in:
![image](https://user-images.githubusercontent.com/22510674/88795596-ab639e00-d176-11ea-9b1b-e476ea075bd6.png)

Other than that, this is exactly what I was looking for! It even logs a warning 💯

**Comment by zhenlan** [comment]
> Is there a reason why the options cannot be configured when registering the feature management services similar to how we configure most of ASP.NET Core services? as in:
> ![image](https://user-images.githubusercontent.com/22510674/88795596-ab639e00-d176-11ea-9b1b-e476ea075bd6.png)

I guess we could. @jimmyca15, are you aware of any reasons?

**Comment by jimmyca15** [comment]
@zhenlan we should be able to do that. It's not a breaking change and it's pretty simple so should be able to get it in by next release.
