### ISSUE TITLE
Log a Message if a feature is not found

### ISSUE THREAD

**Issue by mdarefull** [Azure/AppConfiguration#382]
I'm using "Microsoft.FeatureManagement.AspNetCore" Version="2.0.0" nuget package.

One of the main statements for a good feature flags management, is that we should keep the features count low and for a short amount of time. 
We use enums to centrally declare and reference our features in code, that way we cannot misspell a feature and if we remove an enum value, the application won't build allowing us to easily spot all the places where it is used.

The place where the features are manages (appSettings.json file, Azure App Config, etc.) cannot adopt this pattern, so we need to ensure the names we use here, are the same as the enum names... and that if we decide to remove a feature, we remove it from both places in a correct way.

If a feature is misspelled when configured, or removed from configuration, every reference to the feature in code silently fails marking the feature as disabled. The service should log a warning stating that the feature could not be found, that way the developers would be able to identify misspelled or unused features in production and be able to remove them from code appropriately.

**Comment by zhenlan** [comment]
@mdarefull This PR (https://github.com/microsoft/FeatureManagement-Dotnet/pull/78) is still working in progress, but the new property `IgnoreMissingFeatures` it introduces should serve your need.

**Comment by mdarefull** [comment]
@zhenlan if that option is set to true, would it throw an exception crashing the application if a feature is missing? 

The behavior I think would benefit most real applications is to not throw an exception for missing feature but to log the event somehow.
Most of the time flags are managed by static/hard-coded configuration and some of the time not even by developers but by business people. 
There's a very high probability (and risk) for a feature to be miss-spelled or miss-configured directly in a production environment. I wouldn't like that to cause an exception but I wouldn't like that to pass inadvertently either.

**Comment by zhenlan** [comment]
The `IgnoreMissingFeatures` will be `true` by default, so it will _not_ throw an exception for the exact reason you said, but you can set it to `false` to force an exception.

**Comment by mdarefull** [comment]
I agree, I would just remark that it should behave as the IgnoreMissingFeatureFilters behaves today, when they log a warning when a filter hasn't been found.

In the current implementation, if a feature is not found, no message is logged.

**Comment by zhenlan** [comment]
Good point about logging a warning. I just added a [comment in the PR](https://github.com/microsoft/FeatureManagement-Dotnet/pull/78/files#r463163835) for it.
