### ISSUE TITLE
Unable to import all keys in a properties file

### ISSUE THREAD

**Issue by Tankatronic** [Azure/AppConfiguration#386]
I am trying to figure out the expected format when uploading a bulk list of key\values to app configuration. I created a handful of keys and exported them in the properties file format, and then deleted those keys. Then, I uploaded the same file that was exported but only 2 of the 6 keys were added and the values were incorrect.

Here are the key\values I had created in app configuration and how they were exported.

```
AC30:BatchSize=1000
AC30:BlobConnectionString=someconnectionstring
AC30:Container=ac30-files
AdminPortal:PaymentCardAdmin:AuthPassword=somepassword
AdminPortal:PaymentCardAdmin:AuthUser=nvp-pmtcardadminsvcauth
AdminPortal:QueryMaxNumberOfDays=60
```

when I imported the file in the above format, it only imported two keys below:
![image](https://user-images.githubusercontent.com/4115700/89450080-d5850500-d70e-11ea-8981-b8ec967945f7.png)

I am aware that things like passwords\connection strings are considered secret and should live in key vault.. that is my plan, but I am just trying to figure out how I can bulk load all of our existing settings into app config.

Thanks

**Comment by zhenlan** [comment]
We assume `.` as the separator in key names for properties file. The example is using `:`. 

@Tankatronic, would it work if you change the separator to `.`, for example, `AC30.BatchSize=1000`?

**Comment by Tankatronic** [comment]
That did work, but the UI does provide an option to select a separator and it defaults to ':'. I would prefer if we could use that as a separator. Is this something that can be supported?

![image](https://user-images.githubusercontent.com/4115700/89466800-5650fa80-d729-11ea-8a09-701a9b8f0231.png)

**Comment by zhenlan** [comment]
@Tankatronic I am glad it worked for you.

Sorry for the confusion. That's a UI bug. We actually have a tracking work item to remove the selection of separator (or only allow `.`) when the input is a properties file because the spec of properties files only supports `.` as the separator.

**Comment by Tankatronic** [comment]
Thank you. This is outside the scope of this issue, but do you know of a way that I can easily convert the data in this properties file into a format that would support ':' as a separator? I've seen what the export looks like in JSON format, where it groups the keys based on their hierarchy, but getting my large flat list of properties into that format seems challenging in and of itself. If that's the only option, we can probably figure out some sort of script to make it happen, but I wanted to be sure I am not missing a more obvious solution.

**Comment by zhenlan** [comment]
Depending on how complex your files are, most editor apps such as Windows Notepad that has batch replace function may just do the trick. If your files are more complex than simple colon-to-dot replacement, then yes, you may need some script.

**Comment by zhenlan** [comment]
@jiayi11 is this done? [This](https://github.com/Azure/AppConfiguration/issues/386#issuecomment-669631097) should be a simple fix.

**Comment by jiayi11** [comment]
This is fixed, we currently only allow '.' separator for properties files. 
Closing the issue.
