### ISSUE TITLE
"overwrite" option with az appconfig kv import

### ISSUE THREAD

**Issue by sureleo** [Azure/AppConfiguration#389]
Hello, 

Is there a way to completely overwrite key-values in App Configuration with "az appconfig kv import"? I could not find it in the documentation.

For instance, I have two key values in App Configuration:
```json
{
    "key1": "value1",
    "key2": "value2"
}
```

If I run ```az appconfig kv import --overwrite``` with json file ```{ "key1": "value3" }```, ```key2``` will be removed and ```key1``` value will be updated to ```value3```.

**Comment by abhilasharora** [comment]
One way to accomplish it is to use `az appconfig kv delete --key *` to delete all key-values before running the import command.

**Comment by zhenlan** [comment]
@sureleo are you looking for something similar to the **strict mode** in [App Config GitHub Action](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-github-action#use-strict-sync)?  If you don't use the GitHub action, what @abhilasharora suggested should give you what you need. Note that you don't have to delete everything in the store. You can use label and prefix filters to limit what to delete when you run `az appconfig kv delete`.

**Comment by sureleo** [comment]
We don't use github action.

We are using Shell extension in Express V2 pipeline to run script that contains "az appconfig kv import". The config file is version controlled in Azure Dev Ops. Once there is a change in the config file, we'll trigger EV2 pipeline to run  az appconfig kv import and propagate the config files two 20+ regions.

The problem is that... it does not seem there is a way to remove a feature via the above mechanism. I need to come up with something that can calculate the diff of the file. I believe using delete --key * sounds a little bit risky if import failed.

I would still prefer if there is a "overwrite" option if possible.

**Comment by sureleo** [comment]
Actually, I think of a workaround for me though... @zhenlan please close this if needed.

Solution:
In each import, remove all key values except Sentinel, and import all the values.
In code, only listen to the change on Sentinel. 

Nevertheless, it would still be great that "overwrite" can be done. Thanks!

**Comment by zhenlan** [comment]
We do have an extension for Azure Pipelines, which supports "strict mode" too, but it may not work for you as you are using Ev2.
https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push

What you planned sounds right. That's how it would have been implemented if the "overwrite/strict mode" were supported.
