### ISSUE TITLE
Azure App Configuration Extensions does not support feature flags

### ISSUE THREAD

**Issue by stotlyakov** [Azure/AppConfiguration#391]
I understand that for Core applications we should be using  Microsoft.FeatureManagement NuGet. What, about none Core Applications. You wrote nice Extensions and also Azure.Data.AppConfiguration.ConfigurationClient libraries that work regardles of Core or .Net Framework. However, none of those two can work with feature flags. Is there a plan to add support for it to any of those Standard NuGet packages?

**Comment by zhenlan** [comment]
Hi @stotlyakov, the `Microsoft.FeatureManagement` is a .NET Standard library. It can be used in .NET Framework applications too. You may like to check out this quickstart.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-dotnet

**Comment by stotlyakov** [comment]
Ahah, there it is :). 
Thanks, You guys are great.
