### ISSUE TITLE
Missing Blazor WebAssembly and Azure App Configuration Docs

### ISSUE THREAD

**Issue by jongio** [Azure/AppConfiguration#394]
I attempted to get Azure App Configuration working in a Blazor WebAssembly app and could not.  Here are my recommendations.

Scenario: I have a .NET app with Blazor Wasm front-end and ASP.NET Core API.  I want to have a feature flag to conditionally show a delete button for items.

## Docs
- We do not have Blazor and App Configuration docs, so the end user does not know by docs if the Blazor Wasm/AppConfig combination will work.
- I spent a few hours trying to get the App Config extension to work in Blazor, but ultimately gave up because of the ManagedIdentity issue mentioned below. 
- The tree nav in ref docs is hard to visually parse.  So many namespaces to cipher through.
- Blazor wasm and the AppConfig Extension
  - Looks like the extension is built on TagHelpers, Blazor wasm doesn’t support TagHelpers.  I only found that out because I know someone on the .NET team and he told me.  A general Blazor and AppConfig doc should include this.
  - If I google “azure app configuration blazor webassembly”, I only get info about using Blazor’s configuration via appSettings.  Adding docs and SEO should solve this.
  - Here’s a good blog on Blazor and Azure App Config, but that is for “hosted” not wasm https://www.mcbeev.com/Blog/July-2020/Add-Azure-App-Configuration-and-Feature-Flags-into-Blazor and it uses Connection string, not Managed Identity.  Here’s another for server-side https://devblogs.microsoft.com/aspnet/configuring-a-server-side-blazor-app-with-azure-app-configuration/
## Managed Identity
- My entire app uses Managed Identity (except Cosmos), and I want to do the same with AppConfig.  If I’m using AppConfig in Blazor, I’m unable to use ManagedIdentityCredential and there’s no clear guidance on how to use Azure.Identity from the browser.  I wasn't able to find any docs related to Azure.Identity and browser support.

azsdke2e

**Comment by jongio** [comment]
@bradygaster

**Comment by zhenlan** [comment]
@jongio thanks for the suggestion and sharing the information. The Blazor support is tracked in #170. I'm linking this issue to it.

Managed identity is for authentication between Azure services. I don't think it can work in a Blazor app running in browsers. A managed identity can only be obtained when the app is running in a supported Azure service, such as App Service. You can open issues in the .NET SDK repo if you have further questions about the `Azure.Identity` library.

**Comment by bradygaster** [comment]
Thanks for adding me and apologies for the vacation-delay, @jongio. Also adding @danroth27 to the discussion. I presume your goal here was to **solely** use managed identity between your Blazor WebAssembly app? I presume that since you have the Web API in there, you have a hosted blazor app and you're cool with "something on the server" doing the auth? Or do you specifically want the WASM app to do the auth directly via MSI?
