### ISSUE TITLE
App Configuration 401 error using DefaultAzureCredential in VS2019

### ISSUE THREAD

**Issue by dfibuch** [Azure/AppConfiguration#397]
One of my colleagues is seeing [this](https://github.com/Azure/AppConfiguration/issues/281) issue again today, was working fine yesterday and today getting this:

```
Azure.RequestFailedException: 'Service request failed.
Status: 401 (Unauthorized)

Headers:
Server: openresty/1.15.8.3
Date: Thu, 10 Sep 2020 09:53:40 GMT
Connection: keep-alive
WWW-Authenticate: HMAC-SHA256,Bearer error="invalid_token", 
error_description="The access token is from the wrong issuer. It must match the AD tenant associated with the subscription, to which the configuration store belongs. If you just transferred your subscription and see this error message, please try back later."
```

Before we start investigating further than we have (restart things, sign out/in again) can you guys verify there is nothing going on your end?

EDIT: It's working fine for me, with same code base and same level of access. Only difference is I am in a different country to him.

**Comment by zhenlan** [comment]
@dfibuch, are you and your colleague assigned *App Configuration Data Reader/Owner* role directly or via a security group in the access control of the App Configuration store? Which region does your store reside in?

**Comment by dfibuch** [comment]
@zhenlan We are both assigned with those roles as individuals, not through any group. The store is in North Europe.

**Comment by dfibuch** [comment]
Still an issue for us. Is this the best place to try get this fixed or should I be raising a ticket with some Azure department?

**Comment by zhenlan** [comment]
@dfibuch as you are assigned directly to the App Config store, not through a security group, this is a different issue than #287 

Are you in an environment with multiple AAD tenants? Are you and your colleague in different AAD tenants (domains)? According to the error message, you obtained the AAD token from one tenant and used it to authenticate with an App Config store that is created in another AAD tenant.

Given that this works for you but not your colleague, do you see anything else that is different between you two?

**Comment by stotlyakov** [comment]
Hi, we had the same issue. The solution was to ensure that the Tenant you are using in Azure is the same as the default Azure tenant in your Visual Studio. az login in the shell and see which wan has the "isDefault" flag set to true

**Comment by dfibuch** [comment]
@stotlyakov Uh good one, I'll try it out with him tomorrow and report back!

**Comment by zhenlan** [comment]
@dfibuch has the issue been resolved?

**Comment by dfibuch** [comment]
Sorry for inactivity on this @zhenlan , the person in question has been off and is not back until Tuesday so I cannot confirm. If it works for you feel free to close this and I will comment back if it worked or not.

**Comment by dfibuch** [comment]
@zhenlan Sorry again for the delay, I can confirm this is now working again for my colleague without changing a thing...

**Comment by kleky** [comment]
Hi, setting up app config for the first time and getting this error using connection string as provided via portal

**Comment by audex-nz** [comment]
Who is still facing this annoying problem - 2 steps to solve!

1) Visual Studio - Azure Service Authentication 

2) In your project, launchSettings.json
Add variable under profiles>IIS Express>environmentVariables

"AZURE_TENANT_ID": "<your tenant id>"

Happy days! Cheers,
Dex

**Comment by mrgurgle** [comment]
This worked for me:
1. Azure > App Configuration > Access Control > Added myself to "App Configuration Data Reader" role.
2. Fetched the tenant ID från Azure Active directory so I can use it in the code. 
3. Update the program.cs in my .net 6 minimal API app using "VisualStudioTenantId" if you use VS. or VisualStudioCodeTenantId if you use VS code.

**Code:**
`builder.Services.AddAzureAppConfiguration();

builder.Configuration.AddAzureAppConfiguration(options =>
{
    var appUri = builder.Configuration.GetConnectionString("appConfiguration"); //url to my App Configuration resource

    var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions { VisualStudioTenantId = "[MY__AAD_TENANT_ID]" });
    options.Connect(new Uri(appUri), credentials);
    options.ConfigureRefresh(refresh =>
    {
        refresh.Register("refreshAllSentinelKey", true);
        refresh.SetCacheExpiration(TimeSpan.FromSeconds(5));
    });
});

var app = builder.Build();

app.UseAzureAppConfiguration();`

**Comment by chidijude** [comment]
> AZURE_TENANT_ID

Why is this needed if we are supplying the app config endpoint?
