### ISSUE TITLE
Diagnostics Settings portal option and Azure Monitor option should be enabled for Azure App Configuration

### ISSUE THREAD

**Issue by asears** [Azure/AppConfiguration#407]
Diagnostics Settings portal option should be enabled, with logging to Application Insights (telemetry) and Log Analytics (audit) resource-specific tables for audit of keys and feature flags.

References #50

**Comment by zhenlan** [comment]
@asears good suggestion. This is working in progress.

**Comment by vkconsult** [comment]
How is work on this going?
The lack of auditing is keeping us from using AppConfiguration at this time.
We need to be able to get information on all historic requests. Which identity changed, queried or added a configuration etc.

**Comment by zhenlan** [comment]
The feature is available now. You should see *Diagnostic settings* and *Logs* blades under the *Monitoring* group in the Azure portal for App Configuration, where you can enable **HttpRequest** logs.
