### ISSUE TITLE
Error in docs.microsoft for add package reference

### ISSUE THREAD

**Issue by maririos** [Azure/AppConfiguration#41]
Following the instructions in https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-core-app, when doing: 
```
dotnet add package Microsoft.Extensions.Configuration.AzureAppConfiguration
```
I get the following error:
```
info : Adding PackageReference for package 'Microsoft.Extensions.Configuration.AzureAppConfiguration' into project 'D:\repos\work\work.csproj'.
log  : Restoring packages for D:\repos\work\work.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.azureappconfiguration/index.json
error: Unable to find a stable package Microsoft.Extensions.Configuration.AzureAppConfiguration with version
error:   - Found 1 version(s) in nuget.org [ Nearest version: 1.0.0-preview-007830001 ]
error:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
error:   - Found 0 version(s) in CliFallbackFolder
error: Package 'Microsoft.Extensions.Configuration.AzureAppConfiguration' is incompatible with 'all' frameworks in project 'D:\repos\work\work.csproj'.
```

My dotnet version is `2.1.504`

The way to make it work is to explicitly add the version that is defined in [NuGet](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/1.0.0-preview-007830001):
```
dotnet add package Microsoft.Extensions.Configuration.AzureAppConfiguration --version 1.0.0-preview-007830001
```

While the package is in preview, there could be a side note in the documentation explaining that the version needs to be explicitly set and that they can get it from NuGet directly, or something like that.

FYI @zhenlan @drago-draganov

**Comment by zhenlan** [comment]
Good catch. Thanks, @maririos.

@yegu-ms can we update the doc accordingly?

**Comment by zhenlan** [comment]
Fixed
