### ISSUE TITLE
App configuration managed identity flow gives 403

### ISSUE THREAD

**Issue by hem-sharma** [Azure/AppConfiguration#410]
```
Azure.RequestFailedException: 'Service request failed.
Status: 403 (Forbidden)

Headers:
Server: openresty/1.17.8.2
Date: Sat, 26 Sep 2020 11:27:02 GMT
Connection: keep-alive
x-ms-request-id: 85be5383-5fcd-4d9d-9fe6-6f9909721492
x-ms-client-request-id: 29517c65-1920-4a77-8b4d-112e634385c2
x-ms-correlation-request-id: 85be5383-5fcd-4d9d-9fe6-6f9909721492
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0
```

I was using managed identity (on the local machine) to connect with app configuration though it was working fine but giving 503 since the last day. Am I missing something here?

```c#
            var credentials =
#if !DEBUG
                new ManagedIdentityCredential();
#else
                new DefaultAzureCredential();
#endif
            var refreshConfiguration = TimeSpan.FromMinutes(minutesToRefresh);
            IConfigurationRefresher configurationRefresher = null;
            IConfiguration config = new ConfigurationBuilder()
                .AddAzureAppConfiguration(options =>
                {
                    options.Connect(new Uri(secondaryConfigValue), credentials)
                            .Select(KeyFilter.Any, GlobalConfigurationLabel)
                            .ConfigureRefresh(refreshOptions =>
                            {
                                refreshOptions.Register(ConfigurationSentinelKey, GlobalConfigurationLabel, true);
                                refreshOptions.SetCacheExpiration(refreshConfiguration);
                            })
                            .UseFeatureFlags(featureFlagOptions =>
                            {
                                featureFlagOptions.CacheExpirationTime = refreshConfiguration;
                                featureFlagOptions.Label = GlobalConfigurationLabel;
                            });
                    configurationRefresher = options.GetRefresher();
                }, true)
                .AddAzureAppConfiguration(options =>
                {
                    options.Connect(new Uri(primaryConfigValue), credentials)
                            .Select(KeyFilter.Any, GlobalConfigurationLabel)
                            .ConfigureRefresh(refreshOptions =>
                            {
                                refreshOptions.Register(ConfigurationSentinelKey, GlobalConfigurationLabel, true);
                                refreshOptions.SetCacheExpiration(refreshConfiguration);
                            })
                            .UseFeatureFlags(featureFlagOptions =>
                            {
                                featureFlagOptions.CacheExpirationTime = refreshConfiguration;
                                featureFlagOptions.Label = GlobalConfigurationLabel;
                            });
                    configurationRefresher = options.GetRefresher();
                }, true)
                .Build();
```

packages that I'm using are
```xml
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.8" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.7.1" />
    <PackageReference Include="Azure.Identity" Version="1.2.3" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="2.0.0" />
```

Also, how come this gives 503 or any other error if I explicitly set the 'optional' to true?

**Comment by zhenlan** [comment]
@hem-sharma do you mean 403 or 503 because the error you shared is 403 but you said 503 in the text?

I suppose you are using `DefaultAzureCredential` locally. It falls back to your local credentials (eg., the identity you use to log in to Visual Studio) and use it to connect to App Configuration. Please make sure the identity you are using is granted proper roles (`App Configuration Data Reader/Owner`) in your App Configuration store. You can find more details about what credentials the `DefaultAzureCredential` may use [here](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet).

BTW, I noticed you are still using `3.0.0` version of `Microsoft.Azure.AppConfiguration.AspNetCore`. Please consider upgrading to newer versions `3.0.2` or `4.0.0`. Some issues you ran into may have been fixed.

**Comment by hem-sharma** [comment]
@zhenlan Its 403, 503 was mistaken but couple of things I'm concerned with are:

As mentioned in the code, I'm using two app configurations though I'm using only primary one for testing on local.

I gave permission to Primary but secondary doesn't have access for my VS logged in principle. **But the same was working since last week**, I believe this **optional parameter** in AddAppConfiguration was doing the thing, as it says if set to true then errors can be safely handled.

Secondly, I know about version upgrade for packages but in latest one, configuration listed has been divided as Parent:child so it became messy to update all our mygets to support such configuration.

**Comment by ZhijunZhao** [comment]
@hem-sharma Could you share your 403 call stack? Managed identity is NOT supported in local machine. So, which authentication are you using? Is it `VisualStudioCredential`?

```
EnvironmentCredential
ManagedIdentityCredential
SharedTokenCacheCredential
VisualStudioCredential
VisualStudioCodeCredential
AzureCliCredential
InteractiveBrowserCredential
```

**Comment by hem-sharma** [comment]
@ZhijunZhao  I'm using DefaultAzureCredential on my local machine, my main concern is why `bool optional = false` is not working with AddAzureAppConfiguration() extension in case of any error while connecting?

**Comment by hem-sharma** [comment]
Another issue I'm facing is after upgrading `Microsoft.Azure.Functions.Extensions` to `1.1.0` from `1.0.0`, registered `IOptionsSnapshot` configurations stopped working.

I'm registering as:

```c#
serviceDescriptors.AddOptions<MyConfigurationPOCO>().Configure<IConfiguration>((settings, configuration) =>
            {
                settings = configuration.GetSection("MyConfigurationPOCOSection").Value.Deserialize<MyConfigurationPOCO>();
            });
```
earlier the same was working fine.

**Comment by raymens** [comment]
> @ZhijunZhao I'm using DefaultAzureCredential on my local machine, my main concern is why `bool optional = false` is not working with AddAzureAppConfiguration() extension in case of any error while connecting?

Somewhat (un)related. But I was hitting a similar issue. My intention is to have Azure App Config as an optional dependency to seamlessly start using it as some point. The `bool optional = false` parameter seemed like an excellent fit. However, it still throws any error like missing connection strings or missing connection logic.

**Comment by hem-sharma** [comment]
@raymens Yes, similar it is. I got intermittent authentication issues with `DefaultAzureCredential ` along with `bool optional = true` not handling these authntication failures.

**Comment by hem-sharma** [comment]
@ZhijunZhao For authentication purposes, I got a service issue alert on my Azure subscription due to some recent configuration changes by Microsoft (mitigated) though I would like to know about this handler parameter.

**Comment by zhenlan** [comment]
> `bool optional = true` not handling these authentication failures.

Please upgrade to the latest version of the package. This should have been fixed. If you see any breaking changes that are not documented in the [release notes](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md) but block you from upgrading, please open a new issue.

**Comment by zhenlan** [comment]
Please let us know if there are further questions. Closing this for now.

**Comment by hem-sharma** [comment]
@zhenlan Been away, apologies! Yes it's working after updating the nuget versions for app configuration package though after updating configuration values further in IConfiguation seems updated e.g.

Earlier:

key- abc
value- [{"def":"xyz"}]

After upgrade:

key- abc
value- abc[0].def:xyz

So our serialization impacted with this, any suggestion?

**Comment by zhenlan** [comment]
@hem-sharma not sure I follow. Do you mind opening a new issue with more details? For example, how exactly the key-value looks like in the store (a screenshot will be helpful), how do you use it (code snippet will be helpful), which version of the library you are using exactly?
