### ISSUE TITLE
Visual Studio 16.8.0 Preview 3.1: Azure.Data.AppConfiguration: Service request failed. Status: 403 (Forbidden)

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/AppConfiguration#413]
I have an Azure Function App which uses Azure App Configuration (AAC) which uses Keys from Azure Key Vault. 

```
builder.ConfigurationBuilder
    .AddAzureAppConfiguration(options =>
    {
        var tokenCredential = new DefaultAzureCredential();
        options
            .Connect(new Uri(Environment.GetEnvironmentVariable("AzureAppConfiguration_BaseUrl")), tokenCredential)
            .Select(KeyFilter.Any, LabelFilter.Null)
            .Select(KeyFilter.Any, Environment.GetEnvironmentVariable("AzureAppConfiguration_Label"))
            .ConfigureKeyVault(kv =>
            {
                kv.SetCredential(tokenCredential);
            })
            .UseFeatureFlags(featureFlagOptions =>
            {
                featureFlagOptions.CacheExpirationInterval = TimeSpan.FromSeconds(60);
            });
    });
```

When I try to connect to AAC from a local debugging session, getting **Azure.Data.AppConfiguration: Service request failed.
Status: 403 (Forbidden): Value cannot be null. (Parameter 'provider')**
```
A host error has occurred during startup operation 'b047cd4f-e792-44d5-a274-261cd76e96ec'.
Azure.Data.AppConfiguration: Service request failed.
Status: 403 (Forbidden)
[2020-09-30T03:20:36.998]
Headers:
Server: openresty/1.17.8.2
Date: Wed, 30 Sep 2020 03:20:35 GMT
Connection: keep-alive
x-ms-request-id: aa7eae85-971d-4ef9-ae2b-6aaa4a531a36
x-ms-client-request-id: d4916ec2-a125-4153-a1de-9d3e28c6bcf1
x-ms-correlation-request-id: aa7eae85-971d-4ef9-ae2b-6aaa4a531a36
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With,
If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha2
56, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id,
ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0
.
Value cannot be null. (Parameter 'provider')
```
![image](https://user-images.githubusercontent.com/5653381/94639699-4b85a100-0339-11eb-9c96-a5ab8e0971ff.png)

**Troubleshooting Steps I took**

- I have the latest Azure CLI installed.
```
PS C:\Users\Jaliya> az version
{
  "azure-cli": "2.12.1",
  "azure-cli-core": "2.12.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
- Correct account is set from Visual Studio: `Tools -> Options -> Azure Service Authentication`
- Correct subscription is set for Azure CLI and confirmed by running running `az account show`
- Selected Visual Studio Azure Service account has been given,
-- Contributor access to both AAC and KeyVault
-- In KeyVault, an access policy is defined for this Account

Nothing seems to help. I am on `Visual Studio Version 16.8.0 Preview 3.1`

Any help is highly appreciated.

**Comment by zhenlan** [comment]
> * Selected Visual Studio Azure Service account has been given,
>   -- Contributor access to both AAC and KeyVault

@jaliyaudagedara can you please grant the relevant account `App Configuration Data Reader` role in AAC (and wait ~20 minutes for it to propagate)? The `Contributor` role won't give you access to the data in AAC.

**Comment by jaliyaudagedara** [comment]
Oh right, just gave `App Configuration Data Reader`. That should do,  I have given that to a `User Assigned Managed Identity`, but not for my account.

Will check and update.

Thank you very much!

**Comment by jaliyaudagedara** [comment]
@zhenlan, that did it, thank you very much!
