### ISSUE TITLE
Azure pipelines support to Automate RBAC role addition

### ISSUE THREAD

**Issue by hem-sharma** [Azure/AppConfiguration#416]
We are using azure app configuration for our azure functions with managed identity.

And we need to add '*DataReader' role in app configuration for our web app principle to be able to access the App configuration after app provisioning.

Awaiting suggestions.

**Comment by zhenlan** [comment]
The document below uses App Service as an example, but it's the same idea for Azure Functions.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity

**Comment by hem-sharma** [comment]
@zhenlan I'm able to create a function and it's working fine with a Managed identity like - I added app service principle as 'App configuration data reader' but my concern here is to automate the same using `Azure DevOps` which is missing in the document.

Compared to Azure key-vault, which we were using earlier, it was really easy to add access policies of consumer app service using ARM, but app configuration lacks here..if you can shed some light on the best way or direct me to the relevant document.

I tried exploring but I'm afraid that some existing methods require `AD role write permission` for `Service connection principle` used in the Azure pipeline to do the RBAC assignment.

**Comment by jimmyca15** [comment]
Hello @hem-sharma. Did you consider to user the Azure CLI in the devops pipeline to [create the role assignment](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-cli)? The doc I linked mentions the required permissions "Microsoft.Authorization/roleAssignments/write and Microsoft.Authorization/roleAssignments/delete". There is no way around that. The permissions would need to be present for the service connection principle.

**Comment by hem-sharma** [comment]
Many thanks, @jimmyca15, Any place where "assigning permissions to the service principle associated with Service Connection (Azure DevOps)?

**Comment by jimmyca15** [comment]
Sorry @hem-sharma I don't understand the question. It looks like it wasn't completed.

**Comment by hem-sharma** [comment]
@jimmyca15 I mean this by: how can I allow such permissions to a Service Connection in DevOps, for e.g.

![serviceconnection](https://user-images.githubusercontent.com/15911296/95644937-fc2d3680-0ad7-11eb-8341-621c4919078b.PNG)

So there are only two options.

-> Manage service connection roles

![role](https://user-images.githubusercontent.com/15911296/95645027-aad17700-0ad8-11eb-9619-c18fc39950df.PNG)


-> or Manage Service Principal

![image](https://user-images.githubusercontent.com/15911296/95645039-d6546180-0ad8-11eb-81cc-9bf39651438d.png)

As of now, I assigned an owner role (which can manage the RBAC additions) to the app (created with the service connection) but still, I'm facing 403 issues.

**Comment by jimmyca15** [comment]
@hem-sharma sure, from the image it would be.

Manage service connection roles -> Role Assignments -> Add Role Assignment -> App Configuration Data Reader

**Comment by hem-sharma** [comment]
Able to add RBAC role by using poweshell after adding the service principle of service connection (used in pipeline) as owner of Azure subscription, though it fails after adding role in b/w So I've made the weird solution to put command in a try/catch to silently continue for the time being. It seems like powershell command tries to list role post assignment which fails due to lack of permissions other than owner role. Still exploring a concrete solution...

**Comment by hem-sharma** [comment]
> @hem-sharma sure, from the image it would be.
> 
> 
> 
> Manage service connection roles -> Role Assignments -> Add Role Assignment -> App Configuration Data Reader

@jimmyca15 This one is for accessing App configuration, but my need is to assigning RBAC role using DevOps which requires certain permissions to do so.

**Comment by jimmyca15** [comment]
To accomplish that you need to assign a role that is capable of creating role assignments such as [user-access-administrator](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator).
