### ISSUE TITLE
API for CRUD of feature flags?

### ISSUE THREAD

**Issue by kirk-marple** [Azure/AppConfiguration#417]
I've read through the documentation, and can't find a way to create/update/delete feature flags outside of the Azure Portal.

Is this not supported, or is there an API or CLI command I can use to create feature flags in an automated fashion?

**Comment by zhenlan** [comment]
@kirk-marple feature flags are just special key-values with these [conventions](https://github.com/Azure/AppConfiguration/tree/main/docs/FeatureManagement), so all CRUD APIs of key-values apply to feature flags too.

Yes, you can use CLI to manage feature flags too. Check out `az appconfig feature -h`.

**Comment by kirk-marple** [comment]
Awesome, thanks for quick reply.  That answers my question.
