### ISSUE TITLE
Export Not Working for Feature Management Key/Value Pairs

### ISSUE THREAD

**Issue by toddmeinershagen** [Azure/AppConfiguration#419]
I am using App Configuration as a store for feature flags (FeatureManagement).  I noticed that when I try to export the configuration to a configuration file - it does not recognize any key/value pairs.  Once I add a simple key/value pair to the existing feature, it only exports out the 1 key/value pair.  But from the picture below, it seems that App Config recognizes that there are 3 key/value pairs - 2 being of a feature management content type.

![image](https://user-images.githubusercontent.com/177508/96158028-0f2d7580-0ee1-11eb-810e-ec0e90948e60.png)

Is this the expected behavior?  

We are wanting to use this as a way to promote feature flags (for instance for a beta rollout) through non-production to production.

**Comment by abhilasharora** [comment]
@toddmeinershagen The import/export of feature flags to a _Configuration file_ is not supported through the Azure Portal. There are two ways you could export all settings _including_ feature flags for your scenario.

1. Use Azure CLI to export all key-value pairs and feature flags with null label to a configuration file. More details on the supported parameters can be found [here](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_export).

    `az appconfig kv export -n MyAppConfiguration -d file --path D:/abc.json --format json`

2. Export the configuration directly to another App Configuration resource through Azure Portal

    ![image](https://user-images.githubusercontent.com/47916289/96293191-3a769a00-0f9f-11eb-8bb6-8a80abde3a93.png)

**Comment by zhenlan** [comment]
The support for importing/exporting feature flags from/to files in *portal* is tracked in #190.
