### ISSUE TITLE
Add using statements to C# example in docs.microsoft

### ISSUE THREAD

**Issue by maririos** [Azure/AppConfiguration#42]
Following the instructions in https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-core-app, when doing step #3 of `Connect to app configuration store`, it will be good to also point out that the user needs to add the corresponding using statement in the file, for the application to compile.

By just following the instructions, the user will get the error:
```
Program.cs(9,31): error CS0246: The type or namespace name 'ConfigurationBuilder' could not be found (are you missing a using directive or an assembly reference?) [...]

Build FAILED.

Program.cs(9,31): error CS0246: The type or namespace name 'ConfigurationBuilder' could not be found (are you missing a using directive or an assembly reference?) [...]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.20
```

According to the extensions installed in the code editor the user could see this, although being explicit about it might be better.

**Comment by zhenlan** [comment]
Good feedback. Thanks, @maririos.

@yegu-ms can we update the doc accordingly?

**Comment by zhenlan** [comment]
Fixed.
