### ISSUE TITLE
Feature Request: Ability to Enable/Disable feature flags through code

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/AppConfiguration#425]
It would be great if we can have the ability to Enable/Disable feature flags through the code. So we can use our own UI rather than going into Azure Portal.

**Comment by zhenlan** [comment]
@jaliyaudagedara please let me know if #417 answers your question.

**Comment by jaliyaudagedara** [comment]
@zhenlan, thanks for the reply! Right, so in that case, technically this should work, isn't it?
[Azure App Configuration client library for .NET - Version 1.0.2](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.appconfiguration-readme?WT.mc_id=DT-MVP-5000570)

**Comment by zhenlan** [comment]
Yes, the SDK you mentioned above will work.

And I agree - we should have better documentation for this too. I have this tracked internally (FYI, @AlexandraKemperMS). Thanks for the suggestion, @jaliyaudagedara.

**Comment by jaliyaudagedara** [comment]
Awesome, thank you @zhenlan!
