### ISSUE TITLE
GetRefresher() returning null values

### ISSUE THREAD

**Issue by cannehag** [Azure/AppConfiguration#426]
I have an Azure Function where I configure Azure AppConfiguration like this.
Using latest version
Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.0.0"
Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="4.0.0"

.AddAzureAppConfiguration(options =>
               {
                  options.Connect(Environment.GetEnvironmentVariable("Config:AzureAppConfigurationConnectionString",
                     EnvironmentVariableTarget.User))
                     .Select(KeyFilter.Any, "mykey");
                    
                  var refresher = options.ConfigureRefresh(refreshOptions =>
                     {
                        refreshOptions.Register("sentinelkey", "mykey", true)
                           .SetCacheExpiration(TimeSpan.FromMinutes(5));
                     }).GetRefresher();
                  
               })

However, if I put a breakpoint after the GetRefresher() method and inspect the refresher instance, both the AppConfigurationEndpoint and the _provider values are null.
I have verified that the connectionstring is valid. And if I use the ICnfiguration later on, the values are retrieved from AppConfiguration. This problem here is that I don't get the refresher to work.

**Comment by zhenlan** [comment]
@cannehag I cannot spot the issue from the code snippet you shared. We have an example of Azure Functions. Do you mind to try out the example and see what's the difference between the example and your app?

https://github.com/Azure/AppConfiguration/blob/main/examples/DotNetCore/AzureFunction/FunctionApp/Startup.cs

**Comment by cannehag** [comment]
@zhenlan Aha! I got it. I was lookin at the value of the refresher at line 31 (in the example you linked to). And at that point the values inside the refresher instance was null. But later on, when injecting the IConfigurationRefresher, they seems to be populated. Didn't think of the lazy approach there.
You can close this question/issue and I will figure out the implementation on my side!

Thanks!
