### ISSUE TITLE
Support for various azure service reference

### ISSUE THREAD

**Issue by EmFl** [Azure/AppConfiguration#428]
Is it planned to support references to other azure services ? For example to provide iothub connection string or cosmos db connection string or a web app defined hostname etc.
Or is the usual methodology for this is to store these credentials when deploying the initial resources ?
ie. deploy web app, parse arm/terraform output and push to azure app config ? 

Thanks

**Comment by shenmuxiaosen** [comment]
Hi EmFl, 
We currently support [key vault reference](https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=cmd%2Ccore2x) which integrates with Azure Key Vault where you can keep storing your secretes safely. https://docs.microsoft.com/en-us/azure/azure-app-configuration/faq#should-i-store-secrets-in-app-configuration

**Comment by EmFl** [comment]
Hello @shenmuxiaosen ,
Thanks.
I had seen this vault support in the documentation and tested as well. I was wondering if there was a use case for other type of reference in app config. For example referencing an eventhub where you would specify the eventhub name and namespace etc. This would create something of the type application/vnd.microsoft.appconfig.eventhubtref+json and then the SDK would fetch the associated connection string when needed ?
Same thing with appinsights etc.

The end goal is to say, if I have a reference to an eventhub then I know I can get the url by doing attributename.url or something of the sort.  Without having to provision all of this in the app config itself but by leveraging reference mechanisms like it is done for the azure keyvault secrets.

Thanks

**Comment by shenmuxiaosen** [comment]
Azure Key Vault is designed to store your secrets including connection string for different services in one place with full protection. Although it is possible to fetch the eventhub connection string through management plane operation (Azure Resource Manager), it is not a good idea to do that in production from security perspective. So for service secretes or connection string, we only have the Key Vault reference supported in App Configuration.

**Comment by zhenlan** [comment]
@EmFl what you are asking is reasonable and aligns with our vision too - App Configuration can be a central place with references to many other Azure/non-Azure resources. Key Vault reference is just one example. Besides what @shenmuxiaosen already said, I want to share that we are thinking about a way to allow custom resolution of any references. This issue tracks our latest design proposal: Azure/AppConfiguration-DotnetProvider#157. Please let us know if you have any feedback on that issue.

**Comment by EmFl** [comment]
Awesome, I'll check the issue mentioned and will comment in there if needed. Closing this one to ensure a single place for discussion. Thanks to both of you.
