### ISSUE TITLE
RequestFailedException : Service request failed Status: 401 (Unauthorized) on Docker, WSL2

### ISSUE THREAD

**Issue by DSRAttabotics** [Azure/AppConfiguration#429]
Hello!

I'm not sure this is the right place to report this -- I hope it saves time for someone else.

I've been working with App Configuration in a couple of projects, one which went stale for a period.  I came back to it to find that the App Config SDK seemingly cannot Build(), failing with a RequestFailedException.  The only change I thought I made was switching Docker Desktop to use WSL 2 on the backend, and I've now confirmed this in my testing -- Docker desktop using WSL 2 causes this authentication issue, using HyperV as a back-end runs without issue!!

Steps to repro:
1) Create a new Azure App Configuration instance, or open existing app Configuration instance. 
2) Copy connection string, paste it in the attached project. [appconfigtestproject.zip](https://github.com/Azure/AppConfiguration/files/5505088/appconfigtestproject.zip)
3) Build and Run the attached project using the "appconfigtest" debug profile - verify it runs/exits without exception.
4) Switch and debug the attached project in it's Docker profile, Unix WSL2 -- it fails with the following auth exception, and details:

Headers:
Server: openresty/1.17.8.2
Date: Sat, 07 Nov 2020 15:15:45 GMT
Connection: keep-alive
WWW-Authenticate: HMAC-SHA256 error="invalid_token", error_description="The access token has expired",Bearer
x-ms-request-id: f74e305d-de1e-4d4f-88b3-3171086ce194

Azure Container instances doesn't seem to have this issue; I've not tried with other containers.

Microsoft.Extensions.Configuration.AzureAppConfiguration v 4.0.0

**Comment by zhenlan** [comment]
> error_description="The access token has expired"

According to the error, it's likely the system time in the container is not accurate. The service requires the auth token generated within 15 minutes. See https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-hmac#errors.

**Comment by DSRAttabotics** [comment]
Right - seems like an issue with WSL2 - [https://chrislayers.com/2020/01/23/wsl2-docker-and-time/](https://chrislayers.com/2020/01/23/wsl2-docker-and-time/), specifically:

* Time not synced in WSL2 – causing TLS issues –[ https://github.com/microsoft/WSL/issues/4149]( https://github.com/microsoft/WSL/issues/4149) 
* system date is not same with windows (WSL 2) – [https://github.com/microsoft/WSL/issues/4245](https://github.com/microsoft/WSL/issues/4245)
* WSL2: Clock skewed? – [https://github.com/microsoft/WSL/issues/4677](https://github.com/microsoft/WSL/issues/4677)
