### ISSUE TITLE
Issue with latest version of Azure App Configuration Push task

### ISSUE THREAD

**Issue by aldacosta** [Azure/AppConfiguration#431]
Hello,

Our Azure Devops automatically updated to version 1.0.3 yesterday night and now the task is failing. Seems that the package is missing index.js. Checked the vsix and the file is not there. The exact error is this one:

`##[error]File not found: '/azp/agent/_work/_tasks/AzureAppConfigurationPush_014d1f42-f7ad-4418-b165-5bf03802417e/1.0.3/index.js'`

Thanks!!

**Comment by ruankr** [comment]
Getting exactly the same as well

**Comment by chrismcclure** [comment]
I am also getting this error. Does anyone have a work around or anything I can do?

**Comment by Anne56njeri** [comment]
Working on a fix for this, apologies for any inconvenience caused.

**Comment by aldacosta** [comment]
Thanks @Anne56njeri

**Comment by Anne56njeri** [comment]
There is a new release to fix the issue, it should be good now. In case of anything please reach out :).

**Comment by ruankr** [comment]
You should learn to use task versioning so that we can at least change it to the previous version (or choose when to start using new tasks) when they break/come out. Thanks for the fix tho, gave it a go and seems ok now.

**Comment by jimmyca15** [comment]
Closing this since the issue has been resolved.

@ruankr thanks for the suggestion. We had a post mortem discussion on this issue. We will be relying on minor version updates for future releases to make rollbacks possible if desired, but still enable automatic roll forward.
