### ISSUE TITLE
Key/Value Management

### ISSUE THREAD

**Issue by sp4rc** [Azure/AppConfiguration#437]
I have been digging through the documentation and there is one thing I am unsure about:

Besides the Azure SDK, is the Azure Portal the only way a user can configure key/value pairs (CRUD)?

- I can't find anything from within the Azure PowerShell Module (Az.AppConfiguration)
- Azure CLI does not seem to provide any subcommands 
- [REST API](https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-keys) only seems to provide read-operations 

Can someone please second this? Anything obviously I haven't realized yet in that regard? TIA

**Comment by jimmyca15** [comment]
The REST API link that you provided describes the key-value `set` and `delete` operations. The Azure CLI has [`az appconfig kv`](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest)
