### ISSUE TITLE
ARM template - Key Vault references

### ISSUE THREAD

**Issue by mattboothman** [Azure/AppConfiguration#445]
There's no documentation on adding Key Vault references via ARM.

I had a fiddle and can add these by setting the `contentType` property to `application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`.

When setting up a Key Vault reference in the portal UI, we end up with a JSON object that has a single property - `uri` that contains the URI to the Key Vault item. However, I'm able to supply either a JSON object with a `uri` property, or just a URI string that is not JSON encoded, instead. Is this intended? If it is, the supplied value should be validated according to the supplied content-type:

- `application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8` - must validate as JSON and contain the `uri` property.
- support added for `contentType` `application/vnd.microsoft.appconfig.keyvaultref;charset=utf-8` (without json subtype suffix). This currently is not recognised as a key vault reference content-type.

It does seem that the URI is validated in so far as a check is made to make sure the host matches the pattern `*.vault.azure.net`. I don't think the validation needs to change here.

I have a few questions:

- Could ARM documentation be updated to describe the process of creating Key Vault references?
- Could validation be fixed to force a valid JSON object including required property `uri` where the content-type subtype suffix is `json` (`application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`)?
- Could further support be added to allow cotnent-type `application/vnd.microsoft.appconfig.keyvaultref;charset=utf-8` which accepts only a URI string (not JSON)?
- Is the key vault reference content-type used just to provide UI feedback? As in, to put an icon next to matching items?
- Do I get any other benefit from the key vault reference?

**Comment by recao** [comment]
@drago-draganov

**Comment by zhenlan** [comment]
@mattboothman thanks for the feedback.

I'm thinking about putting up some documentation about how to create Key Vault references (KVR) in various ways including the ARM template too. While that's still on the backlog :), here is an example @ZhijunZhao put in a comment for adding KVR via ARM template:  https://github.com/Azure/AppConfiguration/issues/268#issuecomment-685319249.

We try to keep the App Configuration service simple so it is flexible to fit in different scenarios/languages/frameworks/hosting environments and so on so forth. To the service, everything is simply key-values. Clients, however, can react differently depending on what they see (either a special key prefix or a content-type). Using KVR as an example, the portal uses the special content type to show the icon, and more importantly, the config provider libraries use it to automatically talk to Key Vault to retrieve the actual secret. We are also thinking about adding extensibilities in config providers, so for example, if you don't like the JSON format of KVR, you can implement your own. As you can see, if we put any enforcement on the server-side, all these would not be possible. If any enforcement is desired, the client-side is probably the best place. I hope this provides some context and at least answers some of your questions.

**Comment by drago-draganov** [comment]
@mattboothman 

> Do I get any other benefit from the key vault reference?

Key vault references link secrets to the application configuration, without breaking the security contract between Key vault and you. Proper secrets management (ex. rotation, expiration, granular access control, auditing, specialized HW storage, etc.) are essential and Key vault is built to offer these.
Application Configuration is designed with configuration priority in mind (ex. evolution of settings, grouping, bulk delivery of multiple key-values in a single request, micro-services configuration support, key namespaces, etc.)

Almost all applications need configuration and secrets. Key value references allows to treat Key value secret as configuration item and allows some of the benefits above. It also helps keep track, export and import of both.

**Comment by mattboothman** [comment]
@zhenlan @drago-draganov thank you both for your responses. Apologies for the delay in reply.

@zhenlan, yes that documentation looks very helpful.
