### ISSUE TITLE
.Net Core App Configuration Dynamic Configuration refresh selected values

### ISSUE THREAD

**Issue by sameer-kumar** [Azure/AppConfiguration#448]
Hello,

This is for an Asp.net core 3.1 project using Microsoft.Extensions.Configuration.AzureAppConfiguration 4.1.0.
I have followed along this [tutorial](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core3x) available on MS docs. And I'm able to refresh all of my values once Sentinel key is changed. 

However, I have bit different use case to refresh only specific set of values but not all. Is it possible?

To give a brief background of my app design, I have an AppConfiguration service which has many configurations stored distinguished by labels and/or key prefixes. These are meant to identify the apps to which these configurations belong. 
Each app may have a dozen or more config key/value pairs. I have Sentinel keys specific to each app. Now I want to refresh only those values which belong to the app for which Sentinel is updated. 

Here is my registration code:

```
config.AddAzureAppConfiguration(options => {
                    options.Connect("Endpoint=https://xxx.azconfig.io;Id=l6-s0/8eB;Secret=JwX=");
                    options.ConfigureRefresh(refresh => {
                        refresh.Register("App1Settings:Sentinel", true);
                        refresh.SetCacheExpiration(new System.TimeSpan(0, 1, 0)); 
                    });
                }, 
                optional: true);

```
Thanks!

**Comment by drago-draganov** [comment]
If you use key namespace for app related setting and distinguish between different applications configurations. Here is an example:

app1/setting1
app1/setting2
app1/setting3
....

app2/setting1
app2/setting2
app2/setting3
.....

Then each app can be configured to [select ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.select?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfiguration_AzureAppConfigurationOptions_Select_System_String_System_String_) it's own settings only. This way only the required setting will be requested and refreshed when needed. Now ``app1/sentinel`` will pull only ``app1/*`` settings.

```cs
config.AddAzureAppConfiguration(options => {
                    ...
                    options.Select("app1/*", <some label>)
                                .ConfigureRefresh(refresh => {
                                   refresh.Register("app1/sentinel", true);
                        ...
                    });
                }, 
                optional: true);
```

**Comment by sameer-kumar** [comment]
At that point, I think there won't be any need to have a namespace for Sentinel key? If keys are Selected for a specific app anyhow then sentinel can be global instead of duplicating it for each app like app1/sentinel, app2/sentinel and so on.

Also, what do you recommend between key namespace (as you shown) vs labels to distinguish configurations for apps?

**Comment by drago-draganov** [comment]
Sentinel key per app will allow request for refresh being sent only for the specific app. A global sentinel will trigger refresh for all apps, though only one needs it. It's less efficient, especially if each app config is independent.

I would definitely recommend key namespaces for segmenting config between different apps. Individual app settings are indeed separate entities. Labels are better used as evolution marker for entities. Here is an example

app1/MaxRequestPerSecond  <- this is an entity with evolution based on version
     label: v1
         value: 100
     label: v2
         value: 180 (due to improvement in v2 we can increase the limits, while keeping the same QoS)


app2/MaxRequestsPerSecond <- this is an entity with evolution based on deployment location
    label: regionA
        value: 50 
    label: regionB 
        value: 100 (more resources are deployed in RegionB, so it can accommodate the increased limits)


Even though app1 and app2 have the same setting name, they may choose completely different evolutional approach (as mentioned above) or sometimes even completely different meaning (homographs are good example: i.e. bat - app1/batSize referring to baseball, app2/batSize referring to the animal.

Hope that helps a bit.

**Comment by sameer-kumar** [comment]
That's very helpful. Thanks.
You can mark it as closed.

**Comment by drago-draganov** [comment]
Unfortunately .NET core config system doesn't allow multiple values per key. The Azure AppConfiguration provider is therefore limited to single label. The service supports multiple labels, but you need to use the [sdk ](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.appconfiguration-readme) directly instead. It won't nicely integrate to your application config system, though, but you will have an ultimate control.

**Comment by sameer-kumar** [comment]
Ah! I see. Let me play around it with it. Thanks!
