### ISSUE TITLE
Offline Cache

### ISSUE THREAD

**Issue by kamalsivalingam** [Azure/AppConfiguration#45]
We are building many microservices that might depend on Service Registry based Key Value Store. We originally thought of using either Consul from HashiCorp or use VSTS as the store since it has release variables. 
However We are now thinking of using AppConfiguration for that purpose., 
Since this is going to be central configuration store, we do not want our services go kaboom when the AppConfiguration goes down for any odd reason.
I do see SetOfflineCache method. I am not sure if it is for this purpose of caching the values as a backup?

Are there any examples for SetOfflineCache?

**Comment by zhenlan** [comment]
Hi @kamalsivalingam, yes, the idea behind the offline cache is to save a last known good (LKG) copy of config that the application requested previously to the local environment of the user's application, so the application can still use LKG config when unexpected happens (for example, a network hiccup at the application start-up).

However, the users' application environments can be very different from one to another, so the solution of caching differs too. Each environment will need its implementation of [`IOfflineCache`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.iofflinecache). Currently, the config provider provides [offline file cache](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.offlinefilecache) for applications hosted in *Azure App Service*. The caching file is encrypted and saved at *$home/data/azureAppConfigCache* (so the cache can be shared among multiple web workers). Here is a code snippet to enable it.
```cs
config.AddAzureAppConfiguration(option =>
{
    option.Connect(settings["ConnectionStrings:AppConfig"])
          .SetOfflineCache(new OfflineFileCache());
});
```
Please let us know if this is something you are looking for. Any feedback is welcome.

**Comment by kamalsivalingam** [comment]
This is Awesome :..All the problems we wanted to solve using custom implementation is already taken care
:100:

**Comment by vip32** [comment]
does this also work locally? is %HOME% used there?

**Comment by zhenlan** [comment]
@vip32 when your app is not hosted in App Service, you can set your own offline file path via [`OfflineFileCacheOptions.Path`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.offlinefilecacheoptions.path?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfiguration_OfflineFileCacheOptions_Path). For example,
```cs
.SetOfflineCache(new OfflineFileCache(
    new OfflineFileCacheOptions() { Path = "your offline file path"}))
```

**Comment by vishnu-97** [comment]
I amm getting the following error when using the above way. 

System.Private.CoreLib: Exception while executing function: Function1. AzureKeyVault: The type initializer for 'AzureKeyVault.Function1' threw an exception. System.Text.Json: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.

P.S. I have created File "OfflineCache.json" before setOfflineCache() as it was throwing error for not finding the file

**Comment by pbhughes** [comment]
@vip32  Does this work for IIS hosted apps as well?  We still have apps hosted in IIS that have yet to move to the cloud we want them to consume remote configs as well.

**Comment by avanigupta** [comment]
Hello @pbhughes, @vishnu-97, @vip32, @kamalsivalingam, 
we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?

**Comment by kamalsivalingam** [comment]
@avanigupta I posted this question when I started exploring Azure AppConfig. The web apps and backend consumer apps hosted on Azure App Service that I worked on so far relies on Azure App Config and Azure KeyVault upon bootstrapping the application and so I didnt integrate the offline cache mechanism. However if you are using .net core Options pattern (IOptionsSnapshot) to auto refresh the configuration value in the app upon updating in app config and if you wanted a way to cache the copy of the configuration as a backup for azure app config, you could use this SetOfflineCache method to store the last known copy in a local store.

**Comment by vishnu-97** [comment]
Hii Team,
We used them to serve as a backup incase azure is down for some reason.
Further, we also had the values in in memory, which get updated whenever
there was any update in AppConfiguration which provided faster access
reduced AppConfiguration requests.
So, offline cache, didn't actually came to be much use, it was jst there as
a backup of backup.

Thanks & regards,
Vishnu R Pillai
