### ISSUE TITLE
Application Insights tracing not working for asp.net project 

### ISSUE THREAD

**Issue by Meenakshise** [Azure/AppConfiguration#450]
App Insights is not working in one of project. It works in the MVC project of that solution but it doesn't work in the older aspx project. could you please help me. I updated the sdk to use 2.16 which works in the MVC but the same is not working in the older aspx project. 

Not sure if it is because it has nlog.config file in the older aspx project. I just tried to move the below config from the web.config file to the nlog.config file
 

While doing so, I was not able to specify the target for the Application insights. Please find the error below. I tried changing the type to xsi:type but even that didn't help me.  got a different error. Is this the reason why the tracing didn't work in the portal of Azure? Please help me to fix it. 
![image](https://user-images.githubusercontent.com/5516586/104289008-9be6d000-54de-11eb-97b6-917912753417.png)

![image](https://user-images.githubusercontent.com/5516586/104289166-d0f32280-54de-11eb-87d2-7db813c065bc.png)

**Comment by drago-draganov** [comment]
@Meenakshise Perhaps [Application Insights](https://github.com/microsoft/ApplicationInsights-dotnet) is a better target for this issue.
