### ISSUE TITLE
az appconfig kv export - when exporting to properties format extra escape characters are added to urls and connection strings

### ISSUE THREAD

**Issue by marleypowell** [Azure/AppConfiguration#454]
```bash
// JSON
az appconfig kv export --name $appConfigName --destination file --path config.json --format json --separator '__'

// Properties
az appconfig kv export --name $appConfigName --destination file --path config.properties --format properties
```

azure-cli version: 2.18.0

Input:
```
Key:Value
Service__Url:http://localhost:16571/api/version
Service__Db:Endpoint=sb://db.windows.net/;SharedAccessKeyName=Send;SharedAccessKey=key=;EntityPath=audit
```

JSON output:

```Json
{
    "Service": {
        "Url": "http://localhost:16571/api/version",
        "Db": "Endpoint=sb://db.windows.net/;SharedAccessKeyName=Send;SharedAccessKey=key=;EntityPath=audit"
    }
}
```

Properties output:

```properties
Service__Url=http\://localhost\:16571/api/version
Service__Url=Endpoint\=sb\://db.windows.net/;SharedAccessKeyName\=Send;SharedAccessKey\=key\=;EntityPath\=audit
```
There are extra backslashes for the properties output.

This behaviour only occurs for `azure-cli` as it returns normal output when exporting from `azure portal`.

**Comment by avanigupta** [comment]
Hello @marleypowell, this is an implementation difference due to the fact that Portal and CLI use different libraries to parse properties files. The extra backslashes are added before `:` and `=` to escape these special characters in the value. However, both outputs are formally acceptable. Here are some references for the properties format:
- https://en.wikipedia.org/wiki/.properties#Format
- https://docs.oracle.com/javase/6/docs/api/java/util/Properties.html
- https://github.com/jwodder/javaproperties/issues/3#issuecomment-441060045

If you try to parse either of these files using any standard Java Properties parser, you will get the expected output. In fact, if you try to import any of these files back to AppConfig using Portal or CLI, you will get your original key-values back.

**Comment by marleypowell** [comment]
Is there a way to export using custom parsing?

For example at the moment I want `.env` files and the easiest way to get them without escaping is to export as `yaml` then replace `:` with `=` and replace empty strings `key: ''` with `key=`.

```shell
az appconfig kv export --name $NAME --destination file --label $LABEL --path $CFG_PATH --format yaml --yes
# Used to parse yaml to .env
sed -i "s/:\s/=/g" $CFG_PATH # : -> =
sed -i "s/=''/=/g" $CFG_PATH # ='' -> =
```

**Comment by avanigupta** [comment]
We do not support custom parsing for export. Currently, we only support exporting in json, yaml or properties format. 
Do you mind sharing what type of application will consume your `.env` file?

**Comment by marleypowell** [comment]
The `.env` files are used for a `docker-compose` config for local running containers. For our hosted containers we use `k8s` so I can use `ConfigMaps` and `.properties`

**Comment by avanigupta** [comment]
@marleypowell, If I understood correctly, you want to load AppConfig key-values into your docker environment variables for substitution in your docker-compose.yml file. Is that correct? If yes, I found something that might help solve your issue without creating .env files: [Read JSON-file into environment variable with Docker Compose](https://stackoverflow.com/a/61421270)
You can export AppConfig key-values to a JSON file and load that file directly into local environment variables.

**Comment by marleypowell** [comment]
@avanigupta  Would this approach also work with Kubernetes?

**Comment by shenmuxiaosen** [comment]
@marleypowell If you are using Helm for Kubernetes deployment. This can help. [Integrate with Kubernetes Deployment using Helm](https://docs.microsoft.com/en-us/azure/azure-app-configuration/integrate-kubernetes-deployment-helm)

**Comment by zhenlan** [comment]
@marleypowell please let us know if you have further questions. Closing.
