### ISSUE TITLE
Impossible to import App Service settings with prefix in App Configuration store

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#456]
If we have App settings of several App services in an App Configuration store (in a same resource group), we need to prefix key-values for each App service.
But in the Azure Portal on a App Configuration resource, when we import "App Service" to "App Configuration", we can't define a prefix for imported keys because no "prefix" field is proposed !

A "prefix" field is proposed when we export "App Configuration" to "Configuration File" ! But this "prefix" field is more important when we import key-values in App Configuration store which can be already have existing data. It's possible ot import with a prefix with Azure CLI, but not with the Portal azure (and not with Azure Powershell).

**Comment by jiayi11** [comment]
Thank you for your feedback! We will track this issue and take it into consideration in our next design.

**Comment by Philippe85** [comment]
Could you release this fix ? Now, we can't import several app services in same App Configuration. And is it very blocking.

**Comment by avanigupta** [comment]
Hi @Philippe85, can you use Azure CLI to import configuration from different App Services to the same App Configuration? This should unblock you for the time being:

`az appconfig kv import -s appservice -n <AppConfigName>  --appservice-account <AppServiceResourceId>  --prefix <prefix>`

**Comment by jiayi11** [comment]
Fix is already checked in, plan to be deployed to all regions in about 2 weeks.

**Comment by jiayi11** [comment]
Fix is already deployed. Closing the issue.
