### ISSUE TITLE
Impossible to import key-values from an "App Service" in different environnement (in another resource group or subscription)

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#458]
An App Configuration is planned to manage groups of key-values for each environnements (with labels).

If we have a subscription for each environnement, we need to have only one App Configuration to store data for all environnement (with labels). So, we need to be able to import in App Configuration from App Service in another subscription/resourcegroup.

It is possible manually in Azure Portal, but not by automation with Azure CLI or Azure PowerShell.
`az appconfig kv import` can work only in the same resource group ! So it is unusable.

**Comment by avanigupta** [comment]
Hello @Philippe85, you can achieve this by providing the complete resource ID of your App Service as an argument to the `az appconfig kv import` command:

`az appconfig kv import -n <AppConfigName> -s appservice --appservice-account /subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupId>/providers/Microsoft.Web/sites/<AppServiceName>`

**Comment by Philippe85** [comment]
Thank you @avanigupta.

With the resource ID, I can import key/values from an App Service in other resource group, but in the same subscription.
If the App Configuration and the App Service resources are in differents subscriptions, I get this error :
```
Failed to read key-values from appservice.
(ResourceGroupNotFound) Resource group 'xxx' could not be found.
```

xxx is the ResourceGroupId in this resource ID :
/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupId>/providers/Microsoft.Web/sites/<AppServiceName>

**Comment by zhenlan** [comment]
@Philippe85 thanks for reporting the issue. This may have the same root cause as #459. Let's keep all the discussion there. We can reopen this if this turns out to be a different issue later.
