### ISSUE TITLE
Application reading configuration from another Azure App Configuration service!

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#461]
Hi, 

In my tennant I have 2 Azure App Configuration services. 

I just created a new .Net Framework console app. 
I configured it as per the [.Net Framework quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app).

```
	<configSections>
		<section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="false" requirePermission="false" />
	</configSections>

	<configBuilders>
		<builders>
			<add name="MyConfigStore" mode="Greedy" connectionString="${ConnectionString}" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
			<add name="Environment" mode="Greedy" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
		</builders>
	</configBuilders>

	<appSettings configBuilders="Environment,MyConfigStore">
		<add key="AppName" value="Console App Demo" />
		<add key="ConnectionString" value="Endpoint=https://appconfig-nopermissions.azconfig.io;Id=WOQ4-l9-s0:IdnT1I5zAPFtAbQUode7;Secret=XXX" />
	</appSettings>
```

```
    class Program
    {
        static void Main(string[] args)
        {
            string message = System.Configuration.ConfigurationManager.AppSettings["TestApp:Settings:Message"];

            Console.WriteLine(message);
            Console.ReadKey();
        }
    }
```

Here is the config which is configured in the appconfig-nopermissions service:

![image](https://user-images.githubusercontent.com/25449039/108043150-a6920900-7038-11eb-9fb3-565feaf0556d.png)

When running Program.cs this is the result

![image](https://user-images.githubusercontent.com/25449039/108043003-75b1d400-7038-11eb-8ad5-fed8ddd610ed.png)

Here is the config which is configured in a different App Configuration service in the same tennant

![image](https://user-images.githubusercontent.com/25449039/108043239-c9bcb880-7038-11eb-8251-a91f9354228a.png)

Not sure how this is possible? 

The service the app is configured to read from is standard tier and the other service is free tier. I'd like to delete the free tier ASAP but wanted to highlight this. 

Thanks, 
Tom

**Comment by jimmyca15** [comment]
@SirElTomato That does seem like odd behavior. My first thought is that the application is referenced a non-updated web.config. Is it possible it was copied into the output and then not updated with your changes?
Were you able to repro this with a fresh project?

**Comment by zhenlan** [comment]
@SirElTomato I don't think your app picks what you set in *appsettings* for `${ConnectionString}`. It picks what is in the environment variable. You likely have an environment variable `ConnectionString` pointing to your second store (*tom-test-app-config*).

**Comment by SirElTomato** [comment]
@zhenlan ah yes you're right. Was a little concerned for a sec. I didn't set this manually, when would it have been set out of interest? 

Thanks
