### ISSUE TITLE
azure-spring-cloud-app-configuration-config source code is gone

### ISSUE THREAD

**Issue by alisharifi01** [Azure/AppConfiguration#463]
Hi
I used to be able to see azure-spring-cloud-app-configuration-config source code on Github via 
https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-spring-cloud-appconfiguration-config. 
It gives 404 now. Where can I reach the source code?

**Comment by zhenlan** [comment]
@alisharifi01 thanks for reporting. Indeed the link is broken. 

@mrm9084, any suggestions?

**Comment by mrm9084** [comment]
@alisharifi01 Sorry about that. We are in the middle of a reshuffle of things that caused the App Config to be temporarily removed from that repo. This is link is for the 1.2.7 version of the docs https://github.com/microsoft/spring-cloud-azure/tree/1.2.7/spring-cloud-azure-starters/spring-cloud-starter-azure-appconfiguration-config.

**Comment by mrm9084** [comment]
The source code is back in master in the SDK repo. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/spring-cloud-azure-appconfiguration-config

**Comment by drago-draganov** [comment]
Fixed
