### ISSUE TITLE
Azure-App-Config Monitoring Integration Options

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [Azure/AppConfiguration#465]
Customer raised an issue in QnA 

 I would like to know what all monitoring options i have with Azure-App-Configuration. Can i send app-config logs and security events to an external monitoring solution like Datadog or Splunk using Event Hub? Our security team would like to know whether we can use App-Config with Datadog which is presently in use in our environment

https://docs.microsoft.com/en-us/answers/questions/275480/index.html

**Comment by zhenlan** [comment]
We are adding support for sending logs to Azure Monitor, which allows receiving logs using Event Hub. @jimmyca15/@shenmuxiaosen, can you please confirm?

**Comment by shenmuxiaosen** [comment]
Yes, currently we are able to send logs to Azure Monitoring and working on support for Log Analytics and Event Hub, which are two major consuming scenario. Once the Event Hub is onboarded, it can work with [external partners](https://docs.microsoft.com/en-us/azure/azure-monitor//partners#datadog) like Splunk and Datadog.

**Comment by MonikaReddy-MSFT** [comment]
@zhenlan & @shenmuxiaosen - THank you for providing your insights. 

Do you have any ETA on when Event hub will be onboarded?

**Comment by shenmuxiaosen** [comment]
This is planed to be onboarded in next quarter.

**Comment by zhenlan** [comment]
This is the same request tracked in #407. Closing.
