### ISSUE TITLE
InternalServerError - Cannot Serve the Request - When retrieving the AppConfiguration and creating Key Value from the API

### ISSUE THREAD

**Issue by jizzaki** [Azure/AppConfiguration#466]
I'm using providers such as Terraform & Pulumi to interact with the API and it appears a breaking change was introduced within the past 10 days from the Azure team. This was also replicated in the Portal.

I've tested this using a service principal with full Admin access to the Azure Portal across multiple subscriptions and accounts and still can't seem to get past this error. 

## Expected behavior
Key value is added to App Configuration.

## Current behavior

Using Pulumi:
` error: cannot check existence of resource '/subscriptions/[subscriptionId]/resourceGroups/test-delete-rg/providers/Microsoft.AppConfiguration/configurationStores/test-delete-appconfig123456/keyValues/keyvalue': status code 500, {"error":{"code":"InternalServerError","message":"Cannot serve the request. Please retry.","additionalInfo":[{"type":"ActivityId","info":{"activityId":"48011ef6-8152-4abf-912c-13ea3c6e9260"}}]}}`

From the Portal:
![image](https://user-images.githubusercontent.com/11037600/108539317-b148da00-7294-11eb-95c9-241f6d1e09d2.png)

**Comment by shenmuxiaosen** [comment]
Hi @jizzaki, this is due to a regression in our side that returned the improper response. The key value you are trying to query does not exist. So it should return 404 instead of 500. We already have the fix and will roll it out in the next couple of days.
