### ISSUE TITLE
Include more detail within raised Microsoft.AppConfiguration.KeyValueModified/KeyValueDeleted events

### ISSUE THREAD

**Issue by JakeRoper4** [Azure/AppConfiguration#468]
Hello,

I'm not sure if this is the best place to raise this question, so feel free to point me towards the correct place if incorrect.

I've recently developed a function app that listens to the KeyValueModified/Deleted events, and found that I could use some more information, especially when it raises events based on some feature flags that I'm working with within the app configuration store.

The scenario that I find myself in, is that we have a custom feature filter within each feature flag, and these feature filters govern whether the feature flag is enabled for specific domains/tenants. Would it be possible for the JSON output to come with the rest of each event? just as values are passed through with configuration items for example.

I would expect these new details to be passed into the Modified/Deleted events like (rough psuedocode):

![image](https://user-images.githubusercontent.com/54897068/108860728-6279a800-75e6-11eb-9055-453cb7ae9117.png)

```
[{
	"id": "84e17ea4-66db-4b54-8050-df8f7763f87b",
	"topic": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/testrg/providers/microsoft.appconfiguration/configurationstores/contoso",
	"subject": "https://contoso.azconfig.io/kv/TestFeatureFlag",
	"data": {
		"key": "TestFeatureFlag",
		"etag": "FnUExLaj2moIi4tJX9AXn9sakm0",
		"featureFilters": [{
			"name": "CustomFeatureFilter",
			"data": [{
				"name": "AllowedValues",
				"value": "[\"string\",\"int\",\"double\"]"
			}]
		}]
	},
	"eventType": "Microsoft.AppConfiguration.KeyValueModified",
	"eventTime": "2019-05-31T20:05:03Z",
	"dataVersion": "1",
	"metadataVersion": "1"
}]
```

**Comment by drago-draganov** [comment]
The primary reason that AppConfiguration provides only identity reference in an EvenGrid event is security. Proper authentication/authorization is always required to access AppConfiguration data. Add to this network level security (Private Link),  AppConfiguration data retention policy at rest, etc. Otherwise, EventGrid pipeline can be used to interfere/bypass these.

**Comment by JakeRoper4** [comment]
In a nutshell, are we saying that this information could not be added due to the reasons above? Or is there something that I can do to allow more information to return from the events?

**Comment by jimmyca15** [comment]
>In a nutshell, are we saying that this information could not be added due to the reasons above 

@JakeRoper4 that is correct. The security design considerations that Drago mentioned prevent the possibility of including the value property of a key-value.
