### ISSUE TITLE
Azure App Configuration Push task does not support Service Principal using cert based authentication

### ISSUE THREAD

**Issue by sharvaridesai123** [Azure/AppConfiguration#469]
I am getting an error "Invalid authentication type. Certificate based authentication is not supported." when using a Service Principal using Cert based authentication to deploy to App Configuration using "Azure App Configuration Push " task in Azure DevOps.

Our company standard is to use ONLY certificates for authentication.   Using the pipeline is the most elegant way to deploy App Configurations and not being able to do it is very disappointing.

Could you please allow SP with cert based authentication to push configurations, using "Azure App Configuration Push " task?

**Comment by jimmyca15** [comment]
Hello @sharvaridesai123 

This would be an enhancement to our existing pipeline task. It isn't a committed item on our roadmap at this point, but we will be sure to respond with updates if we decide to take add this enhancement. I know it isn't as elegant, as you mentioned, but an alternative today is to use the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/create-an-azure-service-principal-azure-cli#certificate-based-authentication) for interacting with Azure App Configuration in a DevOps pipeline.

**Comment by MaryanneNjeri** [comment]
Hello @sharvaridesai123  a new release is out for Azure App Configuration Task version - 3.5.16 and Azure App Configuration Push Task version - 1.4.4, they include the enhancement to support cert based authentication. Please feel free to check it out. In case of any questions please feel free to reach out.
