### ISSUE TITLE
Provide a Consul compatible API

### ISSUE THREAD

**Issue by sjwaight** [Azure/AppConfiguration#47]
Consul is a great open source, platform agnostic offering that is popular with many folks. In the same vein as the Cassandra API capability provided by Cosmos DB it would be great if App Configuration provided a Consul compatible API so existing (or new) app components could leverage Consul clients but benefit from the backend power of App Configuration.

**Comment by mlacouture** [comment]
@sjwaight, thank you for your suggestion, we'll consider it when prioritizing the enhancements to be added to the service.

**Comment by zhenlan** [comment]
We don't have a plan for this. If the plan changes in the future, we can reopen.
