### ISSUE TITLE
spring-cloud-starter-azure-appconfiguration-config does not work with spring boot 2.4.0

### ISSUE THREAD

**Issue by J4cku** [Azure/AppConfiguration#470]
AppConfig does not bootstrap in spring boot 2.4.0

**Comment by mrm9084** [comment]
@J4cku Hi, we know about the issue. We are working on a new release that will work with Spring Boot 2.4.0. We don't have an ETA at the moment but will update this issue with updates.

**Comment by mrm9084** [comment]
@J4cku 1.3.0 has been released and supports Spring Boot 2.4 https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-azure-appconfiguration-config/1.3.0
