### ISSUE TITLE
Java client without Spring

### ISSUE THREAD

**Issue by clarkbreyman-yammer** [Azure/AppConfiguration#471]
My organization uses Dropwizard, not Spring. We want to avoid Spring dependencies. Is there any hope of a Java SDK that wraps the Rest API similar to the rest of the Azure SDK?

**Comment by mrm9084** [comment]
@clarkbreyman-yammer App Configuration has a Library in the Azure SDK that should work, it is what the Spring library uses. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-data-appconfiguration
