### ISSUE TITLE
Question on Storage Redundancy

### ISSUE THREAD

**Issue by giacris82** [Azure/AppConfiguration#472]
Azure AppConfig is a regional service as reported in the [Resiliency and disaster recovery documentation](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-disaster-recovery?tabs=core2x). App Configig storage is completely manged service but anywhere in the documentation is reported kind of azure storage service it leaverages. 
Is this storage a Zone Redundant one or it is a Locally Redundant?

**Comment by zhenlan** [comment]
Good question, @giacris82. To customers of App Configuration, it's more than storage that matters in terms of data redundancy. We don't document the whole list of service dependencies including types of storage as they are just implementation details and could change. To customers, if any part of the service is down, they could be impacted. But I'm glad to share that we are working on Availability Zone support, so look out for "Zone Redundancy" support in App Configuration in the near future for Azure regions that support Availability Zones.

**Comment by giacris82** [comment]
So from customer prospective it does't offer at the moment Zone Redundant support. Since ZR seams to be planned for in the near feature, do you have an issue i can follow?

**Comment by zhenlan** [comment]
Please subscribe to our announcements repo for any future updates
https://github.com/Azure/AppConfiguration-Announcements
