### ISSUE TITLE
Rename key not supported

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#474]
To rename a key with several label values, we need to filter and export key, change key name and import renamed key.
Can we have a simplest method ?

**Comment by zhenlan** [comment]
Key and label are the index of each key-value, so they are not really editable.  If a rename function is provided, it will effectively create a new key-value and delete the old key-value. We discussed this in the past and there were some concerns of confusion it may cause, for example, the newly created key does not carry the history the old key has, a key-value restore will not rename it back to its original key and label, etc.

One alternative approach is to provide a "clone" function, so you can quickly create a new key-value by editing the key or label prefilled from an existing key to be cloned. But afterward, you will still have to delete the old key-value. Will this be something work for you?

(Related to #148)

**Comment by Philippe85** [comment]
Ok, I understand. A "clone" fonction will be perfect, if we can clone a key with all its values and labels.
Thank you.

**Comment by Philippe85** [comment]
Hello,

This issue is always opened. How do you think to deliver this fonctionnality ?

Thanks

**Comment by zhenlan** [comment]
The function is available now in the "Configuration explorer" when you click the triple-dots of a key-value.
![image](https://user-images.githubusercontent.com/10566826/181362734-a332ff88-aa76-41f4-84f1-926655cfe1ed.png)
