### ISSUE TITLE
Is it planned to manage App Service connection strings with App Configuration ?

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#475]
In App Service configuration, we have "Application settings" and "Connection strings". We can Import/export Application settings with App Configuration, but not yet the Connection strings. Is App Configuration planned to manage also the connection strings ?
Thanks

**Comment by zhenlan** [comment]
We don't recommend saving connection strings in App Configuration (Key Vault is recommended), so we don't have a plan to support import/export connection strings from/to App Service.
