### ISSUE TITLE
Support for  Golang & native integration to AKS?

### ISSUE THREAD

**Issue by asilverman** [Azure/AppConfiguration#477]
If you run your application in AKS, how can you sync K8s ConfigMaps with Azure AppConfiguration?
Are there plans to support for Golang at some point?

**Comment by shenmuxiaosen** [comment]
@asilverman Can you clarify how you want to integrate with ConfigMap? Like deployment time or run time? We do support integrating with AKS ConfigMap in deployment time with Helm. [Link](https://docs.microsoft.com/en-us/azure/azure-app-configuration/integrate-kubernetes-deployment-helm).   

For Golang, unfortunately we don't have a plan for it in the short term.

**Comment by RichardChen820** [comment]
@asilverman The AKS integration solution is available now, just for your information if you are still interested.

The quickstart tutorial: https://learn.microsoft.com/azure/azure-app-configuration/quickstart-azure-kubernetes-service
