### ISSUE TITLE
Portal: Bulk Delete Configuration

### ISSUE THREAD

**Issue by Abhra1992** [Azure/AppConfiguration#48]
How does one delete config keys in bulk? Or clear/reset the entire config store?
I tried importing a blank file but it did not work.
Can we have a documented way to do this either via portal or REST API?

**Comment by zhenlan** [comment]
Thanks for the feedback @Abhra1992.

You can use Azure CLI (install with `az extension add -n appconfig`) to delete in bulk. For example, the command below clear the entire config store.
```
az appconfig kv delete --name [YourConfigStoreName] --key * --label *
```
You can use `--key` and `--label` parameters to filter a subset of key-values you want to delete.

The Azure portal currently does not provide a way to delete key-values in bulk.

**Comment by VaclavElias** [comment]
Is this something planned to be in UI? e.g. Checkboxes to select what I would like to delete?

**Comment by zhenlan** [comment]
Not planned, but we could if people find it useful to have the bulk deletion in the portal too.

**Comment by VaclavElias** [comment]
Yes, it is difficult to say in the early stage if this is going to be desired. I am learning how this App Configuration works so I am adding and deleting. But once I learnt/set it up all as I want then probably I might not bother about deleting too much.

However, in this case I saw in App Service that you can edit All by clicking on Advanced Edit which opens configuration in json editor, so I could do bulk updates and bulk delete there :)

So maybe it makes sense to have also here Advance Edit? :)

**Comment by kipergil** [comment]
Just tried the service and find out there is no bulk delete feature. You should really consider bulk delete and bulk edit in order to make config management easier.

You should also let the user to edit all configs via json editor which is already available in webapp configuration page (advanced edit like below).

![json-edit](https://user-images.githubusercontent.com/1663748/64480761-90d2b000-d1c5-11e9-81e9-e742fa0ca8fa.png)

**Comment by KirubelTolosa** [comment]
It would be very useful to have a bulk-delete option. Having not known the CLI command before this post, I had to delete the entire store to start over.

**Comment by Bubelgin** [comment]
Same situation, any kind of bulk operations would be useful like bulk delete or add a label for all records, currently, you have to add labels manually on each record or rely on import/export functionality which is not always helpful.

**Comment by crhistianramirez** [comment]
> Thanks for the feedback @Abhra1992.
> 
> You can use Azure CLI (install with `az extension add -n appconfig`) to delete in bulk. For example, the command below clear the entire config store.
> 
> ```
> az appconfig kv delete --name [YourConfigStoreName] --key * --label *
> ```
> 
> You can use `--key` and `--label` parameters to filter a subset of key-values you want to delete.
> 
> The Azure portal currently does not provide a way to delete key-values in bulk.


Trying this in the azure cloud cli and I get this very strange error:
> UnrecognizedArgumentError: unrecognized arguments: nginx.conf

**Comment by zhenlan** [comment]
@avanigupta is what @crhistianramirez reported expected?

**Comment by avanigupta** [comment]
Hello @crhistianramirez, thanks for bringing this to our attention. This issue is confined to only Azure Cloud Shell and we are working with them to resolve this. Meanwhile, you can [install any local Azure CLI client](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) to run the bulk delete command:

`az appconfig kv delete --name [YourConfigStoreName] --key * --label *`

**Comment by mrjamiebowman** [comment]
This would be a really nice feature to have in the UI..

**Comment by carlblanchard** [comment]
Any news on the development of this feature? it's been sat in planned for quite some time now?

**Comment by briiipr** [comment]
I think this functionality should be available in the UI. Seems pretty UX-unfriendly at least for me...

**Comment by MaryanneNjeri** [comment]
We have included the bulk delete functionality in the UI in the latest Portal version. Please give it a try and feel free to reach out in case of anything.

**Comment by carlblanchard** [comment]
Nice, Yeah I have the checkboxes :) Happy Days

**Comment by mrjamiebowman** [comment]
Such a great feature! This will be heavily used in environments, especially like dev where configuration may change drastically.

**Comment by kipergil** [comment]
Well done guys. It's very nice to see that this feature is implemented almost after 3 years 👍 better late than never 😁
