### ISSUE TITLE
Add multi line input field for application/json content

### ISSUE THREAD

**Issue by theo-albers** [Azure/AppConfiguration#482]
It's wonderful that we now have application/json content support, so we can enter JSON as configuration value. The input textbox is however still a single line input field:

![image](https://user-images.githubusercontent.com/9417380/111159506-7424ee80-8599-11eb-818a-dfbb78c86ad3.png)

So what I do is edit my configuration in a regular editor, copy and paste the value from the editor into the AAC input field and hope for the best. This is sub optimal. I had a case where I missed the closing bracket. AAC didn't consider the value being valid JSON, which is good. It took me some time to figure out that was the case. Life could have been much easier when the JSON value was shown in a multi line editor. 

For now it would be good enough having a multi line text box. Nice to have would be a multi line show values option. Nice to have would be JSON input validation when the content type is application/json.

**Comment by drago-draganov** [comment]
That's a great  point, @theo-albers

We are actively looking into improving that experience. Stay tuned.

**Comment by cablooshe** [comment]
Multi line textboxes have now been added for the portal value box. We'll follow up later on the JSON content support.

**Comment by theo-albers** [comment]
I checked it and it works, super!
![image](https://user-images.githubusercontent.com/9417380/113671366-884e9e00-96b6-11eb-9ae3-dc78cada8315.png)

**Comment by theo-albers** [comment]
I checked it and it works, super! 
![image](https://user-images.githubusercontent.com/9417380/113671515-bfbd4a80-96b6-11eb-86e5-3bc6094cb690.png)
