### ISSUE TITLE
Cannot access AppConfiguration with System managed Identity using DefaultAzureCredential

### ISSUE THREAD

**Issue by griddy777** [Azure/AppConfiguration#483]
Hi guys, I have a functionApp (V3) that is trying to access App Configuration using the DefaultAzureCredential. My System managed user is switched on and has the "App Configuration Data Reader" role.  I am running this locally in debug hence the need for a default credential. I also have multiple Tenants so I had to set the VisualStudioTenantId and SharedTokenCacheTenantId  on DefaultAzureCredentialOptions. 

The credential works when accessing Key vault to fetch a secret but it needs SharedTokenCacheTenantId   to be set. 
When connecting to App configuration I get a "Service request failed. Status: 403 (Forbidden).

Thank you for the assistance!
Andre

`public override async void ConfigureAppConfiguration(IFunctionsConfigurationBuilder builder)
{
	var credOptions = new DefaultAzureCredentialOptions();

	var tenantId = Environment.GetEnvironmentVariable("Tenant_Id");

	credOptions.VisualStudioTenantId = tenantId;
	
	credOptions.SharedTokenCacheTenantId = tenantId;

	var cred = new DefaultAzureCredential(credOptions);

	/*Works but requires SharedTokenCacheTenantId*/
	var secretClient = new SecretClient(new Uri(vaultURI), cred);
	var secret = await secretClient.GetSecretAsync("<secret name>");

	/*Does not work - forbidden*/
	builder.ConfigurationBuilder.AddAzureAppConfiguration(options =>
	{
		options.Connect(new Uri(appConfigURI), cred);
		
	}).Build();

}`

**Comment by zhenlan** [comment]
@griddy777 the reason you got 403 is that you didn't grant the credential you used locally proper permission to your App Configuration instance. In your case, you will need to grant the identity from your SharedTokenCacheCredential the "App Configuration Data Reader" role. The managed identity will only work when you deploy your Function app to Azure.

**Comment by griddy777** [comment]
Thank you, that resolved the 403. My VS user has also been given the role. 
One last thing, although I inject IConfiguration in a function, it does not find any keys that only live in my "App Configuration". 
Any suggestions?
