### ISSUE TITLE
Springboot links are broken

### ISSUE THREAD

**Issue by sovietspy2** [Azure/AppConfiguration#486]
Hi!

I've been just looking for some examples and found out that in the readme.md most of the springboot links are broken.

for example: [this](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/azure-spring-cloud-appconfiguration-config-web) this leads to nowhere.

**Comment by zhenlan** [comment]
@mrm9084 any suggestions?

**Comment by mrm9084** [comment]
@sovietspy2 Hi, sorry about that things are in the middle of a renaming. You can find our source here. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/appconfiguration/spring-cloud-azure-appconfiguration-config-web
