### ISSUE TITLE
[Bug] Label bug in configuration explorer 

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#488]
I have a config with 3 labels as below. 
![2021-03-19 15_08_06-appcs-revoke-dev - Microsoft Azure](https://user-images.githubusercontent.com/25449039/111801735-22e06c00-88c5-11eb-9622-2f1e6d9311cc.png)

I then add a value for a 4th label to the same config
![2021-03-19 15_08_24-appcs-revoke-dev - Microsoft Azure](https://user-images.githubusercontent.com/25449039/111801746-24aa2f80-88c5-11eb-8a9a-ab7c345a80c8.png)

I then delete the top value for label 'eu-dev', after deletion the name of the labels is wrong
![2021-03-19 15_08_34-appcs-revoke-dev - Microsoft Azure](https://user-images.githubusercontent.com/25449039/111801751-25db5c80-88c5-11eb-91c9-0a5140234c4e.png)

I then refresh using the refresh button in the portal and the labels names correct themselves. 
![2021-03-19 15_08_41-appcs-revoke-dev - Microsoft Azure](https://user-images.githubusercontent.com/25449039/111801759-270c8980-88c5-11eb-85a5-e3d965c6e4e9.png)

**Comment by jiayi11** [comment]
Thank you for reporting the bug. The fix is in progress.

**Comment by jiayi11** [comment]
The fix is already checked in, it is planned to be deployed to all regions in about 2 weeks.
