### ISSUE TITLE
[Request] Don't make the whole line for the top level label clickable, change to just the arrow instead 

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#489]
When trying to copy data or similar from the top level label of a config, its annoying that it expands/collapses.

**Comment by zhenlan** [comment]
@SirElTomato thanks for sharing feedback.

I can see people may have mixed requests for this function. When you copy the data, are you trying to copy a particular field, eg., the value, or trying to copy the whole line? I am trying to see if we can improve the copy experience.

cc: @AlexandraKemperMS

**Comment by SirElTomato** [comment]
@zhenlan no problem. I am usually trying to copy either the key or the value. A "copy" icon next to the key and next to the value (when values are shown) might work well. 

Thanks

**Comment by zhenlan** [comment]
@SirElTomato thanks for the suggestion.

This will need some design and we may be limited by what the portal framework can do. Loop in more folks from the team @jiayi11 @AlexandraKemperMS

**Comment by jiayi11** [comment]
The rows in config explorer are not clickable now. I'm closing this as it doesn't seem like an issue anymore.
Regarding copy values from the grid, you can either double click the value and Ctrl-C, or use the copyable icons in edit key-value blade.

We looked into adding on-hover copy icons in every row of the grid but didn't find a good solution. Will look back into this if there're more customer feedback for easier copy experience from the grid.
