### ISSUE TITLE
Can AppConfiguration be used with Azure VNET (directly or service endpoint)?

### ISSUE THREAD

**Issue by osudude** [Azure/AppConfiguration#49]
If not, are there plans to add this functionality?

**Comment by zhenlan** [comment]
Hi @osudude, the AppConfig service does not support Azure VNET currently, but it is definitely on our roadmap. Is this a blocker for you?

**Comment by osudude** [comment]
No, just unfortunate.  Will have to stick with app service environment variables 😱

**Comment by zhenlan** [comment]
In case anyone comes across this thread in the future and have the same request, please vote at
https://feedback.azure.com/forums/920545-azure-app-configuration/suggestions/37430311-allow-vnet-integration-support
