### ISSUE TITLE
[Feature request] UI suggestions

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#493]
When scoped using a search such as "MyAPI:Azure:*" it might remove the prefix from the key name in order to make it more readable, this would be useful because the names of my keys are getting quite long e.g. I have settings like: "MyAPI:Azure:ServiceBus:SettingName". Optional 'hide prefix' checkbox might work. 

Also it would be good if the column separator used to expand the column width was double-clickable to auto resize. 

Thanks, I'm enjoying using Azure App Configuration.

**Comment by jiayi11** [comment]
Hi @SirElTomato, thanks for your feedback. I'll bring the first suggestion to our UI designer. 
For grid resizing, I don't see a solution right now cause we are building on azure portal framework and there's some limitation in the control. I can help to follow up with their team to see if there're any suggestions!

**Comment by zhenlan** [comment]
Not exactly the same, but I hope the hierarchical view support (#537) can help this scenario too.

**Comment by zhenlan** [comment]
The hierarchical view support has been completed and rolled out. Please let us know if it helps.
