### ISSUE TITLE
[Feature request] Add option in compare tool to show only configs which are missing 

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#495]
Please can you add another compare option which allows you to show only the configs which are missing between labels. 

In my case I am comparing dev environment with uat environment and expect many of the configs to be different, but I want to know if any are missing which is hard to tell using just the icons.

**Comment by jiayi11** [comment]
Hi @SirElTomato, could you clarify what do you mean by "missing"? If I understand it correctly, lots of the key-values you are comparing have the same key and label, but different values. You want an option to ignore these key-values in compare result, and only show those with different keys or labels?

**Comment by SirElTomato** [comment]
Hi @jiayi11
I'm using labels to set config for different environments e.g. dev, UAT. By "missing" I mean that a config isn't set for a label (environment). 
I want to be able to see when I have a config set for the 'dev' label but I don't have that config set for the 'uat' label. If there was a value set for the 'dev' label but not the 'uat' label I would class that as missing. 

When using the comparison tool, this is currently shown by the arrow icon to indicate that the value is set in one label but not in the other. 

Hopefully that is more clear, but let me know if you need more info

**Comment by jiayi11** [comment]
In scenario like the following, the feature request is to have an option to filter out "key", "key1" and "key2" from the comparison result. Only show those with different keys.
![image](https://user-images.githubusercontent.com/14067510/113223487-21586180-923e-11eb-9f1a-6c1f65a31eff.png)

**Comment by cablooshe** [comment]
We've deployed a change to the compare blade. If you want to only see configs that are fully different between the store, select "Hide all matching keys" in the available options.

**Comment by SirElTomato** [comment]
Thanks @cablooshe, looks good to me!
