### ISSUE TITLE
[Feature request] Add search functionality as well as the Keys filter. 

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#500]
The keys filter is great but sometimes I just want to be able to find a config by searching for a part of the key name which is in the middle of the key name without having to type out the whole prefix exactly. 

e.g. I want to find 'MyAPI:Persistence:DatabaseName' by searching for 'database' without having to type out the prefix.

**Comment by drago-draganov** [comment]
We had that feature on the service side during preview and decided to take it out due to perf complications. 
https://github.com/Azure/AppConfiguration/issues/342

If the result set isn't large, we could consider some client side filtering in portal. Will that work for you?

**Comment by SirElTomato** [comment]
@drago-draganov yes I think some client side filtering would do the job here. I mostly want to be able to do this to quickly find one config, not for working on a filtered set of configs. e.g. be able to quickly find the sentinel key instead of having to type the whole key including case-senstive prefix

Thanks

**Comment by drago-draganov** [comment]
Thanks! 

@jiayi11 is this something we can consider on portal?

**Comment by jiayi11** [comment]
Yes, we can consider adding client side filtering.

**Comment by SirElTomato** [comment]
Any update on this? It's quite a pain having to type out the whole prefix and try and remember the hierarchy of a key name when I just want to search for "email"

**Comment by jiayi11** [comment]
@SirElTomato  This is already in planned. I'll let you know once I have more updates.

**Comment by SirElTomato** [comment]
Any update on this? Searching is the worst thing about this service.

**Comment by SirElTomato** [comment]
Any update? I want to switch all my apps to Azure App Configuration but all my colleagues hate the poor search functionality

**Comment by zhenlan** [comment]
The search feature is available in Portal now.
