### ISSUE TITLE
[Feature request] Improved key filtering

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#501]
It would be useful if the portal could detect the prefixes of keys and have the 'Keys' search option also be a multi-select box which is pre-populated with the prefixes for you to select/unselect. 

It might also be useful to be able to filter by 'application' first and then prefix.

e.g. I have keys for different applications 'MyAPI' and 'MyWebApp' which look like this: 

'MyAPI:Persistence:DatabaseName'
'MyWebApp:UI:BackgroundColour'

so it would be useful to have a multi select box for 'application' to select 'MyAPI' and/or 'MyWebApp'

Not entirely sure how this might look but happy to dicuss more

**Comment by cablooshe** [comment]
Easier key organization is definitely on our minds. We're currently have a hierarchy view in the works where you will be able to sort keys into deeper depths by your prefixes. I believe it should organize your keys in a similar way to what you're describing.

**Comment by SirElTomato** [comment]
@cablooshe Sounds good, I look forward to seeing it in the future

**Comment by zhenlan** [comment]
The support for the hierarchical view is tracked in #537. Close this out.
