### ISSUE TITLE
Connect Spring boot app to App config store using service principal.

### ISSUE THREAD

**Issue by akansha1103** [Azure/AppConfiguration#502]
I want to connect Spring boot application to Application config store using service principal. I have this URL for the sample of the same but it shows 404 Not found. 

https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-appconfiguration-sample

Could you please where this sample code have been moved to? Can I get the URL for the sample code to connect Spring boot application to Application config store using service principal?

**Comment by mrm9084** [comment]
Hi, sorry for the confusion. We are in the middle of renaming the package so the current link should be https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-appconfiguration-sample.
