### ISSUE TITLE
Task Hangs without any logs being written

### ISSUE THREAD

**Issue by andreacapriplexure** [Azure/AppConfiguration#503]
Task just hangs indefinitely, has been working in the past. Raw logs are not different.
![image](https://user-images.githubusercontent.com/50006394/114629410-a21e5f80-9d0c-11eb-976b-f7ddc1a0f015.png)

**Comment by Anne56njeri** [comment]
Hi @andreacapriplexure, are you running the task on Microsoft-hosted agents or a self-hosted agent? Also, could you share your debug logs to help in investigating the issue? Thank you.

**Comment by andreacapriplexure** [comment]
Hi sorry I figured the issue was that the app configuration was throttling requests since we went over the cap. Maybe some better logging for this would be helpful.

**Comment by Anne56njeri** [comment]
Thank you @andreacapriplexure, for the feedback will work on that. Please feel free to reach out in case of any other questions.
Thanks,
Maryanne
