### ISSUE TITLE
App configuration ARM template 

### ISSUE THREAD

**Issue by shilpasrinivas** [Azure/AppConfiguration#505]
I am trying to set the Audience values from portal and I don't want these values to be overriden by ARM deployment. But I am just not able to do that, is there anyway to achieve this.

The Users and Groups list is very dynamic and I don't want that to be part of code base, but the default filtering and percentage is constant so I want this to be set through ARM template. 

But I don't get this flexibility, if I try to configure the audience withtout user and group, then it gets overriden by default and everything configured in portal gets wiped out. 

`"featureFlagValue": {
            "id": "[parameters('featureFlagKey')]",
            "description": "Your description.",
            "enabled": true,
            "conditions": {
                "client_filters": [
                    {
                        "name": "Microsoft.Targeting",
                        "parameters": {
                            "Audience": {

                                "DefaultRolloutPercentage": 0
                            }
                        }
                    }
                ]
            }
        }`

**Comment by zhenlan** [comment]
Each feature flag including the targeting audience information is saved as one single entry, so any changes to it will overwrite the feature flag. So what you observed is as currently designed. With that being said, I do see you have a reasonable scenario. That is something for us to look further into in the future.

For now, I wondering if it will be possible for you to read the feature flag, update it and save it back in your process.
