### ISSUE TITLE
How to create a key vault reference using Azure App Configuration Push

### ISSUE THREAD

**Issue by asagarw** [Azure/AppConfiguration#508]
I am unable to create a key vault reference using a "Azure App Configuration Push" task even though service connection has access to the key vault. I am using the following value in the json input. Is there any documentation on the same?

"Key_Name": { "uri": "https://keyvault_name.vault.azure.net/secrets/secret_name" }

**Comment by zhenlan** [comment]
@asagarw can you please set content-type as `application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`?

**Comment by asagarw** [comment]
> @asagarw can you please set content-type as `application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`?

Thanks this worked. 👍
