### ISSUE TITLE
Trimmed whitespaces in Configuration Explorer

### ISSUE THREAD

**Issue by wolkowsky** [Azure/AppConfiguration#509]
I had an issue with one of our apps because of having whitespace at the beginning of the value, unfortunately, it's hard to find these in Portal because in the list view these are trimmed. So in order to find it, you have to go to the edit screen or export all of them (don't know if there's any other way).

![image](https://user-images.githubusercontent.com/9864208/115559814-53486b00-a2b4-11eb-8a22-bf3288b45c05.png)

Where's in reality one of the values looks like it:

![image](https://user-images.githubusercontent.com/9864208/115561571-ff3e8600-a2b5-11eb-82f3-3b7ac706821e.png)

Probably these whitespaces should be shown in the list too. So it would be easier to maintain it.

**Comment by zhenlan** [comment]
@jiayi11 I remember this was a regression and fixed. Empty spaces are highlighted with dots. Can you please confirm?

**Comment by zhenlan** [comment]
@jiayi11 can this issue be closed?

**Comment by jiayi11** [comment]
Yes this is fixed
