### ISSUE TITLE
A key with leading/trailing space creates a "duplicate" that is hard to distinguish

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/AppConfiguration#51]
I had both a key `"Slack:ReportWebHook"` and a key `" Slack:ReportWebHook"`. In portal, they are indistinguishable unless use Azure CLI to get the keys exported as JSON with values surrounded in double quotes.

![image](https://user-images.githubusercontent.com/1309622/56635267-4390e000-6622-11e9-8e7c-3dae8e9846f6.png)

**Comment by SeanFeldman** [comment]
Just noticed it's been fixed. Thanks!
![image](https://user-images.githubusercontent.com/1309622/57351611-cab07e80-711f-11e9-9bf2-cefd01eb5eec.png)

**Comment by zhenlan** [comment]
Yes, this is fixed in the update of the portal this week too. Thanks for your feedback and keep them coming 😄.
