### ISSUE TITLE
Old key vault connection works, new doesn't

### ISSUE THREAD

**Issue by MRVDH** [Azure/AppConfiguration#511]
When starting the .NET Core app an error is thrown when trying to setup the app configuration.

This is the code that I use:
```C#
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                        .UseStartup<Startup>()
                        .ConfigureAppConfiguration((ctx, builder) =>
                        {
                            builder.AddAzureAppConfiguration(options =>
                            {
                                var appConfigConnectionString = "Endpoint=https://XXX.azconfig.io;Id=XXX;Secret=XXX=";
                                options.Connect(appConfigConnectionString).ConfigureKeyVault(kv =>
                                {
                                    kv.SetCredential(new DefaultAzureCredential());
                                });
                            });
                        })
                        .UseSerilog();
                });
```

Below the output on startup. As you can see in the Content part, it expects one of the following users. However, as you can see in the Headers part, that user is actually given.
```
Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException: Key vault error. ErrorCode:, XXX--XXX, Label:, Etag:XXXPoOq, SecretIdentifier:https://XXX.azure.net/secrets/XXX
 ---> Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)

Content:
{"error":{"code":"Unauthorized","message":"AKV10032: Invalid issuer. Expected one of https://sts.windows.net/XXXc022/, https://sts.windows.net/XXX255a/, https://sts.windows.net/XXX31f4/, found https://sts.windows.net/XXX8982/."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
WWW-Authenticate: Bearer authorization="https://login.windows.net/XXXc022", resource="https://vault.azure.net"
x-ms-keyvault-region: westeurope
x-ms-client-request-id: XXXe2a
x-ms-request-id: XXX4da
x-ms-keyvault-service-version: 1.2.265.0
x-ms-keyvault-network-info: conn_type=Ipv4;addr=XXX;act_addr_fam=InterNetwork;
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Date: Wed, 28 Apr 2021 09:34:05 GMT
Content-Length: 345
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureKeyVault.AzureKeyVaultSecretProvider.GetSecretValue(Uri secretUri, CancellationToken cancellationToken)
(...)
```

It is important to note that I am able to connect to the Key vault without any problems by using this method:
```C#
            var azureServiceTokenProvider = new AzureServiceTokenProvider(connectionString);
            var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback
                )
            );

            configurationBuilder.AddAzureKeyVault(
                uri,
                keyVaultClient,
                new DefaultKeyVaultSecretManager()
            );
```

### Context
We had appsettings in the project that we moved to azure app configuration. We already used the azure key vault, but now we want to get both the app config and key vault values from azure, instead of only the key vault values. The method in the code block above for getting the key vault values works fine, but the azure app config + key vault method at the top does not.

Using .NET Core 3.1 and the latest azure app configuration package.

**Comment by MSGaryWang** [comment]
Looks the "DefaultAzureCredential" can't find the way to authenticate the request with the tenant id where your key vault belongs to. You might try different TokenCredential which could provide the capability to retrieve the token.

**Comment by MRVDH** [comment]
Thanks @MSGaryWang, I tried them earlier but couldn't get them to work. I can give it another try.

Will there be a possibility to use a connection string in the future? Since that is something that works for sure (as seen in the last code block).

**Comment by MRVDH** [comment]
From what I read in the docs VisualStudioCredential should be doing something similar to what I do with the connection string. However, this throws the same error as seen above.

**Comment by MSGaryWang** [comment]
Depends on how you want to do the authenticate and you might just use ClientSecretCredential, ClientCertificateCredential or other ways you could specify tenant id with. Without doing this and it might just use default or the one you had signed with.

**Comment by zhenlan** [comment]
@MRVDH please let us know if you have further questions. Closing for now.

**Comment by MRVDH** [comment]
Hi @zhenlan , I still haven't gotten it to work, and it seems I'm not the only one with this issue. https://github.com/Azure/azure-cli/issues/11871
Could it be related to this?

**Comment by zhenlan** [comment]
Hi @MRVDH, as noted in [App Authentication client library for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication), the usage of `AzureServiceTokenProvider` is no longer recommended with new Azure SDKs. There is also a [migration document](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration) that you may like to check out so you can see what's proper replacement for you in Azure.Identity TokenCredential.

With that being said, maybe as an intermediate step for you, you may like to check out the [AzureAppConfigurationKeyVaultOptions.SetSecretResolver](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationkeyvaultoptions.setsecretresolver?view=azure-dotnet-preview) API. Basically, you can implement the secret resolver by using any libraries by yourself. This [github issue](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/209) has some examples of how to use it.

Hope this helps.

**Comment by MRVDH** [comment]
Hi @zhenlan, Thanks for your reply. I have seen and tried the samples. Unfortunately the secret resolver still relies on the new Azure.Identity TokenCredential classes, which produce the same error.

Someone else is using exactly what I use and is running into exactly the same problem, but they posted it in another repo: https://github.com/Azure/azure-cli/issues/11871#issuecomment-843031145
Please see the answer of @fouufi there.

I'm still unable to determine if the problem lies in this library or if this library uses the azure cli and the azure cli has a problem.

**Comment by zhenlan** [comment]
@MRVDH just want to make sure it's clear. The Secret Resolver takes an input of string, which is the secret identifier URI and it returns a string, which is the value of the secret. You can implement anything in the middle. It does not rely on Azure.Identity.
