### ISSUE TITLE
Getting ##[error]Failed to parse with json file

### ISSUE THREAD

**Issue by mslentz** [Azure/AppConfiguration#513]
Hi,  I'm working in Azure Gov and I'm trying to push my config json file to an App Config service and I keep getting an error:

 ##[error]Failed to parse: .......path to file

the file looks like this:

{
     "Key1":  "value"
}

I am using Azure Pipelines in our DevOps instance.  The pipeline is using a service principle that has permissions to the resource group (it is successfully deploying to an app service) and has the "App Configuration Data Owner" role on the config service.  

The error is a bit non-specific, do you have any ideas on what I can do to further troubleshoot this?

**Comment by MaryanneNjeri** [comment]
Hi @mslentz, could you share the format of your json file, which could have key and value masked and I can use the file to repro the issue?

**Comment by MaryanneNjeri** [comment]
@mslentz, also check if the config json file contains any trailing commas,  can be the cause of the error sometimes

**Comment by mslentz** [comment]
I discovered my issue was with spaces in the path to the file.  Thanks for your help.

**Comment by zhenlan** [comment]
@MaryanneNjeri thanks for looking into this. Just curious, won't it work when there are spaces in the path?

**Comment by MaryanneNjeri** [comment]
I tried it on my end, if the space is present in the file path something like this `$filepath  /configFile.json`, the error presented  is
`##[error]An unexpected error occurred. ENOENT: no such file or directory, open 'path to file' `, but if the space is present in the file name, `config File.json` and the path is `$filepath/config Files.json` it works, maybe @mslentz  could confirm where the spaces are in the filepath ?

**Comment by mslentz** [comment]
I did have spaces in my file path.  I changed to an AZ CLI command and was able to publish a simple json file: {"Key1": "value"} 

I am using this command:
az appconfig kv import -s file --format json --path $file   --separator . --depth 2  --label Development --auth-mode login --endpoint https://xxxxxx --yes

I just added my actual config file:

{
    "ActionCenterDiscussionFetchDays": "30",
    "ActionCenterNotificationFetchDays": "14",
    "AllowedHosts": "*",
    "EnableHelpPage": "true",
    "Logging:LogLevel:Default": "Information",
    "Logging:LogLevel:Microsoft": { "Hosting": { "Lifetime": "Information" } },
    "ResultReplayer": {
      "Enable": "false",
      "RemoveFromKey": "...."
    },

    "api": {
      "Password": "",
      "UserPropertyCacheLengthInMinutes": "0",
      "orgServiceUri": "https://...",
      "username": "xxxx"
    },
    "email": {
      "MailFrom": "xxxx",
      "SMTPServer": "xxxx",
      "SMTPServerEnableSsl": "false",
      "SMTPServerPort": "xxx",
      "SMTPServerUsername": "xxxx",
      "Support": "",
      "disableWorkerService": "false",
      "mailBody": "xxxxxxxxx",
      "mailSubject": "xxxxxxx"
    },
    "form2": { "version": "2" },
    "form3": { "version": "2" },
    "form4A": { "version": "2" },
    "ida:ADFSMetadataCRMApi": "https://xxxxxx",
    "ida:WtrealmCRMApi": "https://xxxxxxxx",
    "owin:AutomaticAppStartup": "true",
    "web": {
      "ApplicationInsights:InstrumentationKey": "xxxxx",
      "AzureKvUri": "https://xxxxxx",
      "AzureWebAppClientId": "xxxxx",
      "AzureWebAppTenantId": "xxxxx",
      "EfsapDbConnStringUrl": "xxxxxxxxxx",
      "HomeRealm": ""
    }
  }

and the CLI is giving an error that says: The input is not a well formatted json file.  I'm not seeing the problem, can you help?

**Comment by avanigupta** [comment]
@mslentz, I tried importing the exact contents of your JSON file using the same command that you are using, and I'm not getting any error. Can you try to format the file you're using with any JSON formatter and see if there's a syntax issue on your side?

**Comment by avanigupta** [comment]
Thanks for bringing this to our attention @mslentz. The error turned out to be due to the presence of a non-ASCII character in the JSON file being imported. We are working on supporting the import of all unicode characters using CLI.

**Comment by zhenlan** [comment]
Great. @MaryanneNjeri, you will fix the 'space in path" issue too?

**Comment by ctvanzandt42** [comment]
I'm also having this issue without any special characters in my JSON file. When I use the Azure CLI, it lets me import with the same file, but the pipeline task throws this every time.

**Comment by MaryanneNjeri** [comment]
Hi @ctvanzandt42 , could you share your json file, which could have key and value masked and I can use the file to reproduce the issue?

**Comment by ctvanzandt42** [comment]
Sure! So here's how I'm using the task: 

`- task: AzureAppConfigurationPush@1
  displayName: 'Push Configuration'
  inputs:
    azureSubscription: '<service principal here>'
    ConfigstoreName: '<config name served by Terraform>'
    ConfigurationFile: 'configuration.json'
    Separator: ':'
    Depth: '2'
    Strict: false`
    
And my JSON looks like this:

`{
  "member-info-cb5ad5d2-722a-46e6-9159-dcb23cd39621-someKey": "32494824",
  "member-info-cb5ad5d2-722a-46e6-9159-dcb23cd39621-someOtherKey": "234324,234234,234234"
}`

Values are not accurate obviously, and I'm also purposely not using hyphens as the separator. Right now, I'm just trying to get these two KV pairs pushed, I can flatten properly later.

**Comment by MaryanneNjeri** [comment]
@ctvanzandt42 I tried using your file with the azure app configuration push task, it succeeded on my end 
<img width="947" alt="73260A47-506A-4890-A8A0-FD0900B44A60" src="https://user-images.githubusercontent.com/33903727/117887300-c724d480-b2b0-11eb-814c-1bba3917bcf2.png">
Could try check that the json file has no syntax issues?

**Comment by ctvanzandt42** [comment]
Can you share how the task looks? That is the exact JSON I'm pushing, with a few strings substituted. Again, it's valid JSON and it works pushing from the CLI.

**Comment by MaryanneNjeri** [comment]
Yes let me share how the task looks like from my end.

**Comment by MaryanneNjeri** [comment]
version: 1.3.4
  displayName: 'azure app config task'
  inputs:
    azureSubscription: 'service principal '
    ConfigstoreName: 'config store name’
    Configuration file path: 'config1.json'
    Separator: ':'
    Depth: '2'
    Strict: false

**Comment by ctvanzandt42** [comment]
Hey Maryanne, that's exactly how the task looks on my end. Very weird; I ended up doing this manually, which is obviously not ideal for production, but had to be done. I'd love to revisit this if you all find there's a bug in here, I'm happy to help you all battle-test this if need be.

**Comment by MaryanneNjeri** [comment]
@ctvanzandt42 will definitely reach out if we find a bug. Please feel free to reach out incase of anything.

**Comment by MaryanneNjeri** [comment]
Hi, @ctvanzandt42  a new release is out for Azure App Configuration Task version - 3.5.16 and Azure App Configuration Push Task version-1.4.4, with the fix that gives more information about the error message above, please feel free to check it out. In case of any questions please feel free to reach out :).

Thanks,
Maryanne

**Comment by ctvanzandt42** [comment]
Wonderful, Maryanne! Let me know when the release notes are posted, I don't see them. Looking forward to implementing the fix.

**Comment by MaryanneNjeri** [comment]
Awesome will let you know once the release notes are posted.

**Comment by MaryanneNjeri** [comment]
@ctvanzandt42  the release notes for this fix were posted, [AzureDevOpspipelineExtension](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPipelineExtension.md) and [AzureDevOpsPushPipelineExtension](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPushPipelineExtension.md)

**Comment by zhenlan** [comment]
@MaryanneNjeri can this be closed?

**Comment by mslentz** [comment]
> @MaryanneNjeri can this be closed?

Yes, thank you so much!
