### ISSUE TITLE
Cannot set publicNetworkAccess  to 'Disabled' until a privateEndpoint is bound to the resource

### ISSUE THREAD

**Issue by stweb1963** [Azure/AppConfiguration#514]
Using ARM deployments

We are attempting to deploy an appConfiguration with a privateEndpoint but cannot set the publicNetworkAccess flag to 'Disabled' because the you need the resource to exist before adding the PLE

We are in a catch 22

We would need to:
- deploy the instance with publicNetworkAccess Enabled
- deploy the PLE 
- return to the resource to set publicNetworkAccess to 'Disabled'

We need to be able to perform this delivery without the 3rd step

![image](https://user-images.githubusercontent.com/57627618/117144551-0ec2d200-ad80-11eb-9323-52d43ee6d7e3.png)

**Comment by jimmyca15** [comment]
@stweb1963

Creating an App Configuration instance with `publicNetworkAccess` set to disabled is temporarily blocked. Previously, this flag did nothing unless the configuration store had a private endpoint assigned to it. Any App Configuration instances that were previously created with `publicNetworkAccess` set to disabled behaved the same as instances with `publicNetworkAccess` set to enabled.

If you wish to disable public network access, you can:
1. Create an instance with `publicNetworkAccess` enabled.
2. Assign a private endpoint to the newly created instance
3. Set `publicNetworkAccess` to disabled

It sounds like this solution is something you already considered. Is there a reason it doesn't work for you?

cc @MSGaryWang

**Comment by stweb1963** [comment]
This appear to contradict what @zhenlan had recently communicated

As I understood, if we enable a Private Endpoint on an App Config resource, the default for publicNetworkAccess to be overriden as 'Disabled' and that we would need to apply 'Enabled' to explicitly allow for publicNetworkAccess

Requiring the additional #3 step would not be required

**Comment by jimmyca15** [comment]
That's correct. When a private endpoint is assigned to an App Configuration instance, if `publicNetworkAccess` is not set then the default behavior is deny access from public networks. Step 3 is only necessary if you want to explicitly set that property to disabled.
