### ISSUE TITLE
[Feature request]  Add Prefix on Feature Flags, namespacing, and import/export

### ISSUE THREAD

**Issue by riaadh** [Azure/AppConfiguration#519]
Hello, 
Could you add the prefix on feature flags ? so it's consistent with the way it's working on normal configuration.
Also it's not possible to have this kind of feature flag  MyApp:featureFlag since the : is not allowed in the name of the feature flag 

Thank you

**Comment by jimmyca15** [comment]
Hello @riaadh. A few questions to make sure I know what you're looking for. Are you using feature flags with one of our client libraries? Is this the type of prefix you are using "MyApp:"?

**Comment by riaadh** [comment]
> Hello @riaadh. A few questions to make sure I know what you're looking for. Are you using feature flags with one of our client libraries? Is this the type of prefix you are using "MyApp:"?

Hello, 
I am using azure app configuration ( key values and feature flags) with c# asp.net core
My problem is there is no consistency in the azure portal and in the SDK between keys and feature flags
I explain: when using key I structure my keys like this (the way the documentation recommend)
AppName:Service1:ApiEndpoint
AppName:Service2:ApiEndpoint
In the SDK for my application I select all keys with the prefix AppName I trim the keys so the application is aware only of the last part of the key example  Service1:ApiEndpoint

But in the feature flags first we don't have prefixes  and also the : is not allowed so I have to create feature flags like this 
AppName_Service1 enabled

I hope it's clear.
Thank you

**Comment by jimmyca15** [comment]
That helps a lot, thanks!

**Comment by riaadh** [comment]
Hello, 
Now i am facing also another issue when i export my configuration. Since there is no Prefix (namespacing) in the Feature Flags they are not exprted. 

there is a lot of incoherance in the feature flag functionality, in .net Core it's already namespaced as "FeatureManagement": { } in the app setting file, in the azure portal it's on .appconfig.featureflag/ 

Please harmonize the behaviour, make feature flag on the same namespace in both appsetting.json and in the azure portal, allow  Prefix, and allow export of all config + feature flags on the azure portal 


thank you

**Comment by riaadh** [comment]
To summarize :  
        Allow Prefix  to Feature Flags
        Allow SDK to select feature flags by Prefix
        Consistent namespace for Feature flags between .net core and azure portal (under FeatureManagement like .net core)
        Allow import/export for the feature flags in the azure portal  the same way for config (the namespace will define if it is a config or a feature flag)


Thanks

**Comment by avanigupta** [comment]
Hello @riaadh, we released the ability to add prefix on feature flags using Azure CLI in [version 2.27.0](https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md#appconfig).  

With this change, the feature flag prefix can be directly added to the key-value key in AppConfig. The feature name can be different from the key and doesn't need to be namespaced. 
For example, if your feature name is "Beta" and you want to namespace feature flags like "AppName:Beta", you can run the following command to create this feature flag with your custom key:

`az appconfig feature set -n <AppConfigName> --feature Beta --key .appconfig.featureflag/AppName:Beta`

Then in your code, you can select all feature flags starting with "AppName:" and you don't need to trim anything from the feature name. Please see [FeatureFlagOptions.Select](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.featuremanagement.featureflagoptions.select?view=azure-dotnet-preview) API to learn how to select feature flags beginning with a specific prefix.

**Comment by MichaCo** [comment]
@avanigupta The Azure dashboard UIs don't seem to know about that yet?
I created your example feature with a path string separated by `:`

When I use the FeatureManager UI to add labels to it. It'll create "new" features without the path (only named Beta) 😕 
![image](https://user-images.githubusercontent.com/5837539/128637834-c771f89e-cf91-434e-a4e0-4435df2f766b.png)

**Comment by riaadh** [comment]
@avanigupta thank you for this change, but I confirm what @MichaCo  said the azure dashboard doest not allow yet
![Uploading image.png…]()
This is a first step for harmonizing feature flags and config.
Could you have a look at this 2 points 

- Consistent namespace for Feature flags between .net core and azure portal (under FeatureManagement like .net core)
 => in .net core app setttings file we add flags under the section FeatureManagement in the JSON file, but in azure we see flags under the section .appconfig.featureflag, if it could be the same between .net core and azure app config i think it will be easier 

- Allow import/export for the feature flags in the azure portal the same way for config (the namespace will define if it is a config or a feature flag), son one export can export everything (config, keyvault reference and feature flags)

Thank you

**Comment by avanigupta** [comment]
@riaadh, @MichaCo, your understanding is correct. This is not available in Azure portal yet but we are actively working on providing the same functionality in the portal too. In the meantime, you can use Azure CLI to achieve namespacing for feature flags as I mentioned earlier. You will see some errors in Azure portal, but your feature flags can still be accessed via any ConfigProvider/SDK/CLI/REST APIs. Once we release this functionality in portal, the errors will automatically disappear.

About consistent namespacing and exporting all data in AppConfig to a single file, we are working on providing import/export of feature flags using Azure portal. In the meantime, you can try using Azure CLI to import/export all AppConfig data (including feature flags) to a single file. Our import/export functionality understands the feature flag file schema and appropriately imports/exports all feature flags under the `FeatureManagement` section in file. Please see [az appconfig kv export](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_export) or [az appconfig kv import](https://docs.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az_appconfig_kv_import) for more details on command usage.

**Comment by zhenlan** [comment]
The support for feature flag namespace/prefix has been added to the Azure portal for a while, but we forgot to update this thread. You may see it already.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/10566826/157772099-08327d02-919d-4962-8cef-a86bce134b8b.png">

Regarding exporting all data in App Configuration to a single file, the support is added in Azure CLI. Please check out the details from https://github.com/Azure/AppConfiguration/issues/552#issuecomment-964584196. We are working on official documentation.
