### ISSUE TITLE
azure build pipeline 400 'The http resource that matches the request uri does not support the api verison '1.0''

### ISSUE THREAD

**Issue by glenn-kallidus** [Azure/AppConfiguration#521]
Hey guys,
I'm trying to setup the azure build pipeline task to download the app config to variables but i get the following error:
##[error]Access to '*' was denied. Please ensure the required role assignment is made for the identity running this task.

When i try to follow the url i get this error:
{"type":"https://azconfig.io/errors/invalid-argument","title":"Invalid API version","name":"api-version","detail":"The HTTP resource that matches the request URI '*' does not support the API version '1.0''.","status":400}

any advice?

**Comment by jimmyca15** [comment]
Hello @glenn-kallidus the error message mentions that the required role assignment needs to be made. Did you assign one of the app configuration data roles mentioned [here ](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration) to the service principal that is being used to access App Configuration?

**Comment by zhenlan** [comment]
@glenn-kallidus I hope @jimmyca15's response has answered your question.
