### ISSUE TITLE
Export Key Vault reference to App Service

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#522]
In configuration explorer, if we add a Key Vault reference, this URI is used :
`{"uri":"https://xxx"}`
But this URI is not recognized in App Settings of an App Service.

Now, in App Settings of an App Service, we need to have :
```
@Microsoft.KeyVault(VaultName=myvault;SecretName=mysecret)
OR
@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/)
```
See this article: https://docs.microsoft.com/fr-fr/azure/app-service/app-service-key-vault-references

Could you fix quickly this bug ?
Because all export of configuration have to be fix manually !

**Comment by jimmyca15** [comment]
@philippe85 Our export doesn't perform conversion based on destination. However, I would consider this a reasonable enhancement that we can look into.

cc @MSGaryWang

**Comment by avanigupta** [comment]
@Philippe85, you can run the following Azure CLI command to export Key Vault references to App Service in the right format:
`az appconfig kv export -d appservice -n <AppConfigName> --appservice-account <AppServiceResourceId>`

**Comment by Philippe85** [comment]
The URI generated in App Configuration does not respect the Microsoft format and is therefore not usable in App Services. This is a bug and not an improvement.

**Comment by jimmyca15** [comment]
@philippe85 It looks like this is indeed a lack of parity between our CLI and Portal. I have reclassified the issue and we are already working on rectifying it. Thanks for reporting!

**Comment by jimmyca15** [comment]
In the mean time, avanigupta's method of using the CLI should perform export with the proper transformation.

**Comment by Philippe85** [comment]
Thanks

**Comment by cablooshe** [comment]
The bug has been fixed. You should be able to import and export from app services and have the keyvault references transfer correctly.
