### ISSUE TITLE
Document/Enforce App service windows containerized app settings limit

### ISSUE THREAD

**Issue by remiminnebo** [Azure/AppConfiguration#523]
There seems to be a a limit on total app settings amount in App Service windows containerized mode.
Once you have more than 70 app settings the container will fail with: error configuring container
This error handling is not so clear, Ideally it would also be enforced on ARM API level that deploying more than 70 app settings returns an error.

**Comment by zhenlan** [comment]
@remiminnebo, please also note that this repo is for the **Azure App Configuration** service, which is a different service than App Service.
