### ISSUE TITLE
Springboot: bean 'Microsoft.Targeting' not found

### ISSUE THREAD

**Issue by invokersavi** [Azure/AppConfiguration#524]
I am using the spring-cloud-azure-feature-management-web library v1.3.0. I can retrieve the features when there are no targeting set on the feature, but when i set a target for a specific feature flag, a `NoSuchBeanDefinitionException` is thrown as it is searching for Microsoft.Targeting'. 

When i look through the documentation [here](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-feature-management-readme?view=azure-java-preview) I should be able to implement `ITargetingContextAccessor` but it seems like it's not available ?

Can anyone point me in the right direction regarding targeted features.

**Comment by mrm9084** [comment]
@invokersavi at this point 'Microsoft.Targeting' is only available in a beta version on the library. We will have an announcement when it is fully released. 
```xml
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-cloud-feature-management</artifactId>
    <version>2.0.0-beta.1</version>
</dependency>
```

**Comment by invokersavi** [comment]
Well okay then. That makes sense but i did not find that in the doc anywhere - that might be a good note to add. Thank you for quickly answering.

**Comment by mrm9084** [comment]
@invokersavi The full 2.0.0 version of azure-spring-cloud-feature-management is out.
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-cloud-feature-management</artifactId>
    <version>2.0.0</version>
</dependency>

Let us know if you have any more issues.
