### ISSUE TITLE
AzureAppConfigurationPush task should show more information in logs by default

### ISSUE THREAD

**Issue by thuijer** [Azure/AppConfiguration#525]
The current output of the AzureAppConfigurationPush task does not show any details about the operation

```
Starting: AzureAppConfigurationPush
==============================================================================
Task         : Azure App Configuration Push
Description  : Push key-values to an Azure App Configuration instance
Version      : 1.3.4
Author       : Microsoft Corporation
Help         : https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.dev-azure-app-configuration-task-push
==============================================================================
Finishing: AzureAppConfigurationPush
```

It should include at least information about:
* which AzureSubscription was used
* which AppConfiguration Service it updated
* which keys where updated
* which label was applied

**Comment by MaryanneNjeri** [comment]
Hi @thuijer you could [Enable System Diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs), to view  Azure Subscription  used and AppConfiguration Service it updated. Currently doesn't show the keys updated and the label applied, this is really good feedback. We'll look into it. 
Please feel free to reach out incase there is anything else we can help with.

Thanks,
Maryanne

**Comment by thuijer** [comment]
Hi, enabling System Diagnostics is an option, but I think this information should be logged always. Many tasks log a lot of information by default, which is normally enough to understand what the task has done. The AzureAppConfigurationPush task doesn't log anything and it should, like almost all other tasks, log basic information about the actions it has carried out. System Diagnostics is meant to see logging at an higher level.

**Comment by MaryanneNjeri** [comment]
@thuijer I see, makes sense. This is really helpful, thank you for the feedback. I think we could add more logs (like keys updated,  AppConfiguration Service it updated and  label applied) to help understand what the task has done.

**Comment by MaryanneNjeri** [comment]
Hi @thuijer a new release is out for the the Azure App Configuration Task- version 3.5.16 and Azure App Configuration Push Task- version 1.4.4, they include the improvement on showing more details about the operation.
