### ISSUE TITLE
Move Microsoft.FeatureManagement doc out of preview

### ISSUE THREAD

**Issue by jsquire** [Azure/AppConfiguration#527]
# Issue Transfer

This issue is being transferred from the Azure SDK repository ([#22011](https://github.com/Azure/azure-sdk-for-net/issues/22011))
## Please be aware that @AlexandraKemperMS is the author of the original issue and be sure to include them on any questions or replies.

Hi, could you please remove the note at the top of this page? The Microsoft.FeatureManagement Namespace is stable and released, a warning about it being in in prerelease is not necessary anymore. Developers are getting confused whether they can use this namespace. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fe8dba5-8f5e-1e3b-22b0-e9b9ce96e157
* Version Independent ID: 6838cdd3-c038-d2cf-14c8-90f5555e96a4
* Content: [Microsoft.FeatureManagement Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement?view=azure-dotnet-preview)
* Content Source: [xml/ns-Microsoft.FeatureManagement.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.FeatureManagement.xml)
* Service: **azure-app-configuration**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by AlexandraKemperMS** [comment]
I was hoping the authors would make this change :)
This is based on the customer feedback that this note was confusing. I can just send in a PR instead.

**Comment by zhenlan** [comment]
@AlexandraKemperMS we are the authors of this library :). We need to follow up just like what we did for `Microsoft.Extensions.Configuration.AzureAppConfiguration` namespace and move the doc out of the preview.

**Comment by AlexandraKemperMS** [comment]
@zhenlan Yes, we are the authors, you are right. This post was before we knew how to make this change on our side - Avani and I were investigating so I created a github comment to see if the docs authors knew. Should be a breeze that we now know.
