### ISSUE TITLE
Is it possible to get Strongly Typed Configuration Settings in my API using the App Configuration Service?

### ISSUE THREAD

**Issue by dcadlereii** [Azure/AppConfiguration#528]
In my .NET 5 web API, prior to considering Azure App Configuration Service, I used strongly typed configuration settings in my Startup.cs so that I didn't have to use magic strings in all of the places where I needed configuration values in my code.

For example, in my Startup.cs --> ConfigureServices method, I have lines like the following;

`    services.Configure<AzureStorageSettings>(Configuration.GetSection(nameof(AzureStorageSettings)));
`
That would populate a strongly typed object with values in my appsettings.json file.

Is there a way to do the same thing or something similar with Azure App Configuration Service so that I don't have to use magic strings like 

    `Configuration["CoreApi:Settings:IdpAuthority"]`

**Comment by avanigupta** [comment]
Hi @dcadlereii, please see [this document](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core5x) for an example of using strongly typed configuration with AppConfig. In the sample, we are binding configuration data to `Settings` class using `services.Configure<Settings>` method.

**Comment by dcadlereii** [comment]
@avanigupta that link got me going. THanks :)
