### ISSUE TITLE
Enter key in the search pattern should perform the search.

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/AppConfiguration#53]
<kbd>Enter</kbd> key in the search pattern should perform the search. No need to force customers to use the mouse to click "Apply" button or tab several times to reach the button.

**Comment by zhenlan** [comment]
@SeanFeldman, good suggestion. Thank you!

**Comment by zhenlan** [comment]
This works now in a new update of the portal this week. After inputting *key* filter, the `enter` key will trigger the `Apply`.
