### ISSUE TITLE
DefaultAzureCredential doesn't work in ConfigurationClient

### ISSUE THREAD

**Issue by gkarnik-gl** [Azure/AppConfiguration#530]
While running locally from Visual Studio, DefaultAzureCredential parameter for ConfigurationClient doesn't work whereas it works for SecretClient. VisualStudioCredential parameter works for both.

Success:
var secretClient = new SecretClient(new Uri("<KeyVaultUri>"), new DefaultAzureCredential());
Fail:
var configClient = new ConfigurationClient(new Uri("<AppConfigUri>"), new DefaultAzureCredential());

Success:
var secretClient = new SecretClient(new Uri("<KeyVaultUri>"), new VisualStudioCredential());
var configClient = new ConfigurationClient(new Uri("<AppConfigUri>"), new VisualStudioCredential());

**Comment by zhenlan** [comment]
Issue moved to [Azure/azure-sdk-for-net #22223](https://github.com/Azure/azure-sdk-for-net/issues/22223) via [**ZenHub**](https://www.zenhub.com/)
