### ISSUE TITLE
Continuous Integration With Feature Management

### ISSUE THREAD

**Issue by XRSHEERAN** [Azure/AppConfiguration#531]
Hello Team,

I've used the pipeline extension ([here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/push-kv-devops-pipeline)) "push app configuration" to change app configuration and hope to know if it supports changing feature flags? 

When I tried to pass an object to feature flag, it treated the object as multiple strings and converted the feature flag into configuration. So I'm wondering does the pipeline extension support changing feature flags or is there anyway to push feature flag changes through release pipeline besides using Azure CLI (we cannot use powershell script to change production settings due to SOX compliance). 

Thank you!

**Comment by MaryanneNjeri** [comment]
Hello @XRSHEERAN, thank you for reaching out. When updating the feature flag changes, did you specify the content-type as "application/vnd.microsoft.appconfig.ff+json;charset=utf-8" in the push app configuration input parameters ?

**Comment by XRSHEERAN** [comment]
Oh thanks Mary, I didn't notice those fields. It works for me then, thanks again!
