### ISSUE TITLE
Wildcard search doesn't work

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#532]
When using *searchterm* as a key filter, it does not do any filtering and still displays all keys.

**Comment by jiayi11** [comment]
@SirElTomato Are you referring to the key filter pillbox in configuration explorer blade on portal? I just tried and the key filter works well for me, can I know what kind of search term you are putting in the filter?

**Comment by zhenlan** [comment]
@SirElTomato please let us know if you have an update. Close for now.

**Comment by SirElTomato** [comment]
Sorry I forgot to escape the * in the original post. The searchterm I used was \*searchterm\*

**Comment by jiayi11** [comment]
*searchterm is not supported right now. This can be improved by adding client side filtering #500
