### ISSUE TITLE
Is there a way to grant  reader role to app services in Azure App Config resource?

### ISSUE THREAD

**Issue by abmis-mi** [Azure/AppConfiguration#534]
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?tabs=core5x#grant-access-to-app-configuration

Is there a way to grant App Configuration Data Reader role to app services using azure cli or through ARM scripts? We want to automate the process of creating all the resources including App Configuration and App Service and do not want to have a manual step to add the app service to the role.

**Comment by zhenlan** [comment]
The standard CLI role assignment command should work: https://docs.microsoft.com/en-us/cli/azure/role/assignment?view=azure-cli-latest

The same is supported in ARM template too: https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-template

**Comment by abmis-mi** [comment]
Just realized even for automation we need a priviledged access to do the changes, unlike adding Access Policies in KeyVault. 

![image](https://user-images.githubusercontent.com/66029786/127286872-f3eae1f3-6862-4c9a-abdf-5ad2b7027a8e.png)

Is there any plan to introduce access policy similar to keyvault, where even a contributor can add the required permission?

**Comment by zhenlan** [comment]
KeyVault has access policies before the support for Azure role-based access control (RBAC) was added recently. RBAC is the way to go moving forward.

**Comment by abmis-mi** [comment]
Thanks! I was not aware about this.
