### ISSUE TITLE
Error adding Spring Boot Parameters to App Configuration via ARM Template

### ISSUE THREAD

**Issue by cmoyer4** [Azure/AppConfiguration#536]
I'm trying to create a App Configuration instance via an ARM template and populate the key value pairs via the template.  According to the Spring Boot Azure App Configuration documentation, all keyName need to have the prefix of '/application/' for Azure Spring Cloud Config to retrieve these values.  But including the prefix while creating the keyName violates the segment length constraint for the naming convention.

I get the following error when trying to run the template.

**ERROR: {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'app_config_sandbox/application/spring.datasource.driver-class-name$development' for type 'Microsoft.AppConfiguration/configurationStores/keyValues' at line '56' and column '72' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":56,"linePosition":72,"path":"properties.template.resources[1].type"}}]}}**

The following template generates this error:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "environment": {
      "type": "String",
      "allowedValues": [
        "sandbox"
      ]
    }
  },
  "variables": {
    "environmentSettings": {
      "sandbox": {
        "appConfigInstanceName": "app_config_sandbox",
        "region": "centralus"
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.AppConfiguration/configurationStores",
      "apiVersion": "2021-03-01-preview",
      "name": "[variables('environmentSettings')[parameters('environment')].appConfigInstanceName]",
      "location": "[variables('environmentSettings')[parameters('environment')].region]",
      "sku": {
        "name": "standard"
      },
      "resources": [
        {
          "name": "application/spring.datasource.driver-class-name$sandbox",
          "type": "keyValues",
          "apiVersion": "2021-03-01-preview",
          "dependsOn": [
            "[variables('environmentSettings')[parameters('environment')].appConfigInstanceName]"
          ],
          "properties": {
            "value": "test"
          }
        }
      ]
    }
  ]
}
```

`az deployment group validate --parameters environment=sandbox --template-file template_2.json --resource-group testRg
`

If I remove the 'application/' prefix from the key name, ARM is able to process the template correctly and create the App Configuration instance, but the keyname is then not in the correct format and the spring-cloud-azure-appconfiguration-config SDK is not able to pick up the parameters from the configuration.

[https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-starter-azure-appconfiguration-config-readme?view=azure-java-stable#supported-properties](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-cloud-starter-azure-appconfiguration-config-readme?view=azure-java-stable#supported-properties)

Is this not a possibility to add key value pairs via an ARM template for Spring Boot apps?  Or am I missing something?

**Comment by zhenlan** [comment]
Hi @cmoyer4 

The key and label specified in the ARM template need to be encoded due to the restriction of characters in the ARM template. In your case *application/* should be encoded as *application~2F*. Please check out the Tip section towards the end of this document for more details: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager

**Comment by zhenlan** [comment]
@cmoyer4 please let us know if you have other questions. Closing for now.
