### ISSUE TITLE
Support for hierarchical view in portal

### ISSUE THREAD

**Issue by TharinduK** [Azure/AppConfiguration#537]
Could you please add the ability to group feature flags based on hierarchy in **Azure Portal, Configuration Explore** ? .  

I currently have setup feature configuration keys to follow the naming structure `Feature1:SubFeature1`. However they do not appear grouped together (with an > and collapsed) when looking in UI.  

![FeatureSetup](https://user-images.githubusercontent.com/19589601/127549985-8775f18f-6504-47c1-8179-2369fdb18c79.jpg)

**Comment by zhenlan** [comment]
Thanks for the suggestion, @TharinduK. We do have plans to support a hierarchical view in the future.

**Comment by lissdy** [comment]
We are looking for the feature as well. May I know any updates on this? Thanks

**Comment by MaryanneNjeri** [comment]
Hello @TharinduK and @lissdy this feature was released and can be accessed by clicking on the toggle (Default view) on the top right 
![image](https://github.com/Azure/AppConfiguration/assets/33903727/8fac7699-3319-4d75-b3fc-9be738f7019e)
Please try it out and let us know what you think :)
![image](https://github.com/Azure/AppConfiguration/assets/33903727/393463b2-723c-41de-8de5-528eeca72b5c)
