### ISSUE TITLE
Can I set/change a Key Value from Source code.

### ISSUE THREAD

**Issue by techierathore** [Azure/AppConfiguration#538]
Can I change a key value from source code ? Currently I am using Configuration[Key] to set the value but it only saves the values till application is in memory, when I refresh the Configuration settings it gets replaced by the original values.
Is App Configuration values read only from code ?

**Comment by zhenlan** [comment]
@techierathore to make changes of key-values in App Configuration, you may use the App Configuration SDK: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/appconfiguration/Azure.Data.AppConfiguration.

**Comment by techierathore** [comment]
Thanks @zhenlan This worked.
