### ISSUE TITLE
App Configuration not refreshing with when using services.AddApplicationInsightsKubernetesEnricher()

### ISSUE THREAD

**Issue by mattsage1991** [Azure/AppConfiguration#539]
When adding services.AddApplicationInsightsKubernetesEnricher() into ConfigureServices, if I update something in AppConfiguration, it doesn't update the cache and always returns the initial value until I restart the application. I've been using this with the FeatureManagement package. 

It only works when I remove services.AddApplicationInsightsKubernetesEnricher() from Startup.

Thought I'd raise it as it took me a while to find out why it wasn't working, in case it helps anyone else.

**Comment by jimmyca15** [comment]
Hello @mattsage1991 thanks for reporting this. It looks like the is an issue in the `services.AddApplicationInsightsKubernetesEnricher` API. I have filed the following issue in the relevant repo so it can be investigated and rectified: https://github.com/microsoft/ApplicationInsights-Kubernetes/issues/236

**Comment by jimmyca15** [comment]
I will close this issue since the underlying problem is in the ApplicationInsights-Kubernetes code library rather than the Azure App Configuration / Microsoft.FeatureManagement side.
