### ISSUE TITLE
Feature Parity with Azure Key Vault

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/AppConfiguration#54]
Does Azure App Configuration have the following features and if not are they planned:

1. ARM template to create an Azure App Configuration.
2. Create settings in Azure App Configuration from an ARM template. Similar to how Key Vault can.
3. Refer to Azure App Configuration settings from Azure DevOps.

**Comment by drago-draganov** [comment]
@RehanSaeed
 
These are planned and in progress.

**Comment by dawwa** [comment]
Vote on this, also please make an example of how to reference the access key and endpoint string in the ARM template, so that we can assign the value to an environment variable of the app service. Such as how we similarly do for assigning the app insights instrumentation key.

"APPINSIGHTS_INSTRUMENTATIONKEY": "[reference(resourceId('microsoft.insights/components', parameters('appInsightsName')), '2015-05-01').InstrumentationKey]",

**Comment by drago-draganov** [comment]
@dawwa

I will update the thread here with the official documentation links once available. We share the importance of detailed and easy to follow examples of how to utilize App Configuration as reference in ARM templates.

Stay tuned. Thanks!

**Comment by c-owens** [comment]
@dawwa I worked out how to get the connection string as output from an ARM template for the current preview API: [appConfigTemplate.json](https://gist.github.com/c-owens/74ab96f669c764e4073b7c8af6522ab5)

**Comment by zhenlan** [comment]
> 3. Refer to Azure App Configuration settings from Azure DevOps.

We just had a release of Azure DevOps pipeline task that will download key-values to build/release pipeline task variables from Azure App Configuration. Please check it out. Feedback is welcome.
https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task

**Comment by arkiaconsulting** [comment]
@dawwa And if you need the endpoint, you can have a look at [this](https://github.com/arkiaconsulting/feature-toggling/blob/master/Resources/tf/arm/app-config.json)

**Comment by zhenlan** [comment]
There are multiple requested features tracked in this issue. 1 and 3 are already available. 2 is tracked in #119. So I am closing this issue.
