### ISSUE TITLE
App Configuration 401 error using DefaultAzureCredential in VS2019

### ISSUE THREAD

**Issue by MarkAtAgilliance** [Azure/AppConfiguration#543]
May be related to this issue [App Configuration 401 error using DefaultAzureCredential in VS2019 #397](https://github.com/Azure/AppConfiguration/issues/397).

I have started getting occasional errors access through the AzureDefaultCredentials.  Not a blocker but annoying that it keeps failing.

Confirmed I have the correct account selected in VS tools/options/Azure Service Authentication / Account Selection.

Confirmed I have AZURE_USERNAME correctly added to the environment variables.

Confirmed there are no changes to subscription, tenancy, resource group or service recently.

After a change / recompile, it often fails (see error details).  If I stop and restart debug, it often (not always) works.

project has:
```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.0.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.4.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.15.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.5" />
  </ItemGroup>
```

**Startup.cs** is fairly standard:  Here is a clip:

```
  public static IHostBuilder CreateHostBuilder(string[] args) =>
     Host.CreateDefaultBuilder(args)
      .ConfigureWebHostDefaults(webBuilder =>
      {
        webBuilder.ConfigureAppConfiguration(config =>
        {
          var settings = config.Build();
          var configHost = settings[_configServiceEndpoint];

                    var configLabel = string.IsNullOrWhiteSpace(settings[_configServiceLabel]) ? LabelFilter.Null :Settings[_configServiceLabel];

                    var configUri = new Uri(configHost);

                    config.AddAzureAppConfiguration(action =>
                    {
                        action
                            .Connect(configUri, new DefaultAzureCredential())
                            .ConfigureKeyVault(kv =>
                            {
                                kv.SetCredential(new DefaultAzureCredential());
                            })
                             .Select(_commonLoggingSettings + ":*", LabelFilter.Null)
                             .TrimKeyPrefix(_commonLoggingSettings + ":");
    ... other config stuff
```

**Error is** 
Azure.RequestFailedException: 'Service request failed.
Status: 401 (Unauthorized)

Headers:
Server: openresty/1.17.8.2
Date: Thu, 12 Aug 2021 19:16:06 GMT
Connection: keep-alive
WWW-Authenticate: HMAC-SHA256,Bearer error="invalid_token", error_description="The access token is from the wrong issuer. It must match the AD tenant associated with the subscription, to which the configuration store belongs. If you just transferred your subscription and see this error message, please try back later."
x-ms-request-id: 801b9c79-ec4c-4abf-9204-ddaea35fdc03
x-ms-client-request-id: 2907b613-9746-4a81-a065-49157a22ce4e
x-ms-correlation-request-id: 801b9c79-ec4c-4abf-9204-ddaea35fdc03
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, x-ms-client-session-id, x-ms-effective-locale, WWW-Authenticate
Strict-Transport-Security: max-age=15724800; includeSubDomains
Content-Length: 0

**Comment by drago-draganov** [comment]
Can you set AZURE_TENANT_ID as well?

**Comment by zhenlan** [comment]
Just expand on what Drago suggested. According to the error "_The access token is from the wrong issuer. It must match the AD tenant associated with the subscription, to which the configuration store belongs. If you just transferred your subscription and see this error message, please try back later._", you are likely in a multi-tenant environment. You need to use the same AAD tenant where your App Configuration store is created. but the `DefaultAzureCredential` sometimes picked the wrong tenant. That's why it works sometimes and sometimes not. You can use `DefaultAzureCredentialOptions` to specify the tenant the code should use.

**Comment by MarkAtAgilliance** [comment]
@drago-draganov , @zhenlan  thanks, that was it.
Strange thing is I have been developing multi-tenant for 3-4 years and this problem only started happening a few days ago.  

To your point "the DefaultAzureCredential sometimes picked the wrong tenant".  Seems like it tripped over to always picks up the wrong tenant id.  It maybe a netcore 5 vs 3.1 since I have only recently started using 5.0.

Thanks and closing..

**Comment by drago-draganov** [comment]
The default DefaultAzureCredential picks up the "home" tenant. If your Identity is part of more than one tenant, those issues could become more often than not.
