### ISSUE TITLE
FeatureFlag targeting filter is case-sensitive

### ISSUE THREAD

**Issue by andyhammar** [Azure/AppConfiguration#545]
Hi!
I saw from the sibling issue of this (https://github.com/Azure/AppConfiguration/issues/52) that the whole AppConfiguration system is case-sensitive by design, but I thought I'd post this anyway.

After implementing this in our app, on the first feature to toggle on our product owner pasted some emails into the user targeting textboxes and it didn't work - they we Name.Name@example.org

Could the targeting user/group comparisons be made case-insensitive, or that is also by design?

Thanks!

**Comment by avanigupta** [comment]
Hi @andyhammar, you can setup [TargetingEvaluationOptions.IgnoreCase](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement.featurefilters.targetingevaluationoptions.ignorecase?view=azure-dotnet-preview) to perform case-insensitive comparison.
