### ISSUE TITLE
How to add/update key-vault references in app-configuration using "Azure App Configuration Push task"

### ISSUE THREAD

**Issue by Aravind-Kump** [Azure/AppConfiguration#546]
Team,

How can I add/update key-vault reference in app-configuration using "Azure App Configuration Push task"?

I tried in below format.
**Pipeline:**
- task: AzureAppConfigurationPush@1
      inputs:
      azureSubscription: 'Subscription'
      ConfigstoreName: 'app-configuration'
      ConfigurationFile: 'keyvault-secrets.json'
      Separator: ':'
      Label: 'dev'
      ContentType: 'application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8'
      Strict: false

**keyvault-secrets.json:**
{
"keyname" : "https://<keyvault>.vault.azure.net/secrets/<value>/<version-id>"
}

Pipeline is getting executed successfully. But, the key-vault secret reference is not getting added/updated as expected. Due to which I am unable to retrieve the secret values during application run-time. 

Please suggest here.

**Comment by zhenlan** [comment]
The value in the json file should be in the format of 
`{"uri":"https://xxx.vault.azure.net/secrets/abc"}` and you may have to json encode it.
