### ISSUE TITLE
##[error]Failed to parse: /home/vsts/work/1/b/publish_output/remote.settings.json, Unexpected token ﻿ in JSON at position 0

### ISSUE THREAD

**Issue by ArmandoPitotti** [Azure/AppConfiguration#550]
**I am trying to use 'Azure App Configuration Push' in my pipeline, but I get the error:**
   Failed to parse: /home/vsts/work/1/b/publish_output/remote.settings.json, Unexpected token ﻿ in JSON at position 0

**My very simple json:**

{
 "FirstKey":"FirstValue"
}

**My task in pipeline for Configuration Push:**

- task: AzureAppConfigurationPush@1
  inputs:
    azureSubscription: 'ServConnection-AzureSubscription'
    ConfigstoreName: 'crmtest-appconfig'
    ConfigurationFile: '$(Build.BinariesDirectory)/publish_output/remote.settings.json'
    Separator: ','
    Strict: false

I hope you can help me, Thanks.

**Comment by MaryanneNjeri** [comment]
Hello @ArmandoPitotti, sorry for the delayed response. Am working on reproducing the issue you are currently facing.

**Comment by MaryanneNjeri** [comment]
@ArmandoPitotti  I have been able to reproduce the error you are experiencing, kindly check the encoding format of the `remote.settings.json` file, if the encoding format is `UTF-8 with BOM` kindly update to `UTF-8`. Please let me know if this helps :) . 
Thanks,
Maryanne

**Comment by ArmandoPitotti** [comment]
@MaryanneNjeri It seems to work now. Thanks

**Comment by zhenlan** [comment]
@MaryanneNjeri, any chance we can either detect the file format or give a better error message so users can confirm their file format?

**Comment by MaryanneNjeri** [comment]
@zhenlan we can detect file format and give a better error message. Let me work on that.
