### ISSUE TITLE
Change priority of AppConfigurationPropertySourceLocator to make it override locally loaded properties

### ISSUE THREAD

**Issue by saiyedzaidi** [Azure/AppConfiguration#554]
At this time, the Azure app config AppConfigurationPropertySourceLocator is added to the property sources without any Order. This makes the remote properties be overwritten by any local properties that were bundled with the deployable.
Ideally this behavior should be customizable and if not, the remote config being more manageable should override the values loaded from local property files.

Expected behavior:
Properties values from application.yml should be overwritten by properties coming from Azure app config.

Actual behavior
Properties values from application.yml override the values coming from Azure app config. Happening because AppConfigurationPropertySourceLocator  is added with least priority.

**Comment by zhenlan** [comment]
@mrm9084 do you have any suggestions?

**Comment by mrm9084** [comment]
@zhenlan I am looking into it.

**Comment by zhenlan** [comment]
Closing due to lack of response.
