### ISSUE TITLE
Stop Application configuration from causing web application to crash

### ISSUE THREAD

**Issue by jcnewman83** [Azure/AppConfiguration#557]
I have recently been in a situation where our request quota was exceeded and it caused the web application to completely crash/stop, it took me a while to get to application config as the root cause, but, I found that I had originally set the application configuration service up using the free tier for which we exceeded the day quota, once I upgraded our service to standard tier and rebooted our app services, the website returned to a working state.

My issue/question is that it would be great if there was a way for me to catch/handle the 429 responses that are returned when a quota has been exceeded and not cause my web app to crash but fail gracefully.

A bit about my application in case this helps:
I am running a .NET 5 Blazor application, I am using the application config to hide in progress development behind feature flags.

My Program.cs:
```
Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureAppConfiguration((context, config) =>
                {
                    IConfigurationRoot builtConfig = config.Build();
                    if (context.HostingEnvironment.IsProduction())
                    {
                        var secretClient = new SecretClient(
                            new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
                            new DefaultAzureCredential());
                        config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
                    }
                })
                .ConfigureWebHostDefaults(webBuilder =>
                    webBuilder.ConfigureAppConfiguration(config =>
                    {
                        IConfigurationRoot settings = config.Build();
                        string connection = settings.GetConnectionString("AppConfig");
                        config.AddAzureAppConfiguration(options =>
                            options.Connect(connection).UseFeatureFlags());
                    }).UseStartup<Startup>());
```

My Startup.cs (shortened for brevity):

```
public void ConfigureServices(IServiceCollection services)
  {
            services.AddRazorPages();
            services.AddServerSideBlazor();
            services.AddFeatureManagement();
            services.AddAzureAppConfiguration();
  }
```

Feature flag usage:
Index.razor
```
<div>
<span>I am already released!</span>
@if(MyFeatureFlagIsEnabled)
{
<span>I Have been enabled but I am still in development</span>
}
</div>
```

Index.razor.cs
```
using Microsoft.FeatureManagement;
public partial class Index : ComponentBase
{
    [Inject]
    public IFeatureManager FeatureManager { get; set; }
    bool MyFeatureFlagIsEnabled { get; set; }

    protected override async Task OnInitializedAsync()
    {
         MyFeatureFlagIsEnabled = await FeatureManager.IsEnabledAsync("MyFeatureFlagAsSetInAzureAppConfig")
    }

}

```
Any advice anyone can offer would be greatly appreciated. Thank you.

**Comment by jimmyca15** [comment]
@jcnewman83 [AddAzureAppConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfigurationextensions.addazureappconfiguration?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfigurationExtensions_AddAzureAppConfiguration_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_AzureAppConfiguration_AzureAppConfigurationOptions__System_Boolean_) takes a boolean that allows the configuration from AzureAppConfiguration to be optional. If an error occurs while retrieving configuration from Azure App Configuration it will be ignored and the app will start without configuration from Azure App Configuration. Is this the behavior you are looking for?

**Comment by jcnewman83** [comment]
> @jcnewman83 [AddAzureAppConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfigurationextensions.addazureappconfiguration?view=azure-dotnet-preview#Microsoft_Extensions_Configuration_AzureAppConfigurationExtensions_AddAzureAppConfiguration_Microsoft_Extensions_Configuration_IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_AzureAppConfiguration_AzureAppConfigurationOptions__System_Boolean_) takes a boolean that allows the configuration from AzureAppConfiguration to be optional. If an error occurs while retrieving configuration from Azure App Configuration it will be ignored and the app will start without configuration from Azure App Configuration. Is this the behavior you are looking for?

@jimmyca15 this is perfect, I will give it a go and if I have any further issues raise them if appropriate, thank you.
