### ISSUE TITLE
Access AppConfiguration from Container Instance using manged identity

### ISSUE THREAD

**Issue by kedzior-io** [Azure/AppConfiguration#558]
I have .net web api running inside the container with the following settings:

```
config.AddAzureAppConfiguration(options => options
                    .Connect(new Uri("https://chucknorris-config.azconfig.io"), new ManagedIdentityCredential()));
```

My containers are spinned up by azure function in azure container instance group: 

```
var containerGroup = azureContext.ContainerGroups.Define(_azureContainerName)
    .WithRegion(Region.USEast)
    .WithExistingResourceGroup(_azureResourceGroupName)
    .WithLinux()
    .WithPrivateImageRegistry(azureRegistry.LoginServerUrl, acrCredentials.Username, acrCredentials.AccessKeys[AccessKeyType.Primary])
    .DefineVolume(_volumeMountName)
        .WithExistingReadWriteAzureFileShare(_azureFilesShare)
        .WithStorageAccountName(_storageAccountName)
        .WithStorageAccountKey(_storageAccountKey)
        .Attach()
    .DefineContainerInstance(_azureProxyContainerName)
        .WithImage(_imageNameProxy)
        .WithExternalTcpPort(443)
        .WithExternalTcpPort(80)
        .WithCpuCoreCount(1.0)
        .WithMemorySizeInGB(0.5)
        .WithVolumeMountSetting(_volumeMountName, _dataMountPath)
        .Attach()
    .DefineContainerInstance(_azureApiContainerName)
        .WithImage(_imageNameApi)
        .WithExternalTcpPort(5000)
        .WithCpuCoreCount(1.0)
        .WithMemorySizeInGB(0.5)
        .Attach()
    .WithDnsPrefix(_azureContainerName)
    .WithSystemAssignedManagedServiceIdentity()
    .WithSystemAssignedIdentityBasedAccessTo("/subscriptions/guid-here}/resourceGroups/resource-here/providers/Microsoft.AppConfiguration/configurationStores/chucknorris-config", BuiltInRole.Pars("App Configuration Data Reader"))
    .Create();
````

The `api` containers starts and throws an exception:

```
Azure.RequestFailedException: Service request failed.
Status: 403 (Forbidden)

  at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, String pageLink, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass20_1.<<LoadAll>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass20_1.<<LoadAll>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, RequestTracingOptions requestTracingOptions, Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.CallWithRequestTracing(Func`1 clientCall)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll(Boolean ignoreFailures)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ApiTest.Program.Main(String[] args) in /src/src/ApiTest/Program.cs:line 26

```

I can confirm that my system identity is enabled on container group. 

![image](https://user-images.githubusercontent.com/40808369/136030174-7ae7de06-87ec-495b-8757-2e49c763af94.png)

though role assignment is empty. Isn't the `WithSystemAssignedIdentityBasedAccessTo` supposed to add that? 

![image](https://user-images.githubusercontent.com/40808369/136030260-76c72b51-6262-4353-8963-eb85e571ad50.png)

so even if I add one:

![image](https://user-images.githubusercontent.com/40808369/136030419-8ac410fa-2540-49d0-ad7a-cd62815c634d.png)

My container log shows:

```
Setting up https://chucknorris-config.azconfig.io
Unhandled exception. Azure.Identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
// omitted stack trace
``` 

 :point_right:  All I want is to be able to read configuration from my `chucknorris-config.azconfig.io` :point_left:

![image](https://user-images.githubusercontent.com/40808369/136034895-5c2fc68f-476a-410d-b144-2e2f0915b564.png)

Any idea?

Update: Just tried the same but using user assigned identity but with same error: `ManagedIdentityCredential authentication unavailable`

Update2: I'm not using Vnets.

**Comment by jimmyca15** [comment]
@kedzior-io that error message `ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found` implies that the container instance doesn't have managed identity set up. I'm wondering if it could be that your code is starting up so quickly that the managed identity isn't ready for use yet. Is it possible for you to create the container instance, stop it and start it again and see if you get the same error?

**Comment by kedzior-io** [comment]
> @kedzior-io that error message `ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found` implies that the container instance doesn't have managed identity set up. I'm wondering if it could be that your code is starting up so quickly that the managed identity isn't ready for use yet. Is it possible for you to create the container instance, stop it and start it again and see if you get the same error?

Thanks. Tried that. Same error.

**Comment by svrooij** [comment]
Really? I faced this issue multiple times when accessing the keyvault with a managed identity. I eventually give up decided that managed identities don’t work yet on container instances….

for those interested I wrote a blog post about how those identities actually work. https://svrooij.io/2021/07/20/managed-identity-without-azure/

**Comment by kedzior-io** [comment]
@svrooij yes it does. I need to measure though how long it takes to propagate. 

![image](https://user-images.githubusercontent.com/40808369/136103555-f06602ed-7a21-44bd-a9e3-20d0c45b37a4.png)

If it is too long I will probably get all those configs from app configuration and set them up as secured environment variables as I create containers:

` .WithEnvironmentVariableWithSecuredValue("AppSettings__What__IsMyPurpose", "You pass butter")`  

than the web api running inside the container have them available via injected configuration:

```
[HttpGet]
public async Task<IActionResult> Get()
{
    return Ok($"AAC Test= {_configuration["AppSettings:What:IsMyPurpose"]}");
}
````

**Comment by jimmyca15** [comment]
@kedzior-io I am not aware of the expected time for when the managed identity service is expected to be available after provisioning an Azure Container Instance. This [feature is in preview](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-managed-identity) and this looks like some valuable feedback for the feature. 

Any feedback for Managed Identities in Azure Container Instances can be provided straight from the [documentation](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-managed-identity#use-user-assigned-identity-to-get-secret-from-key-vault).

I went ahead and looked, it looks like someone has [provided similar feedback](https://github.com/MicrosoftDocs/azure-docs/issues/78610) ([2](https://github.com/MicrosoftDocs/azure-docs/issues/71206)).

**Comment by kedzior-io** [comment]
@jimmyca15 thanks! I get this is preview and might not be all dandy just yet. I will try to get the average time of waiting for AAC being accesible. I have a feeling that user assigned identity will be slightly faster as it only needs to be assigned to the container group resource. As an alternative I fetch values from AAC and set them as secure env variables.

**Comment by zhenlan** [comment]
Please reopen if further assistance is needed. Closing.
