### ISSUE TITLE
  App Configuration CORS issue Anguler front end app

### ISSUE THREAD

**Issue by jayanath007** [Azure/AppConfiguration#566]
![image](https://user-images.githubusercontent.com/2934182/137914449-5041535f-6ec2-44c0-8708-b776e7c763e6.png)

I connected angular application with azure app config . 
when I call  client.getConfigurationSetting({ key: "newFeatureflag" }); this method it get errors CORS error

![image](https://user-images.githubusercontent.com/2934182/137915289-f9241fed-1a62-41de-87e2-9c711482f4a6.png)

**Comment by jimmyca15** [comment]
This was also filed in the sdk repo where the conversation has been ongoing.
https://github.com/Azure/azure-sdk-for-js/issues/18270#issuecomment-960249200

**Comment by jimmyca15** [comment]
@jayanath007 Azure App Configuration now allows the headers that were causing the CORS failures mentioned in this issue. This should no longer occur.
