### ISSUE TITLE
Application Specific Access Control

### ISSUE THREAD

**Issue by arshadazeem** [Azure/AppConfiguration#568]
Provide an ability for individual teams to apply RBAC around configuration entries they manage. E.g. App1 should only have read/write access to entries for App1 and not other Apps. This would help multiple application teams in an organization use the same App Configuration instance

**Comment by zhenlan** [comment]
Good suggestion, @arshadazeem. This is something we are interested in looking into in the future. There is a similar request in #484. I am going to close this one and use the other one for tracking purposes.
