### ISSUE TITLE
Expand a key with multiple labels by click on the key name

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/AppConfiguration#57]
In the portal, to expand a key with multiple labels, one has to click the arrow. Please allow clicking the name to do so.

**Comment by zhenlan** [comment]
Sounds like a good suggestion to me. Thanks, @SeanFeldman. We could even hide/unhide value when the value is clicked, not sure if this is doable by the portal SDK or whether this violates Accessibility requirements though.

cc: @mlacouture @MSGaryWang for their opinions

**Comment by mlacouture** [comment]
Yes, this is a good suggestion.  We'll look into it.

**Comment by mlacouture** [comment]
a fix for this will be available in the next portal prod deployment.

**Comment by mlacouture** [comment]
this is now fix on prod.
