### ISSUE TITLE
Support for Azure China Subscriptions

### ISSUE THREAD

**Issue by Sun5Kong** [Azure/AppConfiguration#572]
I'm using it to publish settings to an Azure China subscription, but got the error "AADSTS90002: Tenant '***' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant." 
I am sure that I have selected the correct service connection. 
I think it's due to the wrong endpoint. 
The endpoint for Mooncake should be "https://xxx.azconfig.azure.cn". 
But the task always used "https://xxx.azconfig.io".

**Comment by zhenlan** [comment]
@Sun5Kong thanks for reporting the issue. The App Config pipeline tasks don't support sovereign clouds yet. We are looking into it.

**Comment by MaryanneNjeri** [comment]
@Sun5Kong apologies for the inconvenience, we are currently working on a fix for this.

**Comment by MaryanneNjeri** [comment]
@Sun5Kong we have a new release for [Azure App configuration Push task version 3.0.0](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push)  that supports sovereign clouds.

**Comment by MaryanneNjeri** [comment]
@Sun5Kong a new release is out  [Azure App Configuration Push version 3.1.0](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push), that supports sovereign clouds. Please try it out, feel free to reach out in case you experience any issues. :)
