### ISSUE TITLE
kv import not removing the key-value from AppConfiguration when they are deleted from json file

### ISSUE THREAD

**Issue by Madhufuture** [Azure/AppConfiguration#574]
We are able to achieve below when we run ```az appconfig kv import``` cli command
1) Import all the kv pair from json file into ACS
2) Updates performed to key-value in json file are getting reflected in the ACS

When we delete  any key-value from json and run the ```az appconfig kv import``` command, the deleted key-value are not getting removed/deleted from ACS.
We can explicitly run ```az appconfig kv delete``` and specify ```--key``` which needs to be deleted. But if there are 10's of keys that needs to be deleted, then we don't see any solution that will help us to achieve this faster. 

Could you please suggest what should be used in these scenarios? And can this be added as part of ```az appconfig kv import``` so that it deletes key-value from ACS also?

**Comment by avanigupta** [comment]
Hi @Madhufuture, currently we don't support deleting key-values from the config store during import. But we will be adding this support in the future.
In the meantime, you can use this 2 step approach to solving your problem:

Step 1: Delete key-values from your AppConfig store by running `az appconfig kv delete --key * --label <label>`
Step 2: Import from your config file using `az appconfig kv import --label <label>`

Ideally, you shouldn't be deleting everything in your AppConfig store in step 1. Make sure that you organize your key-values with prefix/labels, and delete only the key-values matching the required prefix/label. Then you can import new key-values with the same prefix/label that you deleted in step 1.

**Comment by pratiksanglikar** [comment]
Hi @Madhufuture,
With [Azure CLI version 2.33.1](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md), we released a new flag, `--strict` which when specified, will delete the key values that are not present in the JSON file.
Please give it a try and let us know.
