### ISSUE TITLE
Overview blade to show Key-Value explorer

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/AppConfiguration#58]
Most often than not I'm going to the AppConfig service to manage/look-up keys and values. The default `Overview` blade is not useful and I always end up navigating to the `Key-Value Explorer` blade. So fill the `Overview` blade space with `Key-Value Explorer`.

**Comment by zhenlan** [comment]
Thanks for the feedback, @SeanFeldman. I know the overview page is pretty empty today so it feels reasonable to just put key-values there. At some point, I think we will want to put usage and other statistical information there just like other Azure services, so it won't be empty and may look weird to see key-values in the overview page.
