### ISSUE TITLE
Need help to implement dynamic configuration change in push model for azure app config in asp.net mvc application

### ISSUE THREAD

**Issue by SAMBHAV1997** [Azure/AppConfiguration#580]
I have created ASP.NET MVC application and I need to implement dynamic configuration using push model, I don't know how to refresh the configurations used in Dependency Injection pipeline in startup class.

**Comment by zhenlan** [comment]
@SAMBHAV1997 is this a .NET Framework or .NET Core-based MVC app? If it's the former, you can start with [this doc](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-netfx) to set up the dynamic configuration using the _poll_ model first. Then you can follow [this doc ](https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh)to set up event grid, service bus etc. for the _push_ model.

**Comment by SAMBHAV1997** [comment]
Thanks @zhenlan for the resources.
