### ISSUE TITLE
Unable to use in DevOps - Error: invalid_client

### ISSUE THREAD

**Issue by virtualvoid** [Azure/AppConfiguration#582]
`AADSTS7000216: 'client_assertion', 'client_secret' or 'request' is required for the 'client_credentials' grant type.`

The service connection was newly created: Azure Resource Manager/using publish profile based authentication.

edit: forgot to mention, that the `Azure App Configuration Push` is doing this.

**Comment by zhenlan** [comment]
@virtualvoid did you create a new service principal or [use an existing service principal](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-with-an-existing-service-principal) when creating your service connection?

@MaryanneNjeri any suggestions for the issue @virtualvoid ran into?

**Comment by MaryanneNjeri** [comment]
@zhenlan yes, a suggestion I have is @virtualvoid maybe you could try to create a new service connection ? Let me know if this helps or if you still run into the same issue after creating a new service connection.

**Comment by virtualvoid** [comment]
Looks like that i misunderstood the "service principal" part of the documentation.

I thought that the "publish profile" based authentication will somehow work too. Anyway, I've recreated the connection the way it should be and now it's working. Thanks.
