### ISSUE TITLE
Combine KeyVault values in an AppConfiguration setting along with custom strings and other AppConfiguration settings

### ISSUE THREAD

**Issue by PanosKousidis** [Azure/AppConfiguration#585]
Is there any way or any plans to treat a KeyVault reference as a variable that you may combine with others? And to add references of other AppConfiguration values?

E.g. 
I would like to have in a keyvault just the secret key of cosmos not the whole connectionstring. 
I would also like to store my subscription name in another AppConfiguration setting.
Then I should be able to construct the connectionString by combining "AccountEndpoint=@Microsoft.AppSettings(Uri=https://.../subscription).......AccountKey=@Microsoft.KeyVault(SecretUri=https://.../secrets/cosmosKey)....."
(the connectionString is just an example, I have other types of settings that are composite)

**Comment by avanigupta** [comment]
Hello @PanosKousidis, are you referring to key-values stored in [Azure App Configuration service](https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview)? Or are you talking about the [app settings in Azure App Service](https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-app-settings)?

**Comment by zhenlan** [comment]
The intra-service reference is not supported in App Configuration on the server-side. This is normally achieved on the client-side. If your app runs on Java Spring Boot, you can compose new a new setting by referencing other settings, for example, `setting1=${setting2}-${setting3}` where `setting2` and `setting3` are from App Config key-values or Key Vault references. If you are on .NET, configuration composition is normally done in code.

We do work on inter-service references, for example, #62.

**Comment by PanosKousidis** [comment]
Yes, this is what I'm doing right now but I was just wondering if the options were only these 2:
1) Store the whole "_connectionstring_" in the keyvault
2) Compose the "_connectionstring_" on every client that wants to use it, and if something in the composition changes, all clients need to be updated.

The inter-service reference between app settings and app configuration doesn't help with this

P.S. This is off-topic, and I will comment on #62 too:
The inter-service reference looks useful because we could abstract AppConfiguration from the code as we abstract KeyVault, but wouldn't we be losing the ability to inject `IConfigurationRefresher` with sentinels etc or the feature flags with the `[FeatureGate]` attributes on the controllers?

**Comment by zhenlan** [comment]
> Yes, this is what I'm doing right now but I was just wondering if the options were only these 2:
> 
> 1. Store the whole "_connectionstring_" in the keyvault
> 2. Compose the "_connectionstring_" on every client that wants to use it, and if something in the composition changes, all clients need to be updated.

This is correct. I understand the extra benefits of supporting it by the service, but the semantics vary a lot by different platforms. 
As I mentioned earlier, this works for Spring Boot applications (and they have their own convention). In .NET, you can save a "format string" as a separate setting, so the client will compose the final value based on the format string. In case the format changes in the future, you don't have to update all clients but the format string.

**Comment by PanosKousidis** [comment]
Sorry, one last comment and we can close this. 

> This is correct. I understand the extra benefits of supporting it by the service, but the semantics vary a lot by different platforms. As I mentioned earlier, this works for Spring Boot applications (and they have their own convention).

I didn't get why it's important what the client is. I thought App Configuration is a standalone web service that provides values to clients based on literal values or references. So, it can have its own syntax convention and the client should be agnostic of how the evaluation is done server side. Take Octopus Deploy for example, you can reference variables with #{...} and the client (well there's no client in the same way but anyway) doesn't really care because it just gets the result. So theoretically, we could be storing the variable references as I mentioned in my original post and the client, no matter what it is, would just get the evaluated result. 

> In .NET, you can save a "format string" as a separate setting, so the client will compose the final value based on the format string. In case the format changes in the future, you don't have to update all clients but the format string.

I guess I'll go with this for now, as it's a good enough workaround that avoids redeployment.

**Comment by zhenlan** [comment]
@PanosKousidis understood. Thanks for the feedback.
