### ISSUE TITLE
TrimKeyPrefix for FeatureFlagOptions

### ISSUE THREAD

**Issue by Edgaras91** [Azure/AppConfiguration#587]
This is my setup, see the last code line below
```
configBuilder.AddAzureAppConfiguration(options =>
            {
                ...
                options.Select($"{applicationName}:*", $"{azureConfigEnv}");
                options.TrimKeyPrefix($"{applicationName}:");

                options.UseFeatureFlags(featureOptions =>
                {
                    featureOptions.Select($"{applicationName}/", azureConfigEnv);
                    featureOptions.TrimKeyPrefix($"{applicationName}:"); <==== Doesn't Exist!
                });
            });
```

**Comment by zhenlan** [comment]
It's correct that the `TrimKeyPrefix` API doesn't exist for feature flags because you don't need it if you create feature flags like below

<img width="615" alt="image" src="https://user-images.githubusercontent.com/10566826/146417004-d7168945-72e0-4971-bc65-a1bc4a6cb96e.png">

In feature flags, you can add any necessary prefixes to the key, but you don't have to trim them as long as they are not part of the flag name.

**Comment by Edgaras91** [comment]
Then the list of features would be without a prefix, and hard to find (hope features page will have filters and nesting in the future like configs).
We would prepare to see the prefixes and not worry about them in the application (just like the configs).
![image](https://user-images.githubusercontent.com/32236075/147255086-c8824c3d-caa5-47ba-8e21-91c39899c817.png)
![image](https://user-images.githubusercontent.com/32236075/147255152-a6690111-d848-4e08-92f8-c9a210b5a810.png)

**Comment by zhenlan** [comment]
@Edgaras91 in the Feature manager UI, you will see the prefix in the 'Key' column. Maybe we should enable sorting by the 'Key' column so feature flags with the same prefix are organized together. We will soon release an update so you can show/hide or rearrange the columns. We will continue iterating on the UI. Your feedback is appreciated.

**Comment by zhenlan** [comment]
Please let us know if there is further feedback. Closing for now.
