### ISSUE TITLE
UseFeatureFlags are not updating using ConfigureRefresh

### ISSUE THREAD

**Issue by Edgaras91** [Azure/AppConfiguration#591]
Currently, my feature flags are not updating when refreshing all configs using a "sentinel" key, with a refresh all flag:

```
  options.ConfigureRefresh(refresh =>
                {
                    refresh.Register("SupportService_Refresh", azureConfigEnv, true);
                    refresh.SetCacheExpiration(TimeSpan.FromSeconds(refreshIntervalSeconds));
                });
```

They are refreshing using ASP solution using
`IApplicationBuilder.UseAzureAppConfiguration()`

I also do not see an example in the documentation on how to set up a feature refresh in the Core application (not ASP Core) using HostBuilder (not WebHostBuilder).

Are features explicitly for ASP core applications?

We also would want to refresh on a specific controller call manually, and not on a middleware call.

**Comment by Edgaras91** [comment]
Below is the code I am using for completeness.
```
            configBuilder.AddAzureAppConfiguration(options =>
            {
                options.Connect(config.GetConnectionString("AzureAppConfiguration"));
                options.UseFeatureFlags(x =>
                {
                    x.Select("SupportService_*", azureConfigEnv);
                    x.CacheExpirationInterval = TimeSpan.FromSeconds(refreshIntervalSeconds);
                });
                options.Select("SupportService_*", $"{azureConfigEnv}");
                options.TrimKeyPrefix("SupportService_");

                options.ConfigureRefresh(refresh =>
                {
                    refresh.Register("SupportService_Refresh", azureConfigEnv, true);
                    refresh.SetCacheExpiration(TimeSpan.FromSeconds(refreshIntervalSeconds));
                });

                refresher = options.GetRefresher();
            });

   SetupAzureConfigurationRefreshTimer(refresher, refreshIntervalSeconds, config);
```

```
       private static void SetupAzureConfigurationRefreshTimer(IConfigurationRefresher refresher, int intervalSeconds, IConfiguration config)
        {
            var timer = new Timer(TimeSpan.FromSeconds(intervalSeconds).TotalMilliseconds);
            timer.Elapsed += async (sender, arg) =>
            {
                var success = await refresher.TryRefreshAsync();
                var value = config["Tasks.Pure360PriceUpdate.CronSchedule"];
            };
            timer.Start();
        }
```

**Comment by avanigupta** [comment]
Hi @Edgaras91, feature refresh can be setup in any .NET Core application just like regular key-value refresh. If you are using HostBuilder in your .NET Core application, you need to add a call to `IServiceCollection.AddAzureAppConfiguration()` inside your `IHostBuilder.ConfigureServices()` method. This method registers the `IConfigurationRefresherProvider` type, which can be resolved in any controller to obtain an instance of `IConfigurationRefresher` and trigger `TryRefreshAsync()` operations. 

In our ASP .NET Core library, we provide a middleware for asynchronously refreshing config. But the same functionality can be implemented in a .NET core application too. You can refer to our simple [middleware code](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/main/src/Microsoft.Azure.AppConfiguration.AspNetCore/AzureAppConfigurationRefreshMiddleware.cs) and trigger your refresh operations from any controller in a similar manner.

**Comment by Edgaras91** [comment]
Thank you for confirming this.

So am I right to assume that the `AzureAppConfigurationOptions.GetRefresher()` which returns `IConfigurationRefresher` and calling `TryRefreshAsync()` does not refresh the features, but injected `IConfigurationRefresherProvider` and calling `TryRefreshAsync` on each of the "refreshers" does refresh features? Something I may test later and update here if this is not confirmed.

**Comment by zhenlan** [comment]
@Edgaras91 the sections in the following documents have more discussion on this topic. Please let us know if they answer your questions.

For .NET Core app, https://docs.microsoft.com/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core#activity-driven-configuration-refresh

For ASP.NET Core app, https://docs.microsoft.com/azure/azure-app-configuration/enable-dynamic-configuration-aspnet-core?tabs=core5x#reload-data-from-app-configuration

**Comment by zhenlan** [comment]
@Edgaras91 it's the same refresher instance regardless of you obtained it from `AzureAppConfigurationOptions.GetRefresher()` or through dependency injection `IConfigurationRefresherProvider`, so the `TryRefreshAsync()` call behaves the same way. I hope the document I linked earlier explains the behavior. Please let us know if you have further questions. Closing for now.
