### ISSUE TITLE
Extremely slow startup in .Net 6

### ISSUE THREAD

**Issue by bloechan** [Azure/AppConfiguration#595]
I am using the Azure App Configuration in an ASP.NET Api I built in .Net 6.0

When I run the app locally the initialize step takes around 20 seconds to complete.  We use the same initialize command in 3.1 and it is not a problem.

```
builder.Configuration.AddAzureAppConfiguration(options =>
{ 
    options.Connect(new Uri(builder.Configuration["endpoint"]), new DefaultAzureCredential())
        .ConfigureKeyVault(kv =>
        {
            kv.SetCredential(new DefaultAzureCredential());
        })
    .Select(KeyFilter.Any)
    .Select(KeyFilter.Any, builder.Configuration["Env"]);
});
```

Any suggestions would be appreciated.

Thanks

**Comment by drago-draganov** [comment]
Thanks for reaching out, @bloechan 

What's the OS (and other environment specifics) you are seeing the issues on? Can you also help us with collecting perf traces ([see](https://docs.microsoft.com/en-us/aspnet/core/performance/diagnostic-tools?view=aspnetcore-6.0#perfview))

**Comment by bloechan** [comment]
This is on Windows 10 Pro 10.0.19043 Build 19043.  I am using Visual Studio 2022.  I would prefer to not post the perf trace here, can I send it to you directly?

**Comment by drago-draganov** [comment]
We were able to repro in house. Perf traces are not needed at this point in time. 
I will update the thread with more details as soon as the investigation is completed.

**Comment by spowser** [comment]
Just wanted to add that this seems to also be happening in other versions of .NET.  I have seen this behavior in both 4.7.2 and .NET 5 as well

**Comment by avanigupta** [comment]
@bloechan, @spowser could you confirm if there were any other changes to your applications between different .NET versions? 
Also, which version of these packages are you using:
- Microsoft.Azure.AppConfiguration.AspNetCore
- Azure.Identity

**Comment by bloechan** [comment]
My application is a new ASP.NET Api using .Net 6.  I am using Microsoft.Azure.AppConfiguration.AspNetCore 4.5.1 and Azure.Identity 1.5.0

**Comment by avanigupta** [comment]
Thanks @bloechan, were you using the same package versions in your .NET 3 application?

**Comment by bloechan** [comment]
I did not report issues with 3.1.   But to answer your question, I did some timings with the same nuget versions with a 3.1 app and it took about 10 seconds.  In .net 6 it takes about 20 seconds.

**Comment by avanigupta** [comment]
In that case, we would need the perf traces for both your applications since we are not seeing the same delay on our side. Can you send us an email at AzureAppConfig@microsoft.com?

**Comment by drago-draganov** [comment]
@bloechan, a bit more context. We observed perf issues with Azure.Identity 1.5.0 ([details](https://github.com/Azure/azure-sdk-for-net/issues/24767)) in the range you are reporting here. Can you downgrade to Azure.Identity 1.4.0 and run your tests on dotnet 3.1 and dotnet 6?

**Comment by bloechan** [comment]
I .Net 6 application went from 20 seconds to 5 seconds when using Azure.Identity 1.4.0.  The .Net 3.1 application went from 10 seconds to 4 seconds.

**Comment by drago-draganov** [comment]
Thanks @bloechan!
Is it possible for you to use Azure.Identity 1.4.0 as mitigation, until the issue introduced in 1.5.0 is resolved?

**Comment by bloechan** [comment]
No problem.  Thanks for you help.

**Comment by drago-draganov** [comment]
Anytime! Thanks for helping us diagnose the root cause, @bloechan.

**Comment by drago-draganov** [comment]
External [perf issue](https://github.com/Azure/azure-sdk-for-net/issues/24767) introduced in Azure.Identity 1.15.0
