### ISSUE TITLE
Export error if no key-values are found

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#596]
If I try to export label or nolabel with a prefix and no key-values are found :
`az appconfig kv export`

I have these errors which fails my Azure DevOps task in a deployment pipeline :

![image](https://user-images.githubusercontent.com/25458469/149371071-af335357-ac6b-4b43-857c-5c5387cdc7b1.png)
![image](https://user-images.githubusercontent.com/25458469/149370134-68216756-c37a-4fad-8f19-c7fab8df59fc.png)

When can have an environment or a situation where there no pair key-valuers to deploy. It is not an Error.

Could you fix this error ? Or add a parameter to allow this case ?

Thank you for your help.

**Comment by avanigupta** [comment]
Hi @Philippe85, thanks for reporting this issue. Looks like this happens when the export command is run with the `--yes` option. We are working on the fix. In the meantime, you can run the command without the `--yes` option to avoid this error.

**Comment by Philippe85** [comment]
Ok, I wait your fix. I can't remove the `--yes` option because the command is run in an Azure DevOps pipeline to deploy applications.
Thanks

**Comment by Philippe85** [comment]
Hello,

I always wait your fix. My AzureDevOps pipelines always fails. How do you think to deliver the fix ?

Thanks

**Comment by avanigupta** [comment]
Hello @Philippe85, sorry about the delay. This fix should be included in the next CLI release.

**Comment by zhenlan** [comment]
@avanigupta has the fix been released?

**Comment by avanigupta** [comment]
Yes, this has been released in Azure CLI version 2.35.0 - [Release Notes](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/docs-ref-conceptual/release-notes-azure-cli.md#app-config).
