### ISSUE TITLE
Use App configuration as a feature toggle service?

### ISSUE THREAD

**Issue by David-Stark** [Azure/AppConfiguration#60]
Hello!

With a high chance that this question sounds like a stupid one. 

How well will App Configuration work as a simple feature toggle service? We look for a service that can help us to toggle a feature without we have to restart our app.

Thanks in advance

**Comment by yegu-ms** [comment]
@David-Stark App Configuration can be used to store feature toggles as configuration data. You'll need to do some work to consume the data as toggles in your application. We'll be releasing specific support for this use case very shortly. Please stay tuned! :)

**Comment by David-Stark** [comment]
Sounds great! 

Thanks for the fast response =)

**Comment by zhenlan** [comment]
@David-Stark we just rolled out feature management support. Plesae check it out.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core

Any feedback is welcome.

**Comment by zhenlan** [comment]
@chris-eg that's a reasonable scenario. Yes, we will allow labels for feature management just like key/values.
