### ISSUE TITLE
App Configuration Provider for Python

### ISSUE THREAD

**Issue by DhavalShewale** [Azure/AppConfiguration#600]
Currently `azure-appconfiguration` library return the secret uri for keyvault referenced secrects. App Config Provider library should be created for python so that these secrets should be auto-resolved

The issue was originally reported [**here**](https://github.com/Azure/azure-sdk-for-python/issues/21882)

**Comment by shenmuxiaosen** [comment]
We'd like to bring the feature parity to Python but the work is not trivial as we don't have a python provider at this moment. It's in our backlog and may not be available anytime soon. BTW, regarding to the original issue, for java provider we do offer resolving key vault reference. https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-spring-boot

**Comment by DhavalShewale** [comment]
@shenmuxiaosen Tks for the update. I am already using `azure-spring-cloud-appconfiguration-config` for spring boot apps. I was looking to find a similar provider for python apps, but based on your comment it seems we will have to wait for it.

**Comment by mrm9084** [comment]
https://github.com/Azure/AppConfiguration/issues/657

**Comment by mrm9084** [comment]
Beta Released: https://pypi.org/project/azure-appconfiguration-provider/

**Comment by arunAtCSGI** [comment]
When is this slated for a GA release? I want to use App Configurator with Python SDK but need to justify with my company - can only do that if it's GA

**Comment by mrm9084** [comment]
We don't have an exact date at the moment. We are currently finalizing a few things. We have a few changes that we want to make before the final release.

**Comment by mrm9084** [comment]
A new beta version has been released `azure-appconfiguration-provider 1.0.0b2`

**Comment by Sidewinder53** [comment]
The App Configuration Provider for Python is GA since March 9.

**Comment by mrm9084** [comment]
@Sidewinder53  @arunAtCSGI  Note: some breaking changes were made for the GA, check out the announcement for info and links. https://github.com/Azure/AppConfiguration-Announcements/issues/28
