### ISSUE TITLE
Azure portal blade intermittently fails to load / resource provider requests timeout

### ISSUE THREAD

**Issue by maskati** [Azure/AppConfiguration#605]
The App Configuration Azure Portal blade intermittently fails to load, with the cause being a timeout from the [Configuration Stores - Get](https://docs.microsoft.com/en-us/rest/api/appconfiguration/configuration-stores/get) operation. Following an approx. 20 second duration waiting for the blade to load, the following is shown in the portal:

![image](https://user-images.githubusercontent.com/21118898/153074623-ac2538fa-7f5c-4e5c-93d9-a50f30aa9fdd.png)

The same issue manifests across different tenants, subscriptions, resources and tiers (free and standard) over the last few weeks. Sufficient refreshes over a period of time eventually result in a successful call to get the configuration store metadata and load of the portal blade.

An example request (some details redacted):

`{"requests":[{"httpMethod":"GET","name":"46cd8065-0bc3-4f71-aa3a-8f4ef7568000","requestHeaderDetails":{"commandName":"Microsoft_Azure_AzConfig."},"url":"https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.AppConfiguration/configurationStores/xxxxxxxxxx?api-version=2021-03-01-preview"}]}`

And response:

`{"responses":[{"name":"46cd8065-0bc3-4f71-aa3a-8f4ef7568000","httpStatusCode":504,"headers":{"Pragma":"no-cache","x-ms-failure-cause":"service","x-ms-request-id":"feb9e6ff-d034-472a-85cf-5abcbf3a2ab4","x-ms-correlation-request-id":"034deaeb-1b7b-4d57-9812-273754246af6","x-ms-routing-request-id":"SWEDENCENTRAL:20220208T123929Z:feb9e6ff-d034-472a-85cf-5abcbf3a2ab4","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","Connection":"close","Cache-Control":"no-cache","Date":"Tue, 08 Feb 2022 12:39:29 GMT"},"content":{"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.AppConfiguration' within the specified time period."}},"contentLength":154}]}`

**Comment by jmal1** [comment]
Hi, thanks for reaching out! AppConfig does not support Sweden Central yet. It's in progress and will be available by the end of this quarter.

**Comment by maskati** [comment]
The App Configuration resources causing this issue are actually mostly in West Europe, which is a supported region. The `x-ms-routing-request-id` response header is indicating that the Azure Management operation (REST request) is routed through Sweden Central, since that is the closest geographic region to where the request originates (Finland).

Could the gateway timeout error be that the App Configuration resource provider (Microsoft.AppConfiguration) is in Sweden Central, but there is some routing issue from there to the actual App Configuration resource in West Europe?

**Comment by m4m4m4** [comment]
We are noticing the same problem
```
LnDfbnU2HJr2.js:10 [Microsoft_Azure_AzConfig]  09:14:34 Shared/HttpUtils 0 HttpUtils: Failed with batch operation, reason: content: {"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.AppConfiguration' within the specified time period."}}
contentLength: 154
headers: {"Pragma":"no-cache","x-ms-failure-cause":"service","x-ms-request-id":"761dcefc-6e38-4bc9-9710-dc30a95c8b59","x-ms-correlation-request-id":"4d823ecb-e1da-46e0-a301-cd110256a145","x-ms-routing-request-id":"SWEDENCENTRAL:20220209T081434Z:761dcefc-6e38-4bc9-9710-dc30a95c8b59","Strict-Transport-Security":"max-age=31536000; includeSubDomains","X-Content-Type-Options":"nosniff","Connection":"close","Cache-Control":"no-cache","Date":"Wed, 09 Feb 2022 08:14:34 GMT"}
httpStatusCode: 504
name: 204a264d-0ba8-4cc3-9d48-4d3609e4b000
```

**Comment by jmal1** [comment]
> The x-ms-routing-request-id response header is indicating that the Azure Management operation (REST request) is routed through Sweden Central, since that is the closest geographic region to where the request originates (Finland).

You're right. I misread the error

@maskati  @m4m4m4 - Thank you both for the error messages. We will look into the issues you're facing. 

@maskati, you mentioned West Europe. Please let us know if you see the issues elsewhere

**Comment by frli** [comment]
Same issue for us with app configuration service resources in West Europe and calls (people using the portal) originating from Sweden.

**Comment by cjohnsson** [comment]
Same issue, app config resource is in West Europe, trying to access them from Sweden.
Keep getting the error, retrying after a few minutes helps sometimes.

![image](https://user-images.githubusercontent.com/814161/153407433-7469efac-1a4a-46d3-9996-6cfec4869734.png)

**Comment by drago-draganov** [comment]
Update: 
Actively working on this. It's a top priority at the moment. Stay tuned!

**Comment by drago-draganov** [comment]
Update:
Should be back to normal. Please try again.

Thanks for your feedback!

**Comment by maskati** [comment]
@drago-draganov thanks! Seems to be working so far.

**Comment by drago-draganov** [comment]
Mitigated

**Comment by frli** [comment]
Thanks @drago-draganov 👍
