### ISSUE TITLE
Got access denied message

### ISSUE THREAD

**Issue by andreas-sommer-engenious** [Azure/AppConfiguration#606]
Hi,
I'm using the extension to read all key/values-pair from a DevOps-Pipeline. The DevOps-Server is running on premise. I created successfuly a service connection and set all role assignments in Azure. But I still get the following error:
##[error]Access to '[https://ac-xxx.io/kv?key=*&label=***&api-version=1.0'](https://xxx.io/kv?key=*&label=***&api-version=1.0%27) was denied. Please ensure the required role assignment is made for the identity running this task

When I check the permissions in the app configuration service, then the app registration has the contributor rights. I also tried the owner rights, which has no effects.
Do I have to set more API permissions to the app registration? If yes, which permissions do I need?

Thanks for the help.
Regards
Andreas

**Comment by avanigupta** [comment]
Hi @andreas-sommer-engenious, you need to assign `App Configuration Data Owner` or `App Configuration Data Reader` role to perform data operations like read/write/delete key-values. After assigning the role, please wait for 15 minutes before trying to access your data.
You can refer to [this document](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration) for more details.
