### ISSUE TITLE
App Configuration Load Order

### ISSUE THREAD

**Issue by IanDobsonDevfacto** [Azure/AppConfiguration#607]
Is there documentation for the order of operations when loading configuration?  At the moment we are using the following code and appsettings.json is loading AFTER the Azure App config, and we're unsure if that's intended behaviour or not.  This [document ](https://devblogs.microsoft.com/premier-developer/order-of-precedence-when-configuring-asp-net-core/) makes it clear which order things load in, but I can't see anything similar in terms of the Azure App Configuration.  

Here's our code:
 
```
public static IConfiguration GetConfiguration()
        {
            var isDevelopment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")?.ToLower() == "development";

            var configurationBuilder = new ConfigurationBuilder()
                .AddEnvironmentVariables()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
                

            if (isDevelopment)
            {
                configurationBuilder = configurationBuilder.AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: true);
            }

            configurationBuilder = configurationBuilder.AddAzureAppConfiguration(options =>
            {
                var creds = new DefaultAzureCredential(new DefaultAzureCredentialOptions());

                // filter app config variables to those with a label for our environment.
                // this should fallback to "dev" if the variable is not set in local development.
                var appConfigLabelFilter = Environment.GetEnvironmentVariable("appconfig_label_filter") ?? "dev";

                options.Connect(APP_CONFIG_URI, creds)
                       .Select(KeyFilter.Any, appConfigLabelFilter);

                options.ConfigureKeyVault(kvConfig =>
                {
                    kvConfig.SetCredential(creds);
                });
            });

            return configurationBuilder.Build();
        }
```

**Comment by avanigupta** [comment]
Hi @IanDobsonDevfacto, configuration providers that are added later override previous key values (last value wins). You can refer to [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-6.0) for more details.

For your code, the order of loading key-values will be:
 - Environment variables
 - appsettings.json file
 - Azure App Configuration
 - If `isDevelopment` is true,  appsettings.Development.json file

Can you confirm if you may be overriding App Config key-values with the ones in appsettings.Development.json?

**Comment by drago-draganov** [comment]
Do you have key in your AppConfiguration that has corresponding label, defined by this: 

```cs
                // filter app config variables to those with a label for our environment.
                // this should fallback to "dev" if the variable is not set in local development.
                var appConfigLabelFilter = Environment.GetEnvironmentVariable("appconfig_label_filter") ?? "dev";
```

If the key doesn't have the required label, it will not appear in the final Configuration.


Regardless appsetting.development.json override. That's intentional (convention) in .NET Core configuration [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0)

appsettings.Environment.json values override keys in _appsettings.json_. For example, by default:

In development, _appsettings.Development.json_ configuration overwrites values found in _appsettings.json_.
In production, _appsettings.Production.json_ configuration overwrites values found in _appsettings.json_. For example, when deploying the app to Azure.

**Comment by IanDobsonDevfacto** [comment]
Yes I do have a "dev" key in my app configuration.  

![image](https://user-images.githubusercontent.com/58046891/153680440-d338e645-060b-45c8-b95a-0c88fa8fcec0.png)

The problem is that the appsettings.json is overwriting the azure app configuration as well.

**Comment by drago-draganov** [comment]
What's the value of ``appConfigLabelFilter``?

**Comment by IanDobsonDevfacto** [comment]
"dev".  That value in azure app config WILL load, but only if I remove the key from appsettings.development.json as well as appsettings.json.

**Comment by drago-draganov** [comment]
Can you set ``reloadOnChange = false`` for both AddJsonFile?

**Comment by IanDobsonDevfacto** [comment]
Updating the code to appear as so:

```
 public static IConfiguration GetConfiguration()
        {
            var isDevelopment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")?.ToLower() == "development";

            var configurationBuilder = new ConfigurationBuilder()
                .AddEnvironmentVariables()
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: false)
                .AddAzureAppConfiguration(options =>
                {
                    var creds = new DefaultAzureCredential(new DefaultAzureCredentialOptions());

                    // filter app config variables to those with a label for our environment.
                    // this should fallback to "dev" if the variable is not set in local development.
                    var appConfigLabelFilter = Environment.GetEnvironmentVariable("appconfig_label_filter") ?? "dev";

                    options.Connect(APP_CONFIG_URI, creds)
                           .Select(KeyFilter.Any, appConfigLabelFilter);

                    options.ConfigureKeyVault(kvConfig =>
                    {
                        kvConfig.SetCredential(creds);
                    });
                });

            if (isDevelopment)
            {
                configurationBuilder = configurationBuilder.AddJsonFile("appsettings.Development.json", optional: true, reloadOnChange: false);
            }

            return configurationBuilder.Build();
        }
```

Still leads to appsettings being loaded after the azure config.

**Comment by IanDobsonDevfacto** [comment]
That's very frustrating.  Even with updating to .NetCore 5.0, using version 5.0 of `Microsoft.Extensions.Configuration.AzureAppConfiguration`, setting `reloadOnChange` to false and removing the `isDevelopment` check entirely I still get the normal appsettings,json file before Azures.  Not sure if there's a remedy.

**Comment by drago-draganov** [comment]
@IanDobsonDevfacto we will get to the bottom of this.

Can you email me or put your full repro app in github repo?

Please, make sure to remove all config store and security related stuff (endpoints, connection strings, etc.)

**Comment by zhenlan** [comment]
Please reopen if there are any updates about this issue.
