### ISSUE TITLE
Invalid Client

### ISSUE THREAD

**Issue by xUborka** [Azure/AppConfiguration#608]
Heyho,
im trying to use the AzureAppConfiguration@5 task from an azure devops pipeline. We have a service connection (already tested & working) and the service principal has the App Configuration Data Owner role.
The app config endpoint is set ('https://[my-app-config].azconfig.io'), but we are getting the following error: "##[error]Error: invalid_client" (Client assertion audience claim does not match Realm issuer) 

Any ideas why?
Thanks!

**Comment by MaryanneNjeri** [comment]
Hello @xUborka , apologies for the delayed response and thank you for reaching out. I've been able to reproduce the issue you are currently facing. Currently looking into it. In case you are blocked, you can use client secret to authenticate in the meantime.

**Comment by MaryanneNjeri** [comment]
Hi @xUborka, we have a new release [Azure App Configuration 
@5.2.0 ](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task) that addresses the fix for the issue, please check it out . Feel free to reach out incase you experience any issues.

**Comment by jimmyca15** [comment]
The new release should fix this issue. Please reach out if there are any other problems.
