### ISSUE TITLE
Initial Configuration is not loaded at the first shot

### ISSUE THREAD

**Issue by dawwa** [Azure/AppConfiguration#61]
**Step 1:**  Add a configuration MySetting=1 from Azure Portal
**Step 2:**  Started the application and wait until fully loaded, observed MySetting is null
**Step 3:**  Wait 30 seconds and check the MySetting value, it is still null
**Step 4:**  Change the configuration to MySetting=0 from Azure Portal and wait for 30 seconds
**Step 5:**  Mysetting reads 0 now

**Problem:**
You can see the Step#4 acts as a trigger while I'm expecting the value is supposed to be loaded since Step#2 if it can load whatever initial value it is in the configuration store without having to change the configuration as a trigger.

**Comment by zhenlan** [comment]
@dawwa could you please share the code snippet (remove connection string) that is related to how you consume the app config store?

**Comment by dawwa** [comment]
@zhenlan, pretty much like what the tutorial does. 
```
public static void ConfigConfiguration(WebHostBuilderContext ctx, IConfigurationBuilder config)
{
...
var dynamicSettingEndpoint = Environment.GetEnvironmentVariable("DynamicSettingEndpoint");`
// Non Development Environment: Config the Azure Application Configuration through MSI with the supplied endpoint`
                   ` config.AddAzureAppConfiguration(options =>
                    {
                        options.ConnectWithManagedIdentity(dynamicSettingEndpoint)
                            .Use(keyFilter: "DynamicSettings:*")
                            .Watch("DynamicSettings:LUIS_ENV", label: BuildUtil.GetBuildVersion()); // Default internal is 30 seconds turnaround
settings = config.Build();
}
```


```
public HomeController(IOptionsSnapshot<DynamicSettings> dynamicSettings)
        {
            this._dynamicSettings = dynamicSettings.Value;
        }
        public async Task<IActionResult> Index()
        {
          // The value is NULL until I change the config value from Azure Portal or CLI
           ViewData["NLP_ENDPOINT"] = _dynamicSettings.LUIS_ENV;
           ...
        }
 
```

**Comment by zhenlan** [comment]
Hi @dawwa, when the value of the `labelFilter` parameter is not provided, the [`Use(keyFilter, labelFilter)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.use?view=azure-dotnet-preview) function will use *null label (no label)* as the default value. Therefore, in your code, you only load keys with no label for app start-up. Your `Watch(...)` function, however, is watching a key with the label `BuildUtil.GetBuildVersion()`. Watch won't start until the first poll interval time has passed. This is why you don't see your watched key initially but see it 30 seconds later.

If you can share the scenario you intend to achieve, maybe I can share some recommendation.

**Comment by dawwa** [comment]
@zhenlan, thanks for the details, and what you suggested perfectly resolve my issue. : )
