### ISSUE TITLE
Unexpected Behavior When Applying Labels Using .net Client With Null Label Overrides

### ISSUE THREAD

**Issue by landonbass** [Azure/AppConfiguration#610]
**Problem Summary:**

When applying labels conditionally (based on environment variables), if the label string is null or empty, the last label created is applied.

**Expected Outcome:**
The no label value would be applied.

**Actual Outcome:**
The last label created is applied.

**Reproduction Steps:**
- Create a key-value with no label
- Add a value with a label
- Conditionally register the label

``` cs
options
.Select(KeyFilter.Any, LabelFilter.Null)
.Select(KeyFilter.Any, builder.Configuration.GetValue<string>("ConfigLabelOverride"));
```
**Workaround:**
Checking the value before applying resolved this issue, but this is not fail-safe behavior. I would not expect a labeled value to be applied if no matching label is used to select the values.

``` cs
options
.Select(KeyFilter.Any, LabelFilter.Null);
 
var labelOverride = builder.Configuration.GetValue<string>("ConfigLabelOverride");
if (!string.IsNullOrEmpty(labelOverride))
{
   options.Select(KeyFilter.Any, labelOverride);
}
```

**Comment by drago-draganov** [comment]
``Select`` isn't conditional operation. It applies the specified filter. Passing ``null`` is the same as  LabelFilter.Null (valid input).
Multiple ``Select`` perform configuration composition - the last existing wins. 

If you need conditional filtering, extending AzureAppConfigurationOptions is decent alternative.


```cs
static class AzureAppConfigurationOptionsExtentions
{
    public static AzureAppConfigurationOptions SelectIf(
        this AzureAppConfigurationOptions options, 
        string keyFilter, 
        string labelFilter, 
        Func<string, string, bool> predicate)
    {
        if (predicate == null) 
        {
            throw new ArgumentNullException(nameof(predicate));
        }

        if (predicate(keyFilter, labelFilter))
        {
            return options.Select(keyFilter, labelFilter);
        }

        return options;
    }
}
```

**Usage**

```cs
options
.Select(KeyFilter.Any, LabelFilter.Null)
.SelectIf(KeyFilter.Any, builder.Configuration.GetValue<string>("ConfigLabelOverride"), (keyFilter, labelFilter)=> !string.IsNullOrEmpty(labelFilter));
```

Hope that helps.

**Comment by landonbass** [comment]
Yes this works - I am just surprised that the default behavior would be to return the newest label if a null selector is used. Closing the issue since there is a workaround.

**Comment by drago-draganov** [comment]
Keep in mind that ``null`` is valid value for label. ``Select` composition doesn't get the newest label, but rather the last one specified in Select sequence. That's the composition I mentioned. The idea behind is to allow hierarchical setup. Something like this:

```cs
options
    .Select(KeyFilter.Any, LabelFilter.Null)
    .Select(KeyFilter.Any, "prod")
    .Select(KeyFilter.Any, "version3")
```

1. Get items that don't have label (null label) - think of common app defaults
2. Get items with label ``prod`` and override any existing prior - default production settings
3. Get items with label ``version3`` and override any existing prior- specific settings for westus deployment

Here is an example config:

key=maxCacheSize (label: null), value=1MB
key=maxCacheSize (label: "prod"), value=5MB (production defaults)
key=maxCacheSize (label: "version2"), value=7MB (implementation improved) 
key=maxCacheSize (label: "version3"), value=12MB (great implementation) 
key=enableCacheEncryption(label: "version3"), value=true

**Comment by drago-draganov** [comment]
@landonbass, upon further investigation we found indeed an issue related to passing empty string as label filter. Please refer to https://github.com/Azure/AppConfiguration-DotnetProvider/issues/311

Apologies for my misunderstanding. 

Thanks for your feedback!
