### ISSUE TITLE
syntax keyfilter in .Select

### ISSUE THREAD

**Issue by sabbadino** [Azure/AppConfiguration#613]
in the documentation of themethid it's written : 
 // Parameters:
        //   keyFilter:
        //     The key filter to apply when querying Azure App Configuration for key-values.
        //     The characters asterisk (*), comma (,) and backslash (\) are reserved and must
        //     be escaped using a backslash (\). Built-in key filter options: Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyFilter.
        
        still i see that mykeysprefix* works "as expected , with * as a wildcard
        
        what is the supported syntax for filters ?

**Comment by zhenlan** [comment]
`mykeysprefix*` will get you all keys that start with "mykeysprefix".

If you want the key with the name "mykeysprefix*", you will have to escape the asterisk like `mykeysprefix\*`

**Comment by sabbadino** [comment]
Thanks , as far as I can tell, there is no documentation /  samples on the query syntax

**Comment by zhenlan** [comment]
The API document can be found here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.select?view=azure-dotnet#microsoft-extensions-configuration-azureappconfiguration-azureappconfigurationoptions-select(system-string-system-string)

The same can also be found at REST API documentation
https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value#filtering

**Comment by jimmyca15** [comment]
@sabbadino I see how that could be confusing. At a glance it can make it seem that using '*' for wildcard is not allowed. 

@zhenlan I think we may be able to change the wording on KeyFilter description to clear it up a bit.

**Comment by sabbadino** [comment]
That's exactly my point .
I think API documentation is more correct on the matter

**Comment by jimmyca15** [comment]
We put out the following summary update to help alleviate the confusion: https://github.com/Azure/AppConfiguration-DotnetProvider/pull/313

**Comment by sabbadino** [comment]
rest API documentation 

https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value#filtering

also mention this 

key=abc,xyz | Matches keys names abc or xyz (limited to 5 CSV)
-- | --
I cannot see this mentioned in the update

**Comment by jimmyca15** [comment]
Hello @sabbadino

You are right. Although I don't expect that usage much in the configuration provider which is used mostly for querying complete configuration sets. I'm wondering if maybe we should keep it excluded for simplicity?

**Comment by sabbadino** [comment]
I agree, i personally see real use cases for label filleting , but not for keys.. still ,if underlying API support it, just copy and paste rest API documentation :)

**Comment by jimmyca15** [comment]
The new wording should help clarify the usage of '*' in the key filter. I don't think we want to update the summary to be anymore verbose given the expected usage. The label filter in the .NET provider does not allow commas. I believe key filter should be easier to understand now for users, I will go ahead and close this.
