### ISSUE TITLE
Accessing AppConfiguration from on-premise / Registered App

### ISSUE THREAD

**Issue by oyvindi** [Azure/AppConfiguration#614]
We got a few services running on-premise, but uses Azure services. 

Is it possible to access App Configuration in the same manner as KeyVault, by simply using  Registered App / ClientCertificateCredential ?

At the moment, I 
1) Store the connection string in KeyVault
2) Fetch the connection string (synchronously) with SecretClient during startup
3) Add App Configuration based on connection string

I feel this is somewhat hacky though..

**Comment by jimmyca15** [comment]
@oyvindi Yes Azure App Configuration supports [AAD Authentication](https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-azure-ad).

To enable the identity that you would like to authenticate as with the `ClientCertificateCredential` to access Azure App Configuration make sure to assign one of the [App Configuration data plane roles](https://docs.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authorization-azure-ad#roles).

**Comment by jimmyca15** [comment]
Thanks for reaching out. Feel free to re-open if the issue hasn't been addressed.

**Comment by oyvindi** [comment]
Hi, sorry for delayed response.

This is what I tried:

In my App Configuration, I enabled "App Configuration Data Reader" for the registered app.

Client code (using the endpoint URL from "Access Keys"):

```
var credentials = new ClientCertificateCredential(azureConfig.DirectoryId, azureConfig.ApplicationId, cert);
var uri = new Uri("https://some-config.azconfig.io");
config.AddAzureAppConfiguration(options => options.Connect(uri, credentials).UseFeatureFlags());
```

This gives me:
 _=> Unhandled exception. Azure.RequestFailedException: Service request failed.
Status: 403 (Forbidden)_

**Comment by jimmyca15** [comment]
There can be a ~15 minute propagation period between assigning the role and when the permissions are ready. Can you confirm that the request happened after that time window?

**Comment by oyvindi** [comment]
> There can be a ~15 minute propagation period between assigning the role and when the permissions are ready. Can you confirm that the request happened after that time window?


Yep, been a week now ! :D

**Comment by jimmyca15** [comment]
The code looks good. The only way I would expect this to return an HTTP 403 response is if the role is not assigned to the applicationId being used in the ClientCertificateCredential or if you have private endpoints enabled.
