### ISSUE TITLE
Allow the AzureDevOps extension to extract multiple labels at once

### ISSUE THREAD

**Issue by tap1992** [Azure/AppConfiguration#615]
Currently the Azure DevOps extension doesn't allow * or , in the label filter limiting us to have to run the task multiple times to extract config with different labels.

It would be really useful if this functionality could be added.

**Comment by jimmyca15** [comment]
Thanks for the suggestion @tap1992. In your case, if the the same key gets pulled with two different labels are you looking for one to override the other in the DevOps variables or are you looking for both to be available?

**Comment by tap1992** [comment]
Thanks for getting back to me. 

In our scenario we wouldn't have duplicates as we have environments that share some config but also have some that are dedicated. We want to extract the values against the specific env label as well as a 'shared' label, but where the shared label exists there isn't any specific env labels. 

Currently I am working around this by running the App Config task 3 times with the different label defined each time, so would be convenient if I could just run it the once with the labels separated by comma.

I guess if there was a scenario whereby there was both types of labels available within a single key, maybe display an error? as nether overriding or making both available would provide consistency in a pipeline (not being able to know for sure which variable you've picked up for use).

**Comment by jimmyca15** [comment]
@tap1992 thanks for the suggestion. This is an improvement we can track for the DevOps extension.

In our configuration providers that support multiple queries to Azure App Configuration in a single flow we default to overriding keys when they exist in two labels. Most likely we would do this DevOps. It would behave similarly as if you ran the dev ops extension twice, as you are now, and had the same key in different labels.

**Comment by tap1992** [comment]
Works for me! Thankyou very much!

**Comment by MaryanneNjeri** [comment]
@tap1992 , thank you for the suggestion, after careful consideration, we will not be able to support this feature. Implementing it could lead to key-values with the same label getting overwritten, which would cause significant issues, like affecting consistency in a pipeline.
