### ISSUE TITLE
Do not overide feature flag already present in app configuration while pushing via azure pipeline

### ISSUE THREAD

**Issue by psollaud** [Azure/AppConfiguration#620]
I'm trying to push feature flags from an azure pipeline via the "Azure App Configuration Push" extension.
I have created a json file in my repo containing all feature flag definition like the following:
`{
  ".appconfig.featureflag/f3": "{\"id\":\"f3\",\"description\":\"\",\"enabled\":false,\"conditions\":{\"client_filters\":[]}}"
}`

It is working fine to create new feature flag that does not exists.
For those that are already present in azure app configuration, they are overriden. 
I can't remove the `"enabled": false` from the json file, otherwise the feature flag is not well created.

That means that every deployment will disabled all existing flags.

Could it be possible to manage a way to update feature flags except the "enabled" field ?

**Comment by zhenlan** [comment]
@psollaud this is not supported. When you choose to use files as your "source of truth", you should manage all your data via files, which includes enabling/disabling feature flags.

**Comment by psollaud** [comment]
thanks @zhenlan for your reply. I'll try with az cli commands then.
