### ISSUE TITLE
How to convert Microsoft.Identity.Web to Azure.Core?

### ISSUE THREAD

**Issue by v-kentro** [Azure/AppConfiguration#621]
How can I use a token retrieved using the Microsoft.Identity.Web library (TokenAcquisition.GetAuthenticationResultForUserAsync) to authenticate an Azure.Data.AppConfiguration.ConfigurationClient? It seems to only accept implementations of Azure.Core.TokenCredential, but I don't see a way of creating one of the provided implementations with the data I have.

_Originally posted by @AerikAwesome in https://github.com/Azure/AppConfiguration/issues/338#issuecomment-712657628_

**Comment by v-kentro** [comment]
The more general question is where to find an implementation of `TokenCredential` that uses the Microsoft identity platform.

**Comment by zhenlan** [comment]
Issue moved to [Azure/azure-sdk-for-net #27642](https://github.com/Azure/azure-sdk-for-net/issues/27642) via [**ZenHub**](https://www.zenhub.com/)
