### ISSUE TITLE
Migrating feature flags/configuration between App Configuration Service resources 

### ISSUE THREAD

**Issue by TharinduK** [Azure/AppConfiguration#622]
what is the recommended method to migrate feature setting setup under feature flag or configuration setting to a different app config environment.  We currently have multiple development environments (QA, UAT, Production). We have setup individual app configuration service resources  for each environment (different access control rules based on environment).    When we have completed validation of the feature in QA, all the related settings need to be migrated to UAT (and then in turn to production).  Currently there is no good way to do that.   (import/export can work however its lot of manual work)

It would be better if there is a way to combine several app configuration resources, so each resource knows the others, and have option in UI to migrate certain setting to the app configuration of the higher level. If there is a way to do this already please let me know. If not, could you please add a way to easily migrate setting from environment to environment.  I am assuming this is a common use case.

Thank you

**Comment by zhenlan** [comment]
@TharinduK the scenario you described makes sense to me. You can bulk-import key-values from one App Configuration store to another using Azure CLI today. Please let us know if that's a viable solution for you. We are adding the same support in Azure Portal tracked by the issued @avanigupta shared above.

**Comment by zhenlan** [comment]
Close this one. The request is tracked in #192.
