### ISSUE TITLE
Azure app configuration Cli parsing issue for feature filter

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#623]
Azure app configuration

i want to insert following feature filter in the app configuration with CLI but Users arrage section is not getting parsed correctly please help me .
{
"id": "check",
"description": "",
"enabled": true,
"conditions": {
"client_filters": [
{
"name": "Microsoft.Targeting",
"parameters": {
"Audience": {
"Users": [
"[a.n@c.com](mailto:a.n@c.com)",
"[d.g@f.com](mailto:d.g@f.com)"
],
"Groups": [],
"DefaultRolloutPercentage": 0
}
}
}
]
}
}

Command i used

az appconfig feature filter add -n azureDBconfig --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={"DefaultRolloutPercentage":0,"Users"= ["[d.g@f.com](mailto:d.g@f.com)","[a.n@c.com](mailto:a.n@c.com)"]}

Minimum API Version Required
azure-cli 2.30.0 *

core 2.30.0 *
telemetry 1.0.6

**Comment by avanigupta** [comment]
Hi @Bhanu88, the filter parameter value should be a JSON escaped string. Something like this:
`az appconfig feature filter add -n azureDBconfig  --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={\"DefaultRolloutPercentage\":0,\"Users\":[\"d.g@f.com\",\"a.n@c.com\"]}`
