### ISSUE TITLE
adding or deleting a specific user or group in Azure app configuration feature filter CLI

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#628]
i created a filter by following command in azure app configuration 

`az appconfig feature filter add -n azureDBconfig --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={\"DefaultRolloutPercentage\":0,\"Users\":[\"d.g@f.com\",\"a.n@c.com\"]}`

```
{
	"id": "check",
	"description": "",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "Microsoft.Targeting",
				"parameters": {
					"Audience": {
						"DefaultRolloutPercentage": 0,
						"Users": [
							"d.g@f.com",
							"a.n@c.com"
						]
					}
				}
			}
		]
	}
}
```

now i want to add d.q@c.com and delete d.g@f.com from the user list without affecting any other attribute of the feature

`az appconfig feature filter add -n azureDBconfig --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={\"DefaultRolloutPercentage\":0,\"Users\":[\"d.q@c.com\",\"a.n@c.com\"]}`

But when i am trying to do the same the new list is getting appended below the previous list rather than updating .

```
{
	"id": "check",
	"description": "",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "Microsoft.Targeting",
				"parameters": {
					"Audience": {
						"DefaultRolloutPercentage": 0,
						"Users": [
							"d.g@f.com",
							"a.n@c.com"
						]
					}
				}
			},
			{
				"name": "Microsoft.Targeting",
				"parameters": {
					"Audience": {
						"DefaultRolloutPercentage": 0,
						"Users": [
							"d.q@c.com",
							"a.n@c.com"
						]
					}
				}
			}
		]
	}
}

```
 i want the end result like 

```
{
	"id": "check",
	"description": "",
	"enabled": true,
	"conditions": {
		"client_filters": [
			{
				"name": "Microsoft.Targeting",
				"parameters": {
					"Audience": {
						"DefaultRolloutPercentage": 0,
						"Users": [
							"d.q@c.com",
							"a.n@c.com"
						]
					}
				}
			}
		]
	}
}
```

**Comment by avanigupta** [comment]
Hi @Bhanu88, thanks for the feedback! We will add this capability in Azure CLI and keep you posted. 
In the meantime, you can achieve this in 2 steps:
1. Delete the existing filter named "Microsoft.Targeting":
- `az appconfig feature filter delete -n <storeName> --feature <featureName> --filter-name Microsoft.Targeting`
3. Add a new filter called "Microsoft.Targeting" with the updated filter params:
- `az appconfig feature filter add -n azureDBconfig --feature check --filter-name Microsoft.Targeting --filter-parameters Audience={\"DefaultRolloutPercentage\":0,\"Users\":[\"d.q@c.com\",\"a.n@c.com\"]}`

**Comment by Bhanu88** [comment]
@avanigupta thanks for the workaround i will wait for the enhancement

**Comment by albertofori** [comment]
@Bhanu88  The feature filter update functionality is available in preview now with azure-cli version 2.41.0

**Comment by Bhanu88** [comment]
Thanks for the update and I will check and update here

**Comment by Bhanu88** [comment]
its working as expected
