### ISSUE TITLE
Sentinel key not refreshing configuration but interval refreshes

### ISSUE THREAD

**Issue by schen1880** [Azure/AppConfiguration#634]
I had dynamic app configuration working but then added some new keys and now the sentinel key does not seem to be refreshing the values. I ended up starting a new project and brand new app configuration and it still will not refresh using the sentinel key. I feel like I might be missing something but not sure what it could be.

I've tried creating a sentinel key with both a label and without but neither work. The values do update every minute.

The removal of the sentinel key stops the keys from refreshing at all so it should be picking up the sentinel key, just not sure why changing the sentinel key will not update the config values anymore.

Thanks for any help with this.

builder.Host.ConfigureAppConfiguration((hostingContext, config) =>
{
    var settings = config.Build();

    config.AddAzureAppConfiguration(options => 
    {
        options.Connect(settings.GetConnectionString("AppConfig"))
               .Select("MortgageSurveyService*", hostingContext.HostingEnvironment.EnvironmentName)
               .ConfigureRefresh(refresh =>
               {
                   //refresh.Register(key: "MortgageSurveyService:Sentinel", label: "Development", refreshAll: true)
                   refresh.Register(key: "MortgageSurveyService:Sentinel", label: LabelFilter.Null, refreshAll: true)
                          .SetCacheExpiration(cacheExpiration: new TimeSpan(0, 1, 0));
               });
    });
});

builder.Services.Configure<Settings>(builder.Configuration.GetSection("MortgageSurveyService"));
builder.Services.AddAzureAppConfiguration();

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAzureAppConfiguration();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

![image](https://user-images.githubusercontent.com/49198953/166269500-b9706b5a-6e0b-490b-bf8a-3439ea1ecb55.png)

**Comment by avanigupta** [comment]
Hi @schen1880 ,  
In your `Select()` clause, you are loading all key-values starting with `MortgageSurveyService*` and label ` hostingContext.HostingEnvironment.EnvironmentName`. But in your `refresh.Register()` method, you are registering the sentinel key with label `Development`. 

Is it possible that you actually want to register the same label as your `Select` clause? 

```
config.AddAzureAppConfiguration(options => 
{
    options.Connect(settings.GetConnectionString("AppConfig"))
           .Select("MortgageSurveyService*", hostingContext.HostingEnvironment.EnvironmentName)
           .ConfigureRefresh(refresh =>
           {
               refresh.Register(key: "MortgageSurveyService:Sentinel", label: hostingContext.HostingEnvironment.EnvironmentName, refreshAll: true)
                      .SetCacheExpiration(cacheExpiration: new TimeSpan(0, 1, 0));
           });
});
```

Also, can you confirm if there were any changes to your code or AppConfig library version when you started noticing this issue?

**Comment by schen1880** [comment]
@avanigupta thanks for your help.

I checked again and it looks like I just misunderstood how the sentinel key worked. I was under the impression the sentinel key would trigger a refresh or the cache expiration would trigger a refresh but it only checks the sentinel key after the cache expires.
