### ISSUE TITLE
KVSet Profile in Portal

### ISSUE THREAD

**Issue by nareshkaloha** [Azure/AppConfiguration#636]
Hello ,

When exporting/importing through the portal , there is no option to specify the profile . Is this is something that will be supported in future ?

Thank You!

**Comment by zhenlan** [comment]
@nareshkaloha yes, the KVSet profile will be supported in the portal in the future. The work is tracked in #552. As noted in the document, it is only supported in CLI for now.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-config-file#file-content-profile-kvset
