### ISSUE TITLE
Feature Management for all frameworks

### ISSUE THREAD

**Issue by calloncampbell** [Azure/AppConfiguration#64]
This is a great feature and I'm wondering if Feature Management will come to the other framework (.NET Core, .NET, Azure Functions, Java)?

**Comment by zhenlan** [comment]
Thanks, @calloncampbell. The short answer is yes, we do plan to make it available to all popular frameworks.

Please note, the `Microsoft.FeatureManagement` is a .NET Standard library, which means it already can be used in ASP.NET Core, .NET Core, .NET Framework and Azure Functions written in .NET.
