### ISSUE TITLE
Azure App Configuration Task error "ClientConfigurationError: untrusted_authority"

### ISSUE THREAD

**Issue by jtterry2856** [Azure/AppConfiguration#641]
I am receiving below error when using the Azure App Configuration Task (5.2.0) in a deployment job. This job is running on on-prem server behind a proxy using self-hosted azure devops agent (2.202.1) with Agent.ProxyUrl set to proxy used for that server.

`##[error]An unexpected error occurred. endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.`

![ProxySetup](https://user-images.githubusercontent.com/29108797/167862725-132b185c-d12e-41d9-9cbe-3b29fdd2f7e3.png)

![TaskError](https://user-images.githubusercontent.com/29108797/167862789-3f465b4e-db82-4eab-ba0f-5a19075972d1.png)

**Comment by MaryanneNjeri** [comment]
Hi @jtterry2856, thank you for reaching out. Apologies for the delayed response. Currently looking into the issue you are experiencing.

**Comment by MaryanneNjeri** [comment]
@jtterry2856 might you be  using an authenticated proxy if yes please set authenticate proxy credential through the environment variable
`VSTS_HTTP_PROXY_USERNAME` and `VSTS_HTTP_PROXY_PASSWORD`. 
Might I also suggest a workaround for  [Using VSTS Agent behind Proxy](https://github.com/microsoft/azure-pipelines-agent/blob/61b82a80f224e444932e1a830ca49276872f3c54/docs/start/proxyconfig.md)

**Comment by jtterry2856** [comment]
@MaryanneNjeri thanks for quick response on this. Do you have eta when we can expect to see updated version of the task with the change?

**Comment by MaryanneNjeri** [comment]
@jtterry2856 its a bit hard to give an eta since msal node is a dependecy to [azure/identity](https://www.npmjs.com/package/@azure/identity) which is a library we use. I have already filed a Github issue [#21867](https://github.com/Azure/azure-sdk-for-js/issues/21867) I can follow up with.

Also I came across this [workaround](https://github.com/microsoft/azure-pipelines-agent/blob/61b82a80f224e444932e1a830ca49276872f3c54/docs/start/proxyconfig.md) please let me know if this helps.

**Comment by MaryanneNjeri** [comment]
@jtterry2856 @azure/identity got back, the eta to see the updated version is 3 to 4 weeks.

**Comment by jtterry2856** [comment]
@MaryanneNjeri thanks for the update. I will give the work around a try

**Comment by zhenlan** [comment]
@MaryanneNjeri is this issue addressed? Can it be closed?

**Comment by MaryanneNjeri** [comment]
Yes, we can close the issue. We reference [msal-node version 1.6.0](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/CHANGELOG.md#160)
