### ISSUE TITLE
Question : Overriding secrets with local appsettings.json file

### ISSUE THREAD

**Issue by nareshkaloha** [Azure/AppConfiguration#643]
Hello ,

We are exploring the app config service before we can start using in our org applications .We would like to load the keys/secrets from local appsettings.json file and then from the app config store. This works fine in case of regular keys .Keys get loaded from the local file when config store is unavailable .The local file settings is overridden when config store is available .The code can refer to the regular key with the same key name . 'AppFileAndConfigStoreKey ' for an example below.

<h4>AppFileAndConfigStoreKey = @Configuration["AppSettings:AppFileAndConfigStoreKey"]</h4>

But the key name is not same in case of a secret. For  config store , I can refer the key as below -

<h4>From config store --> AppFileAndConfigStoreSecret = @Configuration["AppSettings:AppFileAndConfigStoreSecret"]</h4>
This correctly fetches the secret from the config secret.

To get the same secret from the local file -->
<h4>From app fille --> AppFileAndConfigStoreSecret = @Configuration["AppSettings:AppFileAndConfigStoreSecret:uri"]</h4>

appsettings.json file below -- >

{
  "AppSettings": {   
    "AppFileAndConfigStoreSecret": {
      "uri": "secret from local file"
    }
  }
}
So its "AppFileAndConfigStoreSecret:uri" (when using the local file ) and "AppFileAndConfigStoreSecret" (when using the config store) and this fails our use case to load the settings from both - local file and config store without any code changes.

We can not remove "uri" from the local file as we have planned to import these during CICD and secret are not set up correctly without the "uri" property in json during the import.

Thanks for your help on this.

**Comment by avanigupta** [comment]
Hi @nareshkaloha, the Key Vault references in App Config contain a reference to the secret which is stored in KeyVault. You are not actually storing the secret value in AppConfig. The `Microsoft.Extensions.Configuration.AzureAppConfiguration` library fetches the secret value for you so you dont have to write the code yourself to fetch secrets from KeyVault.  The "uri" field in AppConfig is just a URI that points to the secret in KeyVault. 

From your example, your appsettings.json file should also contain the **_secret URI_** if you are planning on using the same file to import to AppConfig.
```
{
  "AppSettings": {
  "AppFileAndConfigStoreSecret": {
    "uri": "<KEY VAULT SECRET URI>"
    }
 }
}
```

As for the usage, if you want to use appsettings.json file to get secret value from KeyVault, you'll need to implement your own logic to read the "uri" from the file, and get the value of that secret from KeyVault. 
For example, if you define a method called `GetSecretFromKeyVault` which gets the secret value from KeyVault, you can do this:
```
AppFileAndConfigStoreSecret = GetSecretFromKeyVault(@configuration["AppSettings:AppFileAndConfigStoreSecret:uri"])
```

**Comment by nareshkaloha** [comment]
Hi Avani , thanks for your reply. Yes , we need to fetch secrets from the KV on start up. We thinking of this option or export all the config data during CICD with resolve-kevault parameter, place this file on the application root directory and first read from it. Thanks!
