### ISSUE TITLE
LabelFilter to get all labels for a configuration

### ISSUE THREAD

**Issue by anza19** [Azure/AppConfiguration#647]
Hello,

I have a question regarding the `LabelFilter` that we set up with `.Select(key, label)` at `Startup.cs` to get key-value pair from App Configuration.

This class exposes a `Null` label that loads configuration with no label for a specific key. Does there exist a filter that can get us **all** the labels for a configuration? My use case is to get all the labels for a configuration and currently what I do, is after start-time re-establish a new connection to Configuration store to get these, is it possible to do this at startup by providing a label filter that will fetch **all** the labels for a key-value pair?

**Comment by zhenlan** [comment]
The short answer is no, but for a reason. Maybe you can answer the question below to help us understand what you are trying to achieve.

Data retrieved from App Config is put into `IConfiguration`, which supports one value for one key. If you had multiple values (corresponding to multiple labels) of a key retrieved from App Config, which value would you want it to be put in `IConfiguration`?

**Comment by anza19** [comment]
Hello, thank you so much for getting back to me so quick.

So, our use case is such that we get the label from a request and I was hoping I could say get a list of all the values of a configuration, at startup, and then match the label from the request to configurations loaded into `IConfiguration.`

I hope I was able to explain the use case well enough.

**Comment by zhenlan** [comment]
`IConfiguration` doesn't give you a way to store or search more than one value for a given key.

In your scenario, you probably shouldn't use the label to differentiate key-values for different requests. You can use prefix to your key names instead. This way you can retrieve all key-values with different prefixes at once in startup and then you can find the key that matches the prefix coming from a request in `IConfiguration`. Check out this document in deciding when you should use labels and when you should use prefixes (namespaces).

https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value
