### ISSUE TITLE
Config value invisible

### ISSUE THREAD

**Issue by ddobric** [Azure/AppConfiguration#65]
Every time I create a config value with TAG and not specified CONTENTTYPE, configuration value cannot be read by .NET Core client.

Example: Read all config values:
```
config.AsEnumerable().ToArray()
{System.Collections.Generic.KeyValuePair<string, string>[3]}
    [0]: {[SbConnStr,  "Endpoint=sb://bastasample.servicebus.windows.net/;SharedAccessKeyName=demo;SharedAccessKey=MvwVbrrJdsMQyhO/0uwaB5mVbuXyvYa3WRNpalHi0LQ=";]}
    [1]: {[Prop1, 12344]}
    [2]: {[jsonProp, { "prop1": "str", "prop2": { "prop21: 12, "prop22": "aa" } }]}
```

Missing value is AAA:
![image](https://user-images.githubusercontent.com/1756871/57984627-fad01980-7a5d-11e9-9231-88a38318a6e2.png)

Not sure what exact behaviour should be. Do we need to specifiy content type or it is optional value?

**Comment by zhenlan** [comment]
Hi @ddobric, the **ContentType** is _optional_ so is **Tag**. In your example, however, I noticed you had **label** `aaa` for the key `AAA`, so in your .NET Core code, you must specify label `aaa` for the key `AAA` to be loaded. Please check out https://github.com/Azure/AppConfiguration/issues/43#issuecomment-471335983 for more details.

Please let me know if this solves your issue.
