### ISSUE TITLE
[Feature request] Add network bypass for 'AzureServices' in ARM deployments

### ISSUE THREAD

**Issue by johanolssoncab** [Azure/AppConfiguration#650]
According to the documentation [here](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager#review-the-template) a 'note'(1) indicates that the App Configuration resource need to have `enable public network` set to `true` when a ARM deploy of `Microsoft.appconfiguration/2020-07-01-preview/configurationstores/keyvalues` is executed.

In my scenario I want to integrate the App Configuration with VNET, Private Endpoints and RBAC authentication. This will disable all public access (beside private endpoint) and only use RBAC within the network.

This is currently impossible when deploying configuration(keyvalues) using ARM deployments due to the fact that 'AzureServices' is also blocked. At least in my testing, correct me if I'm wrong.

I would like to be able to specify bypass rules for 'AzureServices' for the App Configuration resource. [Maybe the same solution that KeyVault has today with network rule sets?](https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/vaults?tabs=bicep#networkruleset)? 

1. The note says:

    _App Configuration allows key-value data access over a private link from your virtual network. **By default, when the feature is enabled, all requests for your App Configuration data over the public network are denied. Because the ARM template runs outside your virtual network, data access from an ARM template isn't allowed.** To allow data access from an ARM template when a private link is used, you can enable public network access by using the following Azure CLI command. It's important to consider the security implications of enabling public network access in this scenario._

**Comment by zhenlan** [comment]
@johanolssoncab we don't have a viable solution for this problem at this point. We cannot control who can send requests to ARM, so from the security perspective, any backdoor given to ARM will effectively be the same as the opening to the whole public network. Until we have a better solution, we don't want to give you a false impression of security by bypassing Azure services. As suggested in the documentation, please do consider the security implications of doing so.

**Comment by johanolssoncab** [comment]
Ok, thanks for the quick reply.

There are no plans, as of today, to support this feature?

**Comment by zhenlan** [comment]
We will keep looking for a solution and would like to enable the scenario in the future, but no viable solution as of today.
