### ISSUE TITLE
Azure functions Isolated, QueueTriggers and ConnectionStrings

### ISSUE THREAD

**Issue by christianarg** [Azure/AppConfiguration#651]
Given an Azure functions Isolated with a QueueTriggers that get's the queue name by configuration and the ConnectionString also by configuration

```
namespace FunctionApp1
{
    public class MyQueueTrigger
    {
        private readonly ILogger _logger;

        public MyQueueTrigger(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<MyQueueTrigger>();
        }

        [Function("MyQueueTrigger")]
        public void Run([QueueTrigger("%myqueue%", Connection = "MyQueueConnection")] string myQueueItem)
        {
            _logger.LogInformation($"C# Queue trigger function processed: {myQueueItem}");
        }
    }
}
```
myqueue and MyQueueConnection are never read from Azure app Configuration.
If I do a _logger with the values from IConfiguration the values are correct, but the Azure Function never get's this values as it seems they are loaded even before the debugger hits Main(). 

I've configured Program.cs using this sample:

https://github.com/Azure/AppConfiguration/tree/main/examples/DotNetCore/AzureFunction/FunctionAppIsolatedMode 

But there are no samples on a QueueTriggers that get's the queue name by configuration and the ConnectionString 

I'm not sure if this is not implemented by Azure app configuration or there are documentation missingss.

Exactly the same should also apply for ServiceBusTrigger

**Comment by christianarg** [comment]
> What about the ConnectionString? It's not a binding expression, it's the name of the setting
> Without binding expression, I don't think it works even in in-proc Azure Functions, does it? 

It does work

> As a side note, I would recommend using managed identity between Azure services whenever possible, so you don't have to manage any secrets.

Even if you use managed identity, con can have multiple storage accounts that you need to process and you need to include the connection string for your account (without secrets with manage identity)

> I don't have an answer. Azure Functions team will be in a better position to answer this question. It will be valuable if you can share your demand with the team directly.

Can you kindly tell me where do I have to open the issue for de Azure Functions Team. Is it here https://github.com/Azure/azure-functions-dotnet-worker?

**Comment by christianarg** [comment]
@zhenlan can you take a look at my last reply?

**Comment by zhenlan** [comment]
Yes, you can reach the Azure Functions team from https://github.com/Azure/azure-functions-host.

Closing this issue as the Azure Functions trigger is tracked in https://github.com/Azure/AppConfiguration/issues/203.
