### ISSUE TITLE
follow Use dynamic configuration using push refresh in a Java Spring app step，get some trouble

### ISSUE THREAD

**Issue by Ryan9017** [Azure/AppConfiguration#652]
<1st>
     https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-push-refresh?tabs=cmd
spring.cloud.azure.appconfiguration.stores[0].monitoring.cacheExpiration= 30d
the '30d',if i change to 'abcd',
eg. spring.cloud.azure.appconfiguration.stores[0].monitoring.cacheExpiration= abcd
it passed.
i can't find the filed named 'cacheExpiration' in AppConfigurationStoreMonitoring class,

my dependency : 
<dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>azure-spring-cloud-appconfiguration-config-web</artifactId>
            <version>2.6.0</version>
        </dependency>

And i find here. <2nd>
      https://microsoft.github.io/spring-cloud-azure/docs/azure-app-configuration/2.6.0/reference/html/index.html#push-based-refresh
      it is say that 'these endpoints work sort of similarly to their counterparts refresh and refresh-bus, where the app configuration endpoints expire the refresh interval instead of forcing a refresh upon receiving. '
And i find the source:
      com.azure.spring.cloud.config.AppConfigurationRefresh in the method refreshStores() , 
      the code : if (refreshInterval != null && StateHolder.getNextForcedRefresh() != null && 
                             Instant.now().isAfter(StateHolder.getNextForcedRefresh())) {
so i try to add spring.cloud.azure.appconfiguration.refresh-interval = 30d ,
But https://docs.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-java-spring-push-refresh?tabs=cmd
i cant find the instruction about spring.cloud.azure.appconfiguration.refresh-interval.
So i want to confirm that which one i should follow , <1st> or <2nd>,
Please forgive me for my poor English writing, thanks.

**Comment by mrm9084** [comment]
`spring.cloud.azure.appconfiguration.refresh-interval ` is correct. Thanks for letting us know, that doc will be updated.

**Comment by zhenlan** [comment]
@mrm9084 is the doc fixed? Can this be closed now?

**Comment by mrm9084** [comment]
Yes it has been.
