### ISSUE TITLE
Azure Functions and IOptionsMonitor refresh

### ISSUE THREAD

**Issue by mho105** [Azure/AppConfiguration#655]
Hi, I'm trying to get IOptionsMonitor and App Configuration refresh working with Azure Functions.

I took the following example:
https://github.com/Azure/AppConfiguration/tree/main/examples/DotNetCore/AzureFunction/FunctionApp

And instead of just injecting `IConfiguration` I also injected `IOptionsSnapshot<HelloConfiguration>` and `IOptionsMonitor<HelloConfiguration>`

As well as registering this using:
```
builder.Services
                .AddOptions<HelloConfiguration>()
                .Configure<IConfiguration>((settings, c) =>
                    c.GetSection(HelloConfiguration.Section).Bind(settings));
```

Now when I run the Azure Function, and then refresh the config value along with the sentinel key, the value updates for `IConfiguration` and `IOptionsSnapshot` but not for `IOptionsMonitor`.

I would expect the IOptionsMonitor value to reflect the change. Am I correct, or am I misunderstanding?

Thank you.

UPDATE: 
I think it's the registering that I've got wrong, the following works
```
builder.Services
                .AddOptions<HelloConfiguration>()
                .Bind(configuration.GetSection(HelloConfiguration.Section));
```

Please close, if this is the correct way.

**Comment by zhenlan** [comment]
Glad it worked out and thanks for sharing, @mho105.
