### ISSUE TITLE
Validate JSON value 

### ISSUE THREAD

**Issue by theo-albers** [Azure/AppConfiguration#658]
There have been several improvements to support JSON values in the Azure Portal:
- support for application/json in the first place
- multiline edit box
- larger edit box

What's missing is JSON validation on save. It has happened to us a couple of times that we added a JSON property to an existing JSON value and we created invalid JSON by leaving a trailing comma. 

Invalid JSON values will be ignored in the final Microsoft extensions configuration on the client. 

The problem is that your Azure App Service might fail to start due to incomplete configuration. This is a costly op failure and you're looking for a needle in a haystack trying to debug the problem.

A simple solution would be to validate the JSON value on save in the Azure Portal.

**Comment by zhenlan** [comment]
@theo-albers that's a good suggestion. App Config Azure portal should have better JSON support including validation. Thanks!

**Comment by theo-albers** [comment]
Yes, it works, fantastic!

![image](https://user-images.githubusercontent.com/9417380/179768494-4617eb33-08f8-4145-901b-db674a0e3e84.png)
