### ISSUE TITLE
Locking a feature flag / key leads to invalid state

### ISSUE THREAD

**Issue by 5Heinzelmann** [Azure/AppConfiguration#663]
To reproduce:
- Go to Feature manager
- Right click a feature / key -> Lock
- Everything seems fine (Success message appears)
- Refresh page
- You an error "Some of your feature flags are not valid. Please navigate to Advanced Edit for more details."

The name + id of the flag are missing in the list.
If you open it in Advanced edit you see random (hashed?) characters like
"BGNCL2sUEmbC8Uxx [...] rtB66"

**Comment by 5Heinzelmann** [comment]
![Screenshot from 2022-06-28 13-55-07](https://user-images.githubusercontent.com/23219135/176172418-d402c0a3-0194-494e-8902-59cfbc59aa1f.png)

**Comment by drago-draganov** [comment]
Thanks for reporting this, @5Heinzelmann! We identified the problem, and the fix is rolling out as we speak. Please allow for a few hours to apply.

**Comment by drago-draganov** [comment]
The fix is deployed.
