### ISSUE TITLE
Recommendations of using Azure app configurations with staging slots

### ISSUE THREAD

**Issue by Shuvajyoti** [Azure/AppConfiguration#664]
We are planning to use azure app configurations for our Azure Function app which uses slots in dedicated App service.
As of today (without Azure App Configuration), in our CI/CD pipeline we update Configs along with Code changes.

We wanted to know the recommendations for maintaining/updating configurations in Azure App Configurations considering these slots (staging and production).
Wanted to know any recommendations on deploying these configs along with our code and also rollback scenarios.

**Comment by zhenlan** [comment]
Hi @Shuvajyoti, indeed. It will be problematic if your prod and staging share the same set of configurations. If anything goes wrong with your staging, the prod is impacted.

I would recommend you start versioning your configuration. For example, if prod is using v1 of the configuration currently, you set the label `v2` (or a build number) when you push data to App Configuration for your staging. Your staging code references only the v2 version of the configuration. This way, when you have to roll back staging, none of the prod v1 configurations is impacted.

**Comment by Philippe85** [comment]
Hi,
If we want to deploy an app service version n+1 in a second slot, we need in a same time a set of keys/values for versions n (in slot1 in production) and n+1 (slot2), and also for each environment.

If we have 5 environments, and app services with 50 key/values, it's difficult to manage all these configurations in App Configuration. What's more, we can't easily duplicate a set of keys/values. Furthermore, we need to have a single "Dev", "Staging" or "Production" Label, fixed beacause used in CICD to deploy on an environment "Dev", "Staging" or "Production".

Another thing, in the App Settings of an app service, we have a "Deployment slot setting" checkbox which allows us to indicate whether the value is slot-specific or not. This configuration is not currently possible in App Configuration and must be done manually.

So we need improvements in App Configuration to use deployements in slot wtih only on label for each environnement :
- Have versionning on configuration, to depoy a specific version and not a version at a date-time.
- Have possibility to set value of the "Deployment slot setting" checkbox for each key/value

Thanks

**Comment by zhenlan** [comment]
It may not solve all the issues, but I'd like to share an option. You can add App Configuration references in the App Settings of an App Service:

https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references

This way, you can indicate if a referenced key-value should go with a deployment slot. Unfortunately, App Service only supports referencing individual key-values in App Configuration today, so it may work well if you have a small number of settings that need to be attached to certain deployment slots.
