### ISSUE TITLE
Looking for an API to create/update feature flags through SDK

### ISSUE THREAD

**Issue by wngjian4814** [Azure/AppConfiguration#665]
Hi team, I'm trying to fly the App Configuration Service to our service, at the same time, I would like to have an API to enable me create/update feature flags through SDK. Could you please tell me where I could find this kind of API? It will be great if you could provide some examples. Thanks!

**Comment by zhenlan** [comment]
An FAQ is added to the documentation for this question.

https://docs.microsoft.com/azure/azure-app-configuration/faq#can-i-create-and-update-feature-flags-or-key-vault-references-programmatically
