### ISSUE TITLE
Reference another app configuration item

### ISSUE THREAD

**Issue by beukerz** [Azure/AppConfiguration#669]
In an App Configuration entry can I reference another entries value?

For example I have 2 app configuration entries. One called MyApi:Uri with value https://myapi.azurewebsites.net and I have an entry ReverseProxy:Clusters:MyApi:Destinations:destination1:Address. This value should also be https://myapi.azurewebsites.net but I would like to add/maintain it only once.

Note I am using one app configuration instance for several API's.

**Comment by zhenlan** [comment]
@beukerz, this is not supported natively by the App Configuration service today.

While I understand what you described could be useful, this is, however, often handled by the application or the framework depending on the type of the application. For example, 
- .NET doesn't have a concept/convention for one setting to reference another. .NET applications often use different variables referring to the same constant/setting to avoid duplication.
- Spring does have the support for one setting to reference another. For example, users can create keys like `setting2=${setting1}` in their App Configuration store, and the value of `setting2` will be resolved to the value of `setting1` in a Spring application automatically.
