### ISSUE TITLE
List by Configuration Store API is not working as expected (HTTP 404) received.

### ISSUE THREAD

**Issue by artisticcheese** [Azure/AppConfiguration#674]
Hello,

Using following API (https://docs.microsoft.com/en-us/rest/api/appconfiguration/stable/key-values/list-by-configuration-store?tabs=HTTP) I'm receiving HTTP 404. I'm owner of both control plane and `App Configuration Data Owner`. All other APIs are working fine, just this specific one returns HTTP 404

```
GET /subscriptions/11b16e25-0e5f-4e76-87bc-XXXXX/resourceGroups/managed-identity-apps-dev1-eastus/providers/Microsoft.AppConfiguration/configurationStores/XX-cicd/keyValues?api-version=2022-05-01 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGXXXXXX
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 7551a40a-7e3a-4116-9cdc-6c00c7abf33c
Host: management.azure.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
HTTP/1.1 404 Not Found
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
x-ms-ratelimit-remaining-subscription-writes: 1199
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-request-id: f4fb2805-6e28-4841-a834-5fdc0016533c
x-ms-correlation-request-id: 84d2ab52-123e-4b79-be05-bf7a33214d11
Server: nginx/1.17.10
x-ms-routing-request-id: SOUTHCENTRALUS:20220816T132552Z:84d2ab52-123e-4b79-be05-bf7a33214d11
X-Content-Type-Options: nosniff
Date: Tue, 16 Aug 2022 13:25:51 GMT
Content-Length: 0
```

**Comment by drago-draganov** [comment]
List of KeyValues through the management plane (ARM) isn't supported. Only individual GET/PUT/DELETE per key-value. This is to enable ARM template scenarios, where key-values are read/modified during ARM template deployment.
There is discrepancy with the documentation and should be addressed with the next API version.

For any key-value operation (except ARM template references), please consider using the data plane directly.

**Comment by artisticcheese** [comment]
> List of KeyValues through the management plane (ARM) isn't supported. Only individual GET/PUT/DELETE per key-value. This is to enable ARM template scenarios, where key-values are read/modified during ARM template deployment. There is discrepancy with the documentation and should be addressed with the next API version.
> 
> For any key-value operation (except ARM template references), please consider using the data plane directly.

What do you mean by `use dataplane directly`. How do we list all values in one sweep?

**Comment by drago-draganov** [comment]
- The direct way is via any of [Azure AppConfiguration SDKs](https://github.com/Azure/AppConfiguration#sdks)
- To integrate and use into application, consider any of [Azure AppConfiguration Providers] (https://github.com/Azure/AppConfiguration#configuration-providers)

In terms of REST, the endpoint is:
https://<your-config-store-name>.azconfig.io/kv
