### ISSUE TITLE
Feature Flag API not returning updated value on first call

### ISSUE THREAD

**Issue by sindhu-r** [Azure/AppConfiguration#675]
I have created an API for fetching feature flag from Azure. If we change a feature flag, the updated value is getting reflected only on the second API call.

But if we add a Task.Delay , updated or the changed value is getting in the first call itself

[HttpGet("Get")]
public async Task<ActionResult<FeatureFlag>> GetAllFeatureFlags()
        {
                     
            await _configurationRefresher.TryRefreshAsync();          

          // await Task.Delay(50);

            var featureList = new List<FeatureFlag>();
            var featureNames = _featureManager.GetFeatureNamesAsync();

            await foreach (var name in featureNames)
            {
                var isEnabled = await _featureManager.IsEnabledAsync(name);
                featureList.Add(new FeatureFlag()
                {
                    FeatureName = name,
                    IsEnabled = isEnabled
                });
            }
}

**Comment by zhenlan** [comment]
Given you have `await` for `TryRefreshAsync`, I do expect the data from App Configuration will be refreshed for the same call. Do you see regular key-values are updated or is it only about feature flags?

In most real-world apps, it doesn't really matter which requests (the first or second) get the refreshed data, so normally I don't recommend `await`, which potentially slows down your overall throughput.

**Comment by sindhu-r** [comment]
Even if I removed TryRefreshAzync , and update a feature flag the changed data not reflecting on the first API call.
I have created feature flag with no labels.

 .UseFeatureFlags(featureFlagOptions => {
                       featureFlagOptions.CacheExpirationInterval = TimeSpan.FromSeconds(1);
                       featureFlagOptions.Label = LabelFilter.Null;
                   })

**Comment by zhenlan** [comment]
After a second look, you probably miss an `await` for `GetFeatureNamesAsync` if you want everything completes in the same call.

```cs
var featureNames = await _featureManager.GetFeatureNamesAsync();
```

**Comment by zhenlan** [comment]
@sindhu-r I hope the issue has been resolved on your end. Closing.
