### ISSUE TITLE
How to delete key-value with configure as code deployment

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration#676]
We are adopting configuration as code deployment to make sure configurations are managed under version control.
But the question is, some configurations are JSON array,
AAC keys are expressed as
Test:Setting:0, Test:Setting:1

it works well for add, update. But if  Test:Setting:1 is deleted in configuration file, how to delete AAC related key-value with configuration as code model?

**Comment by drago-draganov** [comment]
Please use JSON based configuration settings for JSON arrays.
https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type

That allows arrays to be expressed in a singular form:

Test:Setting -> ["a", "b", "c"]

_Update of the array simply means to replace the value_

instead of .NET Config specific binding.

Test:Setting:0 -> "a"
Test:Setting:1 -> "b"
Test:Setting:2 -> "c"

**Comment by lissdy** [comment]
> Please use JSON based configuration settings for JSON arrays. https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type
> 
> That allows arrays to be expressed in a singular form:
> 
> Test:Setting -> ["a", "b", "c"]
> 
> _Update of the array simply means to replace the value_
> 
> instead of .NET Config specific binding.
> 
> Test:Setting:0 -> "a" Test:Setting:1 -> "b" Test:Setting:2 -> "c"

Thanks for replying, appending and updating work well.
But If I need to remove the last item Test:Setting -> ["a", "b", "c"] to Test:Setting -> ["a", "b"] and import the configuration file again, Test:Setting:2 -> "c" still exist in AAC.
Any suggestion to handle deletion?

**Comment by drago-draganov** [comment]
Remove all entries that represent the flattened array from your AAC

Test:Setting:XXX

When do config file import, use Content-Type JSON (application/json)

![image](https://user-images.githubusercontent.com/12902911/186532338-7b10ff6a-2dc1-4d83-b342-0faabc18333e.png)

**Comment by lissdy** [comment]
> Remove all entries that represent the flattened array from your AAC
> 
> aka Test:Setting:XXX
> 
> When do config file import, use Content-Type JSON (application/json)
> 
> ![image](https://user-images.githubusercontent.com/12902911/186532338-7b10ff6a-2dc1-4d83-b342-0faabc18333e.png)
> 
> You should see the array represented as a single entry.
> 
> Test:Setting -> ["a", "b", "c"]

Cool, the solution helps. Thanks a lot.
