### ISSUE TITLE
Purged App Configuration Services are not releasing the name

### ISSUE THREAD

**Issue by teowa** [Azure/AppConfiguration#677]
### Background

Hi, I am working on support `soft_delete` feature of App Configuration 2022-05-01 in Terraform https://github.com/hashicorp/terraform-provider-azurerm/pull/17714, seems the purged App Configuration are not releasing the name(for about serveral minutes with location `west us`), which affects some of the automation. From a previous issue https://github.com/Azure/AppConfiguration/issues/264, I know maybe it is by design. 

As a workaround, I find there is a POST operation [`checkNameAvailability`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2022-05-01/appconfiguration.json#L1150-L1157) can check the name availibility in certain location. I plan to add logic to retry `checkNameAvailability` before PUT. Seems there is no doc about this, please help check once this `checkNameAvailability` returns the name is availble then I can PUT without the `NameUnavailable` error, right? From my own test, the result is expected (`checkNameAvailability` returns OK then PUT is OK). And please tell if there is other insights, thanks.

###  Repro Steps (with REST API)
1. PUT a Appconfiguration with Standard sku (`purge_protection` is off)
2. DELETE the App Configuration
3. POST purge the soft-deleted App Configuration, checked that both of GET the first created and the deleted return 404
4. PUT a same named App Configuration, return the error 

### Error
Code="NameUnavailable" Message="The specified name is already in use."

### Releated
1. https://github.com/hashicorp/terraform-provider-azurerm/pull/17714
2. previous issue: https://github.com/Azure/AppConfiguration/issues/264

**Comment by jiayi11** [comment]
Hi @teowa
Yes, you are right, it's by design that the store name will not be released immediately after purging the store. You should use the CheckNameAvailability API to check if the name is available for use. 
https://docs.microsoft.com/en-us/rest/api/appconfiguration/stable/operations/regional-check-name-availability?tabs=HTTP
