### ISSUE TITLE
[Feature request] Push partial key/value change instead of re-updating the whole store at a time

### ISSUE THREAD

**Issue by datduyng** [Azure/AppConfiguration#685]
After a discussion with the AAC team, we found out that Azure App Config has a 5000 write requests per hour limit
 (Note that current [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#are-there-any-limits-on-the-number-of-requests-made-to-app-configuration) doesn't clarify this)

Our platform team serve more than 20+ team and services. Since the platform shared a common layer Azure App Config, we are facing the 5000 write requests per hour limit. 

In most cases, our client and our team only make change to 1-2 key value pair at a time but since Azure App Configure only allow user to upload the whole store (note that this is true for Azure pipe App Config push task and Azure App Config portal)

**Feature Request**: Update partial store by uploading a .json file

![image](https://user-images.githubusercontent.com/35666615/194635581-52319c09-68c6-403e-a617-18c9c0ffec1a.png)

**Comment by zhenlan** [comment]
This has been addressed in the latest release of the Azure App Configuration Push task, introducing the new **Import Mode** option to ignore matching keys.
