### ISSUE TITLE
Endpoint ID conflict in connection string still works

### ISSUE THREAD

**Issue by mack0196** [Azure/AppConfiguration#686]
We use many azure app configuration instances.
A mistake was made to use the id\secret from one AAC instance with the endpoint of another.
This resulted in read from the id AAC resource.

In the scenario that the ID and endpoint conflict, I don't think 200 response should happen if there is a conflict between the ID and Endpoint.

**Comment by drago-draganov** [comment]
@mack0196, can you provide which API did you use to connect to your Azure AppConfiguration instance?
A request-id would be useful to investigate further.

**Comment by drago-draganov** [comment]
@mack0196, Thanks for reaching out! We were able to identify the issue and the fix is already deployed.
