### ISSUE TITLE
Fields no longer included in AACHttpRequest

### ISSUE THREAD

**Issue by joachimdalen** [Azure/AppConfiguration#688]
Sometime in the last 48 hours `AACHttpRequest` exported from a Configuration Store no longer contains fields such as

- StatusCode
- RequestLength
- ResponseLength

At the same time, the `RequestURI` changed from `/kv/<KEY>?label=<LABEL>&api-version=1.0` to `https://<STORE_NAME>.azconfig.io/kv/<KEY>?label=<LABEL>&api-version=1.0` making me think there has been an update?

These fields missing breaks some custom Workbooks and Alerts. Has there been a change in the scheme that is not communicated out yet? I see that the [Azure Monitor Reference](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/aachttprequest) still lists these fields.

I see the same issue across multiple Configuration Stores (both existing and new) in multiple tenants.

**Comment by zhenlan** [comment]
@joachimdalen, thanks for reporting this. We are working on a fix for the issue.

**Comment by joachimdalen** [comment]
@zhenlan / @drago-draganov Do you have any expected ETA on when this issue will be fix and rolled out?

**Comment by drago-draganov** [comment]
ETA - next two weeks.

**Comment by joachimdalen** [comment]
Seems like this issue is now fixed for us. Thanks for the quick response.

**Comment by zhenlan** [comment]
Thanks for the confirmation, @joachimdalen.
