### ISSUE TITLE
Register for configuration changed event

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration#691]
Is there a way to register for ConfigurationChanged event to log and emit telemetry. This can help give confidence configurations are propagating as expected.

**Comment by drago-draganov** [comment]
Hello @lissdy 

Please let me know if this helps.

[Use Event Grid for App Configuration data change notifications](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-app-configuration-event)

[Monitoring App Configuration](https://learn.microsoft.com/en-us/azure/azure-app-configuration/monitor-app-configuration?tabs=portal)

**Comment by zhenlan** [comment]
@lissdy in case you are using .NET, I hope what is suggested in the issue below can be helpful to you.
https://github.com/Azure/AppConfiguration-DotnetProvider/issues/212
