### ISSUE TITLE
Configuration explorer does not show key values if using search

### ISSUE THREAD

**Issue by bradleyFS** [Azure/AppConfiguration#693]
Configuration explorer does not show all the key values if using the search. The only way I can get them to display is to repeatedly click the 'Load more key-values' at the bottom of the page. You do see the keys appear briefly but to make them stay on the page long enough to read, you have to click the button around 10 or 15 times.
![image](https://user-images.githubusercontent.com/94322230/202436801-f44a9377-cf36-45e9-9030-78b239a752b0.png)

**Comment by MaryanneNjeri** [comment]
Hello @bradleyFS, to confirm when doing the search after clicking "load more key-values" the first time you are able to see the results briefly then they disappear? Or after clicking "load more key-values" a blank page appears and you have to keep clicking load more 10 to 15 times, to see the results ?

**Comment by bradleyFS** [comment]
You may see 1 or 2 results the first time, briefly.

**Comment by MaryanneNjeri** [comment]
The results disappear after some time?

**Comment by bradleyFS** [comment]
The results flash up briefly

**Comment by zhenlan** [comment]
@bradleyFS, do you have any key-values in your store that contain "my key" in either key name, label, or value? Do you have hundreds of key-values in your store? The search occurs only among the key-values that have been loaded in your browser, so you may have to click "load more key-values" multiple times for a complete search.

**Comment by bradleyFS** [comment]
I find it odd you have to click load more key-values multiple times and the text 'no results' appears. It is not intuitive to click load more key-values multiple times, each time seeing no results and then eventually the results appear.

**Comment by MaryanneNjeri** [comment]
The results flash up briefly - I see what you mean, that is as a result of the search being performed after the key-values are loaded.

**Comment by MaryanneNjeri** [comment]
We are currently working on improving the configuration explorer search experience by adding an info string that informs users that the search results are only from the loaded key values and that they'll have to click load more to get more search results.

**Comment by MaryanneNjeri** [comment]
@bradleyFS an update is available with the improved  search experience on configuration explorer
![image](https://user-images.githubusercontent.com/33903727/227871617-65e175d7-b293-48ec-8032-c8a2c2e1aba2.png)
Please let me know if this helps.
