### ISSUE TITLE
Strict import with prefix removes all feature flags

### ISSUE THREAD

**Issue by audrius-freemarket** [Azure/AppConfiguration#694]
We have multiple applications managing their own key values in a shared App Configuration instance. This is easy to do with the following command that only creates and deletes key values with specific prefix:

`az appconfig kv import -n $AppConfigurationName --source file --path appsettings.json --format json --yes --prefix "MyApp:" --strict $true` 

Unfortunately, I just found out that this will delete all feature flags regardless of prefix. I tried to use `--skip-features` but I get the following error:

`az : ERROR: The option '--skip-features' cannot be used with the '--strict' option.`

Is there a way to make import process to ignore feature flags entirely while still maintaining functionality that --strict in combination with --prefix provides?

P.S. I do not want to import feature flags in the same way as key values due to the fact that an import resets the flag to its original setting. For us, deployment should never change flag status, otherwise it beats the purpose of a flag.

**Comment by RichardChen820** [comment]
You presumably can leverage "Label" property, set the label of the key values to a specific value which is different from the feature flag's label, then you can import the key values only without affecting feature by running:

`az appconfig kv import -n $AppConfigurationName --source file --path appsettings.json --label <label of key values> --format json --yes --prefix "MyApp:" --strict $true`

**Comment by audrius-freemarket** [comment]
That's a brilliant suggestion and it worked perfectly. Thank you.
