### ISSUE TITLE
Using connection strings/secret with App Configuration pipeline task

### ISSUE THREAD

**Issue by InspiringCode** [Azure/AppConfiguration#703]
I need to use the Azure App Configuration pipeline task to fetch some values that I need in my Release pipeline. Unfortunately I can't use the Azure Service Principal to connect to my App Configuration store for various reasons.

Is there any way to connect using a connection string with id and secret (like in .NET)? I would really need a way to use a full "Endpoint=..." connection string.

Some users mentioned that they "swichted to using secrets" but I just could not figure out how to do it and I couldn't find any docs on this.

I would be really grateful for any hints!

**Comment by MaryanneNjeri** [comment]
Hello @InspiringCode apologies for the late reply. Unfortunately there is no way to connect using a connection string.

**Comment by InspiringCode** [comment]
Thanks for the reply. Am I correct that there is also no way to connect using a secret? Are there any plans to extend the pipeline task in this way in the near future? I guess this would be useful for many users out there.

**Comment by MaryanneNjeri** [comment]
Yes that is correct,  there is no way to connect using a connection string only with a service principal. When using a service principal we support certificate authentication or using a secret. We can look into supporting other forms of authentication.

**Comment by InspiringCode** [comment]
I didn't know that! How can I use a service principal with a secret? Could you please point me to a resource that describes how to create/configure such a principal?

**Comment by InspiringCode** [comment]
I didn't know that! How can I use a service principal with a secret? Could you please point me to a resource that describes how to create/configure such a principal?

**Comment by MaryanneNjeri** [comment]
Yes, please checkout [Creating a service principal](https://learn.microsoft.com/en-us/azure/purview/create-service-principal-azure). Please let me know if this helps. Incase you run into any issues please feel reach out.
