### ISSUE TITLE
How to ensure shared configuration data consistency among multiple micro services

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration#707]
In our case, we have multiple microservices sharing the common configuration that is stored in the app configuration.
For any shared configuration change, during the configuration refresh intervals, the data may be inconsistent among the multiple microservices.
Eventual consistency is acceptable but considering app configuration throttling, it's not a good idea to pull data from app configuration too frequently, do you have any suggestions to ensure shared configuration data consistency among multiple microservices or to achieve eventual consistency as soon as possible?

**Comment by drago-draganov** [comment]
Hi @lissdy,

Thanks for reaching out! Can you provide a bit more details on your requirements:

- What is the number of instances (microservices) that watch for configurations changes (including future scaling).
- Do you use Sentinel Key pattern to detect changes?
- How frequently would you be OK to pool for changes (eventual consistency window)?
- How often on average do you expect changes in your Azure AppConfiguration store?

**Comment by lissdy** [comment]
Thanks, @drago-draganov for replying.
As the document [External Configuration Store pattern](https://learn.microsoft.com/en-us/azure/architecture/patterns/external-configuration-store)  mentioned, The pattern can provide opportunities for easier management and control of configuration data, and for sharing configuration data across applications and application instances.
But considering latency and App Configuration throttling, caching configuration value is mandatory, but data inconsistency is unavoidable with caching, it would be appreciated if you could provide best practices for the case.

For your questions:
- The configurations are shared among 10+ microservices. (each service with 5~10 instances)
- Yes, we use the sentinel key + poll model to detect changes.
- the eventual consistency windows can be 30s. The inconsistency state can be covered via retry in 30s
- The configurations actually don't change a lot, monthly at most.

**Comment by zhenlan** [comment]
@lissdy, in case you are not aware, please see the document below to estimate the total number of requests your application may send to App Configuration. Based on the numbers you provided, you seem to have ample room before hitting the hourly throttling limit using the poll model.

https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#how-do-i-estimate-the-number-of-requests-my-application-may-send-to-app-configuration

**Comment by lissdy** [comment]
Thanks @zhenlan, I have read the document and done the calculation.
Considering further scale-out, we may have 20 microservices, each service with 10 instances. if it checks for a sentinel key for configuration changes every 30 seconds. To sum up there are 120(=3600/30) * 200 = 24000 requests /hour for change detection. Which is close to the 30k limitation.
With more and more configuration setting onboard,  seems it is highly like leading to hourly throttling. 
And as the configuration values do not change frequently, I am wondering the 30s refresh timeout is too short. 

From https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#reduce-requests-made-to-app-configuration,
Increasing the refresh timeout is a good practice to reduce requests made to AAC,
but the tricky part is configurations(don't change frequently) shared among multiple applications. it seems hard to balance between the short eventually consistent window and avoid AAC throttling. 

Looking forward to your advice on this, thanks

**Comment by drago-draganov** [comment]
Thanks, @lissdy!

Azure AppConfiguration handles repetitive requests (applicable for watching indeed) a bit differently than general purpose requests. For frequent repetitive requests your hourly quota is unlikely not be used. There are certain optimizations just for that.
Based on your notes, I would suggest to setup a quick test that is close to what you anticipate in your production workload and give it a try. I hope you find your Azure AppConfiguration store capable to handle that volume just fine with very low latency as well. 

Please keep us posted with your findings.

**Comment by lissdy** [comment]
Thank @drago-draganov for replying, but sorry I am a little confused. Do you mean as an optimization for AAC in the further, the sentinel check won't be counted into the hourly 30k quota?  If that is the truth, it's definitely a great support for shared configuration cases.

**Comment by drago-draganov** [comment]
That optimization already exists. Basically, AppConfiguration caches frequent requests and will not count these against the hourly quota. Since your watch requests (Sentinel key) fits such scenario, I expect that they won't affect the available quota.

**Comment by lissdy** [comment]
Great to know that frequent sentinel key checks won't be counted as the hourly quota. Then maybe the document can be updated accordingly? The example https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#how-do-i-estimate-the-number-of-requests-my-application-may-send-to-app-configuration seems to count all sentinel key check requests to the hourly quota.
The optimization is definitely a great support for the shared configuration case. I will set up a test to have a try.

For the shared configuration case, actually one of my considerations is to set up a proxy service between AAC store and microservices, services communicate to the proxy service(with a custom configuration provider) every 30s to avoid AAC throttling. With the optimization that AAC already implemented, maybe the proxy service is not needed.

One more quota detail that needs to double check is how you count the requests for configuration file import.
My understands is each key-value write/update is count as one request, is this correct?

Thanks a lot for your information

**Comment by drago-draganov** [comment]
Thanks for your feedback, @lissdy. We will update the documentation to reflect the existing optimization behavior.

Re: Proxy
I also think that you won't need to proxy calls to your Azure AppConfiguration Store. Direct connection between your microservices and your AppConfiguration store should be enough.
If your microservices have deployment in multiple regions, you may be interested in [Geo-Replication (preview)](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-geo-replication).  In addition to improved resiliency, failover capability, low latency and regional deployment silo, each replica also offers independent request quota.

Re: Import
In general, each key-value in the import file issues a separate write request. It counts as one request per key-value. That's different for reads where an entire page (up to 100 key-values) is count as one request.
As a side note, if you are using [Azure AppConfiguration Push Task](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push) for import, there is [ImportMode=Ignore-Match](https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-devops-pipeline#parameters) parameter that will import only the modified/different key-values and skip those that are the same. Some customers find this helpful to avoid unnecessary updates, thus significantly reducing write requests and speed up the import process.

**Comment by lissdy** [comment]
Thanks, @drago-draganov 
We do need geo-replication for high availability, planning to enable the feature once it's generally available.
For now, we have the active-active pattern(primary AAC + failover AAC) for resiliency.

For import, thanks for confirming that each key-value would issue a separate write request. We are using `az appconfig kv import` for configuration import, it would be really helpful to reduce the requests if the az command can support ImportMode=Ignore-Match as well. Not sure if you have plans for this? Thanks

**Comment by drago-draganov** [comment]
@lissdy Please refer to #710 for CLI support of ImportMode=Ignore-Match
