### ISSUE TITLE
Couldn't you think of another name for this?

### ISSUE THREAD

**Issue by lukos** [Azure/AppConfiguration#708]
"App" and "Configuration" are two of the most common words used in Development so searching for anything related to this product in the future will be super annoying for everyone. Conversely, people might not know this exists because when they search for "app configuration" they get 100s of other results related to other types of apps and configurations!

Even an acronym or something like ADAC (Azure Distributed App Configuration), I don't know but just a thought!

**Comment by zhenlan** [comment]
Thanks for sharing your input, @lukos. The full product name is "Azure App Configuration". It should be the first hit on Google and Bing. The product naming went through many considerations, including branding and marketing, so it's not something that can be changed lightly. Again, thanks for sharing your thoughts!
