### ISSUE TITLE
Provide App Configuration part of  Azure Arc Enable Kubernetes 

### ISSUE THREAD

**Issue by Ashengross** [Azure/AppConfiguration#709]
Provide App Configuration as a service to Azure Arc Enable Kubernetes like there is preview for App Service, Function and Logic app.
the goal for solution that are deployed in multi cloud can use App configuration out side of Azure with Azure Arc enable Kubernetes

**Comment by zhenlan** [comment]
@Ashengross, are you a current Azure Arc user? Can you help us better understand the request?

Do you run into any issues that prevent you from connecting to App Configuration from your Azure Arc workload? How do you solve issues related to other "data services" like Azure Key Vault and Cosmos DB (or similar services your application may use)?

**Comment by zhenlan** [comment]
@Ashengross, please feel free to reactivate the issue when you have more details to share.

**Comment by Ashengross** [comment]
Sorry for late respond.
the use case where the customer run workload on Azure and on-prem.
on the on-prem workload he is looking for on-prem solution for the app configuration tool and don't want to keep the app configuration running on cloud while the workload deployed on-prem.
I wonder, if like Azure Arc enable application services (App Service, Function, Logic App, etc.) will we be able to deploy configuration solution on customer Azure enable Kubernetes running on-prem.
