### ISSUE TITLE
Add support for ImportMode=Ignore-Match in CLI

### ISSUE THREAD

**Issue by drago-draganov** [Azure/AppConfiguration#710]
#707 

[Azure AppConfiguration Push Task](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push) has [ImportMode=Ignore-Match](https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-devops-pipeline#parameters) parameter that will import only the modified/different key-values and skip those that are the same.  Customers find this helpful to avoid unnecessary updates, thus significantly reducing write requests and speed up the import process.

**Comment by lissdy** [comment]
Still looking forward to the feature, thanks @albertofori

**Comment by albertofori** [comment]
Hi @lissdy. Thanks for following up on this. A Pull Request should be out early next week.
Thanks!

**Comment by lissdy** [comment]
Thanks for replying, and may I know the maximum file size for importing configuration data to Azure App Configuration using the `az appconfig kv import ` command? Looks the document https://learn.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-import doesn't mention it.

**Comment by albertofori** [comment]
@lissdy We have a size limits for the configuration store (10MB for free tier and 1GB for the standard tier)
Since this constitutes the entirety of the key (including content-type, tags, etc.), the maximum import size will depend not only on file size, but also on the specified  label and content-type arguments during import. For imports using the kvset profile, the file size should be closer to the store limit.

**Comment by lissdy** [comment]
Thanks @albertofori , while I import JSON files with `az appconfig kv import`, sometimes may encounter momentary throttling if the JSON file with thousands key-value, may I know if `az  appconfig kv import` would handle the momentary throttling with retry logic? Or do I have to re-import the whole JSON file?

>A configuration store may experience momentary throttling if it receives a large burst of requests. App Configuration clients, such as the Azure SDK, configuration provider libraries, and Azure Pipeline tasks, automatically retry on throttled requests.

Seems Azure Cli is not mentioned in the document. https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#my-application-receives-http-status-code-429-responses--why

**Comment by albertofori** [comment]
Hi @lissdy, please the CLI is based on the Azure App Configuration python SDK which has retries built in. The CLI will therefore retry on the 429s.

**Comment by albertofori** [comment]
`ImportMode` feature has been merged in and should be available in the next release. ETA is September 5, 2023. Closing this issue.
