### ISSUE TITLE
In push mode, is there a way to only update the specified key?

### ISSUE THREAD

**Issue by elias-rod** [Azure/AppConfiguration#711]
Using the current [approach](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh), I've an Azure Function with EventGridTrigger that gets executed when I update one key x in the portal, that doesn't refresh anything because I have to also modify a second key (Sentinel) and I get notified a second time. With that last one the azureAppConfigurationRefreshOptions.Register("Sentinel", refreshAll: true) refreshes ALL the keys. Given that I'm getting an update per key modified, is it possible to only refresh the specified key without having to use the AzureAppConfigurationRefreshOptions.Register method for each of the 100's keys stored in an Azure AppConfiguration?

**Comment by zhenlan** [comment]
When you set up EventGrid, you can add a filter so only the "Sentinel" key will trigger an event.

![image](https://user-images.githubusercontent.com/10566826/214728368-df1e05b9-6fa1-4647-abac-d56e0a6f58cf.png)

**Comment by elias-rod** [comment]
Thanks. Now, if I change one key and I receive one EventGridEvent for it, isn't there an option to refresh only that one without having to Register each of the 100 keys?

**Comment by zhenlan** [comment]
The EventGrid event simply notifies the application that "something" has changed. It's up to the application to find out which key has changed and whether it should refresh one key or all keys. This part is no different than the poll model. So, if you want each key to be refreshed individually, you have to call azureAppConfigurationRefreshOptions.Register for each of them.

**Comment by elias-rod** [comment]
Understood. Then, I would like to file a request for that feature, to be able to refresh just the key that was changed, as that information is available in the EventGridEvent.

**Comment by zhenlan** [comment]
We can decouple the push model from this request here. Basically, you want to monitor a group of keys without specifying them individually. The request is tracked in #153.

**Comment by elias-rod** [comment]
I think this is more a one-key scenario without having to restart the app. One key is changed, one EventGridEvent is currently being fired with that key info, request is to only refresh that key.

**Comment by zhenlan** [comment]
The app is never restarted in any case. I understand what you are saying, but that's not how the push model is designed. To achieve what you want, we will need the app to be able to monitor arbitrary keys (without specifying them explicitly).

**Comment by elias-rod** [comment]
If this was achieved, it would be the most efficient method as only the setting that changed would be updated in the app and not others. But I'm limited on the implementation details, so I just leave it up to your consideration.

**Comment by drago-draganov** [comment]
@elias-rod,

Thanks for bringing this up. May I ask how many key-values your application uses?

**Comment by drago-draganov** [comment]
Up to 100 key-values can be delivered in a single request. Practically there won't be any notable difference in efficiency if refresh all.

**Comment by elias-rod** [comment]
Got it. Still, could the improvement yet be implemented to only download the ones that need to be downloaded?

**Comment by drago-draganov** [comment]
Theoretically, yes. In general, perf investment needs measurable readings beyond statistical noise levels. Between 1 and 100 key-values, I'm expecting comparable perf results.

But what I'm more concern is that such partial update may cause issues with client config composition in some cases. Here is an example:

```cs
configBuilder.AddAzureAppConfiguration(options => {
           ...
           options
                 //
                 // Composition:
                 .Select("MyApp*", "default") // Append all with key prefix 'MyApp' with label 'default'
                 .Select("MyApp*", "v2") // Append all with key prefix 'MyApp*' with label 'v2'. That replaces matching settings from the step above! The last one wins.

                 //
                 // Watch for changes for key prefix 'MyApp' and label 'default'
                 .ConfigureRefresh(refresh =>
                        refresh
                            .Register("MyApp*", "default", refreshAll: false) // Assume this works. Updates only the settings requested.
                    );
});
```

Now, when the application starts the composition is as expected. But when the refresh detects changes, it will replace existing 'v2' settings with 'default', which is definitely not expected. In composition, the last one wins. The safest is to rerun the composition pipeline, which is basically what _refreshAll = true_ does.

**Comment by zhenlan** [comment]
@elias-rod I hope @drago-draganov has addressed your questions. Please reactivate if you have further questions.
