### ISSUE TITLE
No logs with App Configuration export when 'yes' flag is setted

### ISSUE THREAD

**Issue by Philippe85** [Azure/AppConfiguration#712]
Hello,

When we export App Configuration to App Service without the 'yes' flag as this :
`az appconfig kv export  ...`

we can get this information message :
```
Exporting feature flags to properties file or appservice is currently not supported.
---------------- Key Values Preview ----------------
Target configuration already contains all key-values in source. No changes will be made.
```

But if we use the flag '--yes' as this :
`az appconfig kv export  ...  --yes`

we don't see the information message, which is very useful.

Could you show the same logs when '--yes' flag is setted or not ?

Thanks.

**Comment by zhenlan** [comment]
@avanigupta what's the convention in CLI about whether warning messages should be showed when `--yes` is provided?

**Comment by avanigupta** [comment]
Warning messages are always shown by default in CLI, unless turned off by specifying `--only-show-errors` option.
The purpose of `--yes` is to disable user confirmation prompts, but we can still log print preview.

**Comment by zhenlan** [comment]
So sounds like we should show the warning message even with `--yes`?

**Comment by avanigupta** [comment]
We don't show it today, but yes, we can surely add it.

**Comment by zhenlan** [comment]
Sounds good. Let's add it then as it doesn't sound intentional to be hidden with `--yes`.

**Comment by Philippe85** [comment]
Very good. Thanks.

**Comment by albertofori** [comment]
@Philippe85 Thank you for reaching out. I had wanted to confirm if the full key-values shown in the preview are required for your workflow. This information can be a lot. For instance, if you are importing 5 key-values in strict mode and your store has a 500 key-values. You might end up seeing 495 key-values that are going to be deleted. 

I had wanted to confirm if this information is a requirement for you, or a more summarized output showing the number of added, updated and deleted key-values would be good enough. Also, if no key-values are exported, then we can show the message outlined in your post. Kindly let me know what works best for you😀

**Comment by brental** [comment]
This issue also seems to affect other `az appconfig` commands such as `az appconfig kv import`. Does the fix applied in Azure/azure-cli#25560 fix the issue for all `az appconfig` commands or is it just for the `az appconfig kv export` command?

**Comment by brental** [comment]
Okay, thanks for getting back to me @albertofori . And thanks for the fix as well, it will be useful to have that logging on import.

**Comment by zhenlan** [comment]
The Fix has been merged.
