### ISSUE TITLE
[Question] Configure feature filters from code: Possible?

### ISSUE THREAD

**Issue by Meandron** [Azure/AppConfiguration#714]
In almost all examples about feature filters, the filters for features in Azure's App Configuration are configured via the portal. There is also the possibility to use the azure cli for it.

However, I would like to create filters through C# / in code: Is that possible, and if yes, can you please explain how? I only saw approaches through appsettings.json?

**Comment by zhenlan** [comment]
@Meandron hope this helps

https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#can-i-create-and-update-feature-flags-or-key-vault-references-programmatically

**Comment by Meandron** [comment]
That's what I was looking for:

[Link to code](https://github.com/Azure/azure-sdk-for-net/pull/20866/files/235babd598adc4687066790fb7e0a7e6c25fae52#diff-8ffac0544c046b8904eaabfe5a2aa112beb44c095a9b2cf43d8dbb2b4ef2080b).
