### ISSUE TITLE
Config values will not refresh with updated sentinel key in Azure Function

### ISSUE THREAD

**Issue by Troy1776** [Azure/AppConfiguration#718]
Hello

I am trying to update some values on the azure app config. I for some reason cannot get them to refresh. What is weirder, is that sometimes, they are able to when I deploy my code, and other deployments they aren't. Usually when they are able to refresh, they will be refresh-able for about 10-30 minutes, and then stop being refresh-able.

How I am changing it: I change the value of MyClass on the azure cloud. Then I change refreshConfig. Then I wait about 2-5 minutes. Then I check to see if it has changed.

Program.cs

`        
public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureAppConfiguration(config =>
                {
                    //insert other stuff here
                    var buildConfig = config.Build();
                    var connectionString = buildConfig["AppConfigConnectionString"];

                    config.AddAzureAppConfiguration(options =>
                    {
                        options.Connect(connectionString)
                            .Select("*").ConfigureRefresh(refreshOptions =>
                            refreshOptions.Register("refreshConfig", refreshAll: true).SetCacheExpiration(TimeSpan.FromSeconds(30)));

                        options.ConfigureKeyVault(kv =>
                        {
                            kv.SetCredential(new DefaultAzureCredential());
                        });

                        options.UseFeatureFlags(featureFlagOptions =>
                        {
                            featureFlagOptions.CacheExpirationInterval = TimeSpan.FromSeconds(15);
                            featureFlagOptions.Select(KeyFilter.Any);
                        });

                        _refresher = options.GetRefresher();
                    });

                    config.Build();
                    _configuration = config.Build();
                })
                .ConfigureServices(services =>
                {
                    IConfiguration configuration = services.BuildServiceProvider().GetService<IConfiguration>();
                    services.AddAzureAppConfiguration();
                    
                    //insert other stuff here

                    services.Configure<List<MyClass>>(options => configuration.GetSection(nameof(MyClass)).Bind(options));

                    //insert other stuff here
                })
                .ConfigureFunctionsWorkerDefaults(builder =>
                {
                    builder.UseAzureAppConfiguration();
                    builder.UseMiddleware<TelemetryMiddleware>();
                })
                .Build();
            host.Run();
        }
`

MyClassProvider
`
public MyClassProvider(IOptions<List<MyClass>> myClass, 
            TelemetryClient telemetryClient,
            IConfigurationRefresher configurationRefresher)
        {
            _telemetryClient = telemetryClient;
            //VVVVV This is currently commented out but it didnt work when it was not commented 
            //_configurationRefresher = configurationRefresher;
            //_configurationRefresher.SetDirty();
            //_configurationRefresher.TryRefreshAsync();

            if (myClass != null)
            {
                try
                {
                    _myClass = myClass.Value;
                }
                catch (Exception ex)
                {
                    _telemetryClient.TrackException(ex);
                }
            }
            else
            {
                _telemetryClient.TrackTrace($"MyClassProvider has no config for {nameof(MyClass)}");
            }
        }

public async Task<MyClass> GetMyClass()
        {

            //VVVV this is currently commented out, but it didn't work when it was not commented
            //_configurationRefresher.SetDirty();
            //bool pass = await _configurationRefresher.TryRefreshAsync();

            MyClass myClass = _myClass ?.Where(get a list of MyClass) .FirstOrDefault();

           //This seems to always log the value pre-refresh, it never changes
            _telemetryClient.TrackTrace($"This thing is enabled value after refresh async: {myClass?.BooleanValue}.");

            if(myClass.BooleanValue)
            {
                return myClass;
            }

            return null;
        }`

**Comment by zhenlan** [comment]
Please use `IOptionsSnapshot` instead of `IOptions`. The `IOptions` doesn't refresh after the app startup.

```cs
public MyClassProvider(IOptionsSnapshot<List> myClass, ...
```

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0#options-interfaces

**Comment by Troy1776** [comment]
Hi @zhenlan thank you for your comment. I have made the change but it still will not refresh

**Comment by Troy1776** [comment]
I tried IOptionsMonitor. I get the refreshed value about 50% of the time, & the old value the other 50%.

**Comment by Troy1776** [comment]
Hi, looking again for help. It seems the problem is the fact that this is a List<MyObject>. There seem to be no problems with MyObject

**Comment by zhenlan** [comment]
@Troy1776, thanks for the update. Glad to hear you made progress. Please ensure the type you use in the code matches the configuration section you are binding on. Did you try `IOptionsSnapshot<List<MyClass>>` because it looks like `List<MyClass>` is the type you bind with the configuration section?

**Comment by Troy1776** [comment]
Hello. Yes, it is a <List<MyClass>>, my example in this post is a typo but in my code it is a List. I tried IOptionsSnapshot but that did not refresh anything. IOptionsMonitor seems to refresh it about 50% of the time, and the other 50% it will still provide the old value.

**Comment by Troy1776** [comment]
This is resolved. Needed to change this

"services.Configure<List<MyClass>>(options => configuration.GetSection(nameof(MyClass)).Bind(options));"

to this

"services.AddOptions<List<MyClass>>().Configure<IConfiguration>((settings, configuration) => { configuration.GetSection(nameof(MyClass)).Bind(settings); });
                    
services.**AddScoped**<IMyClass, MyClass>();"
