### ISSUE TITLE
Azure App Configuration Push Task - Push Feature Flags with : symbol

### ISSUE THREAD

**Issue by jadcosta** [Azure/AppConfiguration#733]
Hello, when pushing Feature Flags with : symbol in the key I got the following error:

> ##[error]An unexpected error occurred. Feature flag flags:eu:test:operationscontains invalid character, only alphanumeric characters, '.', '-' and '_' are allowed in feature name. Please provide valid feature name.

However, when importing the Feature Flags with the AZ CLI command **az appconfig kv import**, I'm able to push the Feature Flags with : in the feature name.

Could you please update the Push Task to have the same behaviour has the AZ CLI command?

**Comment by zhenlan** [comment]
The feature management library won't work if a feature flag contains a colon (:) in the name. The Push Task protects you from creating unusable feature flags. Looks like we miss some validation logic in the Azure CLI. @albertofori, can you help take a look?

@jadcosta, if your intent is to create namespaces for your feature flags, you can add them to the key name of the feature flag. This way, you can select to load feature flags with a certain prefix only in your application code. Here is an example
![image](https://user-images.githubusercontent.com/10566826/227590427-6d057143-c7c9-49e9-8ee6-633a145e4625.png)

Your application code can have something like what is mentioned in the Tips in this document:
https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-aspnet-core?tabs=core6x#use-a-feature-flag

**Comment by zhenlan** [comment]
@MaryanneNjeri @albertofori can you please update the Push Task and CLI to match the portal behavior - allow the feature flag name to be anything but `%` and `:` (it's okay for the key name to include `:`)?

**Comment by MaryanneNjeri** [comment]
Push Task has been updated to match Portal behavior in version 6.0.0
