### ISSUE TITLE
App Configuration push Task Failing with Error

### ISSUE THREAD

**Issue by ajith753** [Azure/AppConfiguration#738]
Hi Team,
We are trying to Push few changes to Azure app configuration service using azure app configuration push task. We are getting the below error .

We have tested the same task using 32 bit and 64 bit azure devops agent. Below are the agent details.

Azure App Configuration Push Task Version used - 5.0.0

Azure Devops Server (On-Prem) Version - Azure Devops version 2020 (Version Dev18.M170.6)

64 bit and 32 bit agent details: 

- Agent version - 2.170.1
- Agent OS - Windows_NT
- Agent.OSArchitecture - x64
- Agent.OSVersion - 10.0.14393

**Comment by ajith753** [comment]
Hi @MaryanneNjeri Its working .Thanks a lot

**Comment by zhenlan** [comment]
@MaryanneNjeri does it help to document the minimum agent version too (besides the minimum node version)?

**Comment by MaryanneNjeri** [comment]
@zhenlan yes, I think documenting the minimum agent version will be helpful. I'll make an update.

**Comment by MaryanneNjeri** [comment]
PR to update docs has been checked in.
