### ISSUE TITLE
Add current request quota metric.

### ISSUE THREAD

**Issue by drago-draganov** [Azure/AppConfiguration#739]
With different optimization in place (discounting requests, tec.) it's difficult to predict how close is a configuration store to its quota limits at a given moment. A dedicated quota metric should be able to address this concern.

**Comment by samsadsam** [comment]
Request Quota Usage metric added! Please see our metrics docs reference for more details: https://learn.microsoft.com/en-us/azure/azure-app-configuration/monitor-app-configuration-reference
