### ISSUE TITLE
Updated configurations are not getting refreshed in my application

### ISSUE THREAD

**Issue by spatnaik77** [Azure/AppConfiguration#74]
Hi - I am using the Java SDK. When i update a key value in portal, it does not reflect in my running application. I have set the following properties explicitly.

spring.cloud.azure.config.watch.enabled=true
spring.cloud.azure.config.watch.delay=10s

Thanks,
Siddharth

**Comment by zhenlan** [comment]
Hi @spatnaik77, sorry for running into this. Looks like our document may not be accurate. I will follow up.

Can you please try this instead (replace 'config' with 'appconfiguration')?

spring.cloud.azure.**appconfiguration**.watch.enabled=true

**Comment by zhenlan** [comment]
While we are fixing the documentation, here is the link of the doc for Java spring configuration provider.
https://go.microsoft.com/fwlink/?linkid=2074659

**Comment by zhenlan** [comment]
The documentation has been fixed.

@spatnaik77, please let us know if you run into any other issues.
