### ISSUE TITLE
Users are unable to use the UI to create Key Vault references by browsing unless they also have "get secret" permissions.

### ISSUE THREAD

**Issue by kbuley** [Azure/AppConfiguration#743]
We are able to browse to select the Key Vault and secret name, but are unable to complete the reference because the version drop-down does not populate unless the user has the Microsoft.KeyVault/vaults/secrets/getSecret/action permission.

This is unexpected, as Microsoft.KeyVault/vaults/secrets/readMetadata/action allows the user to see version information while using az cli or the Key Vault UI.

The idea is similar to that of service connections in ADO. Users can leverage the secret without knowing the underlying value. The actual values are eventually retrieved by the application via an MSI with appropriate permissions. Requiring getSecret for the user negates this.

Was this a conscious decision? UI bug?

Is there any workaround other than having the user add the reference by pasting the secret identifier?

**Comment by zhenlan** [comment]
Sounds reasonable to me. @jiayi11, can our Portal require less permission?

**Comment by jiayi11** [comment]
Yes, I agree. This is a UI issue. Users should be able to create key vault references as long as they have access to list secret versions.

I'm tracking this item in our current sprint and will update here once the fix is being rolled out.

**Comment by jiayi11** [comment]
This fix is already deployed in production. Please let us know if you have more questions.
