### ISSUE TITLE
Allow the filtering of key values by tags in the portal

### ISSUE THREAD

**Issue by Gabriel123N** [Azure/AppConfiguration#747]
## Issue

Currently, it is possible to assign tags to the key-values of the app configuration but it is impossible to filter the currently displayed keys using tags or to display the tags in the UI 

![filter](https://user-images.githubusercontent.com/50913834/235159108-b50b28d4-f3cb-432f-bef6-09e795fa5f5d.png)
![columns](https://user-images.githubusercontent.com/50913834/235159377-b045439a-89ac-4071-a62b-7fea98dd499e.png)

## Solution

The filters for the key-values displayed should include the tag property.

Ideally, a new column for tags would also be added.

**Comment by ChristineWanjau** [comment]
@Gabriel123N Thanks for bringing this up . We currently have a rollout this week where we have added an optional tag column. Users can also search based on the tag value using the provided search box on each page.

**Comment by jiayi11** [comment]
Closing as finished.
The Edit Columns options now support tags. Once added into the grid, search result from the search box will include searching tags value.
