### ISSUE TITLE
Watch and WatchAndReloadAll doesn't work with labels and TimeSpan 

### ISSUE THREAD

**Issue by AhmedSa3d-MS** [Azure/AppConfiguration#75]
Hi, 

I'm trying the connect to Config Explorer using connect(connectionstring)

and I wanted to watch a value and change the polling interval and set the label of what I want to reload , but then when I run the code, change the value I'm watching in the portal, I got task cancelled then the process crashes with a TaskCancelledException 

options.Connect("").watchAndReloadAll("LastUpdated", "*Version1*", TimeSpan.FromSeconds(2));

**Comment by zhenlan** [comment]
Hi @AhmedSa3d-MS, you may run into an issue discussed in #70. We are reworking in this area and will fix this issue. Thanks for the feedback!

**Comment by zhenlan** [comment]
Duplicate of #70
