### ISSUE TITLE
Update Azure Key Vault sample code for .Net 7

### ISSUE THREAD

**Issue by PeteCozens** [Azure/AppConfiguration#751]
In the page [Tutorial: Use Key Vault references in an ASP.NET Core app](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core), the code samples only go as far as .Net 5. These are all deprecated in .Net 7, so could you please provide some updated code samples?

**Comment by avanigupta** [comment]
Hello @PeteCozens, we are working on updating all our docs to provide .NET6+ code samples. In the meantime, here's an updated version of the document you're interested in. The only change is in the code snippet on step 3 of "Update your code to use a Key Vault reference" section:

```cs
using Azure.Identity;

var builder = WebApplication.CreateBuilder(args);

// Retrieve the connection string
string connectionString = builder.Configuration.GetConnectionString("AppConfig");

builder.Configuration.AddAzureAppConfiguration(options =>
{
    options.Connect(connectionString)
           // Configure Key Vault options
           .ConfigureKeyVault(kv =>
           {
               kv.SetCredential(new DefaultAzureCredential());
           });
});

```

**Comment by jimmyca15** [comment]
It looks like this has been updated.
