### ISSUE TITLE
AppConfigurationRefresh with Spring Boot 3

### ISSUE THREAD

**Issue by wondris009** [Azure/AppConfiguration#756]
Hello,

I am using:
```
implementation("com.azure.spring:azure-spring-cloud-appconfiguration-config:2.11.0")
```

and when we upgraded to spring boot 3.0.6 app can't find bean which is implementing interface `AppConfigurationRefresh`. 

My usage is stadnart we have our bean:
```
@Configuration
@EnableScheduling
class AppConfigurationUpdater(val appConfigurationRefresh : AppConfigurationRefresh) {
```

If i look directly which class is implementing **AppConfigurationRefresh** interface, there is bean in the library:

```
@Component
public class AppConfigurationPullRefresh implements AppConfigurationRefresh {
```

Problem is that after upgrade to spring boot 3 app can't see it (with spring boot 2.7.9 it was working as expected):
```
caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.azure.spring.cloud.config.AppConfigurationRefresh' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

Any clue why? Any comments are appreciated.

Regards

Lukas

**Comment by mrm9084** [comment]
@wondris009 that version doesn't support Spring Boot 3, you need to use:
`implementation("com.azure.spring:spring-cloud-azure-appconfiguration-config:5.1.0")`

**Comment by wondris009** [comment]
Wow. I couldn't find it. Many thanks.
