### ISSUE TITLE
Facilitate Feature Opt-Out using TargetGroups

### ISSUE THREAD

**Issue by Gordonby** [Azure/AppConfiguration#759]
In the event of a 100% default feature-flag rollout, the Group rollout percentages are ignored.

Given the scenario in the screengrab;

![image](https://github.com/Azure/AppConfiguration/assets/17914476/35221535-1ae8-43c1-8438-875d515e430a)

I want (and expect) that any Groups matching will result in a 0% rollout. However that is not the behaviour that is observed, instead the 0% is ignored in favour of 100% rollout.

The use case this facilitates is allowing a specific user group to opt-out of the feature because of a user-group specific problem.

**Comment by Spaig** [comment]
Can confirm that my testing shows the same thing - would be very convenient to be able to allow a specific user group to opt-out!

**Comment by rossgrambo** [comment]
Hello @Gordonby & @Spaig,

We're introducing a solution for this, called `Exclusion`. We just added support for this in our [2.6.0-preview release of the FeatureManagement library](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.6.0-preview).

The portal changes are still being done, so you will need to wait for those, or use Advanced Edit to achieve it today.

In your situation, the Targeting Audience would look like:
```
"Audience": {
  "DefaultRolloutPercentage": 100,
  "Exclusion": {
    "Groups": [
      "theOptOutGroup"
    ]
  }
}
```

The `FeatureManagement` release will be out of preview soon. Unsure how soon the portal changes will happen, but they're on the way.

**Comment by Gordonby** [comment]
Awesome news 🚀

**Comment by Spaig** [comment]
Excellent news! Is there an ETA on the 2.6 release yet?

**Comment by zhenlan** [comment]
As @rossgrambo mentioned, we are working on the Portal support. We plan to release the 2.6 stable at about the same time as we roll out the Portal update. Please let us know if you need the stable version for prod use even without the Portal support.

**Comment by ChristineWanjau** [comment]
Hello @Gordonby this is just to inform you we have rolled out Portal support for Exclusion. Please give it a try and provide us with feedback. Thank you

**Comment by jimmyca15** [comment]
This support has been rolled out in stable version [2.6.0 of Microsoft.FeatureManagement](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.6.0). Additionally, as Christine mentioned, the App Configuration portal is also updated to allow specifying excluded users/groups.
