### ISSUE TITLE
Is there a way to updated some key/s thru the API?

### ISSUE THREAD

**Issue by vany0114** [Azure/AppConfiguration#76]
Hi guys,

I was wondering if is there a way to update the keys thru the REST API? I might want to update them from my app. I took a look at the API documentation but I haven't seen a resource to update keys, all of them are Get methods.

Thanks.

**Comment by zhenlan** [comment]
Hi @vany0114, yes, all CRUD operations are supported through REST APIs. For example, please check out the `Set` and `Delete` operations of the `/kv` endpoint.
https://github.com/Azure/AppConfiguration/blob/master/docs/REST/kv.md

If you are using .NET, an SDK is also available for "write" operations.
https://go.microsoft.com/fwlink/?linkid=2092056

**Comment by vany0114** [comment]
Oops, I hadn't seen it. Thanks @zhenlan
