### ISSUE TITLE
How to avoid bandwidth usage exhaustion?

### ISSUE THREAD

**Issue by lissdy** [Azure/AppConfiguration#765]
The document https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#my-application-receives-http-status-code-429-responses--why mentioned "Excessive bandwidth usage" would lead to 429 response, but I didn't find any official document mentions a specific bandwidth limit or restriction.  May I know what's the best practice to avoid bandwidth usage exhaustion?

**Comment by Eskibear** [comment]
> May I know what's the best practice to avoid bandwidth usage exhaustion?

@lissdy
https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-best-practices#reduce-requests-made-to-app-configuration See if it helps.

**Comment by lissdy** [comment]
Thanks  @Eskibear  for replying, may I know the relationship between "Excessive requests" and "Excessive bandwidth usage"?
It's easy to understand that > 30k/hour request may lead to 429, but if it possible to hit Excessive bandwidth usage before the HTTP request limitation?

**Comment by Eskibear** [comment]
> Throttling is divided into different quota policies:
> 
> Total Requests - total number of requests
> Total Bandwidth - outbound data in bytes
> Storage - total storage size of user data in bytes

See https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-throttling

AFAIU, it could happen if you keep sending repeated requests for all key-values in a short time. As for the bandwidth quota, @zhenlan might have more information.

**Comment by drago-draganov** [comment]
Bandwidth limit is short-term (per second). It should not be a concern of system availability. The limit is high enough to accommodate high short-term request burst. Quota should not be affected.
In the rare case when the bandwidth limits are reached, all our client-side tools will retry automatically and recover.

**Comment by lissdy** [comment]
Thanks for replying, it would be helpful if the information can be described in the document.
