### ISSUE TITLE
Managed Identity from ACA

### ISSUE THREAD

**Issue by demyte** [Azure/AppConfiguration#768]
Hi there,

We are using Azure Container Apps (.NetCore WebAPI) with a user assigned managed identity.

When I am connecting to the service, I am using the following as per this [guide](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?pivots=framework-dotnet&tabs=core5x)

```c#
options.Connect(new Uri(endpoint), new ManagedIdentityCredential(managedIdentity));
```

Where `endpoint` is the https uri of the instance and `managedIdentity` is the clientId of the user assigned managed identity.

When it connects, it gets a 403.

The managed identity is set as a contributor to the AppConfiguration instance and has Get/List access to the keyvault we use.

Should this scenario work?

How am I able to increase the logging or see the logging to work out why it is giving a 403?

**Comment by RichardChen820** [comment]
Contributor is a management plan role to grant the access to manage the App Configuration resource, to access data in App configuration store, you need grant App Configuration Data Reader role to your managed identity according to this [guide ](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-integrate-azure-managed-service-identity?pivots=framework-dotnet&tabs=core5x#grant-access-to-app-configuration)
