### ISSUE TITLE
Azure Pipeline Task for pulling configurations not maintaining case

### ISSUE THREAD

**Issue by charleshamel73** [Azure/AppConfiguration#77]
The Azure Pipeline Task which pulls app configuration does not maintain the case. 
For example A key like Dev_Connection in App Configuration gets set as dev_connection in the release pipeline. 
This is making XML Variable transformation fail to match and replace configs due to it being case sensitive.

**Comment by zhenlan** [comment]
Hi @charleshamel73, correct me if I am wrong - it's my understanding that the variables in Azure DevOps pipeline are case **insensitive**. Though the App Configuration service is case *sensitive*, the casing cannot be preserved when keys are pulled into DevOps pipeline unless pipeline supports it.

Does your XML variable transformation work without using the App Configuration service?

**Comment by charleshamel73** [comment]
Pipelines do support setting variables that have uppercase in them.
So tested this out and found out:
1) powershell pipeline task are capable of resolving case-insensitive
2) vso variables can be set to maintain casing
3) App Configuration Service Task is in fact setting the variables with all lowercase
4) Xml variable transformation is in fact case-sensitive and tested this by seeing if a lowercase release variable updated a value.

It is failing as the variable set during the task using:
 ##vso[task.setvariable variable=azurewebjobsstorage;issecret=false;]
is what is used to resolve in XML transformation and is case-sensitive
Any way that the Azure App Configuration can be updated to execute this line while maintaining the original casing?

**Comment by Yiming-Jia** [comment]
Hello @charleshamel73 ,

I had the same question against the pipeline team, [issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/534); as well as followed up offline. I was told that this is their by-design, and they currently  don't have a plan to make the case sensitive because it could potentially break any existing customer's changes. 

Previously, we lowercase all variable name in our task, but I had a fix for it and going to release today. But still, in their library, I think they'll uppercase all environment variable names.

Please let me know if there are other questions.

Thanks,
Yiming

**Comment by charleshamel73** [comment]
Did you ever release the fix? How do I ingest the fix and any place I can take a look for the update?

**Comment by Yiming-Jia** [comment]
Yes, the release is already included in the version 1.6.3, which is printed out when you run the extension. Also, I'm writing a release notes, and will update this issue when publish it.

**Comment by Yiming-Jia** [comment]
@charleshamel73 This is our Azure DevOps pipeline task [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/AzureDevOpsPipelineExtension.md)

**Comment by Yiming-Jia** [comment]
Please let me know if you have other questions. Thanks

**Comment by jimmyca15** [comment]
Hello @charleshamel73, this issue appears to be resolved. Please re-open if there is anything pending that I have missed. Thanks!
