### ISSUE TITLE
Application startup exception: System.InvalidOperationException: Unable to access the Azure App Configuration provider on AKS cluster

### ISSUE THREAD

**Issue by shahriak** [Azure/AppConfiguration#772]
Hello,

I am trying to configure and add Azure App Config on an ASP.NET core application. I am able to run it locally, however, once it gets deployed on an aks cluster, I see the error:

Application startup exception: System.InvalidOperationException: Unable to access the Azure App Configuration provider. Please ensure that it has been configured correctly.
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationRefresherProvider..ctor(IConfiguration configuration, ILoggerFactory _loggerFactory)

The project is on .NET 6
Using package: "Microsoft.Azure.AppConfiguration.AspNetCore" Version="6.0.1"

Program.cs file

              var webHost = WebHost.CreateDefaultBuilder()
                    .ConfigureAppConfiguration(config =>
                    {
                        if (azureAppConfigUri != null)
                        {
                            config.AddAzureAppConfiguration(options =>
                            {
                                options.Connect(azureAppConfigUri, new ManagedIdentityCredential())
                                    .ConfigureRefresh(refresh =>
                                    {
                                        refresh.Register(AppCnMasterSentinel, refreshAll: true)
                                            .SetCacheExpiration(environmentRuntime.EnvironmentDefinition.AppConfigCacheExpiration);
                                    });
                            });
                        }
                    })
                    .ConfigureKestrel(
                        (context, options) =>
                        {
                            // TODO: This is necessary for the custom JSON serialization/deserialization. See if we can make it async later.
                            // This applies to all FD.
                            options.AllowSynchronousIO = true;

                            options.ConfigureHttpsDefaults(configureOptions =>
                            {
                                configureOptions.ClientCertificateMode = ClientCertificateMode.AllowCertificate;
                                configureOptions.SslProtocols = environmentRuntime.EnvironmentDefinition.SslProcotols;

                                configureOptions.OnAuthenticate = (connectionContext, sslOptions) =>
                                {
                                    sslOptions.CipherSuitesPolicy =
                                        environmentRuntime.EnvironmentDefinition.CipherSuitePolicy;
                                };

                                // ignore client cert validation temporarily, helps with
                                // testing and does not require us to maintain the CA certs
                                // in repo. should be until commerce mesh can bake in the CA certs
                                // in the image. This is fine because we have a allowed list of thumbprints
                                // that we compare against and ignore certs not in the list.
                                configureOptions.CheckCertificateRevocation = false;
                                configureOptions.ClientCertificateValidation = (cert, chain, policyErrors) => true;
                            });

                            options.Listen(IPAddress.Any, httpPort);
                            options.Listen(IPAddress.Any, httpsPort, listenOptions =>
                            {
                                listenOptions.UseHttps(httpsCert);
                            });

                            options.Limits.MaxConcurrentConnections =
                                role == "licensingentitlementsfd"
                                    ? environmentRuntime.EnvironmentDefinition
                                        .LicensingEntitlementsThrottlingSettings.KestrelMaxConcurrentConnections
                                    : environmentRuntime.EnvironmentDefinition
                                        .EntitlementsThrottlingSettings.KestrelMaxConcurrentConnections;

                            // Disable min request body data rate so we reply even during
                            // network congestion
                            options.Limits.MinRequestBodyDataRate = null;
                        })
                    .ConfigureServices(
                        services =>
                    {
                        services.AddSingleton<IConfiguration>(configuration);
                    })
                    .ConfigureLogging((hostingContext, logging) =>
                    {
                        logging.ClearProviders();
                    })
                    .ConfigureLogging(loggingBuilder =>
                    {
                        loggingBuilder.AddSequencedEventLogger(new NLogEventLogger(NLogConfigFileName));
                        if (region == LocalRegionString)
                        {
                            loggingBuilder.SetMinimumLevel(LogLevel.Warning);
                        }

                    })
                    .UseNLog()
                    .UseShutdownTimeout(environmentRuntime.EnvironmentDefinition.GracefulTimeout)
                    .UseStartup<Startup>();

                webHost.Build().Run();
            }

Startup.cs

        public virtual void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton(this.loggerFactory);
            services.AddSingleton(this.logger);
            services.AddHttpContextAccessor();

            var environmentDefinition = this.environmentRuntime.EnvironmentDefinition;
            services.AddSingleton(environmentDefinition);

            services.AddAzureAppConfiguration();
            services.Configure<EntitlementsStorageRolloutConfig>(this.Configuration.GetSection("MigrationBucketSettings"));
            services.AddSingleton<IOptionsMonitor<FDDynamicConfig>, OptionsMonitor<FDDynamicConfig>>();
            services.AddSingleton<IAppConfigContext<FDDynamicConfig>>(provider =>
            {
                var operatingModeMonitor = provider.GetRequiredService<IOptionsMonitor<FDDynamicConfig>>();
                var logger = provider.GetRequiredService<ILogger<AppConfigContext<FDDynamicConfig>>>();

                return new AppConfigContext<FDDynamicConfig>(operatingModeMonitor, logger);
            });

   
            this.ConfigureExternals(services);
            this.ConfigureAuthentication(services);
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            // Enable automatic configuration refresh from Azure App Configuration
            app.UseAzureAppConfiguration();

            InstrumentationMiddlewareOptions middlewareOptions = new InstrumentationMiddlewareOptions()
            {
                CorrelationAndRequestIdsRequired = false,
                CorrelationVectorExtensionBehavior = CorrelationVectorExtensionBehavior.SeedOnValidationFailure,
                CountTestCalls = false,
                InstanceCountersPerPort = false
            };
            app.UseHealthChecks("/health/keepalive", CompliantHealthCheckOptions.NoSniff);

            app.UseRouting();
            app.UseMiddleware<UnhandledExceptionMiddleware>(
                new EntitlementsServiceExceptionConverter(
                    EntitlementsServiceExceptionProvider.ErrorSource));
            app.UseMiddleware<InstrumentationMiddleware>(middlewareOptions);
            app.UseMiddleware<EntitlementsTestHeaderMiddleware>();
            app.UseMiddleware<TestHeaderMiddleware>();
            app.UseMiddleware<KeepAliveMiddleware>();
            app.UseMiddleware<ShadowValidationMiddleware>();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseMise();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapDefaultControllerRoute();
            });
        }

**Comment by jimmyca15** [comment]
My suspicion is this line is problematic.

`services.AddSingleton<IConfiguration>(configuration);`

ConfigureAppConfiguration should already be adding an instance of IConfiguration to the dependency injection container. The error you mentioned occurs when UseAzureAppConfiguration cannot find the Azure App Configuration provider. I expect the call to `services.AddSingleton<IConfiguration>(configuration);` is hiding it.

What `configuration` is being passed there? I don't see it defined.

**Comment by amerjusupovic** [comment]
@jimmyca15 Sorry, I should've marked this issue as completed. This was in fact the issue, and it was resolved in an ICM.
