### ISSUE TITLE
Include user and request body in AACAudit

### ISSUE THREAD

**Issue by dlmotter** [Azure/AppConfiguration#774]
We need to log when a user changes a Feature Flag value for SOX auditing.

You can see which flag was changed with the TargetResource value, but you cannot see if it was enabled/disabled, or if there were Feature Filters.

Also, if the change is made through the Azure Portal, the CallerIdentity value does not include the user who made the change. It is just an API key. This is where people change the value, so it is important that you can audit this.

**Comment by jimmyca15** [comment]
> Also, if the change is made through the Azure Portal, the CallerIdentity value does not include the user who made the change. It is just an API key.

That will occur whenever connection string/api key authentication is used. This is the default authentication method in the Portal. If you'd like you can disable connection string authentication and force AAD authentication to be used. In that case, caller identity should be populated with the user as you'd expect.

![image](https://github.com/Azure/AppConfiguration/assets/21000428/4d0fe818-1eb7-47b9-9deb-b994682225a8)

**Comment by dlmotter** [comment]
@jimmyca15 thank you for the information
