### ISSUE TITLE
Support for file-like configmap keys in the kubernetes provider

### ISSUE THREAD

**Issue by landintrees** [Azure/AppConfiguration#775]
We are using the AKS flux extension to deploy helm releases and use the valuesFrom field to override helm values via a configmap. This requires the field be a file-like yaml file so flux can merge in the values into the chart. However the kubernetes provider creates a configmap with name-value pairs with cannot be merged in using the valuesFrom directive.

As an example, this is the configmap created by the AppConfigProvider:

```
apiVersion: v1
kind: ConfigMap
data:
  "FQDN": "app.myurl.com"
  "acr_name": "myacr"
  "api_app_id": "24857289457-24524524-2454254"
  ...
```

```
apiVersion: v1
kind: ConfigMap
data:
 terraform.yaml: |
    "terraform":
      "FQDN": "app.myurl.com"
      "acr_name": "myacr"
      "api_app_id": "24857289457-24524524-2454254"
      ...
```

It would be helpful for us if there was an option to output the key-values pairs into a file-like key like the example above to support flux's valuesFrom field.

**Comment by zhenlan** [comment]
Thanks for sharing the feedback, @landintrees. This is in our roadmap to support.

**Comment by RichardChen820** [comment]
@landintrees In your example, you have several key-values in Azure App Configuration 
```
  "FQDN": "app.myurl.com"
  "acr_name": "myacr"
  "api_app_id": "24857289457-24524524-2454254"
```

You propose an option to create a file-style configMap using these key-values:
```
apiVersion: v1
kind: ConfigMap
data:
 terraform.yaml: |
    "terraform":
      "FQDN": "app.myurl.com"
      "acr_name": "myacr"
      "api_app_id": "24857289457-24524524-2454254"
```

I'm wondering that is there any particular reason that you need an extra level `terraform` in your yaml file, rather than requiring a configMap in this style:
```
apiVersion: v1
kind: ConfigMap
data:
 terraform.yaml: |
      "FQDN": "app.myurl.com"
      "acr_name": "myacr"
      "api_app_id": "24857289457-24524524-2454254"
```

**Comment by RichardChen820** [comment]
If you need to have multiple levels, you could leverage the key prefix.

```
apiVersion: v1
kind: ConfigMap
data:
 terraform.yaml: |
      "terraform:FQDN": "app.myurl.com"
      "terraform:acr_name": "myacr"
      "terraform:api_app_id": "24857289457-24524524-2454254"
```

**Comment by landintrees** [comment]
> If you need to have multiple levels, you could leverage the key prefix.
> 
> ```
> apiVersion: v1
> kind: ConfigMap
> data:
>  terraform.yaml: |
>       "terraform:FQDN": "app.myurl.com"
>       "terraform:acr_name": "myacr"
>       "terraform:api_app_id": "24857289457-24524524-2454254"
> ```

Hi @RichardChen820, yes that would also work for us. The main requirement was for the ability to use file-like yaml file.

**Comment by RichardChen820** [comment]
Thanks, we are working on supporting it, please stay tuned.

**Comment by RichardChen820** [comment]
It is available in [preview4](https://mcr.microsoft.com/en-us/product/azure-app-configuration/kubernetes-provider/about) now.

Besides the default data type we've already provided, the provider could generate json , yaml or properties type, that support consuming the generated ConfigMap as a mounted file besides as environment variables.
