### ISSUE TITLE
Azure CLI + Terraform Support

### ISSUE THREAD

**Issue by dazmsft** [Azure/AppConfiguration#78]
Can App Configuration be used with 

a) Azure CLI - I can't see any support
b) terraform, if so which version

If not, when is support planned

**Comment by arkiaconsulting** [comment]
I don't think the Azure CLI nor terraform already support App Configuration.
You could use a `azurerm_template_deployment` resource type, example [here](https://github.com/arkiaconsulting/feature-toggling/blob/master/Resources/tf/arm/app-config.json)

**Comment by zhenlan** [comment]
App Configuration does have Azure CLI support. You can enable it with the command below
```
az extension add -n appconfig
```
Please check out the document below for more examples
https://docs.microsoft.com/en-us/azure/azure-app-configuration/scripts/cli-create-service

Terraform is not supported. As @arkiaconsulting mentioned, you can use Azure Resource Manager (ARM) template to provision App Configuration.

**Comment by zhenlan** [comment]
App Configuration can now be provisioned with Terraform
https://www.terraform.io/docs/providers/azurerm/r/app_configuration.html
