### ISSUE TITLE
Feedback - 30K per hour limit

### ISSUE THREAD

**Issue by wviriya** [Azure/AppConfiguration#780]
We want to store a mix of servers' and clients' configurations on Azure App Configuration standard. However, we have millions of clients and hundreds of servers in a region that could potentially reach 30K requests per hour. I would like to know how to overcome this limitation. Specifically, when the service reaches the limitation, the clients won't be able to make further request to App Configuration Service until an hour has passed. **Would the product team consider rate limiting requests per minute instead of an hour?** This will allow for client to retry after one minute has passed. I also have the following questions:

I can see that the limit is per replica. I would like to confirm that if I reach the limit in the master service, I can make requests to other geo replicas. 

Can the quota be increased?

Do you have any plan to offer a premium tier with higher limit in the future?

I also notice that the service can also be throttled due to a large burst of requests. How many requests (RPS) would trigger this?

**Comment by Muksvso** [comment]
30K requests could either be 30K unique read requests or 30K write requests or a mix of those amounting to 30K. please read more into the requests count [here](https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#how-do-i-estimate-the-number-of-requests-my-application-may-send-to-app-configuration)

It will be a good idea to not use the same Config store for server and client scenario especially from the security perspective.

For the replicas question, yes you can query a replica if the origin or another replica has hit the hourly quota. Or it will be a good idea to balance it out from start and implement querying replicas for config from nearer application deployments.

The limits are fixed and can't be increased today. That said, we have been looking into the possibility of offering more, so it will be very helpful to know what the target number for the mentioned scenario would be, if the increase was possible. 

For client config scenarios, there is an item on the services near term (6 months) roadmap to offer an integration with CDN, to serve configuration to clients over CDN backed by App Config store. 

For the RPS, Short term throttling doesn't start with the 8 requests per second (30K/3600), App Config does serve requests at a much higher rate. not able to put a number on it as it is dependent on multiple factors.

**Comment by zhenlan** [comment]
@wviriya please let us know if you have further questions/feedback.
