### ISSUE TITLE
Is restart of pod required if App Configuration is updated

### ISSUE THREAD

**Issue by priya30m** [Azure/AppConfiguration#781]
For Azure App Configuration Kubernetes Provider, is Config map updated if there is any change in app configuration key/value? 

Also can I mount the the config map created by provider in a volume so that application pod get the updated key/value on periodic sync?

Also how to specify the namespace of configmap created by appconfig provider since configmap in created in one namespace cannot be shared by pods deployed in different namespace?

**Comment by RichardChen820** [comment]
> Is Config map updated if there is any change in app configuration key/value?
Currently, configMap would not be updated automatically with changes in App Configuration. As workaround, you can use one of the following two ways 
1. Delete the generated ConfigMap, the provider will re-create it with the updated key/value
2. Redeply AzureAppConfigurationProvider yaml
We are working on the auto-refresh feature, it would be available soon in the upcoming new version.

> Also can I mount the the config map created by provider in a volume so that application pod get the updated key/value on periodic sync?

**Comment by RichardChen820** [comment]
>Also how to specify the namespace of configmap created by appconfig provider since configmap in created in one namespace cannot be shared by pods deployed in different namespace?
The provider creates configMap under the same namespace of `AzureAppConfigurationProvider`, you can create your `AzureAppConfigurationProvider` resource in different namespaces.

**Comment by priya30m** [comment]
> We are working on the auto-refresh feature, it would be available soon in the upcoming new version. It would poll a sentinel key ( a key that be specified by user) periodically, once the provider detects the sentinel key is changed, it will update the configmap with the present data from your AppConfigruation store.

So as of now config map can be used in pod as env variables only? And restart of pod and redeploy of AzureAppConfigurationProvider yaml file, both steps are needed to get updated values in pod?

**Comment by RichardChen820** [comment]
The ConfigMap can be mounted as a volume as well now, but the data in configMap can only be populated in volume using the configuration key as file name and configuration value as file content.

At present, to get updated values in pod, you should redeploy the yaml and restart the pod.
