### ISSUE TITLE
key vault changes are not automatically recognized

### ISSUE THREAD

**Issue by krenaut1** [Azure/AppConfiguration#784]
Because app config key vault references include the secret version, updates to objects in key vault are not automatically recognized.  This means that all key vault changes require a two step process; 1) create new version of key vault object 2) edit app config key to reference new key vault object version.

This is terribly inconvenient and quite frankly a poor user experience.  Maybe the design is right, I don't know.  But, their should be a more convenient way to achieve this.

**Comment by ivywei0125** [comment]
Hi @krenaut1 , thans for the feedback. We're sorry for the inconvenience. You can manually modify the value of the Key Vault reference through the 'advanced edit' in the right-click menu bar, and remove the **version number** in the value.
We will fix this in the next release.

**Comment by fgarciaips** [comment]
Any news or information around this issue? This behavior appears to be relatively new as some of our automated processes have hit issues related to this.

**Comment by ivywei0125** [comment]
Hi @fgarciaips , Thank you for contacting us. We have fixed this issue, but it will take some time to release. The release is still inprogress and maybe end after a week.
If it's hurry, you could try the workaround way. Manually modify the value of the Key Vault reference through the 'advanced edit' in the right-click menu bar, and remove the version number in the value.

**Comment by fgarciaips** [comment]
The workaround will do for now. Simply hearing that the fix is in the works gives me the peace of mind to move on, thanks!

**Comment by ivywei0125** [comment]
Hi @fgarciaips  @krenaut1 , we have already released the fix. If you create a Key Vault reference now, it should not include the secret version number. Feel free to contact us if you have any qustions.
