### ISSUE TITLE
Order of spring.cloud.azure.appconfiguration.stores

### ISSUE THREAD

**Issue by yashas224** [Azure/AppConfiguration#787]
What is the order in which the configuration is loaded when there are multiple stores defined?

for example:
spring.cloud.azure.appconfiguration.stores[0].connection-string=[first-store-connection-string]
spring.cloud.azure.appconfiguration.stores[1].connection-string=[second-store-connection-string]

What is first checked?  first-store or second-store

Thanks,
Yashas Samaga

**Comment by jimmyca15** [comment]
@mrm9084 can you help here?

**Comment by mrm9084** [comment]
They are read from and take priority in reverse order. i.e. second-store is read from first, and if there is a duplicate key between the stores it takes priority.

**Comment by jimmyca15** [comment]
Thanks @mrm9084 . Closing the issue since it's been answered. @yashas224 feel free to re-open if there is still any question on this.
