### ISSUE TITLE
Access to the target App Configuration instance was denied

### ISSUE THREAD

**Issue by pmateju** [Azure/AppConfiguration#789]
Hello,

setup:

we have service connection in our azure devops org via Azure resource manger , the service principal is assigned 
**App Configuration Data Owner** role for the AAC instance. Basically what is described here:

https://learn.microsoft.com/en-us/azure/azure-app-configuration/push-kv-devops-pipeline

we use latest version of the Azure app config push task (AzureAppConfigurationPush@6) 

Task         : Azure App Configuration Push
Description  : Push key-values to an Azure App Configuration instance
Version      : 6.1.0
Author       : Microsoft Corporation
Help         : https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.dev-azure-app-configuration-task-push

however getting in the pipeline   error about access denied

##[debug]Processed: ##vso[task.issue type=error;]Access to the target App Configuration instance was denied. Please ensure the required role assignment is made for the identity running this task. Status code: 403
##[debug]task result: Failed

Any ideas ?

And forgot to mentioned that  we waited more then 15 minutes for the right to get propagated.

Many thanks

**Comment by dave-5** [comment]
I am experiencing a similar issue, 403 responses when setting keyValues.  In my case, I am setting keyValue via bicep deploy (resource Microsoft.AppConfiguration/configurationStores/keyValues@2023-03-01).  ServicePrincipal is assigned the **App Configuration Data Owner** role, and Contributor for good measure.  Also confirmed that access key authentication is enabled on the app config service.

I have no clue if the AzureAppConfigurationPush pipeline task and bicep/ARM deployment are in any way related.  If not, I don't mean to hijack the discussion.

@pmateju , you may want to give the Access Key auth toggle a look (found under the "Access Keys" section when viewing the App Config Service in the portal), or assigning your Service Principal the Contributor role given the note found [here](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-disable-access-key-authentication?tabs=portal#arm-template-access).  Not knowing the method by which the pipeline task accesses the App Config Service, I'm not certain how applicable that note is to your scenario.

**Comment by MaryanneNjeri** [comment]
Hello @pmateju does the App configuration instance have a private endpoint enabled?

**Comment by pmateju** [comment]
Hello @MaryanneNjeri 

**yes:**
the app configuration has the private endpoint enabled. We execute our pipeline from self hosted agent.
The self hosted agent runs in same private network as the App configuration instance. the error is 403 - so that seems to indicating that the request gets from pipeline to the AAC instance, but there are issues with authorization - however the service principal used has App Configuration Data Owner. The  Azure App Configuration Push even list the correct AAC endpoint when using the design mode while editing.   


**also:**
I tested the task to run against publicly available  App configuration instance running in the Microsoft  ubuntu  managed agent and the result same  - still getting the same error.

**Comment by MaryanneNjeri** [comment]
@pmateju am trying to repro the issue you are encountering, for the publicly available App configuration store you are encountering the same error after a role assignment is made for the service principal and allowing up to 15 minutes for the permission to propagate before accessing data stored in App Configuration?

**Comment by pmateju** [comment]
> @pmateju am trying to repro the issue you are encountering, for the publicly available App configuration store you are encountering the same error after a role assignment is made for the service principal and allowing up to 15 minutes for the permission to propagate before accessing data stored in App Configuration?

Yes. I waited 15 minutes.

however At the end we need to use the private agents, since all our Azure resources including the App configuration are private. 
So publicly available instance of App configuration  is not a way to go for us.

**Comment by pmateju** [comment]
@MaryanneNjeri :
Update , we got the task working from our private self hosted agent  using service connection, **but only against an App configuration instance that is public** .

If we try to run the exact same task using the :

1. exact same service connection that has exact same set of RBAC permission assigned
2. from the exact same agent
3. but  against App Configuration that has private endpoint only -> **the task fails with 403, forbidden**.

**Comment by MaryanneNjeri** [comment]
> Is the Azure app configuration task designed to be able to authenticate against private App configuration work from private, self hosted agents ( supposing the instance of the Azure app configuration is reachable - e.g on the same private network ) ?

Yes, the self-hosted agent running the task should be in the same Virtual network as the private endpoint.

**Comment by pmateju** [comment]
> > Is the Azure app configuration task designed to be able to authenticate against private App configuration work from private, self-hosted agents ( supposing the instance of the Azure app configuration is reachable - e.g on the same private network ) ?
> 
> @pmateju Yes The self-hosted agent running the App Config Push task should be in the same Virtual network as the private endpoint. Is your self-hosted agent running in the same VNET as the app config instance? I'd like to recommend, maybe trying to run the self-hosted agent in a VM with the same virtual network as the private endpoint, please see https://learn.microsoft.com/en-us/azure/private-link/create-private-endpoint-portal?tabs=dynamic-ip#create-test-virtual-machine. Please let me know if this helps

@MaryanneNjeri 

I can confirm , we manage to get it working also by running the az devops pipeline  using our private agents and against the private instance of the azure app configuration.
the issue was on the network,

What helped to identify that is not a permission issue but a network us was using the az app CLI  with debug switch:

`az appconfig kv list -n name-of-the-aac-instance --debug`

while logging on the azure on the private  agent using the service managed identity

After that we get the clear error message:
`azure.appconfiguration._generated.models._models_py3.ErrorException: Operation returned an invalid status 'Forbidden'
Content: {"type":"[https://azconfig.io/errors/ip-address-rejected","title":"Client](https://azconfig.io/errors/ip-address-rejected%22,%22title%22:%22Client) IP address is denied based on the network settings","status":403}`

It would be good for the Task : Azure App Configuration Push  to have a debug switch too. And return similar error message and not just `Access to the target App Configuration instance was denied. Please ensure the required role assignment is made for the identity running this task. Status code: 403`  - which is misleading and indicates rather permission issue.

Many thanks you for the help ! Hope this will help someone else stuck with similar issue.

**Comment by MaryanneNjeri** [comment]
@pmateju I agree, I think it would be good to provide more error details (when a 403 error is encountered), when system.debug is set to true. We'll work on improving the experience of the App config push task. Thank you for the great suggestion.

**Comment by Ruahonen** [comment]
@pmateju how you resolved this problem? Or was problem just that the VM and App Conf Store private endpoint weren't in same VNET?

**Comment by petitess** [comment]
You have to deploy `Resource management private link` to be able to deploy `Microsoft.AppConfiguration/configurationStores/keyValues@2024-05-01` with private andpoint.
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/create-private-link-access-commands?tabs=azure-cli
You can check out my template for `Resource management private link`.
https://github.com/petitess/bicep/tree/main/ampl01
