### ISSUE TITLE
Offline support for feature flags

### ISSUE THREAD

**Issue by jboczek** [Azure/AppConfiguration#79]
Is there any way to use offline cache with feature flags?

Now I'm getting Exception when AppConfiguration Endpoint is down. Rather than exception I'd like to use settings from file or configure it that way: If endpoint can be reached get values from there if not, get default values from appsettings.

**Comment by jimmyca15** [comment]
@jboczek,

Are you using the Azure App Configuration .NET Core configuration provider? If so there is a way to set an offline file cache to do exactly the scenario you are describing.

**Comment by jimmyca15** [comment]
Here's a .NET Core code snippet using the offline file cache functionality.

```
            var builder = new ConfigurationBuilder()
                .AddAzureAppConfiguration(o =>
                {
                    o.ConnectWithManagedIdentity(myStoreUrl)
                     .UseFeatureFlags()
                     .SetOfflineCache(new OfflineFileCache(new OfflineFileCacheOptions
                     {
                         Path = pathToCacheFile // Not needed if hosting in Azure App Services as home directory sub folder is used automatically
                     }));
                });
```

**Comment by jboczek** [comment]
Hi, thanks for your answer.

Yes, I'm doing it in a similar way:
```
 .AddAzureAppConfiguration(options =>
                    {
                        options
                        .Connect(url)
                        .UseFeatureFlags()
                        .SetOfflineCache(new CustomOfflineFileCache());
                    })
```
The only difference is that I'm using custom implementation of IOfflineCache. 
What I noticed is when I run the app and features get downloaded for the first time the Export method is called with data from feature manager and it's ok, but when I change the value or switch off the feature nothing happened in my CustomOfflineFileCache (i suppose Export will be called every time sth change).

Then I simulate connecting issue like timeout or service unavailable with appconfiguration endpoint and instead of executing Import method of my CustomOfflineFileCache I'm getting Exception which crash my app.

**Comment by jimmyca15** [comment]
@jboczek the current design of offline caching is only for caching configuration values retrieved during startup. This way the application can still start up even when it is unable to reach app configuration. You raise a good point about the scenario of wanting feature flags to be cached as well if they are updated during runtime. We can look into this scenario.

Do you mind sharing what exception is crashing your app?

**Comment by jboczek** [comment]
@jimmyca15 I look closer and what I found is:

1. When the app starts it's using LoadAll method and when the endpoint is wrong or there is no Internet connection the HttpRequestException is caught and the OfflineCache.Import is called (it works fine), but then it set observable and after default 30s it's trying to `GET /kv/ `which crash the app because the `System.Net.Http.HttpRequestException: 'No such host is known'` is unhandled.

It looks like observable action is missing the logic from LoadAll that catches the Exception:
`catch (Exception ex) when (ex.InnerException is HttpRequestException || ex.InnerException is UnauthorizedAccessException)` and reads configuration from OfflineCache

2. If I want to simulate timeout and I'm holding up the request for configuration (using fiddler) I've got `System.AggregateException with InnerException: TaskCanceledException:` A task was canceled. which crash the app even on "LoadAll" because it's not HttpRequestException.

**Comment by jimmyca15** [comment]
Thanks for the investigation @jboczek! These are good points. The original design for offline file support was for loading startup configuration and did not take into account observing key-values. This means it's not fully supportive of feature-flag functionality. We will track this issue and fix it for our next release. We are about to have a release today, but it will not have all of the fixes needed to fully support offline feature flags.

**Comment by fernandozago** [comment]
Any updates on this thread ?

**Comment by avanigupta** [comment]
Hi @fernandozago , we are evaluating how Offline Cache is used in different applications. Could you please help us understand the problem you are trying to solve by using Offline Cache?

**Comment by fernandozago** [comment]
If there is no internet connection when the application is starting (or some miss configuration was applied), the whole application crashes and wont start. 

The Offline Cache support should be smart (to avoid crashing at the startup time)

**Comment by zhenlan** [comment]
Given the security implications and our focus on service availability/reliability, we decided to move away from offering offline solutions.
