### ISSUE TITLE
TargetingFilter - Sticky

### ISSUE THREAD

**Issue by jsheetzmt** [Azure/AppConfiguration#790]
Hello, 

According to the [documentation](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core), staged rollout functionality is sticky. Is there any way to see what users are opt'ed into the feature if we are using a percentage based rollout?

**Comment by zhenlan** [comment]
Sticky means the same user will get the same evaluation result between different calls. You can either test it out locally; or more commonly, people will send evaluation results in telemetry for analytics/monitoring purposes.

**Comment by jsheetzmt** [comment]
Is this data internally managed by App Configuration or something stored in the user's browser? Wondering if the same user will be opt'ed in, no matter what device they use.

If it is internally tracked by App Configuration, any plans on exposing the data for us to view in the portal / via CLI?

**Comment by zhenlan** [comment]
> Is this data internally managed by App Configuration or something stored in the user's browser? 

App Configuration doesn't track any user Id, nor save it in the user's browsers. The user is the one you set in `TargetingContext.UserId` (check out the step 2 [TestTargetingContextAccessor.cs](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core#update-the-web-application-code-to-use-targetingfilter)) to the feature management library. The user Id is used locally for feature flag evaluation, and it won't be sent to App Configuration.

> Wondering if the same user will be opt'ed in, no matter what device they use.

You absolutely can do this by setting the user in the [Include Users](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-targetingfilter-aspnet-core#update-the-feature-flag-to-use-targetingfilter).
