### ISSUE TITLE
Redaction of information from output for App Configuration REST API calls

### ISSUE THREAD

**Issue by NemSimpraga** [Azure/AppConfiguration#796]
Issue is very similar to [https://github.com/Azure/AppConfiguration/issues/721](https://github.com/Azure/AppConfiguration/issues/721).
When there is a 404 error, the label is being redacted from the console output. The only difference is that my stack is NodeJS, instead of .NET.

The JS SDK also has the `AppConfigurationClientOptions ` ([link](https://learn.microsoft.com/en-us/javascript/api/@azure/app-configuration/appconfigurationclientoptions?view=azure-node-latest)) interface for the `AppConfigurationClient ` class, but I cannot seem to find any ways of accessing the `Diagnostics.LoggedQueryParameters` attributes. There is no `ConfigureClientOptions` method for the interface. 

Am I missing something? Is this being developed? Any workarounds?

**Comment by jingao-msft** [comment]
Hi @NemSimpraga, can you open an issue to "Azure-sdk-for-js" regarding this problem?  Thanks

**Comment by NSimpragaVolur** [comment]
@jingao-msft Thanks, will do that
