### ISSUE TITLE
AppConfiguration Public Preview not available in CSP Subscription

### ISSUE THREAD

**Issue by ehuggz** [Azure/AppConfiguration#80]
Receive an error in the Portal when trying to create a new App Configuration Service in a CSP Subscription: {"code":"DisallowedProvider","message":"The operation is not permitted for namespace 'Microsoft.AppConfiguration'. List of permitted provider namespaces is ...

**Comment by zhenlan** [comment]
@yegu-ms do you know whom we can follow up to allow AppConfig in CSP subscriptions?

**Comment by zhenlan** [comment]
We are working on enabling CSP subscription to access App Configuration service.

**Comment by jimmyca15** [comment]
Azure App Configuration (provider name: Microsoft.AppConfiguration) has enabled CSP support as of today.
