### ISSUE TITLE
Validation passed but 400 when creating new config from Portal with content type containing \t 

### ISSUE THREAD

**Issue by Eskibear** [Azure/AppConfiguration#802]
#### Description
When I try creating a key-value in portal, if content-type contains a tab char `\t`, it passes front-end validation, but will fail as a bad request after I click "Apply".

<img width="420" alt="image" src="https://github.com/Azure/AppConfiguration/assets/2351748/c1fd258f-c0a5-4729-a70a-99eada437c1a">

Error:
<img width="374" alt="image" src="https://github.com/Azure/AppConfiguration/assets/2351748/cd6c0edf-f129-4d70-b189-b6feb47f01b8">

#### Additional information
- Why I input a tab char?
  I copy paste from a table in [our docs](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type#create-json-key-values-using-azure-portal), and sometimes the selection can contain a tab char.

- I did some experiments, prepending/appending with some whitespaces. They all pass front-end validation, KVs are and successfully created with exact content I input, including whitespaces. See below
 <img width="134" alt="image" src="https://github.com/Azure/AppConfiguration/assets/2351748/3d957b5d-5056-4ab1-ac18-2432160ab177">

#### Expected behavior
1. I would expect an error message in front-end preventing me from submitting, if we know it's illegal in advance.
2. Is leading/trailing whitespaces making any sense for content-type? If not, in portal, can we simply help to trim value in content-type input box before sending the request?
3. About the different behaviors for `\t` and whitespace which is a little bit strange, is that by design?

**Comment by drago-draganov** [comment]
ContentType doesn't allow for control characters. Since \t is a control character, while whitespace is not.

Frontend vs backend validation:
At the end of the day backend is the source of truth. That allows for evolution, without explicit tight coupling. 
In some cases, the front-end can do a bit better to improve UX.

**Comment by zhenlan** [comment]
@MaryanneNjeri do we plan to do anything with this or can this be closed?

**Comment by MaryanneNjeri** [comment]
@zhenlan no plan for this, we can go ahead and close it.
