### ISSUE TITLE
Deploy settings from ARM/Bicep when using Private Endpoints

### ISSUE THREAD

**Issue by rudfoss** [Azure/AppConfiguration#804]
The Key Vault service has the ability to allow trusted Microsoft services to bypass the firewall. This allows me to configure a Key Vault with private endpoints and populate it with secrets produced during ARM deployment. The App Configuration service does not seem to have this ability yet the use cases for using ARM/Bicep to populate it with settings seems much more relevant than the Key Vault. E.g.: adding endpoint urls, connection strings (without secrets of course), resource names and more...

Is there a way to provision settings from ARM/Bicep when an App Configuration service is configured with private endpoints, and if not are there any plans to support this?

Correction: It seems that regardless of how I configure the firewall on Key Vaults I'm able to deploy secrets from my Bicep template.

**Comment by zhenlan** [comment]
Hi @rudfoss, please check out the discussion in #698 for more context on the issue.

We are currently working on a solution that will allow the ARM/Bicep deployment to a private endpoint-enabled App Configuration store as long as you have the [private link for resource management ](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/create-private-link-access-portal)enabled for the relevant subscription. Please let us know if this is a viable solution for you.

**Comment by rudfoss** [comment]
Hi @zhenlan and thanks for the reply.

Private links for resource management looks promising though I think it will take some time to implement within our org as it seems to affect the entire management group. We will look into it and see if it can work for us. Does this mean that the solution currently available for Key Vaults will also disappear in favor of private link for resource management and that there are no plans to support a similar mechanism for app configuration in the future?

**Comment by zhenlan** [comment]
> Does this mean that the solution currently available for Key Vaults will also disappear in favor of private link for resource management 

This is App Configuration only.

> and that there are no plans to support a similar mechanism for app configuration in the future?

Correct.

**Comment by ysbakker** [comment]
> > Does this mean that the solution currently available for Key Vaults will also disappear in favor of private link for resource management
> 
> This is App Configuration only.
> 
> > and that there are no plans to support a similar mechanism for app configuration in the future?
> 
> Correct.

This issue is closed but according to the roadmap this is still in progress. @zhenlan is this supported already?

If not, there is no other way to deploy config to an app configuration that's behind a private endpoint with network access closed? Except for of course the workaround of temporarily opening the network access. Which seems like an unsafe workaround to me.

**Comment by hahahahahaiyiwen** [comment]
@ysbakker the feature to support deploy config from an app configuration store that's behind a private endpoint is in preview now. Please see [documentation](https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-deployment-overview?tabs=portal#private-network-access). In addition to the requirement of setting [private link for resource management](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/create-private-link-access-portal), it also requires the deployment identity to have app configuration data plane roles.
