### ISSUE TITLE
Support workload identity in AzureAppConfigurationPush@6

### ISSUE THREAD

**Issue by wimeling** [Azure/AppConfiguration#805]
Hi,

I am using AzureAppConfigurationPush@6 with a service connection that is created using Workload Identity Federation and when pushing config items to the App Config i am getting the following error: 

`An unexpected error occurred. ClientSecretCredential: tenantId, clientId, and clientSecret are required parameters`

When using a service connection with service principal authentication i don't have any issues. Can somebody confirm that AzureAppConfigurationPush@6 works with Workload Identity Federation and this is not causing the issue ?

**Comment by rudfoss** [comment]
I'm seing the same with Workload Identity Federation. I'm guessing that it is not supported yet. It works fine for Key Vaults.

**Comment by zhenlan** [comment]
The workload identity is not yet supported, but we are working on it.

**Comment by ChristineWanjau** [comment]
@rudfoss @wimeling Hello, we have just released support for workload identity in the AzureAppConfigurationPush@6.3.0 and AzureAppConfiguration@6.5.0. You can try it out and let me know if you have any questions.

**Comment by wimeling** [comment]
The new version of AzureAppConfigurationPush does not seem to work for us this is the error message: 

![config issue](https://github.com/Azure/AppConfiguration/assets/81306726/79704d11-dfa1-4bb4-8c45-00d1827d4285)

**Comment by zhenlan** [comment]
@wimeling plesae open a new issue. The current issue is already closed and yours may or may not be related to the current one.

BTW, please don't mask the ClientRequestId so we can look it up for you.
