### ISSUE TITLE
Support for Keyvault references poorly documented by SDK/API

### ISSUE THREAD

**Issue by carlo-quinonez** [Azure/AppConfiguration#807]
Support for using keyvault references in the various SDKs or AppService Configuration varies significantly and is poorly documented..

For example in the NodeJS client

```typescript
const appConfigClient = new AppConfigurationClient(connectionString);
const getResponse = await appConfigClient.getConfigurationSetting({ key });
const parsedSecretReference = parseSecretReference(getResponse);
const { name: secretName, vaultUrl } = parseKeyVaultSecretIdentifier( parsedSecretReference.value.secretId );
const secret = await secretClient.getSecret(secretName);
console.log(`Get the secret from keyvault key: ${secretName}, value: ${secret.value}`);
```
 
Support for Keyvault references is nodejs sdk is threadbare - there's a predicate function `isSecretReference` that determines if I need the helper function `parseSecretReference` before finally passing the results into a completely separate KeyVault Client. I could even argue the KV reference is harder than doing it manually.

However, In the .NET SDKs, the KeyVault credentials are passed into the AppConfig constructor and retrieving config is identical, regardless whether the value is stored in AppConfig or is actually a keyvault reference.

And it's not clear what the behavior is when using a KeyVault->AppConfig->AppService reference.

**Comment by zhenlan** [comment]
@carlo-quinonez, indeed, we could have done better documentation. There are two layers of client libraries for App Configuration:

1. **App Configuration Azure SDK**: It contains App Configuration-specific APIs mapping to App Configuration REST APIs. It also contains helper APIs for creating or parsing feature flags and Key Vault references (for example, you can write your own management console).
2. **App Configuration Provider**: This is a convenience layer built on top of the Azure SDK. It has deep integration with each framework/system with the goal of making it easier for customers to consume App Configuration. It contains caching, dynamic configuration refresh, Key Vault reference resolution, replica failover, and many other features. It doesn't contain any write operations to App Configuration (one should use Azure SDK for any write operations).

The .NET library you mentioned is a provider library, while the JavaScript one is an Azure SDK. This is why you see the behavior difference. The support of the JavaScript provider is tracked in #808. For the complete list of App Configuration client libraries, please check out https://github.com/Azure/AppConfiguration#client-libraries.

**Comment by avanigupta** [comment]
> And it's not clear what the behavior is when using a KeyVault->AppConfig->AppService reference.

Please refer to the documentation here: [Granting your app access to referenced key vaults](https://learn.microsoft.com/en-us/azure/app-service/app-service-configuration-references#granting-your-app-access-to-referenced-key-vaults)

**Comment by carlo-quinonez** [comment]
From the docs, my understanding is,

given 
- an AppService with an identity that has permissions to access both AppConfig and  KeyVault, and
- an app setting containing an AppConfig Reference on be the value of the reference KeyVault item.


Is that correct?

**Comment by avanigupta** [comment]
> the value of the corresponding environment variable will be the secret value stored in KeyVault.

Your understanding is correct, @carlo-quinonez

**Comment by Eskibear** [comment]
@carlo-quinonez 
@brandon-lavigne-tfs @eric-gonzalez-tfs (you might also be interested as you thumb up the issue)

We released a preview version of JavaScript provider, which resolves secret reference automatically. You can give it a try, and let us know if you have any feedback.

Install:
```
npm i @azure/app-configuration-provider
```
Key Vault secret reference sample:
```js
/**
 * Before you run it, please add a Key Vault reference with key "app.secret" in your App Configuration store.
 * This example uses the same identity to authenticate with both App Configuration and Key Vault. Make sure that this identity has access to read secrets from Key Vault.
 * Value of secret "app.secret" will be printed.
 *
 * Below environment variables are required for this example:
 * - APPCONFIG_ENDPOINT
 * - AZURE_TENANT_ID
 * - AZURE_CLIENT_ID
 * - AZURE_CLIENT_SECRET
 */

const { load } = require("@azure/app-configuration-provider");
const { getDefaultAzureCredential } = require("@azure/identity");

const endpoint = process.env.APPCONFIG_ENDPOINT;  // E.g. https://your-resource-name.azconfig.io
const credential = getDefaultAzureCredential();
const settings = await load(endpoint, credential, {
    keyVaultOptions: {
        credential: credential
    }
});
const secretKey = "app.secret";
const value = settings.get(secretKey);

console.log(`Get the secret from keyvault key: ${secretKey}, value: ${value}`);
```

**Comment by carlo-quinonez** [comment]
Could the keyvault credential default to the appconfig credential if it's not provided?

**Comment by Eskibear** [comment]
> Could the keyvault credential default to the appconfig credential if it's not provided?

I don't feel it's a good idea to have such implicit behavior. And we probably would have to document the behavior somewhere like in comments. 
To use the same credential to resolve key vault secrets, it is simple to explicitly specify it in `keyVaultOptions` just like in the above example. So I prefer to keep the current behavior, which is self-explained.
