### ISSUE TITLE
Any example about how to create credential and secret?

### ISSUE THREAD

**Issue by newsunwu** [Azure/AppConfiguration#81]
I am investigating how to use AppConfiguration in my prototype service.
The REST API has great example about using AppConfiguration API, link is below. But it does not 
mention how to get the credential and secret. Are the credential and secret retrieved from 
AppConfiguration service or it is generated on the fly. 

Could document include an example how to get credential and secret?

Thank you very much for your great help

Best Regards!
Wu Sun

**Comment by jimmyca15** [comment]
@newsunwu the credential and secret are obtained from the Azure App Configuration access keys. If using the portal to view the access keys then only the connection string is shown, but the connection string contains the secret and credential.

Endpoint={endpoint};Id={credential};Secret={secret}

I see that the authentication doc is a bit out of sync with the fact that credential is also referred to as the secret 'Id'. Will need to update it.

**Comment by zhenlan** [comment]
@mlacouture let's also update our portal UI to list the `id` and `secret` separately in addition to the connection string.

**Comment by mlacouture** [comment]
the portal part is done and will be available in the next prod deployment!

**Comment by mlacouture** [comment]
this is now fixed in prod.

**Comment by zhenlan** [comment]
@jimmyca15 do you think anything needs to be changed in the doc?

**Comment by jimmyca15** [comment]
I think it could be a little unclear so I updated it with pr #94.

**Comment by jimmyca15** [comment]
This was resolved in portal and docs.
