### ISSUE TITLE
Allow Pushing of New Snapshot to .NET Core App Without Restart

### ISSUE THREAD

**Issue by bbrandt** [Azure/AppConfiguration#813]
## Current features
* [Tutorial: Use dynamic configuration using push refresh in a .NET Core app](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh?tabs=windowscommandprompt)
* [Manage and use snapshots (preview)](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-create-snapshots?tabs=dotnet) ([Great into video](https://www.youtube.com/watch?v=s-0E0Y_Qnbc))

I do not believe these two features are currently usable together, as snapshots are intended to be immutable and the configuration in the app for what snapshot to use is likely come from some other configuration source that loads before configuring Azure App Configuration Service.

# Feature Request
As a DevOps Engineer, I would like to be able to deploy a newly created snapshot to a running .NET Core app without requiring a restart, so that long running background jobs within the process are not interrupted when configuration changes are made requiring the app to use a new snapshot.

Since I am (depending on the hat I wear today) a DevOps engineer, preferably I'd like this flow to be viewable entirely within an Azure DevOps Pipeline rather than in the Azure Portal.  It makes sense that configuration and application deployment pipelines would sit side by side in the same UI.

**Comment by zhenlan** [comment]
@bbrandt, thanks for sharing the feedback.

What you described sounds like a configuration rollout scenario to me. You will need an orchestrator that understands the different configuration variants (eg, configuration snapshots) you have and knows who should get which configuration variant. You may also want to adjust the rollout strategy dynamically, for example, increase/decrease the percentage of your workload to receive a particular variant or add a new variant of configuration into your rollout. Your workload will update its configuration based on what is allocated to it by the orchestrator dynamically and without restart.

We can discuss the UI of the orchestration (eg., AzDO pipeline) later, but I'd like to confirm first if the above is what you are looking for.

**Comment by bbrandt** [comment]
Thanks for the response, @zhenlan!  I am now thinking this request may be in the _"Hey that'd be cool"_ category rather than a real "need", but below is what I was envisioning.  A lot of the driver for the question may be, not fully understanding how Feature Flagging fits into the Snapshot feature as well since this is what changes most for us.  

--
Yes, I believe that orchestration is needed.  With our current configuration using "[dynamic configuration using push](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh?tabs=windowscommandprompt)", the App Configuration service watches for changes and pushes events to Event Grid.  In the App Configuration svc UI we make all necessary changes and then update a magic "sentinel" value for the refresh to occur.  The ASP.NET Core app using the App Config svc SDK is configured to listen to this stream of events to perform the refresh, possibly only refreshing if the event fits some filter criteria.

What I had in my mind is that in some UI we'd be able to enter a key prefix and label for filtering as well as a new snapshot name and target environment, then a snapshot would be created with the new name and pushed to the specified environment.  Where "pushed to the environment" could be an event grid event as before, which the App Config service SDK in the ASP.NET Core app would be listening to and respond by updating to the use the newly specified snapshot.  As before there is configuration that is read during startup that can't get this refreshed config.  But config read through [IFeatureManager](https://learn.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement.ifeaturemanager?view=azure-dotnet), IOptionsMonitor, or IOptionsSnapshot would have access to the new config snapshot.

### For a balanced view, counter arguments against using runtime refresh of snapshots:
We will be operating our services within AKS using rolling updates.  Our services will [validate IOptions on startup](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsbuilderextensions.validateonstart?view=dotnet-plat-ext-7.0) and [run environment checks](https://jasperfx.github.io/oakton/guide/host/environment.html) to ensure we are in a good state with the new pod starting up before releasing the old pods.  We do not currently have deployment rings, so this is about as gradual as we are needing for our rollout strategy.  **If we dynamically refresh the snapshot and even now using  "[dynamic configuration using push](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-dotnet-core-push-refresh?tabs=windowscommandprompt)" our services config could be shifted into a bad state, which bypasses these 2 safeguards that only execute on startup.**
