### ISSUE TITLE
Azure App Configuration Task exposes secret values on logs

### ISSUE THREAD

**Issue by samuel-barbosa** [Azure/AppConfiguration#827]
When an Azure App Configuration entry references an Azure KeyVault key AND the value of that key is a **multiline string**, its plain/text value (from the second line only) is revealed on the task execution log, which is a serious security breach.

Steps to Reproduce:
- Create a secret entry on Azure KeyVault using Azure CLI, Azure PowerShell, or even Terraform, and set a Multiline String as it value. (Azure Portal does not support creating a secret with multiline value);
- Create an entry on Azure App Configuration that references the multiline secret;
- In your Azure Pipeline, add the task [AzureAppConfiguration@6](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task), referencing the entry created above;
- Run the pipeline, and inspect the log - it will display the secret entry from the second line;

Again, for single line secrets from KeyVault, it works as expected and it value is not shown. The problem occurs only for multiline values.

**Comment by ChristineWanjau** [comment]
Hello @samuel-barbosa , thanks for reporting the issue. A fix has been released in AzureAppConfiguration@7 (release notes  [).](https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/AzureDevOpsPipelineExtension.md) The task will now fail if any Key Vault references cannot be resolved or if the resolved values cannot be set as a pipeline secret properly. We also introduced a new option that allows errors related to the Key Vault references to be treated as warnings. It could be useful for users to fix any invalid secrets during the migration to the new version.
