### ISSUE TITLE
Is it possible to use the <feature> tag in _Layout?

### ISSUE THREAD

**Issue by rfalanga** [Azure/AppConfiguration#833]
I'm trying to use feature flags, by using Microsoft.FeatureManagement. According to [this tutorial](https://github.com/microsoft/FeatureManagement-Dotnet#view) it is possible to add the `<feature>` tag to an ASP.NET Core view. But I'd like to know if it is possible to add the `<feature>` tag to the _Layout.cshtml file? I tried doing that to the _Layout.cshtml file in a new ASP.NET .NET 7 app I'm working on. I believe VS 2022 added this line in the head section:

`<link rel="stylesheet" href="~/FeatureManagementExperiment.styles.css" asp-append-version="true" />`

However, when I looked for FeatureManagementExperiment.styles.css file in that location, it wasn't there. Furthermore, it appears to me that the `<feature>` tag isn't recognized in _Layout.cshtml.

**Comment by zhenlan** [comment]
@rfalanga, yes, here is an example
https://github.com/Azure/AppConfiguration/blob/main/examples/DotNetCore/WebDemoNet6/WebDemoNet6/Pages/Shared/_Layout.cshtml#L28

Please remember to register before using it.
https://github.com/Azure/AppConfiguration/blob/main/examples/DotNetCore/WebDemoNet6/WebDemoNet6/Pages/_ViewImports.cshtml#L4

**Comment by rfalanga** [comment]
@zhenlan properly registering Microsoft.FeatureManagement.AspNetCore in _ViewImports.cshtml was what I had done wrong. I had mistakenly written it like this:

`@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers, Microsoft.FeatureManagement.AspNetCore`

because I didn't know that I should include the two assemblies on separate lines. Boom, it worked!!

I also got rid of that additional line in _Layout.cshtml:

`<link rel="stylesheet" href="~/FeatureManagementExperiment.styles.css" asp-append-version="true" />`

Since there isn't a FeatureManagementExperiment.styles.css file in the project, I didn't see any point in pointing to nothing.

**Comment by zhenlan** [comment]
@rfalanga, I am glad it worked for you. Right, the FeatureManagementExperiment.styles.css is not from us.
