### ISSUE TITLE
Getting a 401 on OSX when using the latest Azure.AppConfiguration.AspNetCore 7.0.0 (works fine from Windows)

### ISSUE THREAD

**Issue by CodeLifterIO** [Azure/AppConfiguration#849]
My primary dev environment has changed from a windows laptop to a Mac. When I run identical code on windows my connection to parameter store executes as expected.

When I run the exact same code on my Mac I receive the error in the below image.

I've verified that the connection string is correct and matches across machines. I've also verified that the string is loading correctly on the Mac. 

Is there any extra configuration step that I may have missed when setting up the new dev environment?

My next steps will be to explore rolling back to an older version of the package.

![EF153604-041E-4E26-966A-FE0069754FD7](https://github.com/Azure/AppConfiguration/assets/47467920/bf4cc725-fddf-40eb-a68b-5db206390ca2)

**Comment by amerjusupovic** [comment]
Hi @CodeLifterIO, I see that you replied to your own question on StackOverflow and said that the problem resolved itself, so I'll close this issue.
