### ISSUE TITLE
Support for Azure Functions .NET 8 Isolated Mode

### ISSUE THREAD

**Issue by iwaldman** [Azure/AppConfiguration#853]
Are there any plans to support Azure Functions .NET 8 Isolated Mode? Thanks in advance.

**Comment by RichardChen820** [comment]
I believe you could use the latest `Microsoft.Azure.AppConfiguration.Functions.Worker` in .NET 8 Isolated Mode Azure Functions

**Comment by iwaldman** [comment]
@RichardChen820 Thanks. I am using `Microsoft.Azure.AppConfiguration.Functions.Worker 7.0.0`. 

I get the following error when I publish the function to Azure:

![image](https://github.com/Azure/AppConfiguration/assets/1025868/1d598ca4-044c-4568-99b8-da6096c8c662)

**Dependencies**

![image](https://github.com/Azure/AppConfiguration/assets/1025868/a78e3430-3251-4853-80c7-6f1cf04b0975)

**Comment by RichardChen820** [comment]
@iwaldman Could you check the stack setting of you Function? Portal -> Your Function -> Configuration

**Comment by iwaldman** [comment]
<img width="1669" alt="Screenshot 2023-12-26 at 8 18 46 PM" src="https://github.com/Azure/AppConfiguration/assets/1025868/b4f59742-7609-48f3-a3da-dff79c39223b">
<img width="1669" alt="Screenshot 2023-12-26 at 8 20 47 PM" src="https://github.com/Azure/AppConfiguration/assets/1025868/54cec706-7007-4302-9472-2612beaf5499">

**Comment by RichardChen820** [comment]
It works well on my end. Could you try to remove the AppConfig-related code/dependency and try to deploy again to see if the issue persists?

**Comment by pros-iwaldman** [comment]
@RichardChen820 I'm sorry for replying late. Initially, it worked on my local machine but encountered issues when deployed on Azure. Interestingly, it began functioning correctly later on. It appears that the US East/Central regions were among the last to receive upgrades. However, it's been operating smoothly for nearly two weeks now.
