### ISSUE TITLE
Missing .Net Core 6.x Example with new Program.Cs Template

### ISSUE THREAD

**Issue by maud-lv** [Azure/AppConfiguration#856]
Moving the following issue to this repo as per discussion in https://github.com/MicrosoftDocs/azure-docs/issues/100346

---
The tutorial is of excellent quality, although from my point of view it would be even better with examples on the usage of the new .Net Core 6.x Program.Cs Template, where the whole Startup.Cs file is discarded.

I believe this new example would be a great addition as it is a bit cloudy now how this feature is represented in and after the .NET Core 6.x changes.

Document Details

Content: [Tutorial for using Azure App Configuration Key Vault references in an ASP.NET Core app](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core5x)
Content Source: [articles/azure-app-configuration/use-key-vault-references-dotnet-core.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/azure-app-configuration/use-key-vault-references-dotnet-core.md)

**Comment by zhenlan** [comment]
@zhiyuanliang-ms do you mind helping update the code snippet in the mentioned document to .NET 6+?

**Comment by zhiyuanliang-ms** [comment]
@zhenlan Sure.

**Comment by zhiyuanliang-ms** [comment]
It seems like I have updated this [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core5x) in this PR [#266622](https://github.com/MicrosoftDocs/azure-docs-pr/pull/266622)

**Comment by jimmyca15** [comment]
@zhiyuanliang-ms is this done?

**Comment by zhiyuanliang-ms** [comment]
@jimmyca15 It's done.
