### ISSUE TITLE
How to check Helm Values

### ISSUE THREAD

**Issue by doug2901** [Azure/AppConfiguration#858]
I need to install CSI in AKS in a specific node pool, I'm using labels. I woudl like to know where is the values that I can put in Helm to install. 

I tried:
helm install azureappconfiguration.kubernetesprovider oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider  --namespace azappconfig-system --create-namespace --set nodeSelector.MYKEY=MYVALUE

but didn't work.

**Comment by linglingye001** [comment]
Hi @doug2901 , you can use `helm get values azureappconfiguration.kubernetesprovider -n  azappconfig-system` to just get the values `install` used/computed rather than the whole chart and everything, or `helm get manifest azureappconfiguration.kubernetesprovider -n azappconfig-system` to view the generated resource configurations. 
Let me know if you have any further questions or encounter any issues.

**Comment by doug2901** [comment]
Hi @linglingye001, when I run `helm get values azureappconfiguration.kubernetesprovider -n  azappconfig-system` I just get

`USER-SUPPLIED VALUES:
`
nothing else.

And when  I run `helm get manifest azureappconfiguration.kubernetesprovider -n azappconfig-system`  I get a lot of values, but isn't clear wich paremeter I need to use.

`# Source: kubernetes-provider/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: az-appconfig-k8s-provider
  labels:

    helm.sh/chart: kubernetes-provider-1.1.0
    app.kubernetes.io/name: appconfig-provider
    app.kubernetes.io/instance: azureappconfiguration.kubernetesprovider
    control-plane: controller-manager
    azure.workload.identity/use: "true"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    azure.workload.identity/client-id: ""
---
# Source: kubernetes-provider/templates/configmap.yaml
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1beta1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: leader.elect.locker.azappconfig.io
kind: ConfigMap
metadata:
  name: az-appconfig-controller-manager-config
---
# Source: kubernetes-provider/templates/azconfig.io_azureappconfigurationproviders.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: azureappconfigurationproviders.azconfig.io
spec:
  group: azconfig.io
  names:
    kind: AzureAppConfigurationProvider
    listKind: AzureAppConfigurationProviderList
    plural: azureappconfigurationproviders
    singular: azureappconfigurationprovider
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: AzureAppConfigurationProvider is the Schema for the AzureAppConfigurationProviders
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AzureAppConfigurationProviderSpec defines the desired state
              of AzureAppConfigurationProvider
            properties:
              auth:
                description: AzureAppConfigurationProviderAuth defines the authentication
                  type used to connect Azure AppConfiguration
                properties:
                  managedIdentityClientId:
                    description: ClientId of the Managed Identity
                    type: string
                  servicePrincipalReference:
                    description: Secret reference for Service Principle
                    type: string
                  workloadIdentity:
                    description: Workload Identity
                    properties:
                      managedIdentityClientId:
                        type: string
                      managedIdentityClientIdReference:
                        description: ManagedIdentityReferenceParameters defines the
                          parameters for configmap reference
                        properties:
                          configMap:
                            description: ConfigMap contains the managed identity client
                              id
                            type: string
                          key:
                            description: Key of the managed identity client id
                            type: string
                        required:
                        - configMap
                        - key
                        type: object
                    type: object
                type: object
              configuration:
                description: AzureAppConfigurationKeyValueOptions defines the options
                  of fetching key-values from AppConfiguration.
                properties:
                  refresh:
                    description: Defines the settings for dynamic configuration.
                    properties:
                      enabled:
                        default: false
                        type: boolean
                      interval:
                        default: 30s
                        format: duration
                        type: string
                      monitoring:
                        description: Defines the settings for change monitoring.
                        properties:
                          keyValues:
                            items:
                              description: Defines the keyValues to be watched.
                              properties:
                                key:
                                  type: string
                                label:
                                  default: "\0"
                                  type: string
                              required:
                              - key
                              type: object
                            minItems: 1
                            type: array
                        required:
                        - keyValues
                        type: object
                    required:
                    - monitoring
                    type: object
                  selectors:
                    items:
                      description: KeyValueSelector defines the filters when fetching
                        the data from Azure AppConfiguration
                      properties:
                        keyFilter:
                          type: string
                        labelFilter:
                          type: string
                      required:
                      - keyFilter
                      type: object
                    type: array
                  trimKeyPrefixes:
                    items:
                      type: string
                    type: array
                type: object
              connectionStringReference:
                type: string
              endpoint:
                description: The endpoint url of AppConfiguration which should sync
                  the configuration key-values from.
                format: uri
                type: string
              secret:
                description: AzureKeyVaultReference defines the authentication type
                  used to Azure KeyVault resolve KeyVaultReference
                properties:
                  auth:
                    properties:
                      keyVaults:
                        items:
                          description: AzureKeyVaultPerVaultAuth defines the authentication
                            type used to Azure KeyVault resolve KeyVaultReference
                          properties:
                            managedIdentityClientId:
                              description: ClientId of the Managed Identity
                              type: string
                            servicePrincipalReference:
                              description: Secret reference for Service Principle
                              type: string
                            uri:
                              description: The uri of KeyVault which should sync the
                                secret reference item from
                              format: uri
                              type: string
                            workloadIdentity:
                              description: Workload Identity
                              properties:
                                managedIdentityClientId:
                                  type: string
                                managedIdentityClientIdReference:
                                  description: ManagedIdentityReferenceParameters
                                    defines the parameters for configmap reference
                                  properties:
                                    configMap:
                                      description: ConfigMap contains the managed
                                        identity client id
                                      type: string
                                    key:
                                      description: Key of the managed identity client
                                        id
                                      type: string
                                  required:
                                  - configMap
                                  - key
                                  type: object
                              type: object
                          required:
                          - uri
                          type: object
                        type: array
                      managedIdentityClientId:
                        description: ClientId of the Managed Identity
                        type: string
                      servicePrincipalReference:
                        description: Secret reference for Service Principle
                        type: string
                      workloadIdentity:
                        description: Workload Identity
                        properties:
                          managedIdentityClientId:
                            type: string
                          managedIdentityClientIdReference:
                            description: ManagedIdentityReferenceParameters defines
                              the parameters for configmap reference
                            properties:
                              configMap:
                                description: ConfigMap contains the managed identity
                                  client id
                                type: string
                              key:
                                description: Key of the managed identity client id
                                type: string
                            required:
                            - configMap
                            - key
                            type: object
                        type: object
                    type: object
                  refresh:
                    description: Defines the settings for refresh.
                    properties:
                      enabled:
                        default: false
                        type: boolean
                      interval:
                        format: duration
                        type: string
                    required:
                    - interval
                    type: object
                  target:
                    description: SecretGenerationParameters defines the name of target
                      Secret
                    properties:
                      secretName:
                        maxLength: 253
                        minLength: 1
                        pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                        type: string
                    required:
                    - secretName
                    type: object
                required:
                - target
                type: object
              target:
                description: ConfigurationGenerationParameters defines the name of
                  target ConfigMap
                properties:
                  configMapData:
                    description: ConfigMapDataOptions defines the options of generating
                      ConfigMap data
                    properties:
                      key:
                        type: string
                      separator:
                        description: The delimiter that is used to output the ConfigMap
                          data in hierarchical format when the type is set to json
                          or yaml.
                        maxLength: 50
                        minLength: 1
                        type: string
                      type:
                        default: default
                        enum:
                        - default
                        - json
                        - yaml
                        - properties
                        type: string
                    type: object
                  configMapName:
                    maxLength: 253
                    minLength: 1
                    pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                    type: string
                required:
                - configMapName
                type: object
            required:
            - target
            type: object
          status:
            description: AzureAppConfigurationProviderStatus defines the observed
              state of AzureAppConfigurationProvider
            properties:
              lastReconcileTime:
                format: date-time
                type: string
              lastSyncTime:
                format: date-time
                type: string
              message:
                type: string
              phase:
                type: string
              refreshStatus:
                description: RefreshStatus defines last refresh time of configmap
                  and secret when dynamic feature is enabled
                properties:
                  lastKeyVaultReferenceRefreshTime:
                    format: date-time
                    type: string
                  lastSentinelBasedRefreshTime:
                    format: date-time
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
# Source: kubernetes-provider/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: appconfig-manager-role
rules:
- apiGroups:
  - azconfig.io
  resources:
  - azureappconfigurationproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azconfig.io
  resources:
  - azureappconfigurationproviders/finalizers
  verbs:
  - update
- apiGroups:
  - azconfig.io
  resources:
  - azureappconfigurationproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
# Source: kubernetes-provider/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appconfig-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appconfig-manager-role
subjects:
- kind: ServiceAccount
  name: az-appconfig-k8s-provider
  namespace: azappconfig-system
---
# Source: kubernetes-provider/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appconfig-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
# Source: kubernetes-provider/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appconfig-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appconfig-leader-election-role
subjects:
- kind: ServiceAccount
  name: az-appconfig-k8s-provider
  namespace: azappconfig-system
---
# Source: kubernetes-provider/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: kubernetes-provider-1.1.0
    app.kubernetes.io/name: appconfig-provider
    app.kubernetes.io/instance: azureappconfiguration.kubernetesprovider
    control-plane: controller-manager
    azure.workload.identity/use: "true"
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  name: az-appconfig-k8s-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: appconfig-provider
      app.kubernetes.io/instance: azureappconfiguration.kubernetesprovider
      control-plane: controller-manager
      azure.workload.identity/use: "true"
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: appconfig-provider
        app.kubernetes.io/instance: azureappconfiguration.kubernetesprovider
        control-plane: controller-manager
        azure.workload.identity/use: "true"
    spec:
      containers:
      - args:
        - --leader-elect
        - -v=1
        command:
        - /manager
        image: "mcr.microsoft.com/azure-app-configuration/kubernetes-provider:1.1.0"
        imagePullPolicy: Always
        env:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
      securityContext:
        runAsNonRoot: true
      serviceAccountName:  az-appconfig-k8s-provider # appconfig-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: az-appconfig-controller-manager-config
        name: manager-config`

**Comment by andras-turbine** [comment]
Hi, I think I have a similar problem with taints and tolerations, the kubernetes-provider helm chart does not seem to support setting tolerations, nodeSelector, or affinity in the values file.

These are not present in the deployment.yaml template, so I think they can not be set during helm install.

Is this correct?
If it is, could these be implemented sometime in the future?

I am good with it running wherever the scheduler puts it down for now, but controlling where the pod(s) are created would be better.

**Comment by linglingye001** [comment]
@doug2901 @andras-turbine The helm-chart values of kubernetes provider can be found [here](https://github.com/Azure/AppConfiguration-KubernetesProvider/blob/main/deploy/parameter/helm-values.yaml), currently the helm chart doesn't support setting nodeSelector, affinity and tolerations, we will consider add them in v1.2.0. Thanks for your feedback.

**Comment by RichardChen820** [comment]
[https://github.com/Azure/AppConfiguration-KubernetesProvider/issues/6](url)

**Comment by RichardChen820** [comment]
Azure/AppConfiguration-KubernetesProvider#6

**Comment by RichardChen820** [comment]
#Azure/AppConfiguration-KubernetesProvider#6

**Comment by RichardChen820** [comment]
https://github.com/Azure/AppConfiguration-KubernetesProvider/issues/6
