### ISSUE TITLE
The pattern of "configuration_reference" is .NET-only

### ISSUE THREAD

**Issue by zhiyuanliang-ms** [Azure/AppConfiguration#878]
The pattern of "configuration_reference" is .NET only since it uses ':' as seperator. When FM libs of other languages want to support variants, this feature flag schema is not suitable for them.

https://github.com/Azure/AppConfiguration/blob/main/docs/FeatureManagement/FeatureFlag.v2.0.0.schema.json#L161

**Comment by zhiyuanliang-ms** [comment]
@zhenlan @jimmyca15 @amerjusupovic

**Comment by zhenlan** [comment]
Right, that's a bug. We shouldn't require `:`.
