### ISSUE TITLE
AzureDevOps tasks to manage configuration and features

### ISSUE THREAD

**Issue by sdib** [Azure/AppConfiguration#88]
It could be interesting to add AzureDevOps Tasks to manage configuration and feature in the CI/CD pipeline.

Actually, it's only possible to pull configuration.

**Comment by zhenlan** [comment]
@sdib is this something you are looking for?
https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/AzureDevOpsPipelineExtension.md

**Comment by sdib** [comment]
@zhenlan yes but this task only enable users to pull config and not put / edit configuration in Azure App Configuration service.

**Comment by zhenlan** [comment]
@sdib can you please help me to understand the scenario where a pipeline task that can add/edit configuration in App Configuration can be useful. How does the pipeline task may look like?

**Comment by sdib** [comment]
@zhenlan I was thinking about a Release pipeline that would enable a feature to Azure App Configuration after deploying new version of an application containing a feature that was disabled until this version. 
Or a pipeline that adds new configurations needed for an application.
We could also have a dedicated pipeline that adds/edits configuration in Azure App Configuration to prevent manual actions.

Maybe I misunderstand the way this service is supposed to be used ? 
Why is the provided Azure Pipelines task pull only today ?

**Comment by zhenlan** [comment]
@sdib thanks for sharing. The idea of current pipeline task is that it pulls configuration from the AppConfig service and make them available as build or release *pipeline variables* so any tasks after the AppConfig pipeline task in your build or release pipeline can consume configuration from pipeline variables just like before without knowing about the AppConfig service at all. So if you have an existing build or release pipeline, all you need is to add the AppConfig pipeline task as the first task, the remainder of your build or release pipeline does not need any changes and it will continue to work.

The scenarios you described can be achieved with a custom task where you can use Azure CLI or SDK of the AppConfig service to make necessary changes to your AppConfig store. The need for configuration change can be very different from one scenario to another, I am not sure a generic pipeline task can work for all of them.
