### ISSUE TITLE
AzureAppConfigurationPush@6 in combination with Workload Identity Federation does not seem to work

### ISSUE THREAD

**Issue by wimeling** [Azure/AppConfiguration#880]
After reporting an issue with the old in this ticket [here](https://github.com/Azure/AppConfiguration/issues/805#issuecomment-1970564313). I received a message that a new version was released but testing this with Workload Identity Federation returns the following error:

![config issue](https://github.com/Azure/AppConfiguration/assets/81306726/44487692-d491-4e4b-8e40-78db4c8fbfa5)

ClientRequestId: 2d86b9cd-9e65-4431-9b0b-9cc0219bbc43

**Comment by MaryanneNjeri** [comment]
Hello @wimeling, please confirm if the store endpoint configured for the Azure AppConfiguration Push task doesn't have any trailing slashes ?
Example 
` AppConfigurationEndpoint: 'https://appconfigstore-resource-docs.azconfig.io/'` it should be `https://appconfigstore-resource-docs.azconfig.io`

**Comment by ChristineWanjau** [comment]
@wimeling I can't seem to repro this with workload identity. Could you also share the repro steps?

**Comment by wimeling** [comment]
> @wimeling I can't seem to repro this with workload identity. Could you also share the repro steps?

@ChristineWanjau I have done some investigating the solution and it seems the action is working as expected. There was a misconfiguration in the networking that caused the error my apologies for opening this ticket.
