### ISSUE TITLE
 Workload Identity Federation (Auotmatic) issue!

### ISSUE THREAD

**Issue by vijganji99** [Azure/AppConfiguration#884]
Couple of days we converted the Service Connection for Azure DevOps , Service Principal (Automatic) to Workload Identity Federation (Auotmatic). We are now seeing the below error while the pipeline trying to connect to Azure App Configuration , can some one advice on this.

**We tried changing v3.4 App configuration Publish task to v6.5, but it is not working as expected. Hence reopening . Can I get some help with this.**

**##[error]An unexpected error occurred. ClientSecretCredential: tenantId, clientId, and clientSecret are required parameters. To troubleshoot, visit https://aka.ms/azsdk/js/identity/serviceprincipalauthentication/troubleshoot.**

**Comment by vijganji99** [comment]
Ah, found the issue, below link helped me :)
https://github.com/Azure/AppConfiguration/issues/805

--------------------- Solution for above issue in our case --------------------------------------------
[ChristineWanjau](https://github.com/ChristineWanjau) commented [on Oct 13, 2023](https://github.com/Azure/AppConfiguration/issues/805#issuecomment-1760900173)
@rudfoss @wimeling Hello, we have just released support for workload identity in the AzureAppConfigurationPush@6.3.0 and AzureAppConfiguration@6.5.0. You can try it out and let me know if you have any questions.
-----------------------------------------------------------------------------------------------------------

We are using the **lower version** of  AzureAppConfigurationPush**@3.x.x**, so we have updated to  AzureAppConfigurationPush**@6.x.x**

**Comment by vijganji99** [comment]
App configuration V6 is not working as expected. Hence reopening .

**Comment by ChristineWanjau** [comment]
@vijganji99 I can't seem to repro the issue. Just to confirm, does this occur when you convert your service connection from service principal to Workload identity from here?
![Screenshot33](https://github.com/Azure/AppConfiguration/assets/62501578/9cc63dfb-74c3-43df-8f7a-9329bbf1327f)

If so, maybe try creating a new service connection with workload identity see if that works?

**Comment by zhenlan** [comment]
@vijganji99 please let us know when you have more information. Closing for now.
