### ISSUE TITLE
FeatureFlagAttribute does not exist 1.0.0-preview-008560001-910

### ISSUE THREAD

**Issue by chivandikwa** [Azure/AppConfiguration#89]
I have noticed decoration of the feature flags definition enums with an attribute [FeatureFlag]. This however does not exist when I try it out using 1.0.0-preview-008560001-910. Does this attribute exist, is it public?

I saw this in the docs here: https://github.com/Azure/AppConfiguration/blob/master/docs/FeatureManagement/Clients/AspNetCore/Microsoft.FeatureManagement.AspNetCore.md for the MyFeatureFlags enum.

[question]

**Comment by jimmyca15** [comment]
Hi @chivandikwa it doesn't exist. It was removed because it didn't add any functionality. The docs should be updated.
