### ISSUE TITLE
Open source Azure App Configuration pipeline tasks

### ISSUE THREAD

**Issue by rvriens** [Azure/AppConfiguration#902]
There are a lot of beaking changes in AzureAppConfigurationPush@5. 

Is source code of AzureAppConfigurationPush extention available ?

The documentation only describes how to use it in the Release pipelines.

**Comment by MaryanneNjeri** [comment]
Hello @rvriens, currently the source code of the Azure App Configuration Push task is not available yet, but we are working on having it available soon will keep you posted. Thanks

**Comment by MaryanneNjeri** [comment]
Hi @rvriens, the source code for the Azure App Configuration Push task, which has been renamed to Azure App Configuration Import, is now available. You can access it [here](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureAppConfigurationImportV10)
