### ISSUE TITLE
How to run a show command with a wildcard for label?

### ISSUE THREAD

**Issue by cveld** [Azure/AppConfiguration#905]
I am looking for a way to run `az appconfig kv show` to query for a key or key wildcard expression to get results irrespective from the label value.

I tried:
`az appconfig kv show --key $SettingKey --name $appconfig --label *`
but it does not yield any result.

The rest api on the other hand works flawlessly:
`    $result = Invoke-AzCli rest --uri "https://$($appconfig).azconfig.io/kv?key=$settingKey&label=*&api-version=2023-10-01" --resource https://$appconfig.azconfig.io`

**Comment by albertofori** [comment]
Hello @cveld, the cli has a the `az appconfig kv list` [command](https://learn.microsoft.com/en-us/cli/azure/appconfig/kv?view=azure-cli-latest#az-appconfig-kv-list)  that can be used to list key-values using wildcard expressions. Kindly let me know if this works for your use case.

Thanks!
