### ISSUE TITLE
Missing release notes for v7.2.0 of `Microsoft.Extensions.Configuration.AzureAppConfiguration`

### ISSUE THREAD

**Issue by julealgon** [Azure/AppConfiguration#910]
I noticed today that there was a minor bump on this package as I'm installing it on a number of projects over the past week or so. I came to the repo to see if I could check the release notes, but the link on the readme only shows changes for 7.1.0:
- https://github.com/Azure/AppConfiguration/blob/main/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md

Can it be updated with whatever was added in 7.2.0?

**Comment by zhenlan** [comment]
It's in PR and should be merged soon https://github.com/Azure/AppConfiguration/pull/908
