### ISSUE TITLE
AppConfigurationPushTask: Handle null values in Configuration file

### ISSUE THREAD

**Issue by MaryanneNjeri** [Azure/AppConfiguration#913]
When null values are present in the json configuration file, the task will fail with the error "Cannot convert undefined or null to object"

We should have an update to handle null values

**Comment by zhenlan** [comment]
@MaryanneNjeri please add details to the issue.

**Comment by MaryanneNjeri** [comment]
Issue is resolved in the latest version of the[ AppConfigurationPush task version 7.0.0](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task-push)
