### ISSUE TITLE
Should we allow FeatureFlag.enabled to be "true"/"false" (string type)?

### ISSUE THREAD

**Issue by Eskibear** [Azure/AppConfiguration#918]
Given `FeatureFlag.enabled` is defined as boolean type in the schema, is it proper to support "true"/"false" of string type, especially in official samples?

Schema:
https://github.com/Azure/AppConfiguration/blob/d0ef7d5507b9cee15893eead5861e3b1a82d3efd/docs/FeatureManagement/FeatureFlag.v2.0.0.schema.json#L43-L46

Samples:
https://github.com/Azure/AppConfiguration/blob/d0ef7d5507b9cee15893eead5861e3b1a82d3efd/docs/FeatureManagement/Samples/NoFilters.sample.json#L21-L35

**Comment by mrm9084** [comment]
These were added as we don't say we support String. But all of our libraries support Strings.

**Comment by zhenlan** [comment]
Implementation for different platforms can vary, sometimes, for compatibility reasons, but the official samples shouldn't violate the schema.

**Comment by jimmyca15** [comment]
@mrm9084 can you take the fix for this?

**Comment by mrm9084** [comment]
I have it fixed locally, just haven't got the PR up yet. Was trying to finish something else first.

**Comment by mrm9084** [comment]
Fixed in this PR https://github.com/Azure/AppConfiguration/pull/923
