### ISSUE TITLE
Loading multiple keys not working in spring webflux application

### ISSUE THREAD

**Issue by jyotijauhari** [Azure/AppConfiguration#939]
We are trying to load multiple keys (keys name: global, delegato) in 2 different configuration classes

our app configuration looks like this:

<img width="1464" alt="image" src="https://github.com/user-attachments/assets/3e1b259e-1010-4a12-9a83-2d20a47b810d">

libraries:
```
    platform("io.opentelemetry:opentelemetry-bom:1.40.0")

    implementation(
        "com.microsoft.azure:applicationinsights-core:3.5.3"
    )
    implementation(
        "com.microsoft.azure:applicationinsights-runtime-attach:3.5.2"
    )
    implementation("com.azure.spring:spring-cloud-azure-appconfiguration-config:5.12.0")
    implementation("io.opentelemetry:opentelemetry-api")
    implementation("io.opentelemetry:opentelemetry-extension-kotlin")

    implementation("com.azure.spring:spring-cloud-azure-feature-management:5.14.0")
```

bootstrap.yaml:
```
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
          - connection-string: our-app-config-connection-string
            selects:
              - key-filter: delegato
              - key-filter: global
                label-filter: dev
            feature-flags:
              enabled: true
              selects:
                - label-filter: dev
```

Configuration classes:

```

@Configuration
@ConfigurationProperties
class DelegatiConfiguration {
    var application: Application? = null
}

data class Application(val name: String)
```

```
@Configuration
@ConfigurationProperties
class GlobalConfiguration {
    var application: ApplicationInsight? = null
    var azurestorage: AzureStorage? = null
}

data class ApplicationInsight(val connectionString: String)
data class AzureStorage(val connectionString: String)
```

We are trying to autowire this configuration classes and trying to read the value, but we are not able to read value of delegationconfiguration, and seems like global key-filter overwriting it.

we tried adding prefix to configuration as well that is also not working.

Our controller: 

```
@RestController
@RequestMapping("/app-config")
class AppConfigController {
    @Autowired private lateinit var globalConfiguration: GlobalConfiguration
    @Autowired private lateinit var delegatiConfiguration: DelegatiConfiguration


    @GetMapping
    suspend fun startOnboarding(): Boolean {
        logger.info("test app configuration new")
        logger.info(globalConfiguration.toString())
        logger.info(delegatiConfiguration.toString())
        return true
    }
```

we even tried using key-filter: ""  (i.e empty string as mentioned in https://microsoft.github.io/spring-cloud-azure/docs/azure-app-configuration/2.9.0/reference/html/index.html#loading-configuration, but thats also not working to load all keys)

Problem is we want to load both keys together in application, but seems like we cant load multiple keys.

**Comment by jyotijauhari** [comment]
Hi @mrm9084 thanks for your comment, my goal is to fetch both delegato and global keys from this personal app config.

1. Do you mean its convention to store my config in format /<application-name>/configuration-properties-name.config
2. I am trying to get 2 keys which are not in format /application-name/configuration-properties but one is global.somekey1.somekey2 and delegato.somekey3.somekey4. I want to load both global and delegato keys (they are not having "/" as prefix or suffix), something like this:
<img width="344" alt="image" src="https://github.com/user-attachments/assets/548c4308-f70f-4fbd-bdba-b649d5fa793b">

I can get one key using key-filter: global and it loads that key directly in configurationClass. But I want to load both in 2 different configuration classes.

As shared by you I tried spring.cloud.azure/appconfiguration.stores[0].trim-key-prefix: ' '

my updated bootstrap.yaml
<img width="701" alt="image" src="https://github.com/user-attachments/assets/88b2ba5d-3a98-4e03-b01f-011ca06d28ce"> 

my global configuration class
<img width="529" alt="image" src="https://github.com/user-attachments/assets/4c61650a-1e14-42df-b629-f3cbffdda252">

my delegato configuration class
<img width="535" alt="image" src="https://github.com/user-attachments/assets/9ce0a7ee-79d9-4a57-9e2e-45bb26f59b69">

But value is not injected now in those classes

**Comment by jyotijauhari** [comment]
Thanks @mrm9084 , It's working now. Loading multiple keys was not much clear from documentation link .

**Comment by jyotijauhari** [comment]
On side note I have another question, we are using managed identity for pod,  the value of connectionString is coming from key vault as shown below:

<img width="1489" alt="image" src="https://github.com/user-attachments/assets/d30f1345-2555-4081-a6a1-16fd0ba0bb1b">


I have following libraries:

springboot version : 2.7.7
azure spring cloud version: 4.14.0
```
        <dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-appconfiguration-config</artifactId>
        </dependency>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.7</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure.spring</groupId>
                <artifactId>spring-cloud-azure-dependencies</artifactId>
                <version>4.14.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

cloud version : ( as using springboot 2, reffering to this article: https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app?tabs=spring-boot-2#connect-to-an-app-configuration-store)

I have this configuration file where i am trying to inject:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/b98fc152-bcb0-437e-8a12-447488dda1ae">

My bootstrap.yaml
```
spring:
  cloud:
    azure:
      appconfiguration:
        stores:
          - endpoint: <url-to-app-config>
            selects:
              - key-filter: global
#                label-filter: dev
        credential:
          managed-identity-enabled: true
        enabled: true
```
        
**Its not loading configurations and its coming as null.**
**I confirm that manged identity is working as I am able to fetch feature flag from feature manager using managed identity.**

```
Logs from pod:  n","logger":"com.azure.spring.cloud.core.implementation.factory.AbstractAzureServiceClientBuilderFactory","message":"Will configure the default credential of type DefaultAzureCredential for class com.azure.identity.DefaultAzureCredentialBuilder.","context":"default"}
{"timestamp":"2024-07-19 06:29:01.541","level":"DEBUG","thread":"main","logger":"com.azure.identity.EnvironmentCredential","message":"Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID","context":"default"}
{"timestamp":"2024-07-19 06:29:01.542","level":"DEBUG","thread":"main","logger":"com.azure.identity.EnvironmentCredential","message":"Azure Identity => ERROR in EnvironmentCredential: Failed to create a ClientSecretCredential or ClientCertificateCredential. Missing required environment variable either AZURE_CLIENT_SECRET or AZURE_CLIENT_CERTIFICATE_PATH","context":"default"}
{"timestamp":"2024-07-19 06:29:01.542","level":"DEBUG","thread":"main","logger":"com.azure.identity.EnvironmentCredential","message":"Azure Identity => ERROR in EnvironmentCredential: Failed to determine an authentication scheme based on the available environment variables. Please specify AZURE_TENANT_ID and AZURE_CLIENT_SECRET to authenticate through a ClientSecretCredential; AZURE_TENANT_ID and AZURE_CLIENT_CERTIFICATE_PATH to authenticate through a ClientCertificateCredential; or AZURE_USERNAME and AZURE_PASSWORD to authenticate through a UserPasswordCredential.","context":"default"}
{"timestamp":"2024-07-19 06:29:01.542","level":"DEBUG","thread":"main","logger":"com.azure.identity.ManagedIdentityCredential","message":"Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID","context":"default"}
{"timestamp":"2024-07-19 06:29:01.543","level":"DEBUG","thread":"main","logger":"com.azure.identity.SharedTokenCacheCredential","message":"Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID","context":"default"}
{"timestamp":"2024-07-19 06:29:01.545","level":"DEBUG","thread":"main","logger":"org.spr
```

**Comment by mrm9084** [comment]
I'm unsure why that would be happening the easiest way to see what is going on would be to add the `Environment` somewhere in your code, and check out which configs we loaded. You will find them under: `Environment.propertySources` which is a list of all the property sources. One will be of type `BootstrapPropertySource` with the name something like `bootstrapProperties-<key-filter><store-name><label-filter>`. Then in that object under delegate you will is a `properties` object with a map of all the loaded key values.

All of the key values in the map are the names after the trim-key-prefix operation. so they would be as you are looking for them. i.e. `global test.applicationinsight.connectionstring`.

Side Note, it isn't suggest to store secrets like connection strings in app configuration. We support key vault references to load key vault secrets as configuration. See: https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq#how-is-app-configuration-different-from-azure-key-vault

**Comment by jyotijauhari** [comment]
Hi @mrm9084 , we tried to debug the same way you mentioned i.e to load BootstrapProperty. In properties we found its having `FM_configurl/label-filter.`  (managed identity approach)

In connection string approach we analysed same object there as well same property we found i.e  FM_configurl/label-filter.
(looks like configs are not there in bootstrap properties in both)

The interesting thing is with connectionString approach the configs are loading and having value in`globaltest.applicationinsight.connectionstring`  while same key is null when using managed identity. 

I am not able to figure out why. Do you know any other way to debug? the approach you mention bootstrap properties its just having feature management in properties.

Also,
thanks for mentioning the point of not storing secrets directly. We are using key-vault itself. Initially while testing loading config with fetch value from key-vault was also returning null, so we tried with normal value.

**Comment by mrm9084** [comment]
@jyotijauhari, there should be a non `FM_*` object. The FM stands for feature management and would be any loaded feature flags. The same thing without that prefix should exist.

**Comment by jyotijauhari** [comment]
Hi @mrm9084 , I have tried to log the properties, I was not able to log the whole properties object as its protected method, but I was able to log the keys in properties and I can see the keys are getting fetched and environment is dev (correct one). The problem is values are null when I am trying to access/log  it

**Comment by mrm9084** [comment]
@jyotijauhari I think I figured it out. I missed that your configuration are not initialized. Spring doesn't auto create the classes for you, it just fills out the properties. So, you need to initialize your 3 classes.

**Comment by jyotijauhari** [comment]
I am not able to understand about initislisation part.

This is my one of configuration class
```
import org.springframework.boot.context.properties.ConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@ConfigurationProperties(prefix = "globaltest")
open class GlobalConfigurationTest {
    var applicationInsight: ApplicationInsight? = null
}
```

I am enabling configuration properties in main class

```
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.EnableConfigurationProperties

@SpringBootApplication
@EnableConfigurationProperties(GlobalConfiguration::class)
open class TestAppConfigApplication

fun main(args: Array<String>) {
    ApplicationInsights.attach()
    SpringApplication.run(TestAppConfigApplication::class.java, *args)
}
```


 controller which I am using to test

```
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.cloud.bootstrap.config.BootstrapPropertySource
import org.springframework.core.env.ConfigurableEnvironment
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

@RestController
@RequestMapping("/test/v1")
class AppConfigController {

    @Autowired private lateinit var environment: ConfigurableEnvironment
    @Autowired private lateinit var globalConfiguration: GlobalConfiguration
    @Autowired private lateinit var globalConfigurationTest: GlobalConfigurationTest

 @GetMapping("/configs-test")
    fun getConfigsTest() {
        val configurableEnvironment = environment

        println("FINALLLYYYY global-> ${globalConfiguration.applicationInsight?.connectionString}")
        println("FINALLLYYYY globaltest-> ${globalConfigurationTest.applicationInsight?.connectionString}")
    }
```
I am not getting what I am missing here for initialisation? I thought  `    @Autowired private lateinit var globalConfigurationTest: GlobalConfigurationTest` initialise the object

**Comment by mrm9084** [comment]
I'm not familiar with how Kotlin works but, I don't think `var applicationInsight` in your `GlobalConfiguration` file is being set to a non null value, which it needs to be before the property can be set into it. Spring will not auto create it.

**Comment by jyotijauhari** [comment]
Just to mention if it helps, I have same code in my other application which uses springboot 3 and latest config dependency (but it has connection string approach to fetch config) and it works. Its having non null value in applicationInsight. I am not able to figure out on how can I debug it.

**Comment by jyotijauhari** [comment]
Able to get it working. Its bit strange that with var in connection string approach is working, but not with managed identity. We made it val and it worked. Thanks @mrm9084 !
