### ISSUE TITLE
Hosting Azure app configuration as container  in K8s cluster

### ISSUE THREAD

**Issue by Bhanu88** [Azure/AppConfiguration#946]
Hello ,

Can we host the Azure app configuration as a container inside a Kubernetes cluster?

or in future is there a plan to release such images?

**Comment by Bhanu88** [comment]
so we are planning to use Azure app configuration to store configuration for all apps.

Until we are on Azure we are good but when we are trying to deploy the solution on other on-premise platform like openshift where the internet access is not allowed we are stuck.

so I was asking if we can deploy azure app configuration in an container way

**Comment by zhenlan** [comment]
@Bhanu88, we currently don't have a plan for an on-prem offering, like Azure Stack.

With that being said, App Configuration strives to meet customers where they are by offering providers for various languages and platforms. For instance, .NET applications can seamlessly consume configuration from both JSON files and an App Configuration store. Similarly, Kubernetes applications/pods can continue to use ConfigMap with an App Configuration Kubernetes provider.

If user applications lack an internet connection, they should use traditional configuration solutions like JSON files or ConfigMap. However, when an internet connection is available, even for on-prem applications, they can easily switch to App Configuration with minimal effort by adopting App Configuration providers.

**Comment by Bhanu88** [comment]
Thanks for the response. it's clear to me .
