### ISSUE TITLE
Feature flags only supported for dotnet 6?

### ISSUE THREAD

**Issue by mikaelsand** [Azure/AppConfiguration#952]
I was looking at this page: https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-feature-flag-azure-functions-csharp According to that page:

"This article currently only supports [C# in-process function apps](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library) that run on .NET 6."

Is feature flags only supported for dotnet 6 for Azure Functions?

**Comment by zhenlan** [comment]
@mikaelsand, feature flags are supported in latest .NET supported by Azure Functions. That document only has instructions for in-process function apps. We haven't yet updated it to include instructions for isolated mode function apps. I do see that note in the document can cause confusion.

You can find an example of feature flags used in isolated mode Azure Functions:
https://github.com/Azure/AppConfiguration/tree/main/examples/DotNetCore/AzureFunction/FunctionAppIsolatedMode

**Comment by mikaelsand** [comment]
Thank you very much for the answer.
