### ISSUE TITLE
Double underscore not completely supported in the AAC UI

### ISSUE THREAD

**Issue by brgrz** [Azure/AppConfiguration#956]
A couple of issues when trying to use double underscore (__) for key separation.

The import/export page allows to select double underscore for separator and so does the hierarchy view. But there is an issue with displaying the keys in the hiearachy:

See the attached screen

<img width="662" alt="aac-double-1" src="https://github.com/user-attachments/assets/d7a3c0ba-bc61-4a1a-a583-1e331565ceb6">

<img width="1028" alt="aac-double-2" src="https://github.com/user-attachments/assets/ec5d1a73-3c6c-4e48-8d4a-955a62268b59">

**Comment by zhenlan** [comment]
@brgrz, looks like a bug in UI. Thanks for reporting it.

@MaryanneNjeri, can you please take a look?

**Comment by MaryanneNjeri** [comment]
@zhenlan yes please let me take a look

**Comment by MaryanneNjeri** [comment]
@brgrz the fix for this issue is available, please try it out and let us know if you run into any issues.
![Image](https://github.com/user-attachments/assets/216fca65-b7f5-4815-b6ef-01243882da00)
