### ISSUE TITLE
Issue fetching service principal details after updating to AzureAppConfiguration@10

### ISSUE THREAD

**Issue by caracha1** [Azure/AppConfiguration#961]
Due to version 8 of AzureAppConfiguration@8 being removed, we have updated the task to AzureAppConfiguration@10

We are now however facing an issue with getting the service principal details from the AzureCLI task.

- task: AzureCLI@2
...
       addSpnToEnvironment: true

We were be able to fecth those 4 variables servicePrincipalId, servicePrincipalKey, idToken, and tenantId from the Azure CLI task

After updating AzureAppConfiguration, servicePrincipalKey is not provided. The 3 others variables are available

I believe the issue from the AzureCLI is somewhat related with the recent changes in AzureAppConfiguration so I am posting this here too :)

**Comment by MaryanneNjeri** [comment]
Version 10 had to be removed to restore the functionality of previous versions and we have updated the [guidance here](https://github.com/Azure/AppConfiguration/issues/959#issuecomment-2330159422) to reflect this.

**Comment by caracha1** [comment]
Hi Maryanna, thank you. However, even after we have reverted to version 10, the AzureCLI@2 is still not setting servicePrincipalKey (other variables are fine).  Is this something that can be related in the background?

**Comment by MaryanneNjeri** [comment]
Hi @caracha1 are you experiencing this issue with version 8 of the  AzureAppConfiguration task ?

**Comment by caracha1** [comment]
Hi again @MaryanneNjeri , we are using using AzureCLI task @2 to fetch the variables. We have noticed that the servicePrincipalKey is not exposed anymore, after we updated the AzureAppConfiguration from 8 => 10, and now we are back to 8, but the issue persists. We got the impression the issue were linked somehow, because the version of the AzureCLI that was working, and the version of the one that is now failing are identical (Downloading task: AzureCLI (2.244.1))

**Comment by MaryanneNjeri** [comment]
Sounds good @caracha1 I'll go ahead and close this one
