### ISSUE TITLE
Automatic Replica Discovery Behavior When Region Is Down

### ISSUE THREAD

**Issue by bbrandt** [Azure/AppConfiguration#965]
https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-geo-replication?tabs=dotnet#automatic-replica-discovery

If my application is pointing to a single Azure App config resource in South Central US and it has replicas across many regions, if the entire South Central US region is down, is the "Automatic replica discovery" going to be down as well since the Azure App config connection string I have is to the regional service in South Central US?  

Or is there some sort of global load balancer that the connection string is pointing to instead that will still be alive during a region outage?

**Comment by zhenlan** [comment]
The replica discovery is built based on the DNS, so no, it won't be impacted if a region is down.
