### ISSUE TITLE
Support in Azure SDK for Go

### ISSUE THREAD

**Issue by brennerm** [Azure/AppConfiguration#98]
Will App Configuration will be supported by the [Azure SDK for go](https://github.com/Azure/azure-sdk-for-go)? If so can you already give some hints on when it'll be available?

**Comment by zhenlan** [comment]
We don't have a plan for go at the moment. We will consider it if the demand is high. You can call the [REST API of the service](https://github.com/Azure/AppConfiguration#rest-api-reference) from go for now. We will add code snippet of how to do authentication in go.

**Comment by zhenlan** [comment]
@brennerm my comments above are about the SDK to interact with your data in the App Configuration. You can do so with REST APIs and here is a [code snippet of authentication with golang](https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authentication.md#golang).

If you are looking for the go SDK to manage the App Configuration (eg. create a resource), it's available here 
https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/appconfiguration/mgmt/2019-02-01-preview/appconfiguration

And install instructions can be found here
https://github.com/azure/azure-sdk-for-go#install-and-use

Please let me know if you have any further questions.
