### ISSUE TITLE
Syncing Values On-Demand with Azure App Configuration Kubernetes Provider When ` spec.configuration.refresh` is Disabled

### ISSUE THREAD

**Issue by ArulSoundar** [Azure/AppConfiguration#980]
I have configured the Azure App Configuration Kubernetes Provider (AAC) on our AKS cluster with the following refresh settings:
```yaml
refresh:
  enabled: true
  interval: 3m
```

We are considering increasing the refresh interval to 5 hours in our lower environments to reduce polling traffic. However, we need to ensure that any changes in the key values in the App Configuration are promptly reflected in the microservice's configmap.

When testing, I found that manually reapplying the AzureAppConfigurationProvider YAML (without any modifications) does not trigger an immediate update of the configmap. The changes are only reflected after the 5-hour interval.

Is there a way to force an on-demand update of the configmap when a key value changes in the App Configuration?

Additionally, for another use case in our lower environments, we are considering disabling the refresh feature entirely:
```yaml
spec:
  configuration:
    refresh: false
```
In this scenario, how can we manually trigger an update to the target configmap when there is a change in the key-value pair in the App Configuration service?

**Comment by RichardChen820** [comment]
Several other ways come to my mind to trigger an update to target configMap without modifying the `AzureAppConfigurationProvider` spec or using the periodic refresh feature:

1. Delete and recreate the `AzureAppConfigurationProvider` resource -  Delete `AzureAppConfigurationProvider` yaml will result in cleaning up the relative configMap, recreate the `AzureAppConfigurationProvider` would attempt to create a new configMap with the most recent data in App Config
2. Delete or temper the target ConfigMap  - App Configuration Kubernetes provider watches the ConfigMap updates, if the update is done by something else, not by the App Configuration Kubernetes provider, it will reconcile to resyncing with App Config to ensure the data is consistent with App Config.
3. Restart the App Configuration Kubernetes provider controller (the deployment), it will reconcile all the `AzureAppConfigurationProvider`.

**Comment by RichardChen820** [comment]
The way #1 and #2 are risky to some extent since they clean or temper the ConfigMap, if there's anything unexpected happen afterward causing the App Configuration Kubernetes provider fail to fetch data from App Config, it will result in your application not be functional.

The way #3 is more error-tolerated since even it fails to fetch data after restarting, the old configMap is still there.

But that's all depends on your requirements, if you want your application must get the latest configuration data to start during deployment, then way #1 would meet your requirement

**Comment by ArulSoundar** [comment]
Thanks  for the suggestion.
The way#3 -  works as expected and solve the purpose for these use case.
