### ISSUE TITLE
Azure App Configuration Kubernetes Provider

### ISSUE THREAD

**Issue by gunayBM** [Azure/AppConfiguration#987]
Hi team, I am trying to follow this documentation and use wildcard to get all key values and labels but it did not work. I have in app configuration with non-label, labeled with different names (tec, tec-dev...). How can I grab all of them?
[https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default](url) 

  target:
    configMapName: test-common-configmap
  configuration:
    selectors:
      - keyFilter: *
        labelFilter: *

**Comment by RichardChen820** [comment]
@gunayBM Please refer to this thread, hope it could answer your question:
https://github.com/Azure/AppConfiguration-KubernetesProvider/issues/38

**Comment by zhenlan** [comment]
@gunayBM please let us know if you have an update. Closing for now.
