### ISSUE TITLE
Make IFeatureSettingsProvider and IFeatureSettings public 

### ISSUE THREAD

**Issue by dmcweeney** [Azure/AppConfiguration#99]
Trying to provide my own feature provider and get:
'IFeatureSettingsProvider' is inaccessible due to its protection level	

Using version 1.0.0-preview-009000001-1251

Also please make IFeatureSettings public.

**Comment by jimmyca15** [comment]
Can you look into this for next release. Thanks @dmcweeney.

**Comment by zhenlan** [comment]
@jimmyca15 is this in the latest release?

**Comment by jimmyca15** [comment]
@zhenlan custom feature setting provider requires design review and has not added in the latest release. It would be a new set of APIs. It is still a target.

Also just realized I said "can **you** look into this" in my previous reply and I meant to just say "can look into this".

**Comment by zhenlan** [comment]
This has been added in recent release of [Microsoft.FeatureManagement 2.2.0-preview](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.2.0-preview).
