### ISSUE TITLE
How to use dependency injection to configure client options using AddAzureAppConfiguration()

### ISSUE THREAD

**Issue by chwilliamson** [Azure/AppConfiguration#995]
Hi, I would appreciate some advice using dependency injection with AddAzureAppConfiguration().

Below is a snippet to help explain my question.  

How would someone retrieve an instance of `httpClientFactory` from the services container?

```c#
var builder = WebApplication.CreateBuilder(args);
// Adds the IHttpClientFactory and related services to the service collection.
builder.Services.AddHttpClient();

builder.AddAzureAppConfiguration(options => {
     //  How to get a httpClientFactory from services?
     options.ConfigureClientOptions(co => co.Transport = new HttpClientTransport(httpClientFactory.CreateClient("AppConfigClient")));
});

// more code
```

Thank you.

**Comment by drago-draganov** [comment]
Unfortunately, DI is not available before the configuration is resolved.

Perhaps you may be interested in a new, related feature we recently added.  

**Give the users the ability to have control over ConfigurationClient instance(s) used by the provider**
https://github.com/Azure/AppConfiguration-DotnetProvider/pull/598

**Comment by chwilliamson** [comment]
Thank you for confirming DI is not available here. I look forward to the new feature. 👍
